-- ============================================================
-- Koto no Ha — Seed Kanji N3 (194 karakter eksklusif)
-- Level: N3 (id=3)
-- Anti-duplikasi: kanji yang sudah ada di N5/N4 TIDAK dimasukkan.
--   (Kanji yang juga ada di N2/N1 tetap dimasukkan ke N3 — level lebih tepat.)
-- Format mengikuti 006_seed_kanji_n5_n4.sql
-- Jalankan SETELAH 002_learning_content.sql
-- ============================================================

-- Idempoten: bersihkan kanji N3 sebelum re-seed
DELETE FROM public.kanji WHERE level_id = 3;

INSERT INTO public.kanji (level_id, kanji, hiragana, romaji, meaning, hint, stroke_count, examples, order_index) VALUES
-- ─── Waktu, perubahan & pergerakan ───────────────────────────
(3, '昨', 'サク', 'saku', 'Kemarin, yang lalu', 'Matahari (日) yang sudah lewat sekejap (乍) — hari kemarin.', 9, '[{"kanji":"昨日","hiragana":"きのう","meaning":"kemarin"},{"kanji":"昨年","hiragana":"さくねん","meaning":"tahun lalu"},{"kanji":"昨夜","hiragana":"さくや","meaning":"tadi malam"}]'::jsonb, 1)
(3, '最', 'サイ／もっと.も', 'sai / motto.mo', 'Paling, ter-', 'Mengambil (取) yang tertinggi — paling, ter-.', 12, '[{"kanji":"最近","hiragana":"さいきん","meaning":"akhir-akhir ini"},{"kanji":"最初","hiragana":"さいしょ","meaning":"paling awal"},{"kanji":"最後","hiragana":"さいご","meaning":"paling akhir"}]'::jsonb, 2)
(3, '初', 'ショ／はじ.め／はつ', 'sho / haji.me / hatsu', 'Permulaan, pertama', 'Pakaian (衤) digunting (刀) pertama kali — permulaan.', 7, '[{"kanji":"最初","hiragana":"さいしょ","meaning":"paling awal"},{"kanji":"初めて","hiragana":"はじめて","meaning":"untuk pertama kali"},{"kanji":"初心者","hiragana":"しょしんしゃ","meaning":"pemula"}]'::jsonb, 3)
(3, '続', 'ゾク／つづ.く', 'zoku / tsudu.ku', 'Berlanjut, menyambung', 'Benang (糸) yang dijual (売) tersambung terus — berlanjut.', 13, '[{"kanji":"続く","hiragana":"つづく","meaning":"berlanjut"},{"kanji":"続ける","hiragana":"つづける","meaning":"melanjutkan"},{"kanji":"連続","hiragana":"れんぞく","meaning":"berturut-turut"}]'::jsonb, 4)
(3, '変', 'ヘン／か.わる／か.える', 'hen / ka.waru / ka.eru', 'Berubah, aneh', 'Sesuatu (亦) yang menyimpang (夂) — berubah, aneh.', 9, '[{"kanji":"変わる","hiragana":"かわる","meaning":"berubah (sendiri)"},{"kanji":"変える","hiragana":"かえる","meaning":"mengubah"},{"kanji":"大変","hiragana":"たいへん","meaning":"berat, gawat"}]'::jsonb, 5)
(3, '戻', 'レイ／もど.る／もど.す', 'rei / modo.ru / modo.su', 'Kembali, mengembalikan', 'Pintu (戸) tempat anjing besar (大) kembali — kembali.', 7, '[{"kanji":"戻る","hiragana":"もどる","meaning":"kembali"},{"kanji":"戻す","hiragana":"もどす","meaning":"mengembalikan"},{"kanji":"払い戻し","hiragana":"はらいもどし","meaning":"pengembalian uang"}]'::jsonb, 6)
(3, '向', 'コウ／む.く／む.かう', 'kou / mu.ku / mu.kau', 'Menghadap, arah', 'Jendela menghadap satu arah — menghadap.', 6, '[{"kanji":"向かう","hiragana":"むかう","meaning":"menuju"},{"kanji":"方向","hiragana":"ほうこう","meaning":"arah"},{"kanji":"向上","hiragana":"こうじょう","meaning":"peningkatan"}]'::jsonb, 7)
(3, '移', 'イ／うつ.る／うつ.す', 'i / utsu.ru / utsu.su', 'Berpindah, memindah', 'Padi (禾) yang banyak (多) dipindah — berpindah.', 11, '[{"kanji":"移る","hiragana":"うつる","meaning":"berpindah"},{"kanji":"移動","hiragana":"いどう","meaning":"perpindahan"},{"kanji":"移乗","hiragana":"いじょう","meaning":"transfer (pindah duduk)"}]'::jsonb, 8)
(3, '過', 'カ／す.ぎる／す.ごす', 'ka / su.giru / su.gosu', 'Melewati, berlebihan', 'Berjalan (辶) melewati batas (咼) — lewat, berlalu.', 12, '[{"kanji":"過ぎる","hiragana":"すぎる","meaning":"lewat, melampaui"},{"kanji":"過去","hiragana":"かこ","meaning":"masa lalu"},{"kanji":"過程","hiragana":"かてい","meaning":"proses"}]'::jsonb, 9)
(3, '期', 'キ／ゴ', 'ki / go', 'Periode, masa', 'Bulan (月) dalam jangka tertentu (其) — periode.', 12, '[{"kanji":"期間","hiragana":"きかん","meaning":"jangka waktu"},{"kanji":"期待","hiragana":"きたい","meaning":"harapan"},{"kanji":"学期","hiragana":"がっき","meaning":"semester"}]'::jsonb, 10)
-- ─── Manusia & hubungan sosial ───────────────────────────────
(3, '彼', 'ヒ／かれ／かの', 'hi / kare / kano', 'Dia, ia (lk)', 'Orang (彳) di sana (皮) — dia (orang ketiga).', 8, '[{"kanji":"彼","hiragana":"かれ","meaning":"dia (laki-laki)"},{"kanji":"彼女","hiragana":"かのじょ","meaning":"dia (perempuan), pacar"},{"kanji":"彼ら","hiragana":"かれら","meaning":"mereka"}]'::jsonb, 11)
(3, '友', 'ユウ／とも', 'yuu / tomo', 'Teman', 'Dua tangan saling menggenggam — teman.', 4, '[{"kanji":"友達","hiragana":"ともだち","meaning":"teman"},{"kanji":"親友","hiragana":"しんゆう","meaning":"sahabat karib"},{"kanji":"友情","hiragana":"ゆうじょう","meaning":"persahabatan"}]'::jsonb, 12)
(3, '息', 'ソク／いき', 'soku / iki', 'Napas, anak', 'Diri (自) dari hati (心) — napas; juga anak (息子).', 10, '[{"kanji":"息","hiragana":"いき","meaning":"napas"},{"kanji":"息子","hiragana":"むすこ","meaning":"anak laki-laki"},{"kanji":"休息","hiragana":"きゅうそく","meaning":"istirahat"}]'::jsonb, 13)
(3, '娘', 'ジョウ／むすめ', 'jou / musume', 'Anak perempuan', 'Perempuan (女) yang baik (良) — anak perempuan, gadis.', 10, '[{"kanji":"娘","hiragana":"むすめ","meaning":"anak perempuan"},{"kanji":"娘さん","hiragana":"むすめさん","meaning":"putri (orang lain)"},{"kanji":"一人娘","hiragana":"ひとりむすめ","meaning":"anak perempuan tunggal"}]'::jsonb, 14)
(3, '夫', 'フ／おっと', 'fu / otto', 'Suami', 'Orang dewasa (大) dengan tusuk konde di kepala — suami.', 4, '[{"kanji":"夫","hiragana":"おっと","meaning":"suami"},{"kanji":"夫婦","hiragana":"ふうふ","meaning":"suami-istri"},{"kanji":"工夫","hiragana":"くふう","meaning":"akal, ide kreatif"}]'::jsonb, 15)
(3, '妻', 'サイ／つま', 'sai / tsuma', 'Istri', 'Perempuan (女) dengan tangan memegang sapu — istri.', 8, '[{"kanji":"妻","hiragana":"つま","meaning":"istri"},{"kanji":"夫妻","hiragana":"ふさい","meaning":"suami-istri (sopan)"},{"kanji":"妻子","hiragana":"さいし","meaning":"istri dan anak"}]'::jsonb, 16)
(3, '祖', 'ソ', 'so', 'Leluhur, kakek-nenek', 'Altar pemujaan (示) leluhur yang bertumpuk (且) — leluhur.', 9, '[{"kanji":"祖父","hiragana":"そふ","meaning":"kakek"},{"kanji":"祖母","hiragana":"そぼ","meaning":"nenek"},{"kanji":"祖先","hiragana":"そせん","meaning":"leluhur"}]'::jsonb, 17)
(3, '孫', 'ソン／まご', 'son / mago', 'Cucu', 'Anak (子) yang tersambung (系) ke generasi berikut — cucu.', 10, '[{"kanji":"孫","hiragana":"まご","meaning":"cucu"},{"kanji":"子孫","hiragana":"しそん","meaning":"keturunan"},{"kanji":"孫娘","hiragana":"まごむすめ","meaning":"cucu perempuan"}]'::jsonb, 18)
(3, '他', 'タ／ほか', 'ta / hoka', 'Lain, lainnya', 'Orang (亻) yang lain (也) — yang lain.', 5, '[{"kanji":"他","hiragana":"ほか","meaning":"yang lain"},{"kanji":"他人","hiragana":"たにん","meaning":"orang lain"},{"kanji":"その他","hiragana":"そのた","meaning":"selain itu"}]'::jsonb, 19)
(3, '自', 'ジ／みずか.ら', 'ji / mizuka.ra', 'Diri sendiri', 'Gambar hidung — orang Jepang menunjuk hidung untuk berkata "saya".', 6, '[{"kanji":"自分","hiragana":"じぶん","meaning":"diri sendiri"},{"kanji":"自由","hiragana":"じゆう","meaning":"kebebasan"},{"kanji":"自然","hiragana":"しぜん","meaning":"alam"}]'::jsonb, 20)
(3, '相', 'ソウ／あい', 'sou / ai', 'Saling, wujud', 'Mata (目) memandang pohon (木) — saling memperhatikan.', 9, '[{"kanji":"相手","hiragana":"あいて","meaning":"lawan, mitra"},{"kanji":"相談","hiragana":"そうだん","meaning":"konsultasi"},{"kanji":"相互","hiragana":"そうご","meaning":"timbal balik"}]'::jsonb, 21)
(3, '共', 'キョウ／とも', 'kyou / tomo', 'Bersama', 'Dua tangan mengangkat sesuatu bersama — bersama.', 6, '[{"kanji":"共に","hiragana":"ともに","meaning":"bersama"},{"kanji":"共通","hiragana":"きょうつう","meaning":"kesamaan"},{"kanji":"共同","hiragana":"きょうどう","meaning":"kerja sama"}]'::jsonb, 22)
(3, '協', 'キョウ', 'kyou', 'Kerja sama', 'Banyak tenaga (力) disatukan (十) — kerja sama.', 8, '[{"kanji":"協力","hiragana":"きょうりょく","meaning":"kerja sama"},{"kanji":"協会","hiragana":"きょうかい","meaning":"asosiasi"},{"kanji":"妥協","hiragana":"だきょう","meaning":"kompromi"}]'::jsonb, 23)
(3, '助', 'ジョ／たす.ける／たす.かる', 'jo / tasu.keru / tasu.karu', 'Menolong', 'Menambah (且) tenaga (力) — menolong.', 7, '[{"kanji":"助ける","hiragana":"たすける","meaning":"menolong"},{"kanji":"助かる","hiragana":"たすかる","meaning":"tertolong"},{"kanji":"助手","hiragana":"じょしゅ","meaning":"asisten"}]'::jsonb, 24)
(3, '支', 'シ／ささ.える', 'shi / sasa.eru', 'Menopang, cabang', 'Tangan (又) memegang ranting (十) — menopang.', 4, '[{"kanji":"支える","hiragana":"ささえる","meaning":"menopang"},{"kanji":"支払い","hiragana":"しはらい","meaning":"pembayaran"},{"kanji":"支援","hiragana":"しえん","meaning":"dukungan, bantuan"}]'::jsonb, 25)
(3, '頼', 'ライ／たの.む／たよ.る', 'rai / tano.mu / tayo.ru', 'Meminta, mengandalkan', 'Keuntungan (束+頁) yang diandalkan — meminta tolong, mengandalkan.', 16, '[{"kanji":"頼む","hiragana":"たのむ","meaning":"meminta tolong"},{"kanji":"頼る","hiragana":"たよる","meaning":"mengandalkan"},{"kanji":"信頼","hiragana":"しんらい","meaning":"kepercayaan"}]'::jsonb, 26)
(3, '信', 'シン', 'shin', 'Percaya', 'Perkataan (言) seseorang (亻) yang dipercaya — percaya.', 9, '[{"kanji":"信じる","hiragana":"しんじる","meaning":"mempercayai"},{"kanji":"信頼","hiragana":"しんらい","meaning":"kepercayaan"},{"kanji":"自信","hiragana":"じしん","meaning":"percaya diri"}]'::jsonb, 27)
(3, '望', 'ボウ／のぞ.む', 'bou / nozo.mu', 'Berharap, memandang', 'Memandang bulan (月) dari jauh dengan harapan — berharap.', 11, '[{"kanji":"望む","hiragana":"のぞむ","meaning":"berharap"},{"kanji":"希望","hiragana":"きぼう","meaning":"harapan"},{"kanji":"願望","hiragana":"がんぼう","meaning":"keinginan"}]'::jsonb, 28)
(3, '約', 'ヤク', 'yaku', 'Janji, sekitar', 'Benang (糸) yang diikat (勺) — janji, perjanjian.', 9, '[{"kanji":"約束","hiragana":"やくそく","meaning":"janji"},{"kanji":"予約","hiragana":"よやく","meaning":"reservasi"},{"kanji":"契約","hiragana":"けいやく","meaning":"kontrak"}]'::jsonb, 29)
(3, '責', 'セキ／せ.める', 'seki / se.meru', 'Tanggung jawab, menyalahkan', 'Beban harta (貝) yang dipikul — tanggung jawab.', 11, '[{"kanji":"責任","hiragana":"せきにん","meaning":"tanggung jawab"},{"kanji":"責める","hiragana":"せめる","meaning":"menyalahkan"},{"kanji":"無責任","hiragana":"むせきにん","meaning":"tidak bertanggung jawab"}]'::jsonb, 30)
(3, '役', 'ヤク／エキ', 'yaku / eki', 'Peran, tugas', 'Orang (彳) yang diberi tugas (殳) — peran, jabatan.', 7, '[{"kanji":"役に立つ","hiragana":"やくにたつ","meaning":"berguna"},{"kanji":"役割","hiragana":"やくわり","meaning":"peran"},{"kanji":"市役所","hiragana":"しやくしょ","meaning":"kantor kota"}]'::jsonb, 31)
(3, '参', 'サン／まい.る', 'san / mai.ru', 'Ikut serta, datang (rendah hati)', 'Tiga rambut berkumpul — ikut berpartisipasi.', 8, '[{"kanji":"参加","hiragana":"さんか","meaning":"partisipasi"},{"kanji":"参考","hiragana":"さんこう","meaning":"referensi"},{"kanji":"参る","hiragana":"まいる","meaning":"datang/pergi (rendah hati)"}]'::jsonb, 32)
(3, '礼', 'レイ／ライ', 'rei / rai', 'Tata krama, terima kasih', 'Altar (示) tempat memberi hormat — tata krama, salam.', 5, '[{"kanji":"礼儀","hiragana":"れいぎ","meaning":"sopan santun"},{"kanji":"お礼","hiragana":"おれい","meaning":"ucapan terima kasih"},{"kanji":"失礼","hiragana":"しつれい","meaning":"tidak sopan, permisi"}]'::jsonb, 33)
(3, '迷', 'メイ／まよ.う', 'mei / mayo.u', 'Tersesat, bingung', 'Berjalan (辶) di antara banyak jalan (米) — tersesat.', 9, '[{"kanji":"迷う","hiragana":"まよう","meaning":"bingung, tersesat"},{"kanji":"迷惑","hiragana":"めいわく","meaning":"gangguan, merepotkan"},{"kanji":"迷子","hiragana":"まいご","meaning":"anak hilang"}]'::jsonb, 34)
-- ─── Pekerjaan, uang & barang ────────────────────────────────
(3, '職', 'ショク', 'shoku', 'Jabatan, profesi', 'Telinga (耳) yang mendengar tugas — jabatan, profesi.', 18, '[{"kanji":"職業","hiragana":"しょくぎょう","meaning":"profesi"},{"kanji":"就職","hiragana":"しゅうしょく","meaning":"mendapat kerja"},{"kanji":"職場","hiragana":"しょくば","meaning":"tempat kerja"}]'::jsonb, 35)
(3, '勤', 'キン／つと.める', 'kin / tsuto.meru', 'Bekerja, bertugas', 'Mengerahkan tenaga (力) dengan tekun (堇) — bertugas.', 12, '[{"kanji":"勤める","hiragana":"つとめる","meaning":"bekerja (di)"},{"kanji":"出勤","hiragana":"しゅっきん","meaning":"masuk kerja"},{"kanji":"勤務","hiragana":"きんむ","meaning":"dinas, tugas"}]'::jsonb, 36)
(3, '給', 'キュウ', 'kyuu', 'Memberi, gaji', 'Benang (糸) yang disatukan (合) dan diberikan — pasokan, gaji.', 12, '[{"kanji":"給料","hiragana":"きゅうりょう","meaning":"gaji"},{"kanji":"時給","hiragana":"じきゅう","meaning":"upah per jam"},{"kanji":"支給","hiragana":"しきゅう","meaning":"pemberian tunjangan"}]'::jsonb, 37)
(3, '費', 'ヒ／つい.やす', 'hi / tsui.yasu', 'Biaya, menghabiskan', 'Uang (貝) yang dikeluarkan (弗) — biaya.', 12, '[{"kanji":"費用","hiragana":"ひよう","meaning":"biaya"},{"kanji":"交通費","hiragana":"こうつうひ","meaning":"ongkos transport"},{"kanji":"生活費","hiragana":"せいかつひ","meaning":"biaya hidup"}]'::jsonb, 38)
(3, '税', 'ゼイ', 'zei', 'Pajak', 'Padi (禾) yang diserahkan ke negara — pajak.', 12, '[{"kanji":"税金","hiragana":"ぜいきん","meaning":"pajak"},{"kanji":"消費税","hiragana":"しょうひぜい","meaning":"pajak konsumsi"},{"kanji":"税込み","hiragana":"ぜいこみ","meaning":"termasuk pajak"}]'::jsonb, 39)
(3, '収', 'シュウ／おさ.める', 'shuu / osa.meru', 'Memungut, pemasukan', 'Tangan menarik dan mengumpulkan — memungut, pendapatan.', 4, '[{"kanji":"収入","hiragana":"しゅうにゅう","meaning":"pendapatan"},{"kanji":"収集","hiragana":"しゅうしゅう","meaning":"pengumpulan"},{"kanji":"領収書","hiragana":"りょうしゅうしょ","meaning":"kuitansi"}]'::jsonb, 40)
(3, '払', 'フツ／はら.う', 'futsu / hara.u', 'Membayar, mengibas', 'Tangan (扌) menyingkirkan (厶) — membayar.', 5, '[{"kanji":"払う","hiragana":"はらう","meaning":"membayar"},{"kanji":"支払い","hiragana":"しはらい","meaning":"pembayaran"},{"kanji":"払い戻し","hiragana":"はらいもどし","meaning":"pengembalian uang"}]'::jsonb, 41)
(3, '返', 'ヘン／かえ.す／かえ.る', 'hen / kae.su / kae.ru', 'Mengembalikan', 'Berjalan (辶) berbalik (反) — kembali, mengembalikan.', 7, '[{"kanji":"返す","hiragana":"かえす","meaning":"mengembalikan"},{"kanji":"返事","hiragana":"へんじ","meaning":"balasan, jawaban"},{"kanji":"返却","hiragana":"へんきゃく","meaning":"pengembalian"}]'::jsonb, 42)
(3, '配', 'ハイ／くば.る', 'hai / kuba.ru', 'Membagikan, mengatur', 'Tong arak (酉) dibagikan ke diri (己) — membagikan.', 10, '[{"kanji":"配る","hiragana":"くばる","meaning":"membagikan"},{"kanji":"配達","hiragana":"はいたつ","meaning":"pengantaran"},{"kanji":"心配","hiragana":"しんぱい","meaning":"khawatir"}]'::jsonb, 43)
(3, '整', 'セイ／ととの.える', 'sei / totono.eru', 'Merapikan, teratur', 'Mengikat (束) dan memukul (攵) lurus (正) — merapikan.', 16, '[{"kanji":"整理","hiragana":"せいり","meaning":"penataan"},{"kanji":"整える","hiragana":"ととのえる","meaning":"merapikan"},{"kanji":"調整","hiragana":"ちょうせい","meaning":"penyesuaian"}]'::jsonb, 44)
(3, '直', 'チョク／ジキ／なお.す／なお.る', 'choku / jiki / nao.su / nao.ru', 'Lurus, memperbaiki', 'Sepuluh (十) mata (目) memandang lurus — lurus, langsung.', 8, '[{"kanji":"直す","hiragana":"なおす","meaning":"memperbaiki"},{"kanji":"直接","hiragana":"ちょくせつ","meaning":"langsung"},{"kanji":"正直","hiragana":"しょうじき","meaning":"jujur"}]'::jsonb, 45)
(3, '治', 'ジ／チ／なお.す／おさ.める', 'ji / chi / nao.su / osa.meru', 'Menyembuhkan, memerintah', 'Air (氵) yang dikendalikan (台) — mengatur, menyembuhkan.', 8, '[{"kanji":"治る","hiragana":"なおる","meaning":"sembuh"},{"kanji":"治療","hiragana":"ちりょう","meaning":"pengobatan"},{"kanji":"政治","hiragana":"せいじ","meaning":"politik"}]'::jsonb, 46)
(3, '修', 'シュウ／おさ.める', 'shuu / osa.meru', 'Memperbaiki, menempa diri', 'Orang menata diri dengan rajin — memperbaiki, belajar.', 10, '[{"kanji":"修理","hiragana":"しゅうり","meaning":"reparasi"},{"kanji":"研修","hiragana":"けんしゅう","meaning":"pelatihan"},{"kanji":"修正","hiragana":"しゅうせい","meaning":"koreksi"}]'::jsonb, 47)
(3, '壊', 'カイ／こわ.す／こわ.れる', 'kai / kowa.su / kowa.reru', 'Menghancurkan, rusak', 'Tanah (土) yang runtuh — menghancurkan, rusak.', 16, '[{"kanji":"壊す","hiragana":"こわす","meaning":"merusak"},{"kanji":"壊れる","hiragana":"こわれる","meaning":"rusak"},{"kanji":"破壊","hiragana":"はかい","meaning":"perusakan"}]'::jsonb, 48)
(3, '造', 'ゾウ／つく.る', 'zou / tsuku.ru', 'Membuat, memproduksi', 'Berjalan (辶) memberi tahu (告) cara membuat — memproduksi.', 10, '[{"kanji":"造る","hiragana":"つくる","meaning":"membuat (skala besar)"},{"kanji":"製造","hiragana":"せいぞう","meaning":"manufaktur"},{"kanji":"構造","hiragana":"こうぞう","meaning":"struktur"}]'::jsonb, 49)
(3, '製', 'セイ', 'sei', 'Buatan, produk', 'Pakaian (衣) dibuat menurut aturan (制) — produk buatan.', 14, '[{"kanji":"製品","hiragana":"せいひん","meaning":"produk"},{"kanji":"日本製","hiragana":"にほんせい","meaning":"buatan Jepang"},{"kanji":"製造","hiragana":"せいぞう","meaning":"manufaktur"}]'::jsonb, 50)
-- ─── Tempat & lingkungan ─────────────────────────────────────
(3, '都', 'ト／ツ／みやこ', 'to / tsu / miyako', 'Ibu kota, metropolitan', 'Kota besar (者+阝) — ibu kota.', 11, '[{"kanji":"都市","hiragana":"とし","meaning":"kota besar"},{"kanji":"東京都","hiragana":"とうきょうと","meaning":"Metropolitan Tokyo"},{"kanji":"都合","hiragana":"つごう","meaning":"keadaan, kesempatan"}]'::jsonb, 51)
(3, '内', 'ナイ／うち', 'nai / uchi', 'Dalam', 'Sesuatu masuk (入) ke dalam batas — bagian dalam.', 4, '[{"kanji":"内","hiragana":"うち","meaning":"dalam"},{"kanji":"案内","hiragana":"あんない","meaning":"panduan"},{"kanji":"内容","hiragana":"ないよう","meaning":"isi"}]'::jsonb, 52)
(3, '周', 'シュウ／まわ.り', 'shuu / mawa.ri', 'Sekeliling', 'Keliling area sawah — sekitar, keliling.', 8, '[{"kanji":"周り","hiragana":"まわり","meaning":"sekeliling"},{"kanji":"周辺","hiragana":"しゅうへん","meaning":"sekitar, pinggiran"},{"kanji":"一周","hiragana":"いっしゅう","meaning":"satu putaran"}]'::jsonb, 53)
(3, '角', 'カク／かど／つの', 'kaku / kado / tsuno', 'Sudut, tanduk', 'Bentuk tanduk binatang — sudut, tanduk.', 7, '[{"kanji":"角","hiragana":"かど","meaning":"sudut, pojok"},{"kanji":"三角","hiragana":"さんかく","meaning":"segitiga"},{"kanji":"角度","hiragana":"かくど","meaning":"sudut (derajat)"}]'::jsonb, 54)
(3, '野', 'ヤ／の', 'ya / no', 'Padang, liar', 'Tanah desa (里) yang luas — padang, alam liar.', 11, '[{"kanji":"野菜","hiragana":"やさい","meaning":"sayuran"},{"kanji":"野球","hiragana":"やきゅう","meaning":"bisbol"},{"kanji":"分野","hiragana":"ぶんや","meaning":"bidang"}]'::jsonb, 55)
-- ─── Pikiran, indera & komunikasi ────────────────────────────
(3, '覚', 'カク／おぼ.える／さ.める', 'kaku / obo.eru / sa.meru', 'Mengingat, sadar', 'Melihat (見) dan menyadari — mengingat, sadar.', 12, '[{"kanji":"覚える","hiragana":"おぼえる","meaning":"menghafal, mengingat"},{"kanji":"感覚","hiragana":"かんかく","meaning":"indra, sensasi"},{"kanji":"目が覚める","hiragana":"めがさめる","meaning":"terbangun"}]'::jsonb, 56)
(3, '説', 'セツ／と.く', 'setsu / to.ku', 'Menjelaskan, teori', 'Perkataan (言) yang menggembirakan (兌) dengan jelas — menjelaskan.', 14, '[{"kanji":"説明","hiragana":"せつめい","meaning":"penjelasan"},{"kanji":"小説","hiragana":"しょうせつ","meaning":"novel"},{"kanji":"説得","hiragana":"せっとく","meaning":"persuasi"}]'::jsonb, 57)
(3, '伝', 'デン／つた.える', 'den / tsuta.eru', 'Menyampaikan', 'Orang (亻) meneruskan (云) pesan — menyampaikan.', 6, '[{"kanji":"伝える","hiragana":"つたえる","meaning":"menyampaikan"},{"kanji":"手伝う","hiragana":"てつだう","meaning":"membantu"},{"kanji":"伝統","hiragana":"でんとう","meaning":"tradisi"}]'::jsonb, 58)
(3, '報', 'ホウ／むく.いる', 'hou / muku.iru', 'Melaporkan, membalas', 'Berita yang disampaikan sebagai balasan — laporan, informasi.', 12, '[{"kanji":"報告","hiragana":"ほうこく","meaning":"laporan"},{"kanji":"情報","hiragana":"じょうほう","meaning":"informasi"},{"kanji":"予報","hiragana":"よほう","meaning":"prakiraan"}]'::jsonb, 59)
(3, '調', 'チョウ／しら.べる', 'chou / shira.beru', 'Memeriksa, nada', 'Perkataan (言) yang ditata merata (周) — menyelaraskan, memeriksa.', 15, '[{"kanji":"調べる","hiragana":"しらべる","meaning":"memeriksa, menyelidiki"},{"kanji":"調子","hiragana":"ちょうし","meaning":"kondisi, irama"},{"kanji":"調査","hiragana":"ちょうさ","meaning":"survei, investigasi"}]'::jsonb, 60)
-- ─── Tubuh & kesehatan ───────────────────────────────────────
(3, '耳', 'ジ／みみ', 'ji / mimi', 'Telinga', 'Gambar bentuk telinga — telinga.', 6, '[{"kanji":"耳","hiragana":"みみ","meaning":"telinga"},{"kanji":"耳鼻科","hiragana":"じびか","meaning":"THT"},{"kanji":"中耳炎","hiragana":"ちゅうじえん","meaning":"radang telinga tengah"}]'::jsonb, 61)
(3, '腕', 'ワン／うで', 'wan / ude', 'Lengan, keahlian', 'Bagian tubuh (月) yang lentur (宛) — lengan; juga keahlian.', 12, '[{"kanji":"腕","hiragana":"うで","meaning":"lengan"},{"kanji":"腕時計","hiragana":"うでどけい","meaning":"jam tangan"},{"kanji":"腕前","hiragana":"うでまえ","meaning":"keterampilan"}]'::jsonb, 62)
(3, '背', 'ハイ／せ／せい', 'hai / se / sei', 'Punggung, tinggi badan', 'Bagian tubuh (月) yang berlawanan (北) dengan depan — punggung.', 9, '[{"kanji":"背中","hiragana":"せなか","meaning":"punggung"},{"kanji":"背が高い","hiragana":"せがたかい","meaning":"badan tinggi"},{"kanji":"背景","hiragana":"はいけい","meaning":"latar belakang"}]'::jsonb, 63)
(3, '腹', 'フク／はら', 'fuku / hara', 'Perut', 'Bagian tubuh (月) yang penuh berulang (复) — perut.', 13, '[{"kanji":"お腹","hiragana":"おなか","meaning":"perut"},{"kanji":"腹痛","hiragana":"ふくつう","meaning":"sakit perut"},{"kanji":"満腹","hiragana":"まんぷく","meaning":"kenyang"}]'::jsonb, 64)
(3, '血', 'ケツ／ち', 'ketsu / chi', 'Darah', 'Tetesan di atas wadah persembahan — darah.', 6, '[{"kanji":"血","hiragana":"ち","meaning":"darah"},{"kanji":"血液","hiragana":"けつえき","meaning":"darah (medis)"},{"kanji":"出血","hiragana":"しゅっけつ","meaning":"pendarahan"}]'::jsonb, 65)
(3, '痛', 'ツウ／いた.い', 'tsuu / ita.i', 'Sakit, nyeri', 'Penyakit (疒) yang menembus (甬) — nyeri.', 12, '[{"kanji":"痛い","hiragana":"いたい","meaning":"sakit"},{"kanji":"頭痛","hiragana":"ずつう","meaning":"sakit kepala"},{"kanji":"痛み","hiragana":"いたみ","meaning":"rasa sakit"}]'::jsonb, 66)
(3, '熱', 'ネツ／あつ.い', 'netsu / atsu.i', 'Panas, demam', 'Api (灬) yang membara — panas, demam.', 15, '[{"kanji":"熱","hiragana":"ねつ","meaning":"demam, panas"},{"kanji":"熱心","hiragana":"ねっしん","meaning":"bersemangat"},{"kanji":"発熱","hiragana":"はつねつ","meaning":"timbul demam"}]'::jsonb, 67)
(3, '健', 'ケン／すこ.やか', 'ken / suko.yaka', 'Sehat', 'Orang (亻) yang berdiri tegak (建) — sehat.', 11, '[{"kanji":"健康","hiragana":"けんこう","meaning":"kesehatan"},{"kanji":"健診","hiragana":"けんしん","meaning":"pemeriksaan kesehatan"},{"kanji":"健全","hiragana":"けんぜん","meaning":"sehat (sistem)"}]'::jsonb, 68)
(3, '康', 'コウ', 'kou', 'Sehat, tenteram', 'Rumah yang sejahtera — kesehatan, ketenteraman.', 11, '[{"kanji":"健康","hiragana":"けんこう","meaning":"kesehatan"},{"kanji":"小康","hiragana":"しょうこう","meaning":"reda sementara"},{"kanji":"康復","hiragana":"こうふく","meaning":"pemulihan"}]'::jsonb, 69)
(3, '疲', 'ヒ／つか.れる', 'hi / tsuka.reru', 'Lelah', 'Penyakit (疒) di kulit (皮) yang membuat lemas — lelah.', 10, '[{"kanji":"疲れる","hiragana":"つかれる","meaning":"lelah"},{"kanji":"疲労","hiragana":"ひろう","meaning":"kelelahan"},{"kanji":"気疲れ","hiragana":"きづかれ","meaning":"lelah mental"}]'::jsonb, 70)
(3, '眠', 'ミン／ねむ.る／ねむ.い', 'min / nemu.ru / nemu.i', 'Tidur, mengantuk', 'Mata (目) yang menutup (民) — tidur.', 10, '[{"kanji":"眠る","hiragana":"ねむる","meaning":"tidur"},{"kanji":"眠い","hiragana":"ねむい","meaning":"mengantuk"},{"kanji":"睡眠","hiragana":"すいみん","meaning":"tidur (medis)"}]'::jsonb, 71)
-- ─── Alam & cuaca ────────────────────────────────────────────
(3, '雲', 'ウン／くも', 'un / kumo', 'Awan', 'Hujan (雨) yang mengepul (云) — awan.', 12, '[{"kanji":"雲","hiragana":"くも","meaning":"awan"},{"kanji":"雷雲","hiragana":"かみなりぐも","meaning":"awan petir"},{"kanji":"暗雲","hiragana":"あんうん","meaning":"awan gelap"}]'::jsonb, 72)
(3, '光', 'コウ／ひか.る／ひかり', 'kou / hika.ru / hikari', 'Cahaya', 'Api di atas orang — cahaya yang menyinari.', 6, '[{"kanji":"光","hiragana":"ひかり","meaning":"cahaya"},{"kanji":"光る","hiragana":"ひかる","meaning":"bersinar"},{"kanji":"観光","hiragana":"かんこう","meaning":"wisata"}]'::jsonb, 73)
(3, '暖', 'ダン／あたた.かい', 'dan / atata.kai', 'Hangat (udara)', 'Matahari (日) yang menghangatkan (爰) — hangat.', 13, '[{"kanji":"暖かい","hiragana":"あたたかい","meaning":"hangat (udara)"},{"kanji":"暖房","hiragana":"だんぼう","meaning":"pemanas ruangan"},{"kanji":"温暖","hiragana":"おんだん","meaning":"hangat (iklim)"}]'::jsonb, 74)
(3, '涼', 'リョウ／すず.しい', 'ryou / suzu.shii', 'Sejuk', 'Air (氵) yang membuat segar (京) — sejuk.', 11, '[{"kanji":"涼しい","hiragana":"すずしい","meaning":"sejuk"},{"kanji":"涼む","hiragana":"すずむ","meaning":"mendinginkan diri"},{"kanji":"納涼","hiragana":"のうりょう","meaning":"menikmati kesejukan"}]'::jsonb, 75)
(3, '晴', 'セイ／は.れる', 'sei / ha.reru', 'Cerah', 'Matahari (日) yang biru jernih (青) — cuaca cerah.', 12, '[{"kanji":"晴れる","hiragana":"はれる","meaning":"cerah"},{"kanji":"晴天","hiragana":"せいてん","meaning":"langit cerah"},{"kanji":"快晴","hiragana":"かいせい","meaning":"cerah sempurna"}]'::jsonb, 76)
(3, '曇', 'ドン／くも.る', 'don / kumo.ru', 'Mendung', 'Matahari (日) tertutup awan (雲) — mendung.', 16, '[{"kanji":"曇る","hiragana":"くもる","meaning":"mendung, berkabut"},{"kanji":"曇り","hiragana":"くもり","meaning":"cuaca mendung"},{"kanji":"曇天","hiragana":"どんてん","meaning":"langit mendung"}]'::jsonb, 77)
(3, '台', 'ダイ／タイ', 'dai / tai', 'Dudukan, satuan mesin', 'Dasar tempat berdiri — alas, dudukan, satuan.', 5, '[{"kanji":"台所","hiragana":"だいどころ","meaning":"dapur"},{"kanji":"台風","hiragana":"たいふう","meaning":"topan"},{"kanji":"一台","hiragana":"いちだい","meaning":"satu (mesin/mobil)"}]'::jsonb, 78)
(3, '波', 'ハ／なみ', 'ha / nami', 'Ombak, gelombang', 'Air (氵) yang berlipat di permukaan (皮) — ombak.', 8, '[{"kanji":"波","hiragana":"なみ","meaning":"ombak"},{"kanji":"電波","hiragana":"でんぱ","meaning":"gelombang radio"},{"kanji":"津波","hiragana":"つなみ","meaning":"tsunami"}]'::jsonb, 79)
(3, '草', 'ソウ／くさ', 'sou / kusa', 'Rumput', 'Tumbuhan (艹) yang muncul pagi (早) — rumput.', 9, '[{"kanji":"草","hiragana":"くさ","meaning":"rumput"},{"kanji":"草原","hiragana":"そうげん","meaning":"padang rumput"},{"kanji":"雑草","hiragana":"ざっそう","meaning":"gulma"}]'::jsonb, 80)
(3, '葉', 'ヨウ／は', 'you / ha', 'Daun', 'Tumbuhan (艹) pada generasi pohon (世+木) — daun.', 12, '[{"kanji":"葉","hiragana":"は","meaning":"daun"},{"kanji":"言葉","hiragana":"ことば","meaning":"kata, bahasa"},{"kanji":"紅葉","hiragana":"こうよう","meaning":"daun musim gugur"}]'::jsonb, 81)
-- ─── Sifat & kondisi ─────────────────────────────────────────
(3, '弱', 'ジャク／よわ.い', 'jaku / yowa.i', 'Lemah', 'Dua busur lentur dengan hiasan — lemah.', 10, '[{"kanji":"弱い","hiragana":"よわい","meaning":"lemah"},{"kanji":"弱点","hiragana":"じゃくてん","meaning":"kelemahan"},{"kanji":"弱気","hiragana":"よわき","meaning":"penakut, pesimis"}]'::jsonb, 82)
(3, '重', 'ジュウ／チョウ／おも.い／かさ.ねる', 'juu / chou / omo.i / kasa.neru', 'Berat, bertumpuk', 'Orang memikul beban berat — berat, penting.', 9, '[{"kanji":"重い","hiragana":"おもい","meaning":"berat"},{"kanji":"重要","hiragana":"じゅうよう","meaning":"penting"},{"kanji":"体重","hiragana":"たいじゅう","meaning":"berat badan"}]'::jsonb, 83)
(3, '軽', 'ケイ／かる.い', 'kei / karu.i', 'Ringan', 'Kendaraan (車) yang ringan jalannya — ringan.', 12, '[{"kanji":"軽い","hiragana":"かるい","meaning":"ringan"},{"kanji":"軽食","hiragana":"けいしょく","meaning":"makanan ringan"},{"kanji":"気軽","hiragana":"きがる","meaning":"santai, tanpa beban"}]'::jsonb, 84)
(3, '硬', 'コウ／かた.い', 'kou / kata.i', 'Keras (benda)', 'Batu (石) yang kokoh (更) — keras.', 12, '[{"kanji":"硬い","hiragana":"かたい","meaning":"keras (benda)"},{"kanji":"硬貨","hiragana":"こうか","meaning":"koin"},{"kanji":"強硬","hiragana":"きょうこう","meaning":"keras (sikap)"}]'::jsonb, 85)
(3, '柔', 'ジュウ／ニュウ／やわ.らかい', 'juu / nyuu / yawa.rakai', 'Lembut, lentur', 'Tombak (矛) dan pohon (木) yang lentur — lembut.', 9, '[{"kanji":"柔らかい","hiragana":"やわらかい","meaning":"lembut"},{"kanji":"柔道","hiragana":"じゅうどう","meaning":"judo"},{"kanji":"柔軟","hiragana":"じゅうなん","meaning":"fleksibel"}]'::jsonb, 86)
(3, '速', 'ソク／はや.い', 'soku / haya.i', 'Cepat', 'Berjalan (辶) dengan ikatan (束) yang cepat — cepat.', 10, '[{"kanji":"速い","hiragana":"はやい","meaning":"cepat (kecepatan)"},{"kanji":"速度","hiragana":"そくど","meaning":"kecepatan"},{"kanji":"高速","hiragana":"こうそく","meaning":"berkecepatan tinggi"}]'::jsonb, 87)
(3, '遅', 'チ／おく.れる／おそ.い', 'chi / oku.reru / oso.i', 'Terlambat, lambat', 'Berjalan (辶) seperti kambing (犀) yang lamban — lambat.', 12, '[{"kanji":"遅い","hiragana":"おそい","meaning":"lambat, larut"},{"kanji":"遅れる","hiragana":"おくれる","meaning":"terlambat"},{"kanji":"遅刻","hiragana":"ちこく","meaning":"keterlambatan"}]'::jsonb, 88)
(3, '正', 'セイ／ショウ／ただ.しい', 'sei / shou / tada.shii', 'Benar, lurus', 'Berhenti (止) pada garis yang tepat (一) — benar.', 5, '[{"kanji":"正しい","hiragana":"ただしい","meaning":"benar"},{"kanji":"正確","hiragana":"せいかく","meaning":"akurat"},{"kanji":"正直","hiragana":"しょうじき","meaning":"jujur"}]'::jsonb, 89)
(3, '誤', 'ゴ／あやま.る', 'go / ayama.ru', 'Salah, keliru', 'Perkataan (言) yang keliru (呉) — salah.', 14, '[{"kanji":"誤る","hiragana":"あやまる","meaning":"keliru, salah"},{"kanji":"誤解","hiragana":"ごかい","meaning":"salah paham"},{"kanji":"誤字","hiragana":"ごじ","meaning":"salah huruf"}]'::jsonb, 90)
(3, '良', 'リョウ／よ.い', 'ryou / yo.i', 'Baik', 'Sesuatu yang murni dan pilihan — baik.', 7, '[{"kanji":"良い","hiragana":"よい","meaning":"baik"},{"kanji":"良好","hiragana":"りょうこう","meaning":"kondisi baik"},{"kanji":"改良","hiragana":"かいりょう","meaning":"perbaikan"}]'::jsonb, 91)
(3, '悪', 'アク／オ／わる.い', 'aku / o / waru.i', 'Buruk, jahat', 'Hati (心) yang tertekan (亜) — buruk, jahat.', 11, '[{"kanji":"悪い","hiragana":"わるい","meaning":"buruk"},{"kanji":"悪化","hiragana":"あっか","meaning":"memburuk"},{"kanji":"最悪","hiragana":"さいあく","meaning":"terburuk"}]'::jsonb, 92)
(3, '美', 'ビ／うつく.しい', 'bi / utsuku.shii', 'Indah', 'Domba (羊) yang besar (大) dianggap indah — indah.', 9, '[{"kanji":"美しい","hiragana":"うつくしい","meaning":"indah"},{"kanji":"美術","hiragana":"びじゅつ","meaning":"seni rupa"},{"kanji":"美容","hiragana":"びよう","meaning":"kecantikan"}]'::jsonb, 93)
(3, '醜', 'シュウ／みにく.い', 'shuu / miniku.i', 'Buruk rupa, jelek', 'Arak (酉) dan setan (鬼) — buruk rupa, memalukan.', 17, '[{"kanji":"醜い","hiragana":"みにくい","meaning":"buruk rupa"},{"kanji":"醜聞","hiragana":"しゅうぶん","meaning":"skandal"},{"kanji":"醜態","hiragana":"しゅうたい","meaning":"tingkah memalukan"}]'::jsonb, 94)
(3, '易', 'エキ／イ／やさ.しい', 'eki / i / yasa.shii', 'Mudah', 'Bunglon yang mudah berubah — mudah, gampang.', 8, '[{"kanji":"易しい","hiragana":"やさしい","meaning":"mudah"},{"kanji":"簡単","hiragana":"かんたん","meaning":"sederhana"},{"kanji":"貿易","hiragana":"ぼうえき","meaning":"perdagangan"}]'::jsonb, 95)
(3, '難', 'ナン／むずか.しい', 'nan / muzuka.shii', 'Sulit', 'Sesuatu yang sukar diatasi seperti burung (隹) di tanah liat — sulit.', 18, '[{"kanji":"難しい","hiragana":"むずかしい","meaning":"sulit"},{"kanji":"困難","hiragana":"こんなん","meaning":"kesulitan"},{"kanji":"難民","hiragana":"なんみん","meaning":"pengungsi"}]'::jsonb, 96)
(3, '深', 'シン／ふか.い', 'shin / fuka.i', 'Dalam', 'Air (氵) yang dalam sampai dasar — dalam.', 11, '[{"kanji":"深い","hiragana":"ふかい","meaning":"dalam"},{"kanji":"深夜","hiragana":"しんや","meaning":"larut malam"},{"kanji":"深呼吸","hiragana":"しんこきゅう","meaning":"tarik napas dalam"}]'::jsonb, 97)
(3, '浅', 'セン／あさ.い', 'sen / asa.i', 'Dangkal', 'Air (氵) yang sedikit (戔) — dangkal.', 9, '[{"kanji":"浅い","hiragana":"あさい","meaning":"dangkal"},{"kanji":"浅瀬","hiragana":"あさせ","meaning":"perairan dangkal"},{"kanji":"経験が浅い","hiragana":"けいけんがあさい","meaning":"minim pengalaman"}]'::jsonb, 98)
(3, '細', 'サイ／ほそ.い／こま.かい', 'sai / hoso.i / koma.kai', 'Halus, tipis', 'Benang (糸) yang halus (田) — tipis, rinci.', 11, '[{"kanji":"細い","hiragana":"ほそい","meaning":"tipis, ramping"},{"kanji":"細かい","hiragana":"こまかい","meaning":"rinci, kecil-kecil"},{"kanji":"詳細","hiragana":"しょうさい","meaning":"detail"}]'::jsonb, 99)
(3, '太', 'タイ／タ／ふと.い', 'tai / ta / futo.i', 'Gemuk, tebal', 'Orang besar (大) dengan tambahan titik — gemuk, tebal.', 4, '[{"kanji":"太い","hiragana":"ふとい","meaning":"tebal, besar (diameter)"},{"kanji":"太る","hiragana":"ふとる","meaning":"menjadi gemuk"},{"kanji":"太陽","hiragana":"たいよう","meaning":"matahari"}]'::jsonb, 100)
(3, '丸', 'ガン／まる.い', 'gan / maru.i', 'Bulat', 'Bentuk membulat — bulat.', 3, '[{"kanji":"丸い","hiragana":"まるい","meaning":"bulat"},{"kanji":"丸","hiragana":"まる","meaning":"lingkaran"},{"kanji":"一丸","hiragana":"いちがん","meaning":"bersatu padu"}]'::jsonb, 101)
(3, '平', 'ヘイ／ビョウ／たい.ら', 'hei / byou / tai.ra', 'Datar, damai', 'Permukaan yang rata — datar, damai.', 5, '[{"kanji":"平和","hiragana":"へいわ","meaning":"perdamaian"},{"kanji":"平日","hiragana":"へいじつ","meaning":"hari kerja"},{"kanji":"平ら","hiragana":"たいら","meaning":"rata"}]'::jsonb, 102)
(3, '真', 'シン／ま', 'shin / ma', 'Sejati, benar-benar', 'Sesuatu yang asli dan murni — sejati.', 10, '[{"kanji":"真面目","hiragana":"まじめ","meaning":"serius, rajin"},{"kanji":"真実","hiragana":"しんじつ","meaning":"kebenaran"},{"kanji":"写真","hiragana":"しゃしん","meaning":"foto"}]'::jsonb, 103)
(3, '偽', 'ギ／にせ／いつわ.る', 'gi / nise / itsuwa.ru', 'Palsu', 'Orang (亻) yang berbuat (為) tipu — palsu.', 11, '[{"kanji":"偽","hiragana":"にせ","meaning":"palsu"},{"kanji":"偽物","hiragana":"にせもの","meaning":"barang palsu"},{"kanji":"偽造","hiragana":"ぎぞう","meaning":"pemalsuan"}]'::jsonb, 104)
(3, '全', 'ゼン／まった.く／すべ.て', 'zen / matta.ku / sube.te', 'Seluruh, lengkap', 'Atap (人) menutupi raja (王) — seluruhnya, lengkap.', 6, '[{"kanji":"全部","hiragana":"ぜんぶ","meaning":"semua"},{"kanji":"全体","hiragana":"ぜんたい","meaning":"keseluruhan"},{"kanji":"安全","hiragana":"あんぜん","meaning":"keselamatan"}]'::jsonb, 105)
(3, '半', 'ハン／なか.ば', 'han / naka.ba', 'Setengah', 'Benda yang dibelah jadi dua — setengah.', 5, '[{"kanji":"半分","hiragana":"はんぶん","meaning":"separuh"},{"kanji":"半年","hiragana":"はんとし","meaning":"setengah tahun"},{"kanji":"後半","hiragana":"こうはん","meaning":"paruh kedua"}]'::jsonb, 106)
(3, '満', 'マン／み.ちる', 'man / mi.chiru', 'Penuh', 'Air (氵) yang meluap penuh (㒼) — penuh.', 12, '[{"kanji":"満員","hiragana":"まんいん","meaning":"penuh (orang)"},{"kanji":"満足","hiragana":"まんぞく","meaning":"puas"},{"kanji":"不満","hiragana":"ふまん","meaning":"tidak puas"}]'::jsonb, 107)
-- ─── Angka, ukuran & derajat ─────────────────────────────────
(3, '億', 'オク', 'oku', 'Seratus juta', 'Orang (亻) dengan ide besar (意) — jumlah amat besar, 100 juta.', 15, '[{"kanji":"一億","hiragana":"いちおく","meaning":"seratus juta"},{"kanji":"億万長者","hiragana":"おくまんちょうじゃ","meaning":"miliarder"},{"kanji":"数億","hiragana":"すうおく","meaning":"beberapa ratus juta"}]'::jsonb, 108)
(3, '兆', 'チョウ／きざ.し', 'chou / kiza.shi', 'Triliun, pertanda', 'Retakan cangkang ramalan — pertanda; juga triliun.', 6, '[{"kanji":"一兆","hiragana":"いっちょう","meaning":"satu triliun"},{"kanji":"兆候","hiragana":"ちょうこう","meaning":"gejala, tanda"},{"kanji":"前兆","hiragana":"ぜんちょう","meaning":"pertanda"}]'::jsonb, 109)
(3, '倍', 'バイ', 'bai', 'Kali lipat', 'Orang (亻) yang membelah berlipat (咅) — kelipatan.', 10, '[{"kanji":"倍","hiragana":"ばい","meaning":"dua kali lipat"},{"kanji":"二倍","hiragana":"にばい","meaning":"dua kali lipat"},{"kanji":"倍率","hiragana":"ばいりつ","meaning":"rasio, perbesaran"}]'::jsonb, 110)
(3, '割', 'カツ／わ.る／わ.り', 'katsu / wa.ru / wa.ri', 'Membagi, persentase (×10%)', 'Pisau (刂) membelah (害) — membagi; 一割 = 10%.', 12, '[{"kanji":"割る","hiragana":"わる","meaning":"membagi, memecah"},{"kanji":"割引","hiragana":"わりびき","meaning":"diskon"},{"kanji":"役割","hiragana":"やくわり","meaning":"peran"}]'::jsonb, 111)
(3, '以', 'イ', 'i', 'Dengan, sejak (batas)', 'Menyatakan titik patokan — sejak, lebih dari.', 5, '[{"kanji":"以上","hiragana":"いじょう","meaning":"ke atas, lebih dari"},{"kanji":"以下","hiragana":"いか","meaning":"ke bawah, kurang dari"},{"kanji":"以外","hiragana":"いがい","meaning":"selain"}]'::jsonb, 112)
(3, '超', 'チョウ／こ.える', 'chou / ko.eru', 'Melampaui, super', 'Berlari (走) memanggil (召) melewati batas — melampaui.', 12, '[{"kanji":"超える","hiragana":"こえる","meaning":"melampaui"},{"kanji":"超過","hiragana":"ちょうか","meaning":"kelebihan"},{"kanji":"超人","hiragana":"ちょうじん","meaning":"manusia super"}]'::jsonb, 113)
(3, '程', 'テイ／ほど', 'tei / hodo', 'Derajat, sekitar', 'Padi (禾) diukur menurut aturan (呈) — tingkatan, kira-kira.', 12, '[{"kanji":"程度","hiragana":"ていど","meaning":"tingkat, kadar"},{"kanji":"日程","hiragana":"にってい","meaning":"jadwal"},{"kanji":"過程","hiragana":"かてい","meaning":"proses"}]'::jsonb, 114)
(3, '度', 'ド／タク／たび', 'do / taku / tabi', 'Derajat, kali', 'Ukuran yang diukur dengan tangan — derajat, kali.', 9, '[{"kanji":"今度","hiragana":"こんど","meaning":"kali ini, lain kali"},{"kanji":"温度","hiragana":"おんど","meaning":"suhu"},{"kanji":"態度","hiragana":"たいど","meaning":"sikap"}]'::jsonb, 115)
(3, '量', 'リョウ／はか.る', 'ryou / haka.ru', 'Jumlah, mengukur', 'Matahari (日) menimbang berat (重) — kuantitas.', 12, '[{"kanji":"量","hiragana":"りょう","meaning":"jumlah, kuantitas"},{"kanji":"大量","hiragana":"たいりょう","meaning":"jumlah besar"},{"kanji":"測量","hiragana":"そくりょう","meaning":"pengukuran"}]'::jsonb, 116)
-- ─── Rencana, izin & kejadian (compound) ─────────────────────
(3, '準', 'ジュン', 'jun', 'Standar, persiapan', 'Air (氵) sebagai patokan datar — standar, persiapan.', 13, '[{"kanji":"準備","hiragana":"じゅんび","meaning":"persiapan"},{"kanji":"基準","hiragana":"きじゅん","meaning":"standar"},{"kanji":"準決勝","hiragana":"じゅんけっしょう","meaning":"semifinal"}]'::jsonb, 117)
(3, '備', 'ビ／そな.える', 'bi / sona.eru', 'Menyiapkan, melengkapi', 'Orang (亻) menyiapkan perlengkapan — bersiap.', 12, '[{"kanji":"準備","hiragana":"じゅんび","meaning":"persiapan"},{"kanji":"設備","hiragana":"せつび","meaning":"fasilitas, peralatan"},{"kanji":"備える","hiragana":"そなえる","meaning":"menyiapkan, berjaga"}]'::jsonb, 118)
(3, '予', 'ヨ', 'yo', 'Sebelumnya, prakira', 'Sesuatu yang dilakukan lebih dulu — pra-, sebelumnya.', 4, '[{"kanji":"予約","hiragana":"よやく","meaning":"reservasi"},{"kanji":"予定","hiragana":"よてい","meaning":"rencana, jadwal"},{"kanji":"予報","hiragana":"よほう","meaning":"prakiraan"}]'::jsonb, 119)
(3, '定', 'テイ／ジョウ／さだ.める', 'tei / jou / sada.meru', 'Menetapkan, tetap', 'Rumah (宀) yang stabil (疋) — menetapkan.', 8, '[{"kanji":"予定","hiragana":"よてい","meaning":"rencana"},{"kanji":"決定","hiragana":"けってい","meaning":"keputusan"},{"kanji":"定期","hiragana":"ていき","meaning":"berkala, tetap"}]'::jsonb, 120)
(3, '案', 'アン', 'an', 'Usulan, ide', 'Meja (木) tempat menaruh gagasan (安) — usulan.', 10, '[{"kanji":"案内","hiragana":"あんない","meaning":"panduan"},{"kanji":"提案","hiragana":"ていあん","meaning":"usulan"},{"kanji":"案外","hiragana":"あんがい","meaning":"di luar dugaan"}]'::jsonb, 121)
(3, '提', 'テイ／さ.げる', 'tei / sa.geru', 'Mengajukan, menjinjing', 'Tangan (扌) mengangkat dan menyodorkan (是) — mengajukan.', 12, '[{"kanji":"提案","hiragana":"ていあん","meaning":"usulan"},{"kanji":"提出","hiragana":"ていしゅつ","meaning":"penyerahan"},{"kanji":"提供","hiragana":"ていきょう","meaning":"penyediaan"}]'::jsonb, 122)
(3, '申', 'シン／もう.す', 'shin / mou.su', 'Mengatakan (rendah hati)', 'Petir membentang — menyampaikan; juga bentuk rendah hati "berkata".', 5, '[{"kanji":"申し込み","hiragana":"もうしこみ","meaning":"pendaftaran"},{"kanji":"申請","hiragana":"しんせい","meaning":"pengajuan (resmi)"},{"kanji":"申し訳ない","hiragana":"もうしわけない","meaning":"mohon maaf"}]'::jsonb, 123)
(3, '連', 'レン／つら.なる／つ.れる', 'ren / tsura.naru / tsu.reru', 'Bersambung, mengajak', 'Kendaraan (車) berjalan (辶) beriringan — berturut, mengajak.', 10, '[{"kanji":"連絡","hiragana":"れんらく","meaning":"kontak, kabar"},{"kanji":"連続","hiragana":"れんぞく","meaning":"berturut-turut"},{"kanji":"連れる","hiragana":"つれる","meaning":"mengajak"}]'::jsonb, 124)
(3, '絡', 'ラク／から.む', 'raku / kara.mu', 'Terjalin, menghubungi', 'Benang (糸) yang saling melilit (各) — terjalin.', 12, '[{"kanji":"連絡","hiragana":"れんらく","meaning":"kontak, kabar"},{"kanji":"絡む","hiragana":"からむ","meaning":"terjalin, terkait"},{"kanji":"連絡先","hiragana":"れんらくさき","meaning":"kontak (alamat/no)"}]'::jsonb, 125)
(3, '確', 'カク／たし.か／たし.かめる', 'kaku / tashi.ka / tashi.kameru', 'Pasti, memastikan', 'Batu (石) yang kokoh seperti burung bangau (隺) — pasti.', 15, '[{"kanji":"確認","hiragana":"かくにん","meaning":"konfirmasi"},{"kanji":"確かめる","hiragana":"たしかめる","meaning":"memastikan"},{"kanji":"正確","hiragana":"せいかく","meaning":"akurat"}]'::jsonb, 126)
(3, '認', 'ニン／みと.める', 'nin / mito.meru', 'Mengakui, menyetujui', 'Perkataan (言) yang ditahan di hati (忍) — mengakui.', 14, '[{"kanji":"確認","hiragana":"かくにん","meaning":"konfirmasi"},{"kanji":"認める","hiragana":"みとめる","meaning":"mengakui"},{"kanji":"承認","hiragana":"しょうにん","meaning":"persetujuan"}]'::jsonb, 127)
(3, '許', 'キョ／ゆる.す', 'kyo / yuru.su', 'Mengizinkan', 'Perkataan (言) yang membolehkan (午) — mengizinkan.', 11, '[{"kanji":"許す","hiragana":"ゆるす","meaning":"mengizinkan, memaafkan"},{"kanji":"許可","hiragana":"きょか","meaning":"izin"},{"kanji":"免許","hiragana":"めんきょ","meaning":"lisensi, SIM"}]'::jsonb, 128)
(3, '可', 'カ', 'ka', 'Boleh, bisa', 'Mulut menyetujui — boleh, mungkin.', 5, '[{"kanji":"可能","hiragana":"かのう","meaning":"mungkin, bisa"},{"kanji":"許可","hiragana":"きょか","meaning":"izin"},{"kanji":"可愛い","hiragana":"かわいい","meaning":"imut"}]'::jsonb, 129)
(3, '禁', 'キン', 'kin', 'Larangan', 'Hutan (林) di depan altar (示) yang terlarang — larangan.', 13, '[{"kanji":"禁止","hiragana":"きんし","meaning":"larangan"},{"kanji":"禁煙","hiragana":"きんえん","meaning":"dilarang merokok"},{"kanji":"厳禁","hiragana":"げんきん","meaning":"dilarang keras"}]'::jsonb, 130)
(3, '危', 'キ／あぶ.ない', 'ki / abu.nai', 'Bahaya', 'Orang di tepi tebing — berbahaya.', 6, '[{"kanji":"危ない","hiragana":"あぶない","meaning":"berbahaya"},{"kanji":"危険","hiragana":"きけん","meaning":"bahaya"},{"kanji":"危機","hiragana":"きき","meaning":"krisis"}]'::jsonb, 131)
(3, '険', 'ケン／けわ.しい', 'ken / kewa.shii', 'Curam, bahaya', 'Bukit (阝) yang terjal dan banyak (僉) — curam, berisiko.', 11, '[{"kanji":"危険","hiragana":"きけん","meaning":"bahaya"},{"kanji":"保険","hiragana":"ほけん","meaning":"asuransi"},{"kanji":"冒険","hiragana":"ぼうけん","meaning":"petualangan"}]'::jsonb, 132)
(3, '故', 'コ／ゆえ', 'ko / yue', 'Sebab, lama, mendiang', 'Sesuatu lama (古) yang dipukul (攵) — sebab, kejadian.', 9, '[{"kanji":"事故","hiragana":"じこ","meaning":"kecelakaan"},{"kanji":"故障","hiragana":"こしょう","meaning":"kerusakan"},{"kanji":"故郷","hiragana":"こきょう","meaning":"kampung halaman"}]'::jsonb, 133)
(3, '件', 'ケン', 'ken', 'Perkara, kasus (satuan)', 'Orang (亻) dan sapi (牛) — urusan, perkara.', 6, '[{"kanji":"事件","hiragana":"じけん","meaning":"insiden, kasus"},{"kanji":"条件","hiragana":"じょうけん","meaning":"syarat"},{"kanji":"件名","hiragana":"けんめい","meaning":"subjek (email)"}]'::jsonb, 134)
(3, '解', 'カイ／ゲ／と.く', 'kai / ge / to.ku', 'Memecahkan, mengurai', 'Pisau (刀) memisahkan tanduk (角) sapi (牛) — mengurai, memecahkan.', 13, '[{"kanji":"解決","hiragana":"かいけつ","meaning":"penyelesaian"},{"kanji":"理解","hiragana":"りかい","meaning":"pemahaman"},{"kanji":"解説","hiragana":"かいせつ","meaning":"penjelasan"}]'::jsonb, 135)
(3, '決', 'ケツ／き.める／き.まる', 'ketsu / ki.meru / ki.maru', 'Memutuskan', 'Air (氵) yang menerobos tegas — memutuskan.', 7, '[{"kanji":"決める","hiragana":"きめる","meaning":"memutuskan"},{"kanji":"決定","hiragana":"けってい","meaning":"keputusan"},{"kanji":"解決","hiragana":"かいけつ","meaning":"penyelesaian"}]'::jsonb, 136)
(3, '改', 'カイ／あらた.める', 'kai / arata.meru', 'Memperbarui, mengubah', 'Diri sendiri (己) dipukul (攵) untuk berubah — memperbaiki.', 7, '[{"kanji":"改善","hiragana":"かいぜん","meaning":"perbaikan"},{"kanji":"改札","hiragana":"かいさつ","meaning":"gerbang tiket"},{"kanji":"改正","hiragana":"かいせい","meaning":"revisi (aturan)"}]'::jsonb, 137)
(3, '善', 'ゼン／よ.い', 'zen / yo.i', 'Kebaikan, baik', 'Domba (羊) dan perkataan baik — kebajikan.', 12, '[{"kanji":"改善","hiragana":"かいぜん","meaning":"perbaikan"},{"kanji":"善悪","hiragana":"ぜんあく","meaning":"baik-buruk"},{"kanji":"最善","hiragana":"さいぜん","meaning":"yang terbaik"}]'::jsonb, 138)
(3, '増', 'ゾウ／ふ.える／ふ.やす', 'zou / fu.eru / fu.yasu', 'Bertambah', 'Tanah (土) yang ditumpuk bertingkat (曽) — bertambah.', 14, '[{"kanji":"増える","hiragana":"ふえる","meaning":"bertambah"},{"kanji":"増加","hiragana":"ぞうか","meaning":"peningkatan"},{"kanji":"増税","hiragana":"ぞうぜい","meaning":"kenaikan pajak"}]'::jsonb, 139)
(3, '減', 'ゲン／へ.る／へ.らす', 'gen / he.ru / he.rasu', 'Berkurang', 'Air (氵) yang menyusut (咸) — berkurang.', 12, '[{"kanji":"減る","hiragana":"へる","meaning":"berkurang"},{"kanji":"減少","hiragana":"げんしょう","meaning":"penurunan"},{"kanji":"削減","hiragana":"さくげん","meaning":"pemotongan"}]'::jsonb, 140)
(3, '展', 'テン', 'ten', 'Membentang, pameran', 'Sesuatu yang dibentangkan — perkembangan, pameran.', 10, '[{"kanji":"発展","hiragana":"はってん","meaning":"perkembangan"},{"kanji":"展示","hiragana":"てんじ","meaning":"pameran"},{"kanji":"展開","hiragana":"てんかい","meaning":"pengembangan, alur"}]'::jsonb, 141)
(3, '成', 'セイ／ジョウ／な.る', 'sei / jou / na.ru', 'Menjadi, tercapai', 'Senjata yang menyelesaikan tugas — tercapai, terbentuk.', 6, '[{"kanji":"成功","hiragana":"せいこう","meaning":"keberhasilan"},{"kanji":"成長","hiragana":"せいちょう","meaning":"pertumbuhan"},{"kanji":"完成","hiragana":"かんせい","meaning":"penyelesaian"}]'::jsonb, 142)
(3, '努', 'ド／つと.める', 'do / tsuto.meru', 'Berupaya', 'Mengerahkan tenaga (力) seperti budak (奴) — berusaha keras.', 7, '[{"kanji":"努力","hiragana":"どりょく","meaning":"usaha"},{"kanji":"努める","hiragana":"つとめる","meaning":"berupaya"},{"kanji":"努力家","hiragana":"どりょくか","meaning":"orang pekerja keras"}]'::jsonb, 143)
(3, '力', 'リョク／リキ／ちから', 'ryoku / riki / chikara', 'Tenaga, kekuatan', 'Gambar lengan berotot — tenaga.', 2, '[{"kanji":"力","hiragana":"ちから","meaning":"tenaga, kekuatan"},{"kanji":"努力","hiragana":"どりょく","meaning":"usaha"},{"kanji":"協力","hiragana":"きょうりょく","meaning":"kerja sama"}]'::jsonb, 144)
(3, '標', 'ヒョウ', 'hyou', 'Tanda, sasaran', 'Pohon (木) dengan penanda di pucuk (票) — tanda, target.', 15, '[{"kanji":"目標","hiragana":"もくひょう","meaning":"target, sasaran"},{"kanji":"標準","hiragana":"ひょうじゅん","meaning":"standar"},{"kanji":"標識","hiragana":"ひょうしき","meaning":"rambu, tanda"}]'::jsonb, 145)
(3, '達', 'タツ', 'tatsu', 'Mencapai, jamak orang', 'Berjalan (辶) sampai tujuan — mencapai; juga penanda jamak (達).', 12, '[{"kanji":"達成","hiragana":"たっせい","meaning":"pencapaian"},{"kanji":"友達","hiragana":"ともだち","meaning":"teman"},{"kanji":"配達","hiragana":"はいたつ","meaning":"pengantaran"}]'::jsonb, 146)
(3, '功', 'コウ／ク', 'kou / ku', 'Jasa, keberhasilan', 'Hasil dari kerja keras (工) dan tenaga (力) — jasa, prestasi.', 5, '[{"kanji":"成功","hiragana":"せいこう","meaning":"keberhasilan"},{"kanji":"功績","hiragana":"こうせき","meaning":"jasa, kontribusi"},{"kanji":"功労","hiragana":"こうろう","meaning":"jasa besar"}]'::jsonb, 147)
(3, '失', 'シツ／うしな.う', 'shitsu / ushina.u', 'Kehilangan, gagal', 'Tangan yang menjatuhkan sesuatu — kehilangan.', 5, '[{"kanji":"失敗","hiragana":"しっぱい","meaning":"kegagalan"},{"kanji":"失礼","hiragana":"しつれい","meaning":"tidak sopan, permisi"},{"kanji":"失業","hiragana":"しつぎょう","meaning":"pengangguran"}]'::jsonb, 148)
(3, '敗', 'ハイ／やぶ.れる', 'hai / yabu.reru', 'Kalah, gagal', 'Harta (貝) yang dihancurkan (攵) — kekalahan.', 11, '[{"kanji":"失敗","hiragana":"しっぱい","meaning":"kegagalan"},{"kanji":"敗北","hiragana":"はいぼく","meaning":"kekalahan"},{"kanji":"勝敗","hiragana":"しょうはい","meaning":"menang-kalah"}]'::jsonb, 149)
(3, '結', 'ケツ／むす.ぶ', 'ketsu / musu.bu', 'Mengikat, hasil', 'Benang (糸) yang diikat erat (吉) — mengikat, menyimpulkan.', 12, '[{"kanji":"結果","hiragana":"けっか","meaning":"hasil"},{"kanji":"結婚","hiragana":"けっこん","meaning":"pernikahan"},{"kanji":"結局","hiragana":"けっきょく","meaning":"pada akhirnya"}]'::jsonb, 150)
(3, '果', 'カ／は.たす／は.て', 'ka / ha.tasu / ha.te', 'Buah, hasil', 'Buah di atas pohon (木) — buah, hasil.', 8, '[{"kanji":"結果","hiragana":"けっか","meaning":"hasil"},{"kanji":"効果","hiragana":"こうか","meaning":"efek"},{"kanji":"果物","hiragana":"くだもの","meaning":"buah-buahan"}]'::jsonb, 151)
-- ─── Dampak & sebab ──────────────────────────────────────────
(3, '影', 'エイ／かげ', 'ei / kage', 'Bayangan', 'Cahaya (景) yang membentuk corak (彡) — bayangan.', 15, '[{"kanji":"影響","hiragana":"えいきょう","meaning":"pengaruh"},{"kanji":"影","hiragana":"かげ","meaning":"bayangan"},{"kanji":"面影","hiragana":"おもかげ","meaning":"raut wajah yang terkenang"}]'::jsonb, 152)
(3, '響', 'キョウ／ひび.く', 'kyou / hibi.ku', 'Bergema, berpengaruh', 'Suara (音) dari kampung (郷) yang menggema — bergema.', 20, '[{"kanji":"影響","hiragana":"えいきょう","meaning":"pengaruh"},{"kanji":"響く","hiragana":"ひびく","meaning":"bergema"},{"kanji":"音響","hiragana":"おんきょう","meaning":"akustik"}]'::jsonb, 153)
(3, '原', 'ゲン／はら', 'gen / hara', 'Asal, dataran', 'Mata air dari tebing — sumber, asal; juga padang.', 10, '[{"kanji":"原因","hiragana":"げんいん","meaning":"penyebab"},{"kanji":"原料","hiragana":"げんりょう","meaning":"bahan baku"},{"kanji":"高原","hiragana":"こうげん","meaning":"dataran tinggi"}]'::jsonb, 154)
(3, '因', 'イン／よ.る', 'in / yo.ru', 'Sebab', 'Orang (大) dalam batas (囗) — sebab, penyebab.', 6, '[{"kanji":"原因","hiragana":"げんいん","meaning":"penyebab"},{"kanji":"因果","hiragana":"いんが","meaning":"sebab-akibat"},{"kanji":"要因","hiragana":"よういん","meaning":"faktor"}]'::jsonb, 155)
-- ─── SSW / Kaigo (perawatan) ─────────────────────────────────
(3, '介', 'カイ', 'kai', 'Perantara, bantuan', 'Orang di antara dua sisi — menengahi, membantu.', 4, '[{"kanji":"介護","hiragana":"かいご","meaning":"perawatan (lansia/disabilitas)"},{"kanji":"介助","hiragana":"かいじょ","meaning":"asistensi (fisik)"},{"kanji":"紹介","hiragana":"しょうかい","meaning":"perkenalan"}]'::jsonb, 156)
(3, '護', 'ゴ／まも.る', 'go / mamo.ru', 'Melindungi, merawat', 'Perkataan (言) yang menjaga burung (蒦) — melindungi.', 20, '[{"kanji":"介護","hiragana":"かいご","meaning":"perawatan"},{"kanji":"看護師","hiragana":"かんごし","meaning":"perawat"},{"kanji":"保護","hiragana":"ほご","meaning":"perlindungan"}]'::jsonb, 157)
(3, '福', 'フク', 'fuku', 'Keberuntungan, kesejahteraan', 'Altar (示) penuh berkat (畐) — keberuntungan, kesejahteraan.', 13, '[{"kanji":"福祉","hiragana":"ふくし","meaning":"kesejahteraan sosial"},{"kanji":"幸福","hiragana":"こうふく","meaning":"kebahagiaan"},{"kanji":"福利","hiragana":"ふくり","meaning":"kesejahteraan (tunjangan)"}]'::jsonb, 158)
(3, '祉', 'シ', 'shi', 'Kesejahteraan', 'Altar (示) tempat memohon berhenti (止) pada berkah — kesejahteraan.', 8, '[{"kanji":"福祉","hiragana":"ふくし","meaning":"kesejahteraan sosial"},{"kanji":"社会福祉","hiragana":"しゃかいふくし","meaning":"kesejahteraan sosial"},{"kanji":"福祉施設","hiragana":"ふくししせつ","meaning":"fasilitas kesejahteraan"}]'::jsonb, 159)
(3, '施', 'シ／セ／ほどこ.す', 'shi / se / hodoko.su', 'Melaksanakan, memberi', 'Bendera yang dikibarkan — melaksanakan, memberi.', 9, '[{"kanji":"施設","hiragana":"しせつ","meaning":"fasilitas"},{"kanji":"実施","hiragana":"じっし","meaning":"pelaksanaan"},{"kanji":"施す","hiragana":"ほどこす","meaning":"memberikan, menerapkan"}]'::jsonb, 160)
(3, '設', 'セツ／もう.ける', 'setsu / mou.keru', 'Mendirikan, memasang', 'Perkataan (言) memerintahkan membangun (殳) — mendirikan.', 11, '[{"kanji":"施設","hiragana":"しせつ","meaning":"fasilitas"},{"kanji":"設備","hiragana":"せつび","meaning":"peralatan, fasilitas"},{"kanji":"設定","hiragana":"せってい","meaning":"pengaturan"}]'::jsonb, 161)
(3, '援', 'エン', 'en', 'Membantu, mendukung', 'Tangan (扌) yang mengulurkan pertolongan (爰) — mendukung.', 12, '[{"kanji":"支援","hiragana":"しえん","meaning":"dukungan, bantuan"},{"kanji":"応援","hiragana":"おうえん","meaning":"dukungan, sorakan"},{"kanji":"援助","hiragana":"えんじょ","meaning":"bantuan"}]'::jsonb, 162)
(3, '談', 'ダン', 'dan', 'Berbincang, konsultasi', 'Perkataan (言) yang hangat seperti api (炎) — berbincang.', 15, '[{"kanji":"相談","hiragana":"そうだん","meaning":"konsultasi"},{"kanji":"面談","hiragana":"めんだん","meaning":"wawancara, tatap muka"},{"kanji":"相談員","hiragana":"そうだんいん","meaning":"konselor"}]'::jsonb, 163)
(3, '記', 'キ／しる.す', 'ki / shiru.su', 'Mencatat', 'Perkataan (言) yang ditandai pada diri (己) — mencatat.', 10, '[{"kanji":"記録","hiragana":"きろく","meaning":"catatan, rekaman"},{"kanji":"記入","hiragana":"きにゅう","meaning":"pengisian (formulir)"},{"kanji":"日記","hiragana":"にっき","meaning":"buku harian"}]'::jsonb, 164)
(3, '録', 'ロク', 'roku', 'Merekam, mencatat', 'Logam (金) tempat mengukir catatan (彔) — merekam.', 16, '[{"kanji":"記録","hiragana":"きろく","meaning":"catatan, rekaman"},{"kanji":"登録","hiragana":"とうろく","meaning":"registrasi"},{"kanji":"録音","hiragana":"ろくおん","meaning":"rekaman suara"}]'::jsonb, 165)
(3, '告', 'コク／つ.げる', 'koku / tsu.geru', 'Memberitahu', 'Mulut (口) yang menyampaikan dengan jelas — memberitahu.', 7, '[{"kanji":"報告","hiragana":"ほうこく","meaning":"laporan"},{"kanji":"広告","hiragana":"こうこく","meaning":"iklan"},{"kanji":"申し送り","hiragana":"もうしおくり","meaning":"serah terima tugas (kaigo)"}]'::jsonb, 166)
(3, '携', 'ケイ／たずさ.わる', 'kei / tazusa.waru', 'Membawa, bekerja sama', 'Tangan (扌) yang menggandeng (巂) — menggenggam, terlibat.', 13, '[{"kanji":"連携","hiragana":"れんけい","meaning":"koordinasi, kerja sama"},{"kanji":"携帯","hiragana":"けいたい","meaning":"ponsel; membawa"},{"kanji":"携わる","hiragana":"たずさわる","meaning":"terlibat dalam"}]'::jsonb, 167)
(3, '排', 'ハイ', 'hai', 'Mengeluarkan, menolak', 'Tangan (扌) yang mendorong keluar (非) — mengeluarkan.', 11, '[{"kanji":"排泄","hiragana":"はいせつ","meaning":"ekskresi (BAB/BAK)"},{"kanji":"排出","hiragana":"はいしゅつ","meaning":"emisi, pembuangan"},{"kanji":"排除","hiragana":"はいじょ","meaning":"penyingkiran"}]'::jsonb, 168)
(3, '泄', 'セツ／エイ', 'setsu / ei', 'Membuang (ekskresi)', 'Air (氵) yang dikeluarkan tubuh — ekskresi.', 8, '[{"kanji":"排泄","hiragana":"はいせつ","meaning":"ekskresi (BAB/BAK)"},{"kanji":"排泄物","hiragana":"はいせつぶつ","meaning":"kotoran (tubuh)"},{"kanji":"排泄介助","hiragana":"はいせつかいじょ","meaning":"bantuan toileting"}]'::jsonb, 169)
(3, '浴', 'ヨク／あ.びる', 'yoku / a.biru', 'Mandi, mengguyur', 'Air (氵) yang menampung tubuh (谷) — mandi.', 10, '[{"kanji":"入浴","hiragana":"にゅうよく","meaning":"mandi berendam"},{"kanji":"浴びる","hiragana":"あびる","meaning":"mengguyur, terkena"},{"kanji":"入浴介助","hiragana":"にゅうよくかいじょ","meaning":"bantuan mandi (kaigo)"}]'::jsonb, 170)
-- ─── Masyarakat, hukum & pengetahuan ─────────────────────────
(3, '政', 'セイ／ショウ／まつりごと', 'sei / shou / matsurigoto', 'Pemerintahan, politik', 'Mengatur dengan benar (正) memakai tangan (攵) — pemerintahan.', 9, '[{"kanji":"政治","hiragana":"せいじ","meaning":"politik"},{"kanji":"政府","hiragana":"せいふ","meaning":"pemerintah"},{"kanji":"政策","hiragana":"せいさく","meaning":"kebijakan"}]'::jsonb, 171)
(3, '府', 'フ', 'fu', 'Pemerintahan, prefektur (Osaka/Kyoto)', 'Gudang (广) tempat menyimpan dokumen negara — pemerintahan.', 8, '[{"kanji":"政府","hiragana":"せいふ","meaning":"pemerintah"},{"kanji":"大阪府","hiragana":"おおさかふ","meaning":"Prefektur Osaka"},{"kanji":"府立","hiragana":"ふりつ","meaning":"milik prefektur"}]'::jsonb, 172)
(3, '法', 'ホウ／ハッ', 'hou / hat', 'Hukum, cara', 'Air (氵) yang mengalir menurut aturan (去) — hukum.', 8, '[{"kanji":"法律","hiragana":"ほうりつ","meaning":"undang-undang"},{"kanji":"方法","hiragana":"ほうほう","meaning":"cara, metode"},{"kanji":"文法","hiragana":"ぶんぽう","meaning":"tata bahasa"}]'::jsonb, 173)
(3, '律', 'リツ／リチ', 'ritsu / richi', 'Aturan, hukum', 'Langkah (彳) yang diatur pena (聿) — aturan.', 9, '[{"kanji":"法律","hiragana":"ほうりつ","meaning":"undang-undang"},{"kanji":"規律","hiragana":"きりつ","meaning":"disiplin, tata tertib"},{"kanji":"自律","hiragana":"じりつ","meaning":"otonomi"}]'::jsonb, 174)
(3, '規', 'キ', 'ki', 'Aturan, standar', 'Suami (夫) memandang (見) ukuran baku — aturan, standar.', 11, '[{"kanji":"規則","hiragana":"きそく","meaning":"peraturan"},{"kanji":"規模","hiragana":"きぼ","meaning":"skala"},{"kanji":"規定","hiragana":"きてい","meaning":"ketentuan"}]'::jsonb, 175)
(3, '則', 'ソク', 'soku', 'Aturan, kaidah', 'Harta (貝) dibagi pisau (刂) menurut kaidah — aturan.', 9, '[{"kanji":"規則","hiragana":"きそく","meaning":"peraturan"},{"kanji":"原則","hiragana":"げんそく","meaning":"prinsip"},{"kanji":"法則","hiragana":"ほうそく","meaning":"hukum (alam)"}]'::jsonb, 176)
(3, '制', 'セイ', 'sei', 'Sistem, mengatur', 'Memangkas (刂) cabang agar teratur — sistem, kendali.', 8, '[{"kanji":"制度","hiragana":"せいど","meaning":"sistem, pranata"},{"kanji":"制服","hiragana":"せいふく","meaning":"seragam"},{"kanji":"制限","hiragana":"せいげん","meaning":"pembatasan"}]'::jsonb, 177)
(3, '産', 'サン／う.む', 'san / u.mu', 'Melahirkan, produksi', 'Sesuatu yang dihasilkan dan lahir — produksi, kelahiran.', 11, '[{"kanji":"産業","hiragana":"さんぎょう","meaning":"industri"},{"kanji":"生産","hiragana":"せいさん","meaning":"produksi"},{"kanji":"出産","hiragana":"しゅっさん","meaning":"melahirkan"}]'::jsonb, 178)
(3, '技', 'ギ／わざ', 'gi / waza', 'Keterampilan, teknik', 'Tangan (扌) yang cekatan dengan ranting (支) — keahlian.', 7, '[{"kanji":"技術","hiragana":"ぎじゅつ","meaning":"teknologi, teknik"},{"kanji":"技能","hiragana":"ぎのう","meaning":"keterampilan (kerja)"},{"kanji":"特定技能","hiragana":"とくていぎのう","meaning":"Tokutei Ginou (SSW)"}]'::jsonb, 179)
(3, '術', 'ジュツ', 'jutsu', 'Seni, teknik, ilmu', 'Jalan (行) yang ditempuh dengan keahlian — teknik, seni.', 11, '[{"kanji":"技術","hiragana":"ぎじゅつ","meaning":"teknologi"},{"kanji":"手術","hiragana":"しゅじゅつ","meaning":"operasi bedah"},{"kanji":"美術","hiragana":"びじゅつ","meaning":"seni rupa"}]'::jsonb, 180)
(3, '情', 'ジョウ／なさ.け', 'jou / nasa.ke', 'Perasaan, kabar', 'Hati (忄) yang biru jernih (青) — perasaan, keadaan.', 11, '[{"kanji":"情報","hiragana":"じょうほう","meaning":"informasi"},{"kanji":"感情","hiragana":"かんじょう","meaning":"emosi"},{"kanji":"事情","hiragana":"じじょう","meaning":"keadaan, alasan"}]'::jsonb, 181)
(3, '歴', 'レキ', 'reki', 'Riwayat, sejarah', 'Berjalan melewati waktu di bawah tebing — riwayat.', 14, '[{"kanji":"歴史","hiragana":"れきし","meaning":"sejarah"},{"kanji":"経歴","hiragana":"けいれき","meaning":"riwayat karier"},{"kanji":"学歴","hiragana":"がくれき","meaning":"riwayat pendidikan"}]'::jsonb, 182)
(3, '史', 'シ', 'shi', 'Sejarah', 'Tangan memegang catatan peristiwa — sejarah.', 5, '[{"kanji":"歴史","hiragana":"れきし","meaning":"sejarah"},{"kanji":"歴史的","hiragana":"れきしてき","meaning":"bersejarah"},{"kanji":"日本史","hiragana":"にほんし","meaning":"sejarah Jepang"}]'::jsonb, 183)
(3, '統', 'トウ／す.べる', 'tou / su.beru', 'Menyatukan, garis keturunan', 'Benang (糸) yang menyatukan banyak helai (充) — menyatukan.', 12, '[{"kanji":"伝統","hiragana":"でんとう","meaning":"tradisi"},{"kanji":"統一","hiragana":"とういつ","meaning":"penyatuan"},{"kanji":"大統領","hiragana":"だいとうりょう","meaning":"presiden"}]'::jsonb, 184)
(3, '慣', 'カン／な.れる', 'kan / na.reru', 'Terbiasa, kebiasaan', 'Hati (忄) yang menembus berulang (貫) — terbiasa.', 14, '[{"kanji":"習慣","hiragana":"しゅうかん","meaning":"kebiasaan"},{"kanji":"慣れる","hiragana":"なれる","meaning":"terbiasa"},{"kanji":"慣習","hiragana":"かんしゅう","meaning":"adat, kelaziman"}]'::jsonb, 185)
(3, '生', 'セイ／ショウ／い.きる／う.まれる／なま', 'sei / shou / i.kiru / u.mareru / nama', 'Hidup, lahir, mentah', 'Tunas tumbuh dari tanah — kehidupan.', 5, '[{"kanji":"生活","hiragana":"せいかつ","meaning":"kehidupan"},{"kanji":"生きる","hiragana":"いきる","meaning":"hidup"},{"kanji":"学生","hiragana":"がくせい","meaning":"pelajar"}]'::jsonb, 186)
(3, '活', 'カツ', 'katsu', 'Aktif, hidup', 'Air (氵) yang membuat lidah (舌) hidup — kegiatan, aktif.', 9, '[{"kanji":"生活","hiragana":"せいかつ","meaning":"kehidupan"},{"kanji":"活動","hiragana":"かつどう","meaning":"aktivitas"},{"kanji":"就活","hiragana":"しゅうかつ","meaning":"pencarian kerja"}]'::jsonb, 187)
(3, '環', 'カン', 'kan', 'Lingkaran, sekeliling', 'Permata (王) yang melingkar (睘) — lingkaran, lingkungan.', 17, '[{"kanji":"環境","hiragana":"かんきょう","meaning":"lingkungan"},{"kanji":"環境問題","hiragana":"かんきょうもんだい","meaning":"masalah lingkungan"},{"kanji":"循環","hiragana":"じゅんかん","meaning":"sirkulasi"}]'::jsonb, 188)
(3, '境', 'キョウ／ケイ／さかい', 'kyou / kei / sakai', 'Batas, kondisi', 'Tanah (土) di ujung berakhirnya (竟) — batas wilayah.', 14, '[{"kanji":"環境","hiragana":"かんきょう","meaning":"lingkungan"},{"kanji":"国境","hiragana":"こっきょう","meaning":"perbatasan negara"},{"kanji":"境界","hiragana":"きょうかい","meaning":"batas"}]'::jsonb, 189)
(3, '資', 'シ', 'shi', 'Modal, sumber daya', 'Harta (貝) yang dijadikan modal (次) — modal, dana.', 13, '[{"kanji":"資源","hiragana":"しげん","meaning":"sumber daya"},{"kanji":"資料","hiragana":"しりょう","meaning":"materi, dokumen"},{"kanji":"資格","hiragana":"しかく","meaning":"kualifikasi"}]'::jsonb, 190)
(3, '源', 'ゲン／みなもと', 'gen / minamoto', 'Sumber, asal', 'Air (氵) dari mata air asli (原) — sumber.', 13, '[{"kanji":"資源","hiragana":"しげん","meaning":"sumber daya"},{"kanji":"源","hiragana":"みなもと","meaning":"sumber, asal"},{"kanji":"電源","hiragana":"でんげん","meaning":"sumber listrik"}]'::jsonb, 191)
(3, '能', 'ノウ', 'nou', 'Kemampuan, bakat', 'Makhluk yang mampu melakukan banyak hal — kemampuan.', 10, '[{"kanji":"能力","hiragana":"のうりょく","meaning":"kemampuan"},{"kanji":"可能","hiragana":"かのう","meaning":"mungkin"},{"kanji":"技能","hiragana":"ぎのう","meaning":"keterampilan"}]'::jsonb, 192)
(3, '機', 'キ／はた', 'ki / hata', 'Mesin, kesempatan', 'Kayu (木) dengan mekanisme halus (幾) — mesin, peluang.', 16, '[{"kanji":"機会","hiragana":"きかい","meaning":"kesempatan"},{"kanji":"機械","hiragana":"きかい","meaning":"mesin"},{"kanji":"飛行機","hiragana":"ひこうき","meaning":"pesawat"}]'::jsonb, 193)
(3, '必', 'ヒツ／かなら.ず', 'hitsu / kanara.zu', 'Pasti, perlu', 'Hati yang terbelah tekad — pasti, mesti.', 5, '[{"kanji":"必要","hiragana":"ひつよう","meaning":"perlu, diperlukan"},{"kanji":"必ず","hiragana":"かならず","meaning":"pasti, tentu"},{"kanji":"必死","hiragana":"ひっし","meaning":"mati-matian"}]'::jsonb, 194)
(3, '要', 'ヨウ／い.る／かなめ', 'you / i.ru / kaname', 'Penting, perlu', 'Perempuan dengan pinggang sebagai poros — inti, perlu.', 9, '[{"kanji":"必要","hiragana":"ひつよう","meaning":"perlu"},{"kanji":"重要","hiragana":"じゅうよう","meaning":"penting"},{"kanji":"要点","hiragana":"ようてん","meaning":"poin penting"}]'::jsonb, 195)
(3, '般', 'ハン', 'han', 'Umum, jenis', 'Kapal (舟) yang berputar (殳) menyeluruh — umum, secara umum.', 10, '[{"kanji":"一般","hiragana":"いっぱん","meaning":"umum"},{"kanji":"一般的","hiragana":"いっぱんてき","meaning":"pada umumnya"},{"kanji":"全般","hiragana":"ぜんぱん","meaning":"keseluruhan"}]'::jsonb, 196)
(3, '基', 'キ／もと／もとい', 'ki / moto / motoi', 'Dasar, fondasi', 'Tanah (土) sebagai landasan (其) — dasar.', 11, '[{"kanji":"基本","hiragana":"きほん","meaning":"dasar, fundamental"},{"kanji":"基礎","hiragana":"きそ","meaning":"fondasi"},{"kanji":"基準","hiragana":"きじゅん","meaning":"standar"}]'::jsonb, 197)

-- Verifikasi cepat (opsional):
-- SELECT count(*) FROM public.kanji WHERE level_id = 3;  -- harapan: 194
