-- ============================================================
-- Koto no Ha — Seed Vocab N3 Extra (Kosakata Tambahan & SSW)
-- Level: N3 (id=3)
-- Anti-duplikasi: hanya kata yang belum ada di N5/N4
-- Format mengikuti 003_seed_vocab.sql
-- ============================================================

-- Bersihkan data kosakata N3 yang duplikat sebelum re-seed
DELETE FROM public.vocab WHERE level_id = 3 AND word IN ('同僚','上司','部下','残業する','有給休暇','手続き','応募する','採用する','近所','片付ける','整理する','間に合う','羨ましい','がっかりする','ほっとする','緊張する','介護','排泄介助','食事介助','ヒヤリハット','法律','被害','しかし','したがって');

INSERT INTO public.vocab (level_id, word, hiragana, romaji, meaning, part_of_speech, usage_id, usage_jp, full_meaning, example_sentence, example_hiragana, example_meaning, order_index) VALUES
(3, '同僚', 'どうりょう', 'dōryō', 'rekan kerja', 'Kata benda', 'Teman satu level/jabatan di tempat kerja.', '同じ職場で働く仲間', 'rekan kerja, teman sejawat', '同僚と一緒にランチを食べました。', 'どうりょうといっしょにらんちをたべました。', 'Saya makan siang bersama rekan kerja.', 201),
(3, '上司', 'じょうし', 'jōshi', 'atasan', 'Kata benda', 'Pimpinan atau orang dengan jabatan lebih tinggi di kantor.', '自分より上の立場の人', 'atasan, bos, pimpinan', '上司に書類を提出しました。', 'じょうしにしょるいをていしゅつしました。', 'Saya menyerahkan dokumen kepada atasan.', 202),
(3, '部下', 'ぶか', 'buka', 'bawahan', 'Kata benda', 'Orang yang bekerja di bawah pimpinan kita.', '自分より下の立場の人', 'bawahan, anak buah', '彼は部下の面倒をよく見ます。', 'かれはぶかのめんどうをよくみます。', 'Dia merawat bawahannya dengan baik.', 203),
(3, '残業する', 'ざんぎょうする', 'zangyō suru', 'lembur', 'Kata kerja tidak beraturan', 'Bekerja melebihi jam kerja normal.', '規定の時間以外に働くこと', 'bekerja lembur, overtime', '仕事が多いので、今日は残業します。', 'しごとがおおいので、きょうはざんぎょうします。', 'Karena pekerjaan banyak, hari ini saya akan lembur.', 204),
(3, '有給休暇', 'ゆうきゅうきゅうか', 'yūkyū kyūka', 'cuti berbayar', 'Kata benda', 'Cuti kerja tahunan yang gajinya tetap dibayar (biasa disingkat 有給 yūkyū).', '給料が支払われる休み', 'cuti tahunan berbayar', '来週、有給休暇を取って旅行に行きます。', 'らいしゅう、ゆうきゅうきゅうかをとってりょこうにいきます。', 'Minggu depan, saya akan mengambil cuti berbayar dan pergi berlibur.', 205),
(3, '手続き', 'てつづき', 'tetsuzuki', 'prosedur / pengurusan', 'Kata benda', 'Langkah resmi untuk mengurus dokumen atau hal resmi lainnya.', '物事を行うために必要な手順', 'prosedur administratif, urusan resmi', '市役所でビザの手続きをしました。', 'しやくしょでびざのてつづきをしました。', 'Saya mengurus prosedur visa di kantor wali kota.', 206),
(3, '応募する', 'おうぼする', 'ōbo suru', 'melamar / mendaftar', 'Kata kerja tidak beraturan', 'Melamar pekerjaan atau mendaftar untuk suatu posisi/lomba.', '募集に申し込むこと', 'melamar pekerjaan, mendaftar kontes', '日本の会社の求人に応募しました。', 'にほんのかいしゃのきゅうじんにおうぼしました。', 'Saya melamar lowongan kerja di perusahaan Jepang.', 207),
(3, '採用する', 'さいようする', 'saiyō suru', 'menerima kerja / mengadopsi', 'Kata kerja tidak beraturan', 'Menerima pelamar menjadi karyawan resmi.', '人を取り立てて使うこと', 'mempekerjakan, mengadopsi sistem/karyawan', '面接の結果、採用が決まりました。', 'めんせつのけっか、さいようがきまりました。', 'Hasil dari wawancara, diputuskan saya diterima kerja.', 208),
(3, '近所', 'きんじょ', 'kinjo', 'tetangga / sekitar rumah', 'Kata benda', 'Area atau orang-orang yang tinggal di dekat rumah kita.', '住んでいる場所の近く', 'lingkungan sekitar, tetangga', '近所のスーパーはとても安いです。', 'きんじょのすーぱーはとてもやすいです。', 'Supermarket di sekitar rumah sangat murah.', 209),
(3, '片付ける', 'かたづける', 'katazukeru', 'merapikan / membereskan', 'Kata kerja kelompok 2 (Ichidan)', 'Merapikan barang-barang yang berantakan ke tempat semula.', '乱れた状態を整える', 'merapikan kamar/barang, membereskan masalah', '友達が来る前に、部屋を片付けます。', 'ともだちがくるまえに、へやをかたづけます。', 'Sebelum teman datang, saya merapikan kamar.', 210),
(3, '整理する', 'せいりする', 'seiri suru', 'menata / memilah', 'Kata kerja tidak beraturan', 'Memilah barang yang berguna dan membuang yang tidak berguna.', '不要なものを取り除き、整えること', 'organisasi, penataan dokumen/barang', '古い書類を整理しました。', 'ふるいしょるいをせいりしました。', 'Saya menata dokumen-dokumen lama.', 211),
(3, '間に合う', 'まにあう', 'maniau', 'keburu / sempat', 'Kata kerja kelompok 1 (Godan)', 'Tiba tepat waktu sebelum batas yang ditentukan.', '約束の時間に遅れずに到着すること', 'sempat, tiba tepat waktu', '走ったので, 電車に間に合いました。', 'はしったので、でんしゃにまにあいました。', 'Karena berlari, saya sempat mengejar kereta.', 212),
(3, '羨ましい', 'うらやましい', 'urayamashii', 'iri / cemburu (positif)', 'Kata sifat-i', 'Merasa ingin seperti orang lain yang beruntung atau sukses.', '他人の良い状態を見て, 自分もそうありたいと思う気持ち', 'iri hati (nuansa ingin seperti dia, bukan dengki)', '彼女は英語がペラペラで羨ましいです。', 'かのじょはえいごがぺらぺらでうらやましいです。', 'Dia lancar bahasa Inggris, saya iri dengannya.', 213),
(3, 'がっかりする', 'がっかりする', 'gakkari suru', 'kecewa', 'Kata kerja tidak beraturan', 'Merasa sedih/kecewa karena harapan tidak terwujud.', '期待が外れて、元気をなくすこと', 'kecewa berat, patah semangat', '試験に落ちて、がっかりしました。', 'しけんにおちて、がっかりしました。', 'Saya kecewa karena gagal ujian.', 214),
(3, 'ほっとする', 'ほっとする', 'hotto suru', 'lega', 'Kata kerja tidak beraturan', 'Merasa tenang setelah rasa khawatir atau bahaya terlewati.', '緊張が解けて、安心する様子', 'merasa lega, bernapas lega', '母の病気が治って、ほっとしました。', 'ははのびょうきがなおって、ほっとしました。', 'Saya lega setelah penyakit ibu sembuh.', 215),
(3, '緊張する', 'きんちょうする', 'kinchō suru', 'gugup / tegang', 'Kata kerja tidak beraturan', 'Merasa deg-degan saat menghadapi situasi penting (wawancara, pidato).', '体が硬くなり、ドキドキすること', 'gugup, tegang secara mental/fisik', '面接のとき、とても緊張しました。', 'めんせつのとき、とてもきんちょうしました。', 'Saya sangat gugup saat wawancara.', 216),
(3, '介護', 'かいご', 'kaigo', 'perawatan lansia / asuhan', 'Kata benda', 'Merawat lansia atau orang sakit yang memiliki keterbatasan fisik/mental.', '高齢者や病人の生活を支援すること', 'perawatan lansia, caregiving', '日本で介護の仕事をするのが私の夢です。', 'にほんでかいごのしごとをするのがわたしのゆめです。', 'Bekerja di bidang perawatan lansia di Jepang adalah impian saya.', 217),
(3, '排泄介助', 'はいせつかいじょ', 'haisetsu kaijo', 'bantuan eliminasi / toilet', 'Kata benda', 'Membantu pasien/lansia melakukan buang air di toilet atau pispot.', 'トイレでの排泄を支援すること', 'bantuan ke toilet (istilah medis/kaigo)', '排泄介助のときはプライバシーに配慮します。', 'はいせつかいじょのときはぷらいばしーにはいりょします。', 'Saat membantu pasien ke toilet, kami memperhatikan privasi.', 218),
(3, '食事介助', 'しょくじかいじょ', 'shokuji kaijo', 'bantuan makan', 'Kata benda', 'Membantu lansia menyuap atau menyiapkan makanan sesuai kondisi kesehatannya.', 'ご飯を食べるサポートをすること', 'bantuan menyuapi makanan', '安全に食事ができるよう、食事介助を行います。', 'あんぜんにしょくじができるよう、しょくじかいじょをおこないます。', 'Kami melakukan bantuan makan agar pasien dapat makan dengan aman.', 219),
(3, 'ヒヤリハット', 'ひやりはっと', 'hiyari hatto', 'nyaris celaka / near-miss', 'Kata benda', 'Kejadian nyaris kecelakaan yang membuat terkejut/khawatir (istilah penting keselamatan kerja Jepang).', '大事故につながる手前の出来事', 'insiden nyaris celaka (near-miss incident)', 'ヒヤリハット報告書を書いて提出してください。', 'ひやりはっとほうこくしょをかいてていしゅつしてください。', 'Tolong tulis dan serahkan laporan insiden nyaris celaka.', 220),
(3, '法律', 'ほうりつ', 'hōritsu', 'undang-undang / hukum', 'Kata benda', 'Aturan resmi tertulis negara.', '国が決めた公式のルール', 'hukum, undang-undang resmi', 'すべての人が法律を守らなければなりません。', 'すべてのひとがほうりつをまもらなければなりません。', 'Semua orang harus mematuhi hukum.', 221),
(3, '被害', 'ひがい', 'higai', 'kerusakan / kerugian', 'Kata benda', 'Kerusakan atau kerugian yang diderita akibat bencana alam atau kejahatan.', '事故や災害などで受ける悪い影響', 'kerugian, kerusakan, korban bencana', '台風による被害は非常に大きかったです。', 'たいふうによるひがいはひじょうにおおきかったです。', 'Kerusakan akibat topan sangat besar.', 222),
(3, 'しかし', 'しかし', 'shikashi', 'namun / tetapi', 'Konjungsi', 'Kata penghubung formal di awal kalimat untuk menyatakan pertentangan.', '前の文と反対のことを述べる表現', 'tetapi, namun demikian (formal)', '彼は一生懸命勉強しました。しかし、不合格でした。', 'かれはいっしょうけんめいべんきょうしました。しかし、ふごうかくでした。', 'Dia belajar dengan giat. Namun, dia tidak lulus.', 223),
(3, 'したがって', 'したがって', 'shitagatte', 'oleh karena itu', 'Konjungsi', 'Kata hubung sangat formal menyatakan akibat logis (sering muncul di tulisan/berita).', 'だから（文章語で、理由と結果をつなぐ）', 'oleh karena itu, maka dari itu (formal)', '日本の人口は減っています。したがって、労働者が不足しています。', 'にほんのじんこうはへっています。したがって、ろうどうしゃがふそくしています。', 'Populasi Jepang sedang menurun. Oleh karena itu, terjadi kekurangan tenaga kerja.', 224);
