-- ============================================================
-- Koto no Ha — Perbaikan tabrakan antar-level & entri kanji rusak
-- Kebijakan: LEVEL LEBIH TINGGI MENANG.
--   - 73 kanji N3 yang juga ada di N2/N1 dihapus dari N3 (N3 kalah)
--     lalu diganti 73 kanji N3 baru (eksklusif).
--   - 3 kanji N2 (優,訟,訴) yang juga ada di N1 dihapus dari N2 (N1 menang)
--     lalu diganti 3 kanji N2 baru.
--   - 20 entri "kanji" 2-karakter (kata, bukan kanji) di N2 & N1 dihapus
--     lalu diganti kanji tunggal valid (9 N2 + 11 N1).
-- Total: hapus 73 N3 + 3 N2 + 20 rusak; tambah 73 N3 + 12 N2 + 11 N1 = 96.
-- Bacaan & arti kanji pengganti bersumber dari daftar JLPT (jlptsensei/Jisho),
-- arti/hint ditulis Bahasa Indonesia mengikuti gaya 004 & 010.
-- WAJIB dijalankan SETELAH 014_dedup_kanji.sql (butuh unique index utk ON CONFLICT).
-- Idempoten: penghapusan computed; insert pakai ON CONFLICT DO NOTHING.
-- Hasil akhir per level: N3=194, N2=250, N1=250 (semua unik global & 1 karakter).
-- ============================================================

-- ─── 1. Hapus 73 kanji N3 yang kalah (juga ada di N2/N1) ─────────────────────
DELETE FROM public.kanji n3
WHERE n3.level_id = 3
  AND EXISTS (SELECT 1 FROM public.kanji hi WHERE hi.kanji = n3.kanji AND hi.level_id > 3);

-- ─── 2. Hapus 3 kanji N2 yang kalah dari N1 ──────────────────────────────────
DELETE FROM public.kanji WHERE level_id = 4 AND kanji IN ('優','訟','訴');

-- ─── 3. Hapus 20 entri rusak (2 karakter, sebenarnya kata) di N2 & N1 ────────
DELETE FROM public.kanji WHERE level_id IN (4,5) AND char_length(kanji) > 1;

-- ─── 4. Tambah 96 kanji pengganti (order_index di-append setelah max) ────────
INSERT INTO public.kanji (level_id, kanji, hiragana, romaji, meaning, hint, stroke_count, examples, order_index) VALUES
(3, '民', 'ミン・たみ', 'min / tami', 'Rakyat, Bangsa', 'Sekelompok orang di bawah satu naungan — rakyat sebuah bangsa', 5, '[{"kanji": "国民", "hiragana": "こくみん", "meaning": "warga negara"}, {"kanji": "民族", "hiragana": "みんぞく", "meaning": "suku bangsa"}, {"kanji": "住民", "hiragana": "じゅうみん", "meaning": "penduduk"}]'::jsonb, 195),
(3, '合', 'ゴウ／あ.う', 'gō / a.u', 'Cocok, Bergabung', 'Mulut (口) di bawah atap (亼) menyatu — cocok dan bergabung', 6, '[{"kanji": "合う", "hiragana": "あう", "meaning": "cocok"}, {"kanji": "試合", "hiragana": "しあい", "meaning": "pertandingan"}, {"kanji": "合計", "hiragana": "ごうけい", "meaning": "jumlah total"}]'::jsonb, 196),
(3, '選', 'セン／えら.ぶ', 'sen / era.bu', 'Memilih', 'Berjalan (辶) menyusuri pilihan demi pilihan — memilih', 15, '[{"kanji": "選ぶ", "hiragana": "えらぶ", "meaning": "memilih"}, {"kanji": "選挙", "hiragana": "せんきょ", "meaning": "pemilu"}, {"kanji": "選手", "hiragana": "せんしゅ", "meaning": "atlet"}]'::jsonb, 197),
(3, '米', 'ベイ・マイ／こめ', 'bei / mai / kome', 'Beras, Amerika', 'Butir-butir tersebar dari tangkai — beras (juga singkatan Amerika)', 6, '[{"kanji": "米", "hiragana": "こめ", "meaning": "beras"}, {"kanji": "米国", "hiragana": "べいこく", "meaning": "Amerika Serikat"}, {"kanji": "白米", "hiragana": "はくまい", "meaning": "beras putih"}]'::jsonb, 198),
(3, '関', 'カン／せき', 'kan / seki', 'Hubungan, Gerbang', 'Gerbang (門) berpalang — pintu penghubung dan rintangan', 14, '[{"kanji": "関係", "hiragana": "かんけい", "meaning": "hubungan"}, {"kanji": "関心", "hiragana": "かんしん", "meaning": "minat"}, {"kanji": "玄関", "hiragana": "げんかん", "meaning": "pintu masuk"}]'::jsonb, 199),
(3, '表', 'ヒョウ／おもて／あらわ.す', 'hyō / omote / arawa.su', 'Permukaan, Tabel', 'Sisi luar pakaian yang tampak — permukaan yang menyatakan', 8, '[{"kanji": "表面", "hiragana": "ひょうめん", "meaning": "permukaan"}, {"kanji": "発表", "hiragana": "はっぴょう", "meaning": "presentasi"}, {"kanji": "表す", "hiragana": "あらわす", "meaning": "menyatakan"}]'::jsonb, 200),
(3, '現', 'ゲン／あらわ.れる', 'gen / arawa.reru', 'Kini, Muncul', 'Permata (王) yang terlihat (見) nyata — muncul saat ini', 11, '[{"kanji": "現在", "hiragana": "げんざい", "meaning": "saat ini"}, {"kanji": "現実", "hiragana": "げんじつ", "meaning": "kenyataan"}, {"kanji": "表現", "hiragana": "ひょうげん", "meaning": "ungkapan"}]'::jsonb, 201),
(3, '首', 'シュ／くび', 'shu / kubi', 'Leher, Kepala', 'Gambar kepala dengan rambut — leher dan pemimpin', 9, '[{"kanji": "首", "hiragana": "くび", "meaning": "leher"}, {"kanji": "首都", "hiragana": "しゅと", "meaning": "ibu kota"}, {"kanji": "首相", "hiragana": "しゅしょう", "meaning": "perdana menteri"}]'::jsonb, 202),
(3, '性', 'セイ・ショウ', 'sei / shō', 'Sifat, Jenis', 'Hati (忄) sejak lahir (生) — sifat bawaan dan jenis', 8, '[{"kanji": "性格", "hiragana": "せいかく", "meaning": "watak"}, {"kanji": "性別", "hiragana": "せいべつ", "meaning": "jenis kelamin"}, {"kanji": "女性", "hiragana": "じょせい", "meaning": "wanita"}]'::jsonb, 203),
(3, '的', 'テキ', 'teki', 'Sasaran, -nya', 'Tanda putih (白) yang dituju sendok (勺) — sasaran', 8, '[{"kanji": "目的", "hiragana": "もくてき", "meaning": "tujuan"}, {"kanji": "的確", "hiragana": "てきかく", "meaning": "tepat"}, {"kanji": "具体的", "hiragana": "ぐたいてき", "meaning": "konkret"}]'::jsonb, 204),
(3, '和', 'ワ／やわ.らぐ', 'wa / yawa.ragu', 'Harmoni, Jepang', 'Padi (禾) dibagi lewat mulut (口) — keselarasan dan damai', 8, '[{"kanji": "平和", "hiragana": "へいわ", "meaning": "perdamaian"}, {"kanji": "和食", "hiragana": "わしょく", "meaning": "masakan Jepang"}, {"kanji": "調和", "hiragana": "ちょうわ", "meaning": "harmoni"}]'::jsonb, 205),
(3, '点', 'テン／つ.ける', 'ten / tsu.keru', 'Titik, Nilai', 'Percikan api kecil — titik dan angka nilai', 9, '[{"kanji": "点", "hiragana": "てん", "meaning": "titik / poin"}, {"kanji": "点数", "hiragana": "てんすう", "meaning": "skor"}, {"kanji": "地点", "hiragana": "ちてん", "meaning": "lokasi titik"}]'::jsonb, 206),
(3, '得', 'トク／え.る', 'toku / e.ru', 'Memperoleh, Untung', 'Berjalan menemukan kerang berharga — memperoleh keuntungan', 11, '[{"kanji": "得る", "hiragana": "える", "meaning": "memperoleh"}, {"kanji": "得意", "hiragana": "とくい", "meaning": "mahir"}, {"kanji": "損得", "hiragana": "そんとく", "meaning": "untung rugi"}]'::jsonb, 207),
(3, '勝', 'ショウ／か.つ', 'shō / ka.tsu', 'Menang', 'Tubuh kuat mengerahkan tenaga (力) — meraih kemenangan', 12, '[{"kanji": "勝つ", "hiragana": "かつ", "meaning": "menang"}, {"kanji": "勝利", "hiragana": "しょうり", "meaning": "kemenangan"}, {"kanji": "優勝", "hiragana": "ゆうしょう", "meaning": "juara"}]'::jsonb, 208),
(3, '面', 'メン／おもて', 'men / omote', 'Wajah, Sisi', 'Bingkai mengelilingi wajah — permukaan dan aspek', 9, '[{"kanji": "顔面", "hiragana": "がんめん", "meaning": "wajah"}, {"kanji": "面接", "hiragana": "めんせつ", "meaning": "wawancara"}, {"kanji": "表面", "hiragana": "ひょうめん", "meaning": "permukaan"}]'::jsonb, 209),
(3, '組', 'ソ／く.む／くみ', 'so / ku.mu / kumi', 'Kelompok, Merangkai', 'Benang (糸) ditumpuk (且) tersusun — merangkai kelompok', 11, '[{"kanji": "組む", "hiragana": "くむ", "meaning": "merangkai"}, {"kanji": "組織", "hiragana": "そしき", "meaning": "organisasi"}, {"kanji": "番組", "hiragana": "ばんぐみ", "meaning": "acara siaran"}]'::jsonb, 210),
(3, '在', 'ザイ／あ.る', 'zai / a.ru', 'Ada, Berada', 'Bibit (才) menancap di tanah (土) — keberadaan di tempat', 6, '[{"kanji": "現在", "hiragana": "げんざい", "meaning": "saat ini"}, {"kanji": "存在", "hiragana": "そんざい", "meaning": "eksistensi"}, {"kanji": "在宅", "hiragana": "ざいたく", "meaning": "di rumah"}]'::jsonb, 211),
(3, '側', 'ソク／がわ', 'soku / gawa', 'Sisi, Pihak', 'Orang (亻) berdiri di samping aturan (則) — sisi atau pihak', 11, '[{"kanji": "側", "hiragana": "がわ", "meaning": "sisi"}, {"kanji": "右側", "hiragana": "みぎがわ", "meaning": "sisi kanan"}, {"kanji": "両側", "hiragana": "りょうがわ", "meaning": "kedua sisi"}]'::jsonb, 212),
(3, '引', 'イン／ひ.く', 'in / hi.ku', 'Menarik', 'Busur (弓) ditarik tali (丨) — menarik', 4, '[{"kanji": "引く", "hiragana": "ひく", "meaning": "menarik"}, {"kanji": "引退", "hiragana": "いんたい", "meaning": "pensiun"}, {"kanji": "割引", "hiragana": "わりびき", "meaning": "diskon"}]'::jsonb, 213),
(3, '求', 'キュウ／もと.める', 'kyū / moto.meru', 'Menuntut, Mencari', 'Mengulurkan tangan meminta — menuntut dan mencari', 7, '[{"kanji": "求める", "hiragana": "もとめる", "meaning": "menuntut"}, {"kanji": "要求", "hiragana": "ようきゅう", "meaning": "tuntutan"}, {"kanji": "求人", "hiragana": "きゅうじん", "meaning": "lowongan"}]'::jsonb, 214),
(3, '次', 'ジ・シ／つぎ', 'ji / shi / tsugi', 'Berikut, Urutan', 'Embusan napas (欠) berturut — yang berikutnya', 6, '[{"kanji": "次", "hiragana": "つぎ", "meaning": "berikutnya"}, {"kanji": "次回", "hiragana": "じかい", "meaning": "lain kali"}, {"kanji": "目次", "hiragana": "もくじ", "meaning": "daftar isi"}]'::jsonb, 215),
(3, '官', 'カン', 'kan', 'Pejabat, Lembaga', 'Banyak orang di bawah atap (宀) negara — pejabat pemerintah', 8, '[{"kanji": "警官", "hiragana": "けいかん", "meaning": "polisi"}, {"kanji": "官庁", "hiragana": "かんちょう", "meaning": "instansi"}, {"kanji": "外交官", "hiragana": "がいこうかん", "meaning": "diplomat"}]'::jsonb, 216),
(3, '係', 'ケイ／かか.り', 'kei / kaka.ri', 'Penanggung Jawab, Kait', 'Orang (亻) yang terikat (系) tugas — penanggung jawab', 9, '[{"kanji": "係", "hiragana": "かかり", "meaning": "petugas"}, {"kanji": "関係", "hiragana": "かんけい", "meaning": "hubungan"}, {"kanji": "係員", "hiragana": "かかりいん", "meaning": "petugas"}]'::jsonb, 217),
(3, '投', 'トウ／な.げる', 'tō / na.geru', 'Melempar', 'Tangan (扌) mengayun memukul (殳) — melempar', 7, '[{"kanji": "投げる", "hiragana": "なげる", "meaning": "melempar"}, {"kanji": "投資", "hiragana": "とうし", "meaning": "investasi"}, {"kanji": "投票", "hiragana": "とうひょう", "meaning": "pemungutan suara"}]'::jsonb, 218),
(3, '打', 'ダ／う.つ', 'da / u.tsu', 'Memukul', 'Tangan (扌) menghantam paku (丁) — memukul', 5, '[{"kanji": "打つ", "hiragana": "うつ", "meaning": "memukul"}, {"kanji": "打撃", "hiragana": "だげき", "meaning": "pukulan"}, {"kanji": "一打", "hiragana": "いちだ", "meaning": "satu pukulan"}]'::jsonb, 219),
(3, '両', 'リョウ', 'ryō', 'Kedua, Dua', 'Timbangan dengan dua sisi seimbang — keduanya', 6, '[{"kanji": "両方", "hiragana": "りょうほう", "meaning": "keduanya"}, {"kanji": "両親", "hiragana": "りょうしん", "meaning": "orang tua"}, {"kanji": "両手", "hiragana": "りょうて", "meaning": "kedua tangan"}]'::jsonb, 220),
(3, '容', 'ヨウ', 'yō', 'Wadah, Isi, Wajah', 'Lembah (谷) di bawah atap (宀) menampung — memuat isi', 10, '[{"kanji": "内容", "hiragana": "ないよう", "meaning": "isi"}, {"kanji": "容器", "hiragana": "ようき", "meaning": "wadah"}, {"kanji": "容易", "hiragana": "ようい", "meaning": "mudah"}]'::jsonb, 221),
(3, '歳', 'サイ・セイ', 'sai / sei', 'Usia, Tahun', 'Penanda langkah tahun (止) yang berlalu — umur', 13, '[{"kanji": "何歳", "hiragana": "なんさい", "meaning": "berapa umur"}, {"kanji": "二十歳", "hiragana": "はたち", "meaning": "umur 20"}, {"kanji": "歳末", "hiragana": "さいまつ", "meaning": "akhir tahun"}]'::jsonb, 222),
(3, '位', 'イ／くらい', 'i / kurai', 'Peringkat, Sekitar', 'Orang (亻) berdiri (立) di tempatnya — peringkat', 7, '[{"kanji": "一位", "hiragana": "いちい", "meaning": "peringkat 1"}, {"kanji": "地位", "hiragana": "ちい", "meaning": "kedudukan"}, {"kanji": "位置", "hiragana": "いち", "meaning": "posisi"}]'::jsonb, 223),
(3, '置', 'チ／お.く', 'chi / o.ku', 'Meletakkan', 'Jaring (网) menahan benda lurus (直) di tempat — meletakkan', 13, '[{"kanji": "置く", "hiragana": "おく", "meaning": "meletakkan"}, {"kanji": "位置", "hiragana": "いち", "meaning": "posisi"}, {"kanji": "放置", "hiragana": "ほうち", "meaning": "membiarkan"}]'::jsonb, 224),
(3, '流', 'リュウ・ル／なが.れる', 'ryū / ru / naga.reru', 'Mengalir, Aliran', 'Air (氵) membawa anak hanyut — arus mengalir', 10, '[{"kanji": "流れる", "hiragana": "ながれる", "meaning": "mengalir"}, {"kanji": "流行", "hiragana": "りゅうこう", "meaning": "tren"}, {"kanji": "交流", "hiragana": "こうりゅう", "meaning": "pertukaran"}]'::jsonb, 225),
(3, '格', 'カク・コウ', 'kaku / kō', 'Status, Rangka', 'Pohon (木) yang mencapai (各) bentuk — status dan kerangka', 10, '[{"kanji": "性格", "hiragana": "せいかく", "meaning": "watak"}, {"kanji": "合格", "hiragana": "ごうかく", "meaning": "lulus"}, {"kanji": "格安", "hiragana": "かくやす", "meaning": "sangat murah"}]'::jsonb, 226),
(3, '局', 'キョク', 'kyoku', 'Kantor, Babak', 'Ruang terbatas tempat bertugas — kantor atau babak', 7, '[{"kanji": "結局", "hiragana": "けっきょく", "meaning": "akhirnya"}, {"kanji": "放送局", "hiragana": "ほうそうきょく", "meaning": "stasiun siaran"}, {"kanji": "薬局", "hiragana": "やっきょく", "meaning": "apotek"}]'::jsonb, 227),
(3, '常', 'ジョウ／つね', 'jō / tsune', 'Biasa, Tetap', 'Kain (巾) panjang yang selalu dipakai — hal yang lumrah', 11, '[{"kanji": "日常", "hiragana": "にちじょう", "meaning": "sehari-hari"}, {"kanji": "正常", "hiragana": "せいじょう", "meaning": "normal"}, {"kanji": "非常", "hiragana": "ひじょう", "meaning": "darurat"}]'::jsonb, 228),
(3, '球', 'キュウ／たま', 'kyū / tama', 'Bola, Bumi', 'Permata (王) bulat yang dicari (求) — bola', 11, '[{"kanji": "野球", "hiragana": "やきゅう", "meaning": "bisbol"}, {"kanji": "地球", "hiragana": "ちきゅう", "meaning": "bumi"}, {"kanji": "電球", "hiragana": "でんきゅう", "meaning": "bohlam"}]'::jsonb, 229),
(3, '与', 'ヨ／あた.える', 'yo / ata.eru', 'Memberi', 'Dua tangan menyerahkan sesuatu — memberi', 3, '[{"kanji": "与える", "hiragana": "あたえる", "meaning": "memberi"}, {"kanji": "給与", "hiragana": "きゅうよ", "meaning": "gaji"}, {"kanji": "授与", "hiragana": "じゅよ", "meaning": "penganugerahan"}]'::jsonb, 230),
(3, '構', 'コウ／かま.える', 'kō / kama.eru', 'Susunan, Membangun', 'Kayu (木) disusun bersilang — membangun rangka', 14, '[{"kanji": "構造", "hiragana": "こうぞう", "meaning": "struktur"}, {"kanji": "構成", "hiragana": "こうせい", "meaning": "susunan"}, {"kanji": "結構", "hiragana": "けっこう", "meaning": "cukup baik"}]'::jsonb, 231),
(3, '身', 'シン／み', 'shin / mi', 'Tubuh, Diri', 'Gambar tubuh hamil yang membungkuk — badan sendiri', 7, '[{"kanji": "身体", "hiragana": "しんたい", "meaning": "tubuh"}, {"kanji": "自身", "hiragana": "じしん", "meaning": "diri sendiri"}, {"kanji": "中身", "hiragana": "なかみ", "meaning": "isi"}]'::jsonb, 232),
(3, '付', 'フ／つ.ける', 'fu / tsu.keru', 'Menempel, Melampirkan', 'Tangan (寸) menyerahkan ke orang (亻) — menempelkan', 5, '[{"kanji": "付ける", "hiragana": "つける", "meaning": "memasang"}, {"kanji": "付近", "hiragana": "ふきん", "meaning": "sekitar"}, {"kanji": "受付", "hiragana": "うけつけ", "meaning": "resepsi"}]'::jsonb, 233),
(3, '由', 'ユ・ユウ／よし', 'yu / yū / yoshi', 'Sebab, Alasan', 'Ladang (田) dengan tunas keluar — asal mula sebab', 5, '[{"kanji": "理由", "hiragana": "りゆう", "meaning": "alasan"}, {"kanji": "自由", "hiragana": "じゆう", "meaning": "kebebasan"}, {"kanji": "経由", "hiragana": "けいゆ", "meaning": "melalui"}]'::jsonb, 234),
(3, '断', 'ダン／ことわ.る／た.つ', 'dan / kotowa.ru / ta.tsu', 'Memutus, Menolak', 'Kapak (斤) memotong benang — memutuskan dengan tegas', 11, '[{"kanji": "断る", "hiragana": "ことわる", "meaning": "menolak"}, {"kanji": "判断", "hiragana": "はんだん", "meaning": "penilaian"}, {"kanji": "診断", "hiragana": "しんだん", "meaning": "diagnosis"}]'::jsonb, 235),
(3, '消', 'ショウ／き.える／け.す', 'shō / ki.eru / ke.su', 'Padam, Menghapus', 'Air (氵) membuat menyusut (肖) — memadamkan', 10, '[{"kanji": "消す", "hiragana": "けす", "meaning": "menghapus"}, {"kanji": "消える", "hiragana": "きえる", "meaning": "menghilang"}, {"kanji": "消費", "hiragana": "しょうひ", "meaning": "konsumsi"}]'::jsonb, 236),
(3, '神', 'シン・ジン／かみ', 'shin / jin / kami', 'Dewa, Roh', 'Altar (示) tempat petir (申) ilahi — dewa dan roh', 9, '[{"kanji": "神", "hiragana": "かみ", "meaning": "dewa"}, {"kanji": "神社", "hiragana": "じんじゃ", "meaning": "kuil Shinto"}, {"kanji": "精神", "hiragana": "せいしん", "meaning": "jiwa"}]'::jsonb, 237),
(3, '席', 'セキ', 'seki', 'Tempat Duduk', 'Kain (巾) dibentang di bawah atap — tempat duduk', 10, '[{"kanji": "座席", "hiragana": "ざせき", "meaning": "kursi"}, {"kanji": "出席", "hiragana": "しゅっせき", "meaning": "kehadiran"}, {"kanji": "欠席", "hiragana": "けっせき", "meaning": "absen"}]'::jsonb, 238),
(3, '訪', 'ホウ／たず.ねる／おとず.れる', 'hō / tazu.neru / otozu.reru', 'Mengunjungi', 'Kata (言) menanya arah (方) — mengunjungi', 11, '[{"kanji": "訪ねる", "hiragana": "たずねる", "meaning": "mengunjungi"}, {"kanji": "訪問", "hiragana": "ほうもん", "meaning": "kunjungan"}, {"kanji": "来訪", "hiragana": "らいほう", "meaning": "kedatangan tamu"}]'::jsonb, 239),
(3, '乗', 'ジョウ／の.る', 'jō / no.ru', 'Menaiki', 'Orang berdiri di atas pohon — menaiki kendaraan', 9, '[{"kanji": "乗る", "hiragana": "のる", "meaning": "naik"}, {"kanji": "乗車", "hiragana": "じょうしゃ", "meaning": "naik kendaraan"}, {"kanji": "乗客", "hiragana": "じょうきゃく", "meaning": "penumpang"}]'::jsonb, 240),
(3, '残', 'ザン／のこ.る／のこ.す', 'zan / noko.ru / noko.su', 'Sisa, Tersisa', 'Tulang (歹) dan tombak — yang tertinggal sebagai sisa', 10, '[{"kanji": "残る", "hiragana": "のこる", "meaning": "tersisa"}, {"kanji": "残念", "hiragana": "ざんねん", "meaning": "sayang sekali"}, {"kanji": "残業", "hiragana": "ざんぎょう", "meaning": "lembur"}]'::jsonb, 241),
(3, '例', 'レイ／たと.える', 'rei / tato.eru', 'Contoh', 'Orang (亻) menyusun (列) perumpamaan — contoh', 8, '[{"kanji": "例", "hiragana": "れい", "meaning": "contoh"}, {"kanji": "例えば", "hiragana": "たとえば", "meaning": "misalnya"}, {"kanji": "例外", "hiragana": "れいがい", "meaning": "pengecualian"}]'::jsonb, 242),
(3, '然', 'ゼン・ネン', 'zen / nen', 'Begitu, Demikian', 'Daging anjing dibakar api (灬) — keadaan yang demikian', 12, '[{"kanji": "自然", "hiragana": "しぜん", "meaning": "alam"}, {"kanji": "当然", "hiragana": "とうぜん", "meaning": "tentu saja"}, {"kanji": "全然", "hiragana": "ぜんぜん", "meaning": "sama sekali"}]'::jsonb, 243),
(3, '追', 'ツイ／お.う', 'tsui / o.u', 'Mengejar', 'Berjalan (辶) membuntuti — mengejar', 9, '[{"kanji": "追う", "hiragana": "おう", "meaning": "mengejar"}, {"kanji": "追加", "hiragana": "ついか", "meaning": "tambahan"}, {"kanji": "追求", "hiragana": "ついきゅう", "meaning": "pengejaran"}]'::jsonb, 244),
(3, '負', 'フ／ま.ける／お.う', 'fu / ma.keru / o.u', 'Kalah, Memikul', 'Orang memikul kerang (貝) berat — kalah dan menanggung', 9, '[{"kanji": "負ける", "hiragana": "まける", "meaning": "kalah"}, {"kanji": "負担", "hiragana": "ふたん", "meaning": "beban"}, {"kanji": "勝負", "hiragana": "しょうぶ", "meaning": "pertandingan"}]'::jsonb, 245),
(3, '差', 'サ／さ.す', 'sa / sa.su', 'Selisih, Menyodorkan', 'Domba (羊) dan tangan kerja (工) tak sama — selisih', 10, '[{"kanji": "差", "hiragana": "さ", "meaning": "selisih"}, {"kanji": "差別", "hiragana": "さべつ", "meaning": "diskriminasi"}, {"kanji": "時差", "hiragana": "じさ", "meaning": "perbedaan waktu"}]'::jsonb, 246),
(3, '末', 'マツ／すえ', 'matsu / sue', 'Ujung, Akhir', 'Garis di puncak pohon (木) — ujung paling akhir', 5, '[{"kanji": "週末", "hiragana": "しゅうまつ", "meaning": "akhir pekan"}, {"kanji": "末", "hiragana": "すえ", "meaning": "ujung"}, {"kanji": "年末", "hiragana": "ねんまつ", "meaning": "akhir tahun"}]'::jsonb, 247),
(3, '守', 'シュ・ス／まも.る', 'shu / su / mamo.ru', 'Menjaga, Melindungi', 'Tangan (寸) menjaga di bawah atap (宀) — melindungi rumah', 6, '[{"kanji": "守る", "hiragana": "まもる", "meaning": "melindungi"}, {"kanji": "留守", "hiragana": "るす", "meaning": "tidak di rumah"}, {"kanji": "保守", "hiragana": "ほしゅ", "meaning": "konservatif"}]'::jsonb, 248),
(3, '若', 'ジャク／わか.い', 'jaku / waka.i', 'Muda', 'Rumput (艹) yang baru tumbuh — muda dan segar', 8, '[{"kanji": "若い", "hiragana": "わかい", "meaning": "muda"}, {"kanji": "若者", "hiragana": "わかもの", "meaning": "anak muda"}, {"kanji": "若干", "hiragana": "じゃっかん", "meaning": "sedikit"}]'::jsonb, 249),
(3, '種', 'シュ／たね', 'shu / tane', 'Jenis, Benih', 'Padi (禾) yang berat (重) bijinya — benih dan jenis', 14, '[{"kanji": "種類", "hiragana": "しゅるい", "meaning": "jenis"}, {"kanji": "種", "hiragana": "たね", "meaning": "benih"}, {"kanji": "人種", "hiragana": "じんしゅ", "meaning": "ras"}]'::jsonb, 250),
(3, '段', 'ダン', 'dan', 'Tingkat, Tahap', 'Anak tangga yang dipukul terbentuk — undakan dan tahap', 9, '[{"kanji": "段階", "hiragana": "だんかい", "meaning": "tahap"}, {"kanji": "階段", "hiragana": "かいだん", "meaning": "tangga"}, {"kanji": "値段", "hiragana": "ねだん", "meaning": "harga"}]'::jsonb, 251),
(3, '識', 'シキ', 'shiki', 'Mengenali, Pengetahuan', 'Kata (言) yang menandai (戠) — mengenali dan tahu', 19, '[{"kanji": "知識", "hiragana": "ちしき", "meaning": "pengetahuan"}, {"kanji": "意識", "hiragana": "いしき", "meaning": "kesadaran"}, {"kanji": "常識", "hiragana": "じょうしき", "meaning": "akal sehat"}]'::jsonb, 252),
(3, '呼', 'コ／よ.ぶ', 'ko / yo.bu', 'Memanggil', 'Mulut (口) mengembuskan suara — memanggil', 8, '[{"kanji": "呼ぶ", "hiragana": "よぶ", "meaning": "memanggil"}, {"kanji": "呼吸", "hiragana": "こきゅう", "meaning": "pernapasan"}, {"kanji": "点呼", "hiragana": "てんこ", "meaning": "absensi"}]'::jsonb, 253),
(3, '阪', 'ハン／さか', 'han / saka', 'Lereng (Osaka)', 'Bukit (阝) yang miring (反) — lereng, lazim untuk Osaka', 7, '[{"kanji": "大阪", "hiragana": "おおさか", "meaning": "Osaka"}, {"kanji": "阪神", "hiragana": "はんしん", "meaning": "Hanshin"}, {"kanji": "京阪", "hiragana": "けいはん", "meaning": "Kyoto-Osaka"}]'::jsonb, 254),
(3, '候', 'コウ', 'kō', 'Iklim, Musim', 'Orang mengamati tanda-tanda cuaca — iklim dan musim', 10, '[{"kanji": "天候", "hiragana": "てんこう", "meaning": "cuaca"}, {"kanji": "気候", "hiragana": "きこう", "meaning": "iklim"}, {"kanji": "候補", "hiragana": "こうほ", "meaning": "kandidat"}]'::jsonb, 255),
(3, '突', 'トツ／つ.く', 'totsu / tsu.ku', 'Menusuk, Tiba-tiba', 'Anjing (犬) menyeruak dari lubang (穴) — menerjang tiba-tiba', 8, '[{"kanji": "突然", "hiragana": "とつぜん", "meaning": "tiba-tiba"}, {"kanji": "突く", "hiragana": "つく", "meaning": "menusuk"}, {"kanji": "衝突", "hiragana": "しょうとつ", "meaning": "tabrakan"}]'::jsonb, 256),
(3, '科', 'カ', 'ka', 'Bidang, Jurusan', 'Padi (禾) ditakar (斗) dipilah — cabang ilmu', 9, '[{"kanji": "科学", "hiragana": "かがく", "meaning": "sains"}, {"kanji": "教科書", "hiragana": "きょうかしょ", "meaning": "buku pelajaran"}, {"kanji": "外科", "hiragana": "げか", "meaning": "bedah"}]'::jsonb, 257),
(3, '積', 'セキ／つ.む', 'seki / tsu.mu', 'Menumpuk, Volume', 'Padi (禾) ditumpuk sebagai tanggungan (責) — menumpuk', 16, '[{"kanji": "面積", "hiragana": "めんせき", "meaning": "luas"}, {"kanji": "積む", "hiragana": "つむ", "meaning": "menumpuk"}, {"kanji": "積極的", "hiragana": "せっきょくてき", "meaning": "aktif"}]'::jsonb, 258),
(3, '師', 'シ', 'shi', 'Guru, Ahli', 'Banyak orang berkumpul mengelilingi pemimpin — guru ahli', 10, '[{"kanji": "教師", "hiragana": "きょうし", "meaning": "guru"}, {"kanji": "医師", "hiragana": "いし", "meaning": "dokter"}, {"kanji": "師匠", "hiragana": "ししょう", "meaning": "sang guru"}]'::jsonb, 259),
(3, '登', 'トウ・ト／のぼ.る', 'tō / to / nobo.ru', 'Mendaki, Naik', 'Dua kaki naik ke altar tinggi (豆) — mendaki', 12, '[{"kanji": "登る", "hiragana": "のぼる", "meaning": "mendaki"}, {"kanji": "登山", "hiragana": "とざん", "meaning": "mendaki gunung"}, {"kanji": "登録", "hiragana": "とうろく", "meaning": "pendaftaran"}]'::jsonb, 260),
(3, '単', 'タン', 'tan', 'Tunggal, Sederhana', 'Garpu bermata satu — tunggal dan sederhana', 9, '[{"kanji": "簡単", "hiragana": "かんたん", "meaning": "mudah"}, {"kanji": "単語", "hiragana": "たんご", "meaning": "kosakata"}, {"kanji": "単純", "hiragana": "たんじゅん", "meaning": "sederhana"}]'::jsonb, 261),
(3, '降', 'コウ／お.りる／ふ.る', 'kō / o.riru / fu.ru', 'Turun', 'Bukit (阝) dengan kaki melangkah turun — turun, hujan turun', 10, '[{"kanji": "降りる", "hiragana": "おりる", "meaning": "turun"}, {"kanji": "降る", "hiragana": "ふる", "meaning": "turun (hujan)"}, {"kanji": "以降", "hiragana": "いこう", "meaning": "sejak"}]'::jsonb, 262),
(3, '苦', 'ク／くる.しい／にが.い', 'ku / kuru.shii / niga.i', 'Sengsara, Pahit', 'Rumput (艹) tua (古) terasa pahit — penderitaan', 8, '[{"kanji": "苦しい", "hiragana": "くるしい", "meaning": "sengsara"}, {"kanji": "苦手", "hiragana": "にがて", "meaning": "tidak suka"}, {"kanji": "苦労", "hiragana": "くろう", "meaning": "jerih payah"}]'::jsonb, 263),
(3, '辞', 'ジ／や.める', 'ji / ya.meru', 'Berhenti, Kata', 'Lidah (舌) yang tajam (辛) menyusun kata — pamit dan kata', 13, '[{"kanji": "辞書", "hiragana": "じしょ", "meaning": "kamus"}, {"kanji": "辞める", "hiragana": "やめる", "meaning": "berhenti kerja"}, {"kanji": "辞職", "hiragana": "じしょく", "meaning": "pengunduran diri"}]'::jsonb, 264),
(3, '馬', 'バ／うま', 'ba / uma', 'Kuda', 'Gambar kuda berkaki dan bersurai — kuda', 10, '[{"kanji": "馬", "hiragana": "うま", "meaning": "kuda"}, {"kanji": "競馬", "hiragana": "けいば", "meaning": "pacuan kuda"}, {"kanji": "乗馬", "hiragana": "じょうば", "meaning": "berkuda"}]'::jsonb, 265),
(3, '未', 'ミ・ビ／ま.だ', 'mi / bi / ma.da', 'Belum', 'Pohon dengan cabang atas belum tumbuh — belum sempurna', 5, '[{"kanji": "未来", "hiragana": "みらい", "meaning": "masa depan"}, {"kanji": "未定", "hiragana": "みてい", "meaning": "belum ditentukan"}, {"kanji": "未満", "hiragana": "みまん", "meaning": "kurang dari"}]'::jsonb, 266),
(3, '適', 'テキ／かな.う', 'teki / kana.u', 'Sesuai, Cocok', 'Berjalan (辶) menuju yang pas (啇) — sesuai dan cocok', 14, '[{"kanji": "適当", "hiragana": "てきとう", "meaning": "sesuai"}, {"kanji": "適切", "hiragana": "てきせつ", "meaning": "tepat"}, {"kanji": "快適", "hiragana": "かいてき", "meaning": "nyaman"}]'::jsonb, 267),
(4, '総', 'ソウ', 'sō', 'Total, Umum', 'Benang (糸) yang menyatukan semua (悤) — keseluruhan', 14, '[{"kanji": "総理", "hiragana": "そうり", "meaning": "perdana menteri"}, {"kanji": "総合", "hiragana": "そうごう", "meaning": "gabungan"}, {"kanji": "総額", "hiragana": "そうがく", "meaning": "jumlah total"}]'::jsonb, 251),
(4, '領', 'リョウ', 'ryō', 'Wilayah, Kekuasaan', 'Kepala (頁) yang memimpin (令) — wilayah kekuasaan', 14, '[{"kanji": "領土", "hiragana": "りょうど", "meaning": "wilayah"}, {"kanji": "大統領", "hiragana": "だいとうりょう", "meaning": "presiden"}, {"kanji": "要領", "hiragana": "ようりょう", "meaning": "intisari"}]'::jsonb, 252),
(4, '第', 'ダイ', 'dai', 'Nomor, Urutan', 'Bambu (竹) tersusun berurutan — penanda nomor', 11, '[{"kanji": "第一", "hiragana": "だいいち", "meaning": "pertama"}, {"kanji": "次第", "hiragana": "しだい", "meaning": "tergantung"}, {"kanji": "落第", "hiragana": "らくだい", "meaning": "tidak naik kelas"}]'::jsonb, 253),
(4, '派', 'ハ', 'ha', 'Golongan, Aliran', 'Air (氵) yang bercabang — golongan dan aliran', 9, '[{"kanji": "派手", "hiragana": "はで", "meaning": "mencolok"}, {"kanji": "立派", "hiragana": "りっぱ", "meaning": "megah"}, {"kanji": "派遣", "hiragana": "はけん", "meaning": "pengiriman"}]'::jsonb, 254),
(4, '委', 'イ／ゆだ.ねる', 'i / yuda.neru', 'Mempercayakan, Komite', 'Padi (禾) menunduk pada wanita (女) — menyerahkan tugas', 8, '[{"kanji": "委員", "hiragana": "いいん", "meaning": "anggota komite"}, {"kanji": "委員会", "hiragana": "いいんかい", "meaning": "komite"}, {"kanji": "委託", "hiragana": "いたく", "meaning": "pendelegasian"}]'::jsonb, 255),
(4, '策', 'サク', 'saku', 'Siasat, Kebijakan', 'Bambu (竹) duri (朿) untuk mendorong — siasat dan rencana', 12, '[{"kanji": "政策", "hiragana": "せいさく", "meaning": "kebijakan"}, {"kanji": "対策", "hiragana": "たいさく", "meaning": "penanggulangan"}, {"kanji": "策略", "hiragana": "さくりゃく", "meaning": "taktik"}]'::jsonb, 256),
(4, '団', 'ダン・トン', 'dan / ton', 'Kelompok, Rombongan', 'Sesuatu yang diukur (寸) dalam lingkaran (囗) — kumpulan', 6, '[{"kanji": "団体", "hiragana": "だんたい", "meaning": "organisasi"}, {"kanji": "集団", "hiragana": "しゅうだん", "meaning": "kelompok"}, {"kanji": "布団", "hiragana": "ふとん", "meaning": "kasur lipat"}]'::jsonb, 257),
(4, '各', 'カク／おのおの', 'kaku / onoono', 'Masing-masing', 'Kaki (夂) tiba di tiap mulut (口) — setiap dan masing-masing', 6, '[{"kanji": "各自", "hiragana": "かくじ", "meaning": "masing-masing"}, {"kanji": "各国", "hiragana": "かっこく", "meaning": "tiap negara"}, {"kanji": "各種", "hiragana": "かくしゅ", "meaning": "berbagai jenis"}]'::jsonb, 258),
(4, '革', 'カク／かわ', 'kaku / kawa', 'Kulit, Reformasi', 'Gambar kulit hewan dibentang — kulit dan pembaruan', 9, '[{"kanji": "革命", "hiragana": "かくめい", "meaning": "revolusi"}, {"kanji": "改革", "hiragana": "かいかく", "meaning": "reformasi"}, {"kanji": "革", "hiragana": "かわ", "meaning": "kulit"}]'::jsonb, 259),
(4, '勢', 'セイ／いきお.い', 'sei / ikio.i', 'Tenaga, Momentum', 'Menanam (埶) dengan tenaga (力) — daya dorong dan momentum', 13, '[{"kanji": "勢い", "hiragana": "いきおい", "meaning": "momentum"}, {"kanji": "姿勢", "hiragana": "しせい", "meaning": "sikap tubuh"}, {"kanji": "情勢", "hiragana": "じょうせい", "meaning": "situasi"}]'::jsonb, 260),
(4, '再', 'サイ・サ／ふたた.び', 'sai / sa / futata.bi', 'Kembali, Ulang', 'Tumpukan yang diulang — sekali lagi', 6, '[{"kanji": "再会", "hiragana": "さいかい", "meaning": "reuni"}, {"kanji": "再度", "hiragana": "さいど", "meaning": "sekali lagi"}, {"kanji": "再来年", "hiragana": "さらいねん", "meaning": "tahun depan lusa"}]'::jsonb, 261),
(4, '補', 'ホ／おぎな.う', 'ho / ogina.u', 'Melengkapi, Menambal', 'Pakaian (衤) ditambal (甫) — melengkapi kekurangan', 12, '[{"kanji": "補う", "hiragana": "おぎなう", "meaning": "melengkapi"}, {"kanji": "候補", "hiragana": "こうほ", "meaning": "kandidat"}, {"kanji": "補助", "hiragana": "ほじょ", "meaning": "bantuan"}]'::jsonb, 262),
(5, '氏', 'シ／うじ', 'shi / uji', 'Marga, Tuan', 'Penanda garis keturunan — nama keluarga dan sebutan tuan', 4, '[{"kanji": "氏名", "hiragana": "しめい", "meaning": "nama lengkap"}, {"kanji": "彼氏", "hiragana": "かれし", "meaning": "pacar (pria)"}, {"kanji": "某氏", "hiragana": "ぼうし", "meaning": "seseorang"}]'::jsonb, 251),
(5, '挙', 'キョ／あ.げる', 'kyo / a.geru', 'Mengangkat, Menyelenggarakan', 'Banyak tangan (手) mengangkat bersama — mengangkat', 10, '[{"kanji": "選挙", "hiragana": "せんきょ", "meaning": "pemilu"}, {"kanji": "挙げる", "hiragana": "あげる", "meaning": "mengangkat"}, {"kanji": "挙手", "hiragana": "きょしゅ", "meaning": "angkat tangan"}]'::jsonb, 252),
(5, '企', 'キ／くわだ.てる', 'ki / kuwada.teru', 'Merencanakan, Usaha', 'Orang (人) berjinjit (止) memandang jauh — merencanakan', 6, '[{"kanji": "企業", "hiragana": "きぎょう", "meaning": "perusahaan"}, {"kanji": "企画", "hiragana": "きかく", "meaning": "perencanaan"}, {"kanji": "企てる", "hiragana": "くわだてる", "meaning": "merencanakan"}]'::jsonb, 253),
(5, '藤', 'トウ／ふじ', 'tō / fuji', 'Wisteria', 'Rumput (艹) menjalar seperti air terjun — bunga wisteria', 18, '[{"kanji": "藤", "hiragana": "ふじ", "meaning": "wisteria"}, {"kanji": "佐藤", "hiragana": "さとう", "meaning": "Sato (marga)"}, {"kanji": "藤色", "hiragana": "ふじいろ", "meaning": "warna ungu muda"}]'::jsonb, 254),
(5, '沢', 'タク／さわ', 'taku / sawa', 'Rawa, Berlimpah', 'Air (氵) tergenang di tanah rendah — rawa dan kelimpahan', 7, '[{"kanji": "沢山", "hiragana": "たくさん", "meaning": "banyak"}, {"kanji": "沢", "hiragana": "さわ", "meaning": "rawa"}, {"kanji": "光沢", "hiragana": "こうたく", "meaning": "kilau"}]'::jsonb, 255),
(5, '証', 'ショウ／あかし', 'shō / akashi', 'Bukti, Sertifikat', 'Kata (言) yang lurus benar (正) — kesaksian dan bukti', 12, '[{"kanji": "証明", "hiragana": "しょうめい", "meaning": "pembuktian"}, {"kanji": "保証", "hiragana": "ほしょう", "meaning": "jaminan"}, {"kanji": "免許証", "hiragana": "めんきょしょう", "meaning": "SIM"}]'::jsonb, 256),
(5, '井', 'セイ・ショウ／い', 'sei / shō / i', 'Sumur', 'Bingkai kayu mulut sumur — sumur', 4, '[{"kanji": "井戸", "hiragana": "いど", "meaning": "sumur"}, {"kanji": "天井", "hiragana": "てんじょう", "meaning": "langit-langit"}, {"kanji": "福井", "hiragana": "ふくい", "meaning": "Fukui"}]'::jsonb, 257),
(5, '鮮', 'セン／あざ.やか', 'sen / aza.yaka', 'Segar, Cerah', 'Ikan (魚) dan domba (羊) yang baru — segar dan cerah', 17, '[{"kanji": "新鮮", "hiragana": "しんせん", "meaning": "segar"}, {"kanji": "鮮やか", "hiragana": "あざやか", "meaning": "cerah"}, {"kanji": "朝鮮", "hiragana": "ちょうせん", "meaning": "Korea"}]'::jsonb, 258),
(5, '視', 'シ／み.る', 'shi / mi.ru', 'Memandang, Pandangan', 'Altar (示) yang dilihat (見) saksama — memperhatikan', 11, '[{"kanji": "視点", "hiragana": "してん", "meaning": "sudut pandang"}, {"kanji": "無視", "hiragana": "むし", "meaning": "mengabaikan"}, {"kanji": "重視", "hiragana": "じゅうし", "meaning": "menganggap penting"}]'::jsonb, 259),
(5, '条', 'ジョウ', 'jō', 'Pasal, Syarat', 'Ranting dari pohon — garis aturan dan pasal', 7, '[{"kanji": "条件", "hiragana": "じょうけん", "meaning": "syarat"}, {"kanji": "条約", "hiragana": "じょうやく", "meaning": "perjanjian"}, {"kanji": "第一条", "hiragana": "だいいちじょう", "meaning": "pasal 1"}]'::jsonb, 260),
(5, '幹', 'カン／みき', 'kan / miki', 'Batang Pokok, Inti', 'Batang utama yang menopang — pokok dan inti', 13, '[{"kanji": "幹部", "hiragana": "かんぶ", "meaning": "pimpinan inti"}, {"kanji": "新幹線", "hiragana": "しんかんせん", "meaning": "Shinkansen"}, {"kanji": "幹", "hiragana": "みき", "meaning": "batang pohon"}]'::jsonb, 261)
ON CONFLICT (level_id, kanji) DO NOTHING;

-- ─── DONE ────────────────────────────────────────────────────────────────────
-- Verifikasi:
--   SELECT level_id, count(*) FROM public.kanji GROUP BY 1 ORDER BY 1;  -- 3=194,4=250,5=250
--   SELECT kanji FROM public.kanji GROUP BY kanji HAVING count(DISTINCT level_id)>1;  -- 0 baris
--   SELECT kanji FROM public.kanji WHERE char_length(kanji)<>1;  -- 0 baris
