-- ============================================================
-- Koto no Ha — Seed Dokkai N5 (level_id=1) TAMBAHAN: 10 bacaan (order_index 6-15).
-- Lebih panjang dari batch awal (~200-300 huruf, 11-12 kalimat).
-- Tiap kalimat di content_json: jp + furigana + romaji + terjemahan Indonesia (id).
-- 15 kosakata + 6 soal per bacaan. Hanya INSERT (tidak menghapus bacaan lama).
-- ============================================================
INSERT INTO public.dokkai_passages (level_id, order_index, title, text_content, content_json, vocab_notes, questions, is_premium) VALUES
(1, 6, '私の好きな食べ物 — Makanan Kesukaanku',
 '私の好きな食べ物はラーメンです。特にとんこつラーメンが大好きです。家の近くに有名なラーメン屋があります。毎週土曜日にそこへ食べに行きます。スープがとても熱くておいしいです。私はいつも卵とチャーシューを入れます。友だちもラーメンが好きです。でも、妹はうどんの方が好きです。母は時々家でラーメンを作ります。母のラーメンも本当においしいです。私は一週間に三回ぐらいラーメンを食べます。ラーメンを食べると、とても幸せになります。',
 '[
   {"jp":"私の好きな食べ物はラーメンです。","furigana":"わたしのすきなたべものはラーメンです。","romaji":"Watashi no sukina tabemono wa raamen desu.","id":"Makanan kesukaanku adalah ramen."},
   {"jp":"特にとんこつラーメンが大好きです。","furigana":"とくにとんこつラーメンがだいすきです。","romaji":"Toku ni tonkotsu raamen ga daisuki desu.","id":"Aku terutama sangat suka ramen tonkotsu."},
   {"jp":"家の近くに有名なラーメン屋があります。","furigana":"いえのちかくにゆうめいなラーメンやがあります。","romaji":"Ie no chikaku ni yuumei na raamen-ya ga arimasu.","id":"Di dekat rumah ada kedai ramen yang terkenal."},
   {"jp":"毎週土曜日にそこへ食べに行きます。","furigana":"まいしゅうどようびにそこへたべにいきます。","romaji":"Maishuu doyoubi ni soko e tabe ni ikimasu.","id":"Setiap Sabtu aku pergi ke sana untuk makan."},
   {"jp":"スープがとても熱くておいしいです。","furigana":"スープがとてもあつくておいしいです。","romaji":"Suupu ga totemo atsukute oishii desu.","id":"Kuahnya sangat panas dan enak."},
   {"jp":"私はいつも卵とチャーシューを入れます。","furigana":"わたしはいつもたまごとチャーシューをいれます。","romaji":"Watashi wa itsumo tamago to chaashuu o iremasu.","id":"Aku selalu menambahkan telur dan chashu."},
   {"jp":"友だちもラーメンが好きです。","furigana":"ともだちもラーメンがすきです。","romaji":"Tomodachi mo raamen ga suki desu.","id":"Teman-temanku juga suka ramen."},
   {"jp":"でも、妹はうどんの方が好きです。","furigana":"でも、いもうとはうどんのほうがすきです。","romaji":"Demo, imouto wa udon no hou ga suki desu.","id":"Tapi adik perempuanku lebih suka udon."},
   {"jp":"母は時々家でラーメンを作ります。","furigana":"ははときどきいえでラーメンをつくります。","romaji":"Haha wa tokidoki ie de raamen o tsukurimasu.","id":"Ibu kadang membuat ramen di rumah."},
   {"jp":"母のラーメンも本当においしいです。","furigana":"ははのラーメンもほんとうにおいしいです。","romaji":"Haha no raamen mo hontou ni oishii desu.","id":"Ramen buatan ibu juga benar-benar enak."},
   {"jp":"私は一週間に三回ぐらいラーメンを食べます。","furigana":"わたしはいっしゅうかんにさんかいぐらいラーメンをたべます。","romaji":"Watashi wa isshuukan ni sankai gurai raamen o tabemasu.","id":"Aku makan ramen sekitar tiga kali seminggu."},
   {"jp":"ラーメンを食べると、とても幸せになります。","furigana":"ラーメンをたべると、とてもしあわせになります。","romaji":"Raamen o taberu to, totemo shiawase ni narimasu.","id":"Saat makan ramen, aku merasa sangat bahagia."}
 ]'::jsonb,
 '[
   {"word":"好きな","reading":"すきな","romaji":"sukina","meaning":"yang disukai"},
   {"word":"食べ物","reading":"たべもの","romaji":"tabemono","meaning":"makanan"},
   {"word":"特に","reading":"とくに","romaji":"toku ni","meaning":"terutama"},
   {"word":"大好き","reading":"だいすき","romaji":"daisuki","meaning":"sangat suka"},
   {"word":"近く","reading":"ちかく","romaji":"chikaku","meaning":"dekat"},
   {"word":"有名","reading":"ゆうめい","romaji":"yuumei","meaning":"terkenal"},
   {"word":"毎週","reading":"まいしゅう","romaji":"maishuu","meaning":"setiap minggu"},
   {"word":"土曜日","reading":"どようび","romaji":"doyoubi","meaning":"hari Sabtu"},
   {"word":"スープ","reading":"スープ","romaji":"suupu","meaning":"kuah/sup"},
   {"word":"熱い","reading":"あつい","romaji":"atsui","meaning":"panas"},
   {"word":"卵","reading":"たまご","romaji":"tamago","meaning":"telur"},
   {"word":"妹","reading":"いもうと","romaji":"imouto","meaning":"adik perempuan"},
   {"word":"作ります","reading":"つくります","romaji":"tsukurimasu","meaning":"membuat"},
   {"word":"一週間","reading":"いっしゅうかん","romaji":"isshuukan","meaning":"satu minggu"},
   {"word":"幸せ","reading":"しあわせ","romaji":"shiawase","meaning":"bahagia"}
 ]'::jsonb,
 '[
   {"q":"Makanan kesukaan penulis apa?","options":["Udon","Ramen","Sushi","Nasi goreng"],"answer":1,"explanation":"「好きな食べ物はラーメンです」 = makanan kesukaan adalah ramen."},
   {"q":"Ramen jenis apa yang paling disukai?","options":["Shoyu","Miso","Tonkotsu","Shio"],"answer":2,"explanation":"「とんこつラーメンが大好き」 = sangat suka ramen tonkotsu."},
   {"q":"Kapan penulis pergi makan ramen?","options":["Setiap Minggu","Setiap Sabtu","Setiap Senin","Setiap hari"],"answer":1,"explanation":"「毎週土曜日に…行きます」 = setiap Sabtu."},
   {"q":"Apa yang selalu penulis tambahkan ke ramen?","options":["Sayur dan jamur","Telur dan chashu","Ikan dan tahu","Daging sapi"],"answer":1,"explanation":"「卵とチャーシューを入れます」."},
   {"q":"Adik perempuan penulis lebih suka apa?","options":["Ramen","Udon","Soba","Sushi"],"answer":1,"explanation":"「妹はうどんの方が好き」 = adik lebih suka udon."},
   {"q":"Berapa kali seminggu penulis makan ramen?","options":["Sekali","Dua kali","Sekitar tiga kali","Lima kali"],"answer":2,"explanation":"「一週間に三回ぐらい」 = sekitar tiga kali seminggu."}
 ]'::jsonb,
 false),

(1, 7, '買い物 — Berbelanja',
 '今日は母と買い物に行きました。近くのスーパーへ歩いて行きました。私たちは野菜と果物を買いました。りんごが一つ百円でした。母は牛肉と魚も買いました。それから、パン屋でパンを買いました。パン屋のパンはとてもいい匂いでした。全部で三千円ぐらい使いました。荷物が重かったので、タクシーで帰りました。家で母と一緒に晩ごはんを作りました。とても楽しい一日でした。',
 '[
   {"jp":"今日は母と買い物に行きました。","furigana":"きょうはははとかいものにいきました。","romaji":"Kyou wa haha to kaimono ni ikimashita.","id":"Hari ini aku pergi berbelanja dengan ibu."},
   {"jp":"近くのスーパーへ歩いて行きました。","furigana":"ちかくのスーパーへあるいていきました。","romaji":"Chikaku no suupaa e aruite ikimashita.","id":"Kami berjalan kaki ke supermarket terdekat."},
   {"jp":"私たちは野菜と果物を買いました。","furigana":"わたしたちはやさいとくだものをかいました。","romaji":"Watashitachi wa yasai to kudamono o kaimashita.","id":"Kami membeli sayur dan buah."},
   {"jp":"りんごが一つ百円でした。","furigana":"りんごがひとつひゃくえんでした。","romaji":"Ringo ga hitotsu hyaku-en deshita.","id":"Satu apel harganya seratus yen."},
   {"jp":"母は牛肉と魚も買いました。","furigana":"ははぎゅうにくとさかなもかいました。","romaji":"Haha wa gyuuniku to sakana mo kaimashita.","id":"Ibu juga membeli daging sapi dan ikan."},
   {"jp":"それから、パン屋でパンを買いました。","furigana":"それから、パンやでパンをかいました。","romaji":"Sorekara, pan-ya de pan o kaimashita.","id":"Setelah itu, kami membeli roti di toko roti."},
   {"jp":"パン屋のパンはとてもいい匂いでした。","furigana":"パンやのパンはとてもいいにおいでした。","romaji":"Pan-ya no pan wa totemo ii nioi deshita.","id":"Roti di toko roti baunya sangat harum."},
   {"jp":"全部で三千円ぐらい使いました。","furigana":"ぜんぶでさんぜんえんぐらいつかいました。","romaji":"Zenbu de sanzen-en gurai tsukaimashita.","id":"Totalnya kami habiskan sekitar tiga ribu yen."},
   {"jp":"荷物が重かったので、タクシーで帰りました。","furigana":"にもつがおもかったので、タクシーでかえりました。","romaji":"Nimotsu ga omokatta node, takushii de kaerimashita.","id":"Karena belanjaannya berat, kami pulang naik taksi."},
   {"jp":"家で母と一緒に晩ごはんを作りました。","furigana":"いえでははといっしょにばんごはんをつくりました。","romaji":"Ie de haha to issho ni bangohan o tsukurimashita.","id":"Di rumah aku memasak makan malam bersama ibu."},
   {"jp":"とても楽しい一日でした。","furigana":"とてもたのしいいちにちでした。","romaji":"Totemo tanoshii ichinichi deshita.","id":"Hari yang sangat menyenangkan."}
 ]'::jsonb,
 '[
   {"word":"買い物","reading":"かいもの","romaji":"kaimono","meaning":"belanja"},
   {"word":"スーパー","reading":"スーパー","romaji":"suupaa","meaning":"supermarket"},
   {"word":"歩いて","reading":"あるいて","romaji":"aruite","meaning":"berjalan kaki"},
   {"word":"野菜","reading":"やさい","romaji":"yasai","meaning":"sayur"},
   {"word":"果物","reading":"くだもの","romaji":"kudamono","meaning":"buah"},
   {"word":"りんご","reading":"りんご","romaji":"ringo","meaning":"apel"},
   {"word":"牛肉","reading":"ぎゅうにく","romaji":"gyuuniku","meaning":"daging sapi"},
   {"word":"魚","reading":"さかな","romaji":"sakana","meaning":"ikan"},
   {"word":"パン屋","reading":"パンや","romaji":"pan-ya","meaning":"toko roti"},
   {"word":"匂い","reading":"におい","romaji":"nioi","meaning":"bau/aroma"},
   {"word":"全部","reading":"ぜんぶ","romaji":"zenbu","meaning":"semua/total"},
   {"word":"使いました","reading":"つかいました","romaji":"tsukaimashita","meaning":"memakai/menghabiskan"},
   {"word":"荷物","reading":"にもつ","romaji":"nimotsu","meaning":"barang bawaan"},
   {"word":"重い","reading":"おもい","romaji":"omoi","meaning":"berat"},
   {"word":"一緒に","reading":"いっしょに","romaji":"issho ni","meaning":"bersama"}
 ]'::jsonb,
 '[
   {"q":"Penulis pergi belanja dengan siapa?","options":["Ayah","Ibu","Teman","Adik"],"answer":1,"explanation":"「母と買い物に行きました」 = pergi dengan ibu."},
   {"q":"Bagaimana mereka pergi ke supermarket?","options":["Naik bus","Naik mobil","Jalan kaki","Naik sepeda"],"answer":2,"explanation":"「歩いて行きました」 = berjalan kaki."},
   {"q":"Berapa harga satu apel?","options":["50 yen","100 yen","200 yen","300 yen"],"answer":1,"explanation":"「りんごが一つ百円」 = 100 yen."},
   {"q":"Di mana mereka membeli roti?","options":["Toko roti","Supermarket","Konbini","Pasar"],"answer":0,"explanation":"「パン屋でパンを買いました」."},
   {"q":"Berapa total yang dihabiskan?","options":["1000 yen","2000 yen","Sekitar 3000 yen","5000 yen"],"answer":2,"explanation":"「全部で三千円ぐらい」."},
   {"q":"Kenapa mereka pulang naik taksi?","options":["Hujan","Barang berat","Lelah","Jaraknya jauh"],"answer":1,"explanation":"「荷物が重かったので」 = karena barang berat."}
 ]'::jsonb,
 false),

(1, 8, '今日の天気 — Cuaca Hari Ini',
 '今日はとてもいい天気です。空は青くて、雲が一つもありません。朝は少し寒かったです。でも、昼は暖かくなりました。私は公園を散歩しました。昨日は雨が降っていました。天気予報によると、明日は曇りです。来週は雪が降るかもしれません。冬は寒いですが、私は雪が好きです。夏はとても暑いので、海に行きたいです。いい天気の日は、気持ちがいいです。',
 '[
   {"jp":"今日はとてもいい天気です。","furigana":"きょうはとてもいいてんきです。","romaji":"Kyou wa totemo ii tenki desu.","id":"Hari ini cuacanya sangat bagus."},
   {"jp":"空は青くて、雲が一つもありません。","furigana":"そらはあおくて、くもがひとつもありません。","romaji":"Sora wa aokute, kumo ga hitotsu mo arimasen.","id":"Langit biru dan tidak ada satu awan pun."},
   {"jp":"朝は少し寒かったです。","furigana":"あさはすこしさむかったです。","romaji":"Asa wa sukoshi samukatta desu.","id":"Pagi tadi sedikit dingin."},
   {"jp":"でも、昼は暖かくなりました。","furigana":"でも、ひるはあたたかくなりました。","romaji":"Demo, hiru wa atatakaku narimashita.","id":"Tapi siang menjadi hangat."},
   {"jp":"私は公園を散歩しました。","furigana":"わたしはこうえんをさんぽしました。","romaji":"Watashi wa kouen o sanpo shimashita.","id":"Aku berjalan-jalan di taman."},
   {"jp":"昨日は雨が降っていました。","furigana":"きのうはあめがふっていました。","romaji":"Kinou wa ame ga futte imashita.","id":"Kemarin hujan turun."},
   {"jp":"天気予報によると、明日は曇りです。","furigana":"てんきよほうによると、あしたはくもりです。","romaji":"Tenki yohou ni yoru to, ashita wa kumori desu.","id":"Menurut ramalan cuaca, besok mendung."},
   {"jp":"来週は雪が降るかもしれません。","furigana":"らいしゅうはゆきがふるかもしれません。","romaji":"Raishuu wa yuki ga furu kamoshiremasen.","id":"Minggu depan mungkin turun salju."},
   {"jp":"冬は寒いですが、私は雪が好きです。","furigana":"ふゆはさむいですが、わたしはゆきがすきです。","romaji":"Fuyu wa samui desu ga, watashi wa yuki ga suki desu.","id":"Musim dingin memang dingin, tapi aku suka salju."},
   {"jp":"夏はとても暑いので、海に行きたいです。","furigana":"なつはとてもあついので、うみにいきたいです。","romaji":"Natsu wa totemo atsui node, umi ni ikitai desu.","id":"Musim panas sangat panas, jadi aku ingin pergi ke laut."},
   {"jp":"いい天気の日は、気持ちがいいです。","furigana":"いいてんきのひは、きもちがいいです。","romaji":"Ii tenki no hi wa, kimochi ga ii desu.","id":"Di hari yang cerah, perasaan jadi enak."}
 ]'::jsonb,
 '[
   {"word":"天気","reading":"てんき","romaji":"tenki","meaning":"cuaca"},
   {"word":"空","reading":"そら","romaji":"sora","meaning":"langit"},
   {"word":"青い","reading":"あおい","romaji":"aoi","meaning":"biru"},
   {"word":"雲","reading":"くも","romaji":"kumo","meaning":"awan"},
   {"word":"寒い","reading":"さむい","romaji":"samui","meaning":"dingin (udara)"},
   {"word":"暖かい","reading":"あたたかい","romaji":"atatakai","meaning":"hangat"},
   {"word":"散歩","reading":"さんぽ","romaji":"sanpo","meaning":"jalan-jalan"},
   {"word":"雨","reading":"あめ","romaji":"ame","meaning":"hujan"},
   {"word":"降る","reading":"ふる","romaji":"furu","meaning":"turun (hujan/salju)"},
   {"word":"天気予報","reading":"てんきよほう","romaji":"tenki yohou","meaning":"ramalan cuaca"},
   {"word":"曇り","reading":"くもり","romaji":"kumori","meaning":"mendung"},
   {"word":"雪","reading":"ゆき","romaji":"yuki","meaning":"salju"},
   {"word":"冬","reading":"ふゆ","romaji":"fuyu","meaning":"musim dingin"},
   {"word":"夏","reading":"なつ","romaji":"natsu","meaning":"musim panas"},
   {"word":"気持ち","reading":"きもち","romaji":"kimochi","meaning":"perasaan"}
 ]'::jsonb,
 '[
   {"q":"Bagaimana cuaca hari ini?","options":["Hujan","Mendung","Sangat bagus","Bersalju"],"answer":2,"explanation":"「とてもいい天気です」 = cuaca sangat bagus."},
   {"q":"Bagaimana keadaan langit?","options":["Biru tanpa awan","Mendung","Gelap","Berkabut"],"answer":0,"explanation":"「空は青くて、雲が一つもありません」."},
   {"q":"Bagaimana cuaca pagi tadi?","options":["Panas","Sedikit dingin","Hujan","Bersalju"],"answer":1,"explanation":"「朝は少し寒かった」 = pagi sedikit dingin."},
   {"q":"Menurut ramalan, besok bagaimana?","options":["Cerah","Hujan","Mendung","Salju"],"answer":2,"explanation":"「明日は曇り」 = besok mendung."},
   {"q":"Kenapa penulis suka musim dingin?","options":["Suka salju","Suka baju tebal","Suka liburan","Suka dingin"],"answer":0,"explanation":"「私は雪が好き」 = suka salju."},
   {"q":"Musim panas penulis ingin pergi ke mana?","options":["Gunung","Laut","Taman","Kota"],"answer":1,"explanation":"「海に行きたい」 = ingin ke laut."}
 ]'::jsonb,
 false),

(1, 9, '私のペット — Hewan Peliharaanku',
 '私は犬を一匹飼っています。名前はモモで、三歳です。モモは茶色くて、とても小さいです。毎朝、私はモモと散歩します。モモはボールで遊ぶのが大好きです。私が家に帰ると、モモは喜びます。妹は猫が好きですが、私は犬の方が好きです。モモはとても賢いです。「お座り」と言うと、すぐに座ります。夜はいつも私のベッドの近くで寝ます。モモは私の大切な家族です。',
 '[
   {"jp":"私は犬を一匹飼っています。","furigana":"わたしはいぬをいっぴきかっています。","romaji":"Watashi wa inu o ippiki katte imasu.","id":"Aku memelihara seekor anjing."},
   {"jp":"名前はモモで、三歳です。","furigana":"なまえはモモで、さんさいです。","romaji":"Namae wa Momo de, san-sai desu.","id":"Namanya Momo, umurnya tiga tahun."},
   {"jp":"モモは茶色くて、とても小さいです。","furigana":"モモはちゃいろくて、とてもちいさいです。","romaji":"Momo wa chairokute, totemo chiisai desu.","id":"Momo berwarna cokelat dan sangat kecil."},
   {"jp":"毎朝、私はモモと散歩します。","furigana":"まいあさ、わたしはモモとさんぽします。","romaji":"Maiasa, watashi wa Momo to sanpo shimasu.","id":"Setiap pagi aku jalan-jalan dengan Momo."},
   {"jp":"モモはボールで遊ぶのが大好きです。","furigana":"モモはボールであそぶのがだいすきです。","romaji":"Momo wa booru de asobu no ga daisuki desu.","id":"Momo sangat suka bermain bola."},
   {"jp":"私が家に帰ると、モモは喜びます。","furigana":"わたしがいえにかえると、モモはよろこびます。","romaji":"Watashi ga ie ni kaeru to, Momo wa yorokobimasu.","id":"Saat aku pulang, Momo gembira."},
   {"jp":"妹は猫が好きですが、私は犬の方が好きです。","furigana":"いもうとはねこがすきですが、わたしはいぬのほうがすきです。","romaji":"Imouto wa neko ga suki desu ga, watashi wa inu no hou ga suki desu.","id":"Adikku suka kucing, tapi aku lebih suka anjing."},
   {"jp":"モモはとても賢いです。","furigana":"モモはとてもかしこいです。","romaji":"Momo wa totemo kashikoi desu.","id":"Momo sangat pintar."},
   {"jp":"「お座り」と言うと、すぐに座ります。","furigana":"「おすわり」というと、すぐにすわります。","romaji":"\"Osuwari\" to iu to, sugu ni suwarimasu.","id":"Kalau diberi perintah duduk, dia langsung duduk."},
   {"jp":"夜はいつも私のベッドの近くで寝ます。","furigana":"よるはいつもわたしのベッドのちかくでねます。","romaji":"Yoru wa itsumo watashi no beddo no chikaku de nemasu.","id":"Malam dia selalu tidur di dekat kasurku."},
   {"jp":"モモは私の大切な家族です。","furigana":"モモはわたしのたいせつなかぞくです。","romaji":"Momo wa watashi no taisetsu na kazoku desu.","id":"Momo adalah keluargaku yang berharga."}
 ]'::jsonb,
 '[
   {"word":"犬","reading":"いぬ","romaji":"inu","meaning":"anjing"},
   {"word":"飼う","reading":"かう","romaji":"kau","meaning":"memelihara"},
   {"word":"一匹","reading":"いっぴき","romaji":"ippiki","meaning":"seekor"},
   {"word":"名前","reading":"なまえ","romaji":"namae","meaning":"nama"},
   {"word":"茶色","reading":"ちゃいろ","romaji":"chairo","meaning":"cokelat"},
   {"word":"小さい","reading":"ちいさい","romaji":"chiisai","meaning":"kecil"},
   {"word":"遊ぶ","reading":"あそぶ","romaji":"asobu","meaning":"bermain"},
   {"word":"喜ぶ","reading":"よろこぶ","romaji":"yorokobu","meaning":"gembira"},
   {"word":"猫","reading":"ねこ","romaji":"neko","meaning":"kucing"},
   {"word":"賢い","reading":"かしこい","romaji":"kashikoi","meaning":"pintar"},
   {"word":"座る","reading":"すわる","romaji":"suwaru","meaning":"duduk"},
   {"word":"すぐに","reading":"すぐに","romaji":"sugu ni","meaning":"segera/langsung"},
   {"word":"寝る","reading":"ねる","romaji":"neru","meaning":"tidur"},
   {"word":"大切","reading":"たいせつ","romaji":"taisetsu","meaning":"berharga/penting"},
   {"word":"家族","reading":"かぞく","romaji":"kazoku","meaning":"keluarga"}
 ]'::jsonb,
 '[
   {"q":"Hewan apa yang dipelihara penulis?","options":["Kucing","Anjing","Burung","Ikan"],"answer":1,"explanation":"「犬を一匹飼っています」 = memelihara seekor anjing."},
   {"q":"Berapa umur Momo?","options":["Satu tahun","Dua tahun","Tiga tahun","Lima tahun"],"answer":2,"explanation":"「三歳です」 = tiga tahun."},
   {"q":"Apa yang paling disukai Momo?","options":["Tidur","Bermain bola","Makan","Berlari"],"answer":1,"explanation":"「ボールで遊ぶのが大好き」."},
   {"q":"Adik penulis suka hewan apa?","options":["Anjing","Kucing","Kelinci","Burung"],"answer":1,"explanation":"「妹は猫が好き」 = adik suka kucing."},
   {"q":"Apa yang dilakukan Momo saat diperintah duduk?","options":["Berlari","Duduk","Menggonggong","Tidur"],"answer":1,"explanation":"「すぐに座ります」 = langsung duduk."},
   {"q":"Di mana Momo tidur pada malam hari?","options":["Di luar","Di dapur","Dekat kasur penulis","Di taman"],"answer":2,"explanation":"「私のベッドの近くで寝ます」."}
 ]'::jsonb,
 false),

(1, 10, '教室で — Di Dalam Kelas',
 '私のクラスには学生が二十人います。教室は三階にあります。黒板の前に先生の机があります。私の席は窓の近くです。授業は朝九時に始まります。私たちは日本語を勉強しています。先生はとても親切で、説明が分かりやすいです。分からない時は、手を上げて質問します。昼休みに友だちと教室で話します。授業は午後三時に終わります。私はこのクラスが大好きです。',
 '[
   {"jp":"私のクラスには学生が二十人います。","furigana":"わたしのクラスにはがくせいがにじゅうにんいます。","romaji":"Watashi no kurasu ni wa gakusei ga nijuu-nin imasu.","id":"Di kelasku ada dua puluh siswa."},
   {"jp":"教室は三階にあります。","furigana":"きょうしつはさんがいにあります。","romaji":"Kyoushitsu wa san-gai ni arimasu.","id":"Ruang kelas ada di lantai tiga."},
   {"jp":"黒板の前に先生の机があります。","furigana":"こくばんのまえにせんせいのつくえがあります。","romaji":"Kokuban no mae ni sensei no tsukue ga arimasu.","id":"Di depan papan tulis ada meja guru."},
   {"jp":"私の席は窓の近くです。","furigana":"わたしのせきはまどのちかくです。","romaji":"Watashi no seki wa mado no chikaku desu.","id":"Tempat dudukku dekat jendela."},
   {"jp":"授業は朝九時に始まります。","furigana":"じゅぎょうはあさくじにはじまります。","romaji":"Jugyou wa asa kuji ni hajimarimasu.","id":"Pelajaran dimulai jam sembilan pagi."},
   {"jp":"私たちは日本語を勉強しています。","furigana":"わたしたちはにほんごをべんきょうしています。","romaji":"Watashitachi wa nihongo o benkyou shite imasu.","id":"Kami sedang belajar bahasa Jepang."},
   {"jp":"先生はとても親切で、説明が分かりやすいです。","furigana":"せんせいはとてもしんせつで、せつめいがわかりやすいです。","romaji":"Sensei wa totemo shinsetsu de, setsumei ga wakariyasui desu.","id":"Gurunya sangat ramah dan penjelasannya mudah dimengerti."},
   {"jp":"分からない時は、手を上げて質問します。","furigana":"わからないときは、てをあげてしつもんします。","romaji":"Wakaranai toki wa, te o agete shitsumon shimasu.","id":"Saat tidak mengerti, aku angkat tangan dan bertanya."},
   {"jp":"昼休みに友だちと教室で話します。","furigana":"ひるやすみにともだちときょうしつではなします。","romaji":"Hiruyasumi ni tomodachi to kyoushitsu de hanashimasu.","id":"Saat istirahat siang aku mengobrol dengan teman di kelas."},
   {"jp":"授業は午後三時に終わります。","furigana":"じゅぎょうはごごさんじにおわります。","romaji":"Jugyou wa gogo san-ji ni owarimasu.","id":"Pelajaran selesai jam tiga sore."},
   {"jp":"私はこのクラスが大好きです。","furigana":"わたしはこのクラスがだいすきです。","romaji":"Watashi wa kono kurasu ga daisuki desu.","id":"Aku sangat suka kelas ini."}
 ]'::jsonb,
 '[
   {"word":"クラス","reading":"クラス","romaji":"kurasu","meaning":"kelas"},
   {"word":"学生","reading":"がくせい","romaji":"gakusei","meaning":"siswa/mahasiswa"},
   {"word":"教室","reading":"きょうしつ","romaji":"kyoushitsu","meaning":"ruang kelas"},
   {"word":"三階","reading":"さんがい","romaji":"san-gai","meaning":"lantai tiga"},
   {"word":"黒板","reading":"こくばん","romaji":"kokuban","meaning":"papan tulis"},
   {"word":"机","reading":"つくえ","romaji":"tsukue","meaning":"meja"},
   {"word":"席","reading":"せき","romaji":"seki","meaning":"tempat duduk"},
   {"word":"窓","reading":"まど","romaji":"mado","meaning":"jendela"},
   {"word":"授業","reading":"じゅぎょう","romaji":"jugyou","meaning":"pelajaran"},
   {"word":"始まる","reading":"はじまる","romaji":"hajimaru","meaning":"mulai"},
   {"word":"親切","reading":"しんせつ","romaji":"shinsetsu","meaning":"ramah/baik"},
   {"word":"説明","reading":"せつめい","romaji":"setsumei","meaning":"penjelasan"},
   {"word":"質問","reading":"しつもん","romaji":"shitsumon","meaning":"pertanyaan"},
   {"word":"昼休み","reading":"ひるやすみ","romaji":"hiruyasumi","meaning":"istirahat siang"},
   {"word":"終わる","reading":"おわる","romaji":"owaru","meaning":"selesai"}
 ]'::jsonb,
 '[
   {"q":"Berapa jumlah siswa di kelas?","options":["Sepuluh","Lima belas","Dua puluh","Tiga puluh"],"answer":2,"explanation":"「学生が二十人います」 = ada 20 siswa."},
   {"q":"Di lantai berapa ruang kelas?","options":["Lantai satu","Lantai dua","Lantai tiga","Lantai empat"],"answer":2,"explanation":"「教室は三階」 = lantai tiga."},
   {"q":"Di mana tempat duduk penulis?","options":["Dekat pintu","Dekat jendela","Paling depan","Paling belakang"],"answer":1,"explanation":"「席は窓の近く」 = dekat jendela."},
   {"q":"Jam berapa pelajaran dimulai?","options":["Jam delapan","Jam sembilan","Jam sepuluh","Jam tiga"],"answer":1,"explanation":"「朝九時に始まります」."},
   {"q":"Apa yang dipelajari di kelas?","options":["Bahasa Inggris","Bahasa Jepang","Matematika","Sejarah"],"answer":1,"explanation":"「日本語を勉強しています」."},
   {"q":"Apa yang dilakukan penulis saat tidak mengerti?","options":["Diam saja","Tidur","Angkat tangan dan bertanya","Keluar kelas"],"answer":2,"explanation":"「手を上げて質問します」."}
 ]'::jsonb,
 false),

(1, 11, '私の部屋 — Kamarku',
 '私の部屋は二階にあります。部屋はあまり広くないですが、きれいです。窓の近くにベッドがあります。机の上にパソコンと本があります。壁に好きな歌手のポスターを貼っています。本棚にはたくさんの漫画があります。私は毎晩この部屋で勉強します。週末は部屋を掃除します。部屋が片付くと、気持ちがいいです。友だちが来た時は、この部屋で遊びます。私はこの部屋が一番好きです。',
 '[
   {"jp":"私の部屋は二階にあります。","furigana":"わたしのへやはにかいにあります。","romaji":"Watashi no heya wa ni-kai ni arimasu.","id":"Kamarku ada di lantai dua."},
   {"jp":"部屋はあまり広くないですが、きれいです。","furigana":"へやはあまりひろくないですが、きれいです。","romaji":"Heya wa amari hirokunai desu ga, kirei desu.","id":"Kamarnya tidak terlalu luas, tapi bersih."},
   {"jp":"窓の近くにベッドがあります。","furigana":"まどのちかくにベッドがあります。","romaji":"Mado no chikaku ni beddo ga arimasu.","id":"Di dekat jendela ada kasur."},
   {"jp":"机の上にパソコンと本があります。","furigana":"つくえのうえにパソコンとほんがあります。","romaji":"Tsukue no ue ni pasokon to hon ga arimasu.","id":"Di atas meja ada komputer dan buku."},
   {"jp":"壁に好きな歌手のポスターを貼っています。","furigana":"かべにすきなかしゅのポスターをはっています。","romaji":"Kabe ni suki na kashu no posutaa o hatte imasu.","id":"Di dinding aku menempel poster penyanyi kesukaanku."},
   {"jp":"本棚にはたくさんの漫画があります。","furigana":"ほんだなにはたくさんのまんががあります。","romaji":"Hondana ni wa takusan no manga ga arimasu.","id":"Di rak buku ada banyak manga."},
   {"jp":"私は毎晩この部屋で勉強します。","furigana":"わたしはまいばんこのへやでべんきょうします。","romaji":"Watashi wa maiban kono heya de benkyou shimasu.","id":"Aku belajar di kamar ini setiap malam."},
   {"jp":"週末は部屋を掃除します。","furigana":"しゅうまつはへやをそうじします。","romaji":"Shuumatsu wa heya o souji shimasu.","id":"Akhir pekan aku membersihkan kamar."},
   {"jp":"部屋が片付くと、気持ちがいいです。","furigana":"へやがかたづくと、きもちがいいです。","romaji":"Heya ga katazuku to, kimochi ga ii desu.","id":"Saat kamar rapi, perasaan jadi enak."},
   {"jp":"友だちが来た時は、この部屋で遊びます。","furigana":"ともだちがきたときは、このへやであそびます。","romaji":"Tomodachi ga kita toki wa, kono heya de asobimasu.","id":"Saat teman datang, kami bermain di kamar ini."},
   {"jp":"私はこの部屋が一番好きです。","furigana":"わたしはこのへやがいちばんすきです。","romaji":"Watashi wa kono heya ga ichiban suki desu.","id":"Aku paling suka kamar ini."}
 ]'::jsonb,
 '[
   {"word":"部屋","reading":"へや","romaji":"heya","meaning":"kamar"},
   {"word":"二階","reading":"にかい","romaji":"ni-kai","meaning":"lantai dua"},
   {"word":"広い","reading":"ひろい","romaji":"hiroi","meaning":"luas"},
   {"word":"きれい","reading":"きれい","romaji":"kirei","meaning":"bersih/cantik"},
   {"word":"ベッド","reading":"ベッド","romaji":"beddo","meaning":"kasur/tempat tidur"},
   {"word":"机","reading":"つくえ","romaji":"tsukue","meaning":"meja"},
   {"word":"パソコン","reading":"パソコン","romaji":"pasokon","meaning":"komputer"},
   {"word":"壁","reading":"かべ","romaji":"kabe","meaning":"dinding"},
   {"word":"歌手","reading":"かしゅ","romaji":"kashu","meaning":"penyanyi"},
   {"word":"貼る","reading":"はる","romaji":"haru","meaning":"menempel"},
   {"word":"本棚","reading":"ほんだな","romaji":"hondana","meaning":"rak buku"},
   {"word":"漫画","reading":"まんが","romaji":"manga","meaning":"manga/komik"},
   {"word":"毎晩","reading":"まいばん","romaji":"maiban","meaning":"setiap malam"},
   {"word":"掃除","reading":"そうじ","romaji":"souji","meaning":"membersihkan"},
   {"word":"片付く","reading":"かたづく","romaji":"katazuku","meaning":"menjadi rapi"}
 ]'::jsonb,
 '[
   {"q":"Di lantai berapa kamar penulis?","options":["Lantai satu","Lantai dua","Lantai tiga","Lantai empat"],"answer":1,"explanation":"「部屋は二階」 = lantai dua."},
   {"q":"Bagaimana kamarnya?","options":["Tidak luas tapi bersih","Luas dan kotor","Sangat luas","Gelap"],"answer":0,"explanation":"「広くないですが、きれいです」."},
   {"q":"Apa yang ada di atas meja?","options":["TV","Komputer dan buku","Makanan","Tas"],"answer":1,"explanation":"「机の上にパソコンと本」."},
   {"q":"Apa yang ditempel di dinding?","options":["Peta","Poster penyanyi","Foto keluarga","Kalender"],"answer":1,"explanation":"「好きな歌手のポスター」."},
   {"q":"Apa isi rak buku?","options":["Kamus","Banyak manga","Majalah","Album foto"],"answer":1,"explanation":"「たくさんの漫画」 = banyak manga."},
   {"q":"Kapan penulis membersihkan kamar?","options":["Setiap hari","Akhir pekan","Setiap pagi","Sebulan sekali"],"answer":1,"explanation":"「週末は部屋を掃除します」."}
 ]'::jsonb,
 false),

(1, 12, '私の誕生日 — Hari Ulang Tahunku',
 '私の誕生日は八月十日です。去年の誕生日は家族とレストランへ行きました。母が大きなケーキを買ってくれました。ケーキはチョコレートで、とても甘かったです。友だちもプレゼントをくれました。私は新しい本とかばんをもらいました。みんなで「お誕生日おめでとう」と歌いました。私はろうそくの火を消しました。とても嬉しくて、写真をたくさん撮りました。今年の誕生日も家族と過ごしたいです。誕生日は一年で一番楽しい日です。',
 '[
   {"jp":"私の誕生日は八月十日です。","furigana":"わたしのたんじょうびはちがつとおかです。","romaji":"Watashi no tanjoubi wa hachigatsu tooka desu.","id":"Ulang tahunku tanggal sepuluh Agustus."},
   {"jp":"去年の誕生日は家族とレストランへ行きました。","furigana":"きょねんのたんじょうびはかぞくとレストランへいきました。","romaji":"Kyonen no tanjoubi wa kazoku to resutoran e ikimashita.","id":"Ulang tahun tahun lalu aku pergi ke restoran dengan keluarga."},
   {"jp":"母が大きなケーキを買ってくれました。","furigana":"ははがおおきなケーキをかってくれました。","romaji":"Haha ga ooki na keeki o katte kuremashita.","id":"Ibu membelikanku kue besar."},
   {"jp":"ケーキはチョコレートで、とても甘かったです。","furigana":"ケーキはチョコレートで、とてもあまかったです。","romaji":"Keeki wa chokoreeto de, totemo amakatta desu.","id":"Kuenya cokelat dan sangat manis."},
   {"jp":"友だちもプレゼントをくれました。","furigana":"ともだちもプレゼントをくれました。","romaji":"Tomodachi mo purezento o kuremashita.","id":"Teman-teman juga memberiku hadiah."},
   {"jp":"私は新しい本とかばんをもらいました。","furigana":"わたしはあたらしいほんとかばんをもらいました。","romaji":"Watashi wa atarashii hon to kaban o moraimashita.","id":"Aku menerima buku dan tas baru."},
   {"jp":"みんなで「お誕生日おめでとう」と歌いました。","furigana":"みんなで「おたんじょうびおめでとう」とうたいました。","romaji":"Minna de \"otanjoubi omedetou\" to utaimashita.","id":"Semua menyanyikan selamat ulang tahun."},
   {"jp":"私はろうそくの火を消しました。","furigana":"わたしはろうそくのひをけしました。","romaji":"Watashi wa rousoku no hi o keshimashita.","id":"Aku meniup lilin."},
   {"jp":"とても嬉しくて、写真をたくさん撮りました。","furigana":"とてもうれしくて、しゃしんをたくさんとりました。","romaji":"Totemo ureshikute, shashin o takusan torimashita.","id":"Aku sangat senang dan banyak mengambil foto."},
   {"jp":"今年の誕生日も家族と過ごしたいです。","furigana":"ことしのたんじょうびもかぞくとすごしたいです。","romaji":"Kotoshi no tanjoubi mo kazoku to sugoshitai desu.","id":"Tahun ini pun aku ingin merayakannya bersama keluarga."},
   {"jp":"誕生日は一年で一番楽しい日です。","furigana":"たんじょうびはいちねんでいちばんたのしいひです。","romaji":"Tanjoubi wa ichinen de ichiban tanoshii hi desu.","id":"Ulang tahun adalah hari paling menyenangkan dalam setahun."}
 ]'::jsonb,
 '[
   {"word":"誕生日","reading":"たんじょうび","romaji":"tanjoubi","meaning":"ulang tahun"},
   {"word":"八月","reading":"はちがつ","romaji":"hachigatsu","meaning":"Agustus"},
   {"word":"去年","reading":"きょねん","romaji":"kyonen","meaning":"tahun lalu"},
   {"word":"ケーキ","reading":"ケーキ","romaji":"keeki","meaning":"kue"},
   {"word":"甘い","reading":"あまい","romaji":"amai","meaning":"manis"},
   {"word":"プレゼント","reading":"プレゼント","romaji":"purezento","meaning":"hadiah"},
   {"word":"新しい","reading":"あたらしい","romaji":"atarashii","meaning":"baru"},
   {"word":"かばん","reading":"かばん","romaji":"kaban","meaning":"tas"},
   {"word":"もらう","reading":"もらう","romaji":"morau","meaning":"menerima"},
   {"word":"歌う","reading":"うたう","romaji":"utau","meaning":"menyanyi"},
   {"word":"ろうそく","reading":"ろうそく","romaji":"rousoku","meaning":"lilin"},
   {"word":"消す","reading":"けす","romaji":"kesu","meaning":"memadamkan"},
   {"word":"嬉しい","reading":"うれしい","romaji":"ureshii","meaning":"senang/gembira"},
   {"word":"写真","reading":"しゃしん","romaji":"shashin","meaning":"foto"},
   {"word":"過ごす","reading":"すごす","romaji":"sugosu","meaning":"menghabiskan waktu"}
 ]'::jsonb,
 '[
   {"q":"Kapan ulang tahun penulis?","options":["1 Agustus","10 Agustus","10 Juli","8 Oktober"],"answer":1,"explanation":"「八月十日」 = sepuluh Agustus."},
   {"q":"Tahun lalu ulang tahun dirayakan di mana?","options":["Rumah","Sekolah","Restoran","Taman"],"answer":2,"explanation":"「レストランへ行きました」."},
   {"q":"Kue jenis apa yang dibeli?","options":["Stroberi","Keju","Cokelat","Vanila"],"answer":2,"explanation":"「ケーキはチョコレート」 = kue cokelat."},
   {"q":"Hadiah apa yang diterima penulis?","options":["Baju dan sepatu","Buku dan tas","Mainan","Uang"],"answer":1,"explanation":"「新しい本とかばんをもらいました」."},
   {"q":"Apa yang dilakukan penulis dengan lilin?","options":["Menyalakan","Memadamkan","Membeli","Menyimpan"],"answer":1,"explanation":"「ろうそくの火を消しました」."},
   {"q":"Bagaimana perasaan penulis?","options":["Sedih","Bosan","Sangat senang","Lelah"],"answer":2,"explanation":"「とても嬉しくて」 = sangat senang."}
 ]'::jsonb,
 false),

(1, 13, '朝ごはん — Sarapan',
 '私は毎朝、朝ごはんを食べます。朝ごはんは一日で一番大切な食事です。私はいつもご飯と味噌汁を食べます。卵焼きと魚もよく食べます。父はパンとコーヒーが好きです。妹は朝、果物だけ食べます。朝ごはんを食べないと、元気が出ません。私は牛乳も毎朝飲みます。家族みんなで朝ごはんを食べると、楽しいです。時間がない時は、おにぎりを食べます。朝ごはんを食べて、元気に学校へ行きます。',
 '[
   {"jp":"私は毎朝、朝ごはんを食べます。","furigana":"わたしはまいあさ、あさごはんをたべます。","romaji":"Watashi wa maiasa, asagohan o tabemasu.","id":"Aku sarapan setiap pagi."},
   {"jp":"朝ごはんは一日で一番大切な食事です。","furigana":"あさごはんはいちにちでいちばんたいせつなしょくじです。","romaji":"Asagohan wa ichinichi de ichiban taisetsu na shokuji desu.","id":"Sarapan adalah makan yang paling penting dalam sehari."},
   {"jp":"私はいつもご飯と味噌汁を食べます。","furigana":"わたしはいつもごはんとみそしるをたべます。","romaji":"Watashi wa itsumo gohan to misoshiru o tabemasu.","id":"Aku selalu makan nasi dan sup miso."},
   {"jp":"卵焼きと魚もよく食べます。","furigana":"たまごやきとさかなもよくたべます。","romaji":"Tamagoyaki to sakana mo yoku tabemasu.","id":"Aku juga sering makan telur dadar dan ikan."},
   {"jp":"父はパンとコーヒーが好きです。","furigana":"ちちはパンとコーヒーがすきです。","romaji":"Chichi wa pan to koohii ga suki desu.","id":"Ayah suka roti dan kopi."},
   {"jp":"妹は朝、果物だけ食べます。","furigana":"いもうとはあさ、くだものだけたべます。","romaji":"Imouto wa asa, kudamono dake tabemasu.","id":"Adik perempuanku pagi hanya makan buah."},
   {"jp":"朝ごはんを食べないと、元気が出ません。","furigana":"あさごはんをたべないと、げんきがでません。","romaji":"Asagohan o tabenai to, genki ga demasen.","id":"Kalau tidak sarapan, tidak ada tenaga."},
   {"jp":"私は牛乳も毎朝飲みます。","furigana":"わたしはぎゅうにゅうもまいあさのみます。","romaji":"Watashi wa gyuunyuu mo maiasa nomimasu.","id":"Aku juga minum susu setiap pagi."},
   {"jp":"家族みんなで朝ごはんを食べると、楽しいです。","furigana":"かぞくみんなであさごはんをたべると、たのしいです。","romaji":"Kazoku minna de asagohan o taberu to, tanoshii desu.","id":"Sarapan bersama seluruh keluarga itu menyenangkan."},
   {"jp":"時間がない時は、おにぎりを食べます。","furigana":"じかんがないときは、おにぎりをたべます。","romaji":"Jikan ga nai toki wa, onigiri o tabemasu.","id":"Saat tidak ada waktu, aku makan onigiri."},
   {"jp":"朝ごはんを食べて、元気に学校へ行きます。","furigana":"あさごはんをたべて、げんきにがっこうへいきます。","romaji":"Asagohan o tabete, genki ni gakkou e ikimasu.","id":"Setelah sarapan, aku pergi ke sekolah dengan bersemangat."}
 ]'::jsonb,
 '[
   {"word":"朝ごはん","reading":"あさごはん","romaji":"asagohan","meaning":"sarapan"},
   {"word":"毎朝","reading":"まいあさ","romaji":"maiasa","meaning":"setiap pagi"},
   {"word":"大切","reading":"たいせつ","romaji":"taisetsu","meaning":"penting"},
   {"word":"食事","reading":"しょくじ","romaji":"shokuji","meaning":"makan/hidangan"},
   {"word":"ご飯","reading":"ごはん","romaji":"gohan","meaning":"nasi"},
   {"word":"味噌汁","reading":"みそしる","romaji":"misoshiru","meaning":"sup miso"},
   {"word":"卵焼き","reading":"たまごやき","romaji":"tamagoyaki","meaning":"telur dadar"},
   {"word":"魚","reading":"さかな","romaji":"sakana","meaning":"ikan"},
   {"word":"コーヒー","reading":"コーヒー","romaji":"koohii","meaning":"kopi"},
   {"word":"果物","reading":"くだもの","romaji":"kudamono","meaning":"buah"},
   {"word":"元気","reading":"げんき","romaji":"genki","meaning":"sehat/bersemangat"},
   {"word":"牛乳","reading":"ぎゅうにゅう","romaji":"gyuunyuu","meaning":"susu"},
   {"word":"飲む","reading":"のむ","romaji":"nomu","meaning":"minum"},
   {"word":"おにぎり","reading":"おにぎり","romaji":"onigiri","meaning":"onigiri (nasi kepal)"},
   {"word":"時間","reading":"じかん","romaji":"jikan","meaning":"waktu"}
 ]'::jsonb,
 '[
   {"q":"Menurut penulis, sarapan itu apa?","options":["Makan paling penting","Tidak penting","Makanan ringan","Hanya opsional"],"answer":0,"explanation":"「一番大切な食事」 = makan paling penting."},
   {"q":"Apa yang selalu dimakan penulis?","options":["Roti dan kopi","Nasi dan sup miso","Hanya buah","Mie"],"answer":1,"explanation":"「ご飯と味噌汁を食べます」."},
   {"q":"Ayah penulis suka apa untuk sarapan?","options":["Nasi","Roti dan kopi","Onigiri","Ikan"],"answer":1,"explanation":"「父はパンとコーヒーが好き」."},
   {"q":"Adik perempuan pagi hanya makan apa?","options":["Nasi","Buah","Roti","Telur"],"answer":1,"explanation":"「果物だけ食べます」 = hanya buah."},
   {"q":"Apa akibat tidak sarapan menurut penulis?","options":["Jadi sakit","Tidak ada tenaga","Mengantuk","Lapar terus"],"answer":1,"explanation":"「元気が出ません」 = tidak ada tenaga."},
   {"q":"Saat tidak ada waktu, penulis makan apa?","options":["Roti","Onigiri","Buah","Tidak makan"],"answer":1,"explanation":"「おにぎりを食べます」."}
 ]'::jsonb,
 false),

(1, 14, '私の友だち — Temanku',
 '私には仲のいい友だちがいます。名前はゆきさんです。ゆきさんとは小学校から友だちです。彼女は明るくて、優しいです。私たちはよく一緒に買い物に行きます。ゆきさんは歌が上手です。私が困った時、いつも助けてくれます。週末はよく彼女の家で映画を見ます。私たちは趣味が同じです。来月、一緒に旅行に行く予定です。いい友だちがいて、私は幸せです。',
 '[
   {"jp":"私には仲のいい友だちがいます。","furigana":"わたしにはなかのいいともだちがいます。","romaji":"Watashi ni wa naka no ii tomodachi ga imasu.","id":"Aku punya teman akrab."},
   {"jp":"名前はゆきさんです。","furigana":"なまえはゆきさんです。","romaji":"Namae wa Yuki-san desu.","id":"Namanya Yuki."},
   {"jp":"ゆきさんとは小学校から友だちです。","furigana":"ゆきさんとはしょうがっこうからともだちです。","romaji":"Yuki-san to wa shougakkou kara tomodachi desu.","id":"Aku berteman dengan Yuki sejak SD."},
   {"jp":"彼女は明るくて、優しいです。","furigana":"かのじょはあかるくて、やさしいです。","romaji":"Kanojo wa akarukute, yasashii desu.","id":"Dia ceria dan baik hati."},
   {"jp":"私たちはよく一緒に買い物に行きます。","furigana":"わたしたちはよくいっしょにかいものにいきます。","romaji":"Watashitachi wa yoku issho ni kaimono ni ikimasu.","id":"Kami sering pergi belanja bersama."},
   {"jp":"ゆきさんは歌が上手です。","furigana":"ゆきさんはうたがじょうずです。","romaji":"Yuki-san wa uta ga jouzu desu.","id":"Yuki pandai menyanyi."},
   {"jp":"私が困った時、いつも助けてくれます。","furigana":"わたしがこまったとき、いつもたすけてくれます。","romaji":"Watashi ga komatta toki, itsumo tasukete kuremasu.","id":"Saat aku kesulitan, dia selalu menolongku."},
   {"jp":"週末はよく彼女の家で映画を見ます。","furigana":"しゅうまつはよくかのじょのいえでえいがをみます。","romaji":"Shuumatsu wa yoku kanojo no ie de eiga o mimasu.","id":"Akhir pekan kami sering menonton film di rumahnya."},
   {"jp":"私たちは趣味が同じです。","furigana":"わたしたちはしゅみがおなじです。","romaji":"Watashitachi wa shumi ga onaji desu.","id":"Hobi kami sama."},
   {"jp":"来月、一緒に旅行に行く予定です。","furigana":"らいげつ、いっしょにりょこうにいくよていです。","romaji":"Raigetsu, issho ni ryokou ni iku yotei desu.","id":"Bulan depan kami berencana pergi berlibur bersama."},
   {"jp":"いい友だちがいて、私は幸せです。","furigana":"いいともだちがいて、わたしはしあわせです。","romaji":"Ii tomodachi ga ite, watashi wa shiawase desu.","id":"Punya teman baik membuatku bahagia."}
 ]'::jsonb,
 '[
   {"word":"仲のいい","reading":"なかのいい","romaji":"naka no ii","meaning":"akrab"},
   {"word":"友だち","reading":"ともだち","romaji":"tomodachi","meaning":"teman"},
   {"word":"小学校","reading":"しょうがっこう","romaji":"shougakkou","meaning":"SD"},
   {"word":"彼女","reading":"かのじょ","romaji":"kanojo","meaning":"dia (perempuan)"},
   {"word":"明るい","reading":"あかるい","romaji":"akarui","meaning":"ceria/cerah"},
   {"word":"優しい","reading":"やさしい","romaji":"yasashii","meaning":"baik hati"},
   {"word":"一緒に","reading":"いっしょに","romaji":"issho ni","meaning":"bersama"},
   {"word":"上手","reading":"じょうず","romaji":"jouzu","meaning":"pandai/mahir"},
   {"word":"困る","reading":"こまる","romaji":"komaru","meaning":"kesulitan"},
   {"word":"助ける","reading":"たすける","romaji":"tasukeru","meaning":"menolong"},
   {"word":"映画","reading":"えいが","romaji":"eiga","meaning":"film"},
   {"word":"趣味","reading":"しゅみ","romaji":"shumi","meaning":"hobi"},
   {"word":"同じ","reading":"おなじ","romaji":"onaji","meaning":"sama"},
   {"word":"来月","reading":"らいげつ","romaji":"raigetsu","meaning":"bulan depan"},
   {"word":"予定","reading":"よてい","romaji":"yotei","meaning":"rencana"}
 ]'::jsonb,
 '[
   {"q":"Siapa nama teman penulis?","options":["Momo","Yuki","Anisa","Haruka"],"answer":1,"explanation":"「名前はゆきさんです」."},
   {"q":"Sejak kapan mereka berteman?","options":["SMP","SD","SMA","Universitas"],"answer":1,"explanation":"「小学校から友だち」 = sejak SD."},
   {"q":"Bagaimana sifat Yuki?","options":["Pendiam","Ceria dan baik hati","Pemarah","Pemalu"],"answer":1,"explanation":"「明るくて、優しい」."},
   {"q":"Yuki pandai dalam hal apa?","options":["Memasak","Menyanyi","Menggambar","Olahraga"],"answer":1,"explanation":"「歌が上手」 = pandai menyanyi."},
   {"q":"Apa yang Yuki lakukan saat penulis kesulitan?","options":["Pergi","Menolong","Diam","Marah"],"answer":1,"explanation":"「いつも助けてくれます」 = selalu menolong."},
   {"q":"Apa rencana mereka bulan depan?","options":["Belanja","Berlibur bersama","Ujian","Pindah rumah"],"answer":1,"explanation":"「一緒に旅行に行く予定」."}
 ]'::jsonb,
 false),

(1, 15, '夏休み — Libur Musim Panas',
 'もうすぐ夏休みです。夏休みは八月に一か月あります。今年は家族と海に行く予定です。海で泳いだり、魚を釣ったりしたいです。おばあさんの家にも遊びに行きます。おばあさんの家は田舎にあります。田舎は自然が多くて、空気がきれいです。夜は花火を見たいです。でも、宿題もたくさんあります。毎日少しずつ宿題をするつもりです。楽しい夏休みになるといいです。',
 '[
   {"jp":"もうすぐ夏休みです。","furigana":"もうすぐなつやすみです。","romaji":"Mousugu natsuyasumi desu.","id":"Sebentar lagi libur musim panas."},
   {"jp":"夏休みは八月に一か月あります。","furigana":"なつやすみははちがつにいっかげつあります。","romaji":"Natsuyasumi wa hachigatsu ni ikkagetsu arimasu.","id":"Libur musim panas ada satu bulan di bulan Agustus."},
   {"jp":"今年は家族と海に行く予定です。","furigana":"ことしはかぞくとうみにいくよていです。","romaji":"Kotoshi wa kazoku to umi ni iku yotei desu.","id":"Tahun ini aku berencana pergi ke laut dengan keluarga."},
   {"jp":"海で泳いだり、魚を釣ったりしたいです。","furigana":"うみでおよいだり、さかなをつったりしたいです。","romaji":"Umi de oyoidari, sakana o tsuttari shitai desu.","id":"Aku ingin berenang dan memancing di laut."},
   {"jp":"おばあさんの家にも遊びに行きます。","furigana":"おばあさんのいえにもあそびにいきます。","romaji":"Obaasan no ie ni mo asobi ni ikimasu.","id":"Aku juga akan main ke rumah nenek."},
   {"jp":"おばあさんの家は田舎にあります。","furigana":"おばあさんのいえはいなかにあります。","romaji":"Obaasan no ie wa inaka ni arimasu.","id":"Rumah nenek ada di desa."},
   {"jp":"田舎は自然が多くて、空気がきれいです。","furigana":"いなかはしぜんがおおくて、くうきがきれいです。","romaji":"Inaka wa shizen ga ookute, kuuki ga kirei desu.","id":"Di desa banyak alam dan udaranya bersih."},
   {"jp":"夜は花火を見たいです。","furigana":"よるははなびをみたいです。","romaji":"Yoru wa hanabi o mitai desu.","id":"Malam aku ingin melihat kembang api."},
   {"jp":"でも、宿題もたくさんあります。","furigana":"でも、しゅくだいもたくさんあります。","romaji":"Demo, shukudai mo takusan arimasu.","id":"Tapi PR-nya juga banyak."},
   {"jp":"毎日少しずつ宿題をするつもりです。","furigana":"まいにちすこしずつしゅくだいをするつもりです。","romaji":"Mainichi sukoshi zutsu shukudai o suru tsumori desu.","id":"Aku berniat mengerjakan PR sedikit demi sedikit setiap hari."},
   {"jp":"楽しい夏休みになるといいです。","furigana":"たのしいなつやすみになるといいです。","romaji":"Tanoshii natsuyasumi ni naru to ii desu.","id":"Semoga jadi libur musim panas yang menyenangkan."}
 ]'::jsonb,
 '[
   {"word":"夏休み","reading":"なつやすみ","romaji":"natsuyasumi","meaning":"libur musim panas"},
   {"word":"もうすぐ","reading":"もうすぐ","romaji":"mousugu","meaning":"sebentar lagi"},
   {"word":"一か月","reading":"いっかげつ","romaji":"ikkagetsu","meaning":"satu bulan"},
   {"word":"海","reading":"うみ","romaji":"umi","meaning":"laut"},
   {"word":"泳ぐ","reading":"およぐ","romaji":"oyogu","meaning":"berenang"},
   {"word":"釣る","reading":"つる","romaji":"tsuru","meaning":"memancing"},
   {"word":"おばあさん","reading":"おばあさん","romaji":"obaasan","meaning":"nenek"},
   {"word":"田舎","reading":"いなか","romaji":"inaka","meaning":"desa/kampung"},
   {"word":"自然","reading":"しぜん","romaji":"shizen","meaning":"alam"},
   {"word":"空気","reading":"くうき","romaji":"kuuki","meaning":"udara"},
   {"word":"花火","reading":"はなび","romaji":"hanabi","meaning":"kembang api"},
   {"word":"宿題","reading":"しゅくだい","romaji":"shukudai","meaning":"PR"},
   {"word":"少しずつ","reading":"すこしずつ","romaji":"sukoshi zutsu","meaning":"sedikit demi sedikit"},
   {"word":"つもり","reading":"つもり","romaji":"tsumori","meaning":"berniat"},
   {"word":"楽しい","reading":"たのしい","romaji":"tanoshii","meaning":"menyenangkan"}
 ]'::jsonb,
 '[
   {"q":"Berapa lama libur musim panas?","options":["Satu minggu","Dua minggu","Satu bulan","Dua bulan"],"answer":2,"explanation":"「八月に一か月」 = satu bulan."},
   {"q":"Rencana tahun ini pergi ke mana?","options":["Gunung","Laut","Kota","Luar negeri"],"answer":1,"explanation":"「海に行く予定」 = ke laut."},
   {"q":"Apa yang ingin dilakukan di laut?","options":["Tidur","Berenang dan memancing","Belanja","Membaca"],"answer":1,"explanation":"「泳いだり、魚を釣ったり」."},
   {"q":"Rumah nenek ada di mana?","options":["Kota","Desa","Pantai","Pegunungan"],"answer":1,"explanation":"「田舎にあります」 = di desa."},
   {"q":"Apa yang ingin dilihat malam hari?","options":["Bintang","Kembang api","Film","Festival"],"answer":1,"explanation":"「花火を見たい」 = ingin lihat kembang api."},
   {"q":"Bagaimana rencana mengerjakan PR?","options":["Sekaligus","Sedikit demi sedikit tiap hari","Di hari terakhir","Tidak dikerjakan"],"answer":1,"explanation":"「毎日少しずつ…するつもり」."}
 ]'::jsonb,
 false);
