-- ============================================================
-- Koto no Ha — Seed Dokkai N4 (level_id=2) TAMBAHAN: 10 bacaan (order_index 6-15).
-- ~300-400 huruf, 12-13 kalimat. 15 kosakata + 6 soal per bacaan.
-- Hanya INSERT (tidak menghapus bacaan lama).
-- ============================================================
INSERT INTO public.dokkai_passages (level_id, order_index, title, text_content, content_json, vocab_notes, questions, is_premium) VALUES
(2, 6, '電車の乗り方 — Cara Naik Kereta',
 '日本では、電車が一番便利な乗り物です。私は毎日電車で学校に通っています。まず、駅で切符を買うか、ICカードを使います。改札を通って、ホームへ行きます。電車が来たら、降りる人を先に待ちます。朝のラッシュアワーは、とても込んでいます。席が空いていたら、座ることができます。電車の中では、静かにしなければなりません。電話で話すのはマナー違反です。降りる駅に着いたら、忘れ物に気をつけます。時々、電車が遅れることもあります。でも、日本の電車はだいたい時間に正確です。慣れると、電車の旅はとても楽しいです。',
 '[
   {"jp":"日本では、電車が一番便利な乗り物です。","furigana":"にほんでは、でんしゃがいちばんべんりなのりものです。","romaji":"Nihon de wa, densha ga ichiban benri na norimono desu.","id":"Di Jepang, kereta adalah alat transportasi paling praktis."},
   {"jp":"私は毎日電車で学校に通っています。","furigana":"わたしはまいにちでんしゃでがっこうにかよっています。","romaji":"Watashi wa mainichi densha de gakkou ni kayotte imasu.","id":"Aku setiap hari pergi ke sekolah naik kereta."},
   {"jp":"まず、駅で切符を買うか、ICカードを使います。","furigana":"まず、えきできっぷをかうか、アイシーカードをつかいます。","romaji":"Mazu, eki de kippu o kau ka, ai-shii-kaado o tsukaimasu.","id":"Pertama, beli tiket di stasiun atau gunakan kartu IC."},
   {"jp":"改札を通って、ホームへ行きます。","furigana":"かいさつをとおって、ホームへいきます。","romaji":"Kaisatsu o tootte, hoomu e ikimasu.","id":"Lewati gerbang tiket lalu pergi ke peron."},
   {"jp":"電車が来たら、降りる人を先に待ちます。","furigana":"でんしゃがきたら、おりるひとをさきにまちます。","romaji":"Densha ga kitara, oriru hito o saki ni machimasu.","id":"Kalau kereta datang, tunggu dulu orang yang turun."},
   {"jp":"朝のラッシュアワーは、とても込んでいます。","furigana":"あさのラッシュアワーは、とてもこんでいます。","romaji":"Asa no rasshu awaa wa, totemo konde imasu.","id":"Jam sibuk pagi sangat padat."},
   {"jp":"席が空いていたら、座ることができます。","furigana":"せきがあいていたら、すわることができます。","romaji":"Seki ga aite itara, suwaru koto ga dekimasu.","id":"Kalau ada kursi kosong, kita bisa duduk."},
   {"jp":"電車の中では、静かにしなければなりません。","furigana":"でんしゃのなかでは、しずかにしなければなりません。","romaji":"Densha no naka de wa, shizuka ni shinakereba narimasen.","id":"Di dalam kereta kita harus tenang."},
   {"jp":"電話で話すのはマナー違反です。","furigana":"でんわではなすのはマナーいはんです。","romaji":"Denwa de hanasu no wa manaa ihan desu.","id":"Berbicara di telepon melanggar etika."},
   {"jp":"降りる駅に着いたら、忘れ物に気をつけます。","furigana":"おりるえきについたら、わすれものにきをつけます。","romaji":"Oriru eki ni tsuitara, wasuremono ni ki o tsukemasu.","id":"Saat tiba di stasiun tujuan, hati-hati jangan ada barang tertinggal."},
   {"jp":"時々、電車が遅れることもあります。","furigana":"ときどき、でんしゃがおくれることもあります。","romaji":"Tokidoki, densha ga okureru koto mo arimasu.","id":"Kadang kereta juga terlambat."},
   {"jp":"でも、日本の電車はだいたい時間に正確です。","furigana":"でも、にほんのでんしゃはだいたいじかんにせいかくです。","romaji":"Demo, nihon no densha wa daitai jikan ni seikaku desu.","id":"Tapi kereta Jepang umumnya tepat waktu."},
   {"jp":"慣れると、電車の旅はとても楽しいです。","furigana":"なれると、でんしゃのたびはとてもたのしいです。","romaji":"Nareru to, densha no tabi wa totemo tanoshii desu.","id":"Setelah terbiasa, perjalanan kereta sangat menyenangkan."}
 ]'::jsonb,
 '[
   {"word":"電車","reading":"でんしゃ","romaji":"densha","meaning":"kereta listrik"},
   {"word":"便利","reading":"べんり","romaji":"benri","meaning":"praktis"},
   {"word":"乗り物","reading":"のりもの","romaji":"norimono","meaning":"kendaraan"},
   {"word":"通う","reading":"かよう","romaji":"kayou","meaning":"pergi rutin/bolak-balik"},
   {"word":"切符","reading":"きっぷ","romaji":"kippu","meaning":"tiket"},
   {"word":"改札","reading":"かいさつ","romaji":"kaisatsu","meaning":"gerbang tiket"},
   {"word":"ホーム","reading":"ホーム","romaji":"hoomu","meaning":"peron"},
   {"word":"降りる","reading":"おりる","romaji":"oriru","meaning":"turun"},
   {"word":"込む","reading":"こむ","romaji":"komu","meaning":"padat/ramai"},
   {"word":"席","reading":"せき","romaji":"seki","meaning":"kursi"},
   {"word":"空く","reading":"あく","romaji":"aku","meaning":"kosong"},
   {"word":"静か","reading":"しずか","romaji":"shizuka","meaning":"tenang"},
   {"word":"マナー違反","reading":"マナーいはん","romaji":"manaa ihan","meaning":"pelanggaran etika"},
   {"word":"忘れ物","reading":"わすれもの","romaji":"wasuremono","meaning":"barang tertinggal"},
   {"word":"遅れる","reading":"おくれる","romaji":"okureru","meaning":"terlambat"}
 ]'::jsonb,
 '[
   {"q":"Di Jepang, transportasi paling praktis adalah?","options":["Bus","Kereta","Taksi","Sepeda"],"answer":1,"explanation":"「電車が一番便利な乗り物」 = kereta paling praktis."},
   {"q":"Apa yang dilakukan dulu di stasiun?","options":["Cari kursi","Beli tiket atau pakai kartu IC","Menelepon","Makan"],"answer":1,"explanation":"「切符を買うか、ICカードを使います」."},
   {"q":"Saat kereta datang, apa yang dilakukan dulu?","options":["Langsung masuk","Tunggu orang yang turun dulu","Berlari","Duduk"],"answer":1,"explanation":"「降りる人を先に待ちます」."},
   {"q":"Bagaimana jam sibuk pagi?","options":["Sepi","Sangat padat","Biasa saja","Tutup"],"answer":1,"explanation":"「とても込んでいます」 = sangat padat."},
   {"q":"Apa yang melanggar etika di kereta?","options":["Duduk","Membaca","Bicara di telepon","Tidur"],"answer":2,"explanation":"「電話で話すのはマナー違反」."},
   {"q":"Bagaimana ketepatan waktu kereta Jepang?","options":["Sering telat","Umumnya tepat waktu","Tidak ada jadwal","Selalu telat"],"answer":1,"explanation":"「だいたい時間に正確」 = umumnya tepat waktu."}
 ]'::jsonb,
 false),
(2, 7, '日本のコンビニ — Konbini Jepang',
 '日本のコンビニはとても便利です。コンビニは二十四時間開いています。食べ物や飲み物だけでなく、雑誌も売っています。おにぎりやお弁当は、いつも新鮮です。お弁当は電子レンジで温めてくれます。コンビニで公共料金を払うこともできます。荷物を送ったり、受け取ったりできます。ATMもあるので、お金をおろせます。トイレを貸してくれる店も多いです。店員さんはいつも丁寧で親切です。私はよく帰り道にコンビニに寄ります。コンビニは私たちの生活に欠かせません。',
 '[
   {"jp":"日本のコンビニはとても便利です。","furigana":"にほんのコンビニはとてもべんりです。","romaji":"Nihon no konbini wa totemo benri desu.","id":"Konbini Jepang sangat praktis."},
   {"jp":"コンビニは二十四時間開いています。","furigana":"コンビニはにじゅうよじかんあいています。","romaji":"Konbini wa nijuuyo-jikan aite imasu.","id":"Konbini buka 24 jam."},
   {"jp":"食べ物や飲み物だけでなく、雑誌も売っています。","furigana":"たべものやのみものだけでなく、ざっしもうっています。","romaji":"Tabemono ya nomimono dake de naku, zasshi mo utte imasu.","id":"Tidak hanya makanan dan minuman, majalah pun dijual."},
   {"jp":"おにぎりやお弁当は、いつも新鮮です。","furigana":"おにぎりやおべんとうは、いつもしんせんです。","romaji":"Onigiri ya obentou wa, itsumo shinsen desu.","id":"Onigiri dan bento selalu segar."},
   {"jp":"お弁当は電子レンジで温めてくれます。","furigana":"おべんとうはでんしレンジであたためてくれます。","romaji":"Obentou wa denshi renji de atatamete kuremasu.","id":"Bento dihangatkan dengan microwave untuk kita."},
   {"jp":"コンビニで公共料金を払うこともできます。","furigana":"コンビニでこうきょうりょうきんをはらうこともできます。","romaji":"Konbini de koukyou ryoukin o harau koto mo dekimasu.","id":"Di konbini kita juga bisa membayar tagihan umum."},
   {"jp":"荷物を送ったり、受け取ったりできます。","furigana":"にもつをおくったり、うけとったりできます。","romaji":"Nimotsu o okuttari, uketottari dekimasu.","id":"Kita bisa mengirim dan menerima paket."},
   {"jp":"ATMもあるので、お金をおろせます。","furigana":"エーティーエムもあるので、おかねをおろせます。","romaji":"ATM mo aru node, okane o orosemasu.","id":"Karena ada ATM juga, kita bisa menarik uang."},
   {"jp":"トイレを貸してくれる店も多いです。","furigana":"トイレをかしてくれるみせもおおいです。","romaji":"Toire o kashite kureru mise mo ooi desu.","id":"Banyak juga toko yang meminjamkan toilet."},
   {"jp":"店員さんはいつも丁寧で親切です。","furigana":"てんいんさんはいつもていねいでしんせつです。","romaji":"Ten-in-san wa itsumo teinei de shinsetsu desu.","id":"Pelayan toko selalu sopan dan ramah."},
   {"jp":"私はよく帰り道にコンビニに寄ります。","furigana":"わたしはよくかえりみちにコンビニによります。","romaji":"Watashi wa yoku kaerimichi ni konbini ni yorimasu.","id":"Aku sering mampir ke konbini saat perjalanan pulang."},
   {"jp":"コンビニは私たちの生活に欠かせません。","furigana":"コンビニはわたしたちのせいかつにかかせません。","romaji":"Konbini wa watashitachi no seikatsu ni kakasemasen.","id":"Konbini tak tergantikan dalam kehidupan kita."}
 ]'::jsonb,
 '[
   {"word":"コンビニ","reading":"コンビニ","romaji":"konbini","meaning":"minimarket 24 jam"},
   {"word":"便利","reading":"べんり","romaji":"benri","meaning":"praktis"},
   {"word":"二十四時間","reading":"にじゅうよじかん","romaji":"nijuuyo-jikan","meaning":"24 jam"},
   {"word":"雑誌","reading":"ざっし","romaji":"zasshi","meaning":"majalah"},
   {"word":"売る","reading":"うる","romaji":"uru","meaning":"menjual"},
   {"word":"お弁当","reading":"おべんとう","romaji":"obentou","meaning":"bekal/bento"},
   {"word":"新鮮","reading":"しんせん","romaji":"shinsen","meaning":"segar"},
   {"word":"温める","reading":"あたためる","romaji":"atatameru","meaning":"menghangatkan"},
   {"word":"公共料金","reading":"こうきょうりょうきん","romaji":"koukyou ryoukin","meaning":"tagihan umum (listrik dll.)"},
   {"word":"払う","reading":"はらう","romaji":"harau","meaning":"membayar"},
   {"word":"荷物","reading":"にもつ","romaji":"nimotsu","meaning":"paket/barang"},
   {"word":"受け取る","reading":"うけとる","romaji":"uketoru","meaning":"menerima"},
   {"word":"店員","reading":"てんいん","romaji":"ten-in","meaning":"pelayan toko"},
   {"word":"丁寧","reading":"ていねい","romaji":"teinei","meaning":"sopan/cermat"},
   {"word":"欠かせない","reading":"かかせない","romaji":"kakasenai","meaning":"tak tergantikan"}
 ]'::jsonb,
 '[
   {"q":"Konbini buka berapa lama?","options":["12 jam","24 jam","Siang saja","Sampai malam"],"answer":1,"explanation":"「二十四時間開いています」 = buka 24 jam."},
   {"q":"Selain makanan dan minuman, apa yang dijual?","options":["Baju","Majalah","Sepatu","Obat"],"answer":1,"explanation":"「雑誌も売っています」 = majalah juga dijual."},
   {"q":"Bento dihangatkan dengan apa?","options":["Oven","Microwave","Kompor","Air panas"],"answer":1,"explanation":"「電子レンジで温めて」 = dengan microwave."},
   {"q":"Apa yang bisa dibayar di konbini?","options":["Pajak mobil","Tagihan umum","SPP","Sewa rumah"],"answer":1,"explanation":"「公共料金を払うこともできます」."},
   {"q":"Bagaimana pelayan tokonya?","options":["Cuek","Sopan dan ramah","Galak","Lambat"],"answer":1,"explanation":"「丁寧で親切」 = sopan dan ramah."},
   {"q":"Kapan penulis sering mampir ke konbini?","options":["Pagi hari","Saat perjalanan pulang","Tengah malam","Saat libur"],"answer":1,"explanation":"「帰り道にコンビニに寄ります」."}
 ]'::jsonb,
 false),
(2, 8, 'お祭り — Festival Matsuri',
 '夏になると、日本では色々なお祭りがあります。先週、私は友だちと町のお祭りに行きました。たくさんの人が浴衣を着ていました。道の両側に屋台がたくさん並んでいました。私はたこ焼きとかき氷を食べました。金魚すくいもやってみました。太鼓の音が町中に響いていました。夜になると、大きな花火が上がりました。花火はとてもきれいで、みんな空を見上げました。お祭りは日本の大切な伝統文化です。私はまた来年も行きたいと思います。お祭りの思い出は一生忘れません。',
 '[
   {"jp":"夏になると、日本では色々なお祭りがあります。","furigana":"なつになると、にほんではいろいろなおまつりがあります。","romaji":"Natsu ni naru to, nihon de wa iroiro na omatsuri ga arimasu.","id":"Saat musim panas, di Jepang ada bermacam festival."},
   {"jp":"先週、私は友だちと町のお祭りに行きました。","furigana":"せんしゅう、わたしはともだちとまちのおまつりにいきました。","romaji":"Senshuu, watashi wa tomodachi to machi no omatsuri ni ikimashita.","id":"Minggu lalu aku pergi ke festival kota dengan teman."},
   {"jp":"たくさんの人が浴衣を着ていました。","furigana":"たくさんのひとがゆかたをきていました。","romaji":"Takusan no hito ga yukata o kite imashita.","id":"Banyak orang mengenakan yukata."},
   {"jp":"道の両側に屋台がたくさん並んでいました。","furigana":"みちのりょうがわにやたいがたくさんならんでいました。","romaji":"Michi no ryougawa ni yatai ga takusan narande imashita.","id":"Di kedua sisi jalan berjajar banyak kios."},
   {"jp":"私はたこ焼きとかき氷を食べました。","furigana":"わたしはたこやきとかきごおりをたべました。","romaji":"Watashi wa takoyaki to kakigoori o tabemashita.","id":"Aku makan takoyaki dan es serut."},
   {"jp":"金魚すくいもやってみました。","furigana":"きんぎょすくいもやってみました。","romaji":"Kingyo sukui mo yatte mimashita.","id":"Aku juga mencoba menangkap ikan mas."},
   {"jp":"太鼓の音が町中に響いていました。","furigana":"たいこのおとがまちじゅうにひびいていました。","romaji":"Taiko no oto ga machijuu ni hibiite imashita.","id":"Suara taiko bergema ke seluruh kota."},
   {"jp":"夜になると、大きな花火が上がりました。","furigana":"よるになると、おおきなはなびがあがりました。","romaji":"Yoru ni naru to, ooki na hanabi ga agarimashita.","id":"Saat malam, kembang api besar diluncurkan."},
   {"jp":"花火はとてもきれいで、みんな空を見上げました。","furigana":"はなびはとてもきれいで、みんなそらをみあげました。","romaji":"Hanabi wa totemo kirei de, minna sora o miagemashita.","id":"Kembang apinya sangat indah, semua mendongak ke langit."},
   {"jp":"お祭りは日本の大切な伝統文化です。","furigana":"おまつりはにほんのたいせつなでんとうぶんかです。","romaji":"Omatsuri wa nihon no taisetsu na dentou bunka desu.","id":"Festival adalah budaya tradisional Jepang yang penting."},
   {"jp":"私はまた来年も行きたいと思います。","furigana":"わたしはまたらいねんもいきたいとおもいます。","romaji":"Watashi wa mata rainen mo ikitai to omoimasu.","id":"Aku ingin pergi lagi tahun depan."},
   {"jp":"お祭りの思い出は一生忘れません。","furigana":"おまつりのおもいではいっしょうわすれません。","romaji":"Omatsuri no omoide wa isshou wasuremasen.","id":"Kenangan festival ini takkan kulupakan seumur hidup."}
 ]'::jsonb,
 '[
   {"word":"お祭り","reading":"おまつり","romaji":"omatsuri","meaning":"festival"},
   {"word":"浴衣","reading":"ゆかた","romaji":"yukata","meaning":"yukata (kimono musim panas)"},
   {"word":"屋台","reading":"やたい","romaji":"yatai","meaning":"kios/warung tenda"},
   {"word":"並ぶ","reading":"ならぶ","romaji":"narabu","meaning":"berjajar"},
   {"word":"たこ焼き","reading":"たこやき","romaji":"takoyaki","meaning":"takoyaki"},
   {"word":"かき氷","reading":"かきごおり","romaji":"kakigoori","meaning":"es serut"},
   {"word":"金魚すくい","reading":"きんぎょすくい","romaji":"kingyo sukui","meaning":"permainan tangkap ikan mas"},
   {"word":"太鼓","reading":"たいこ","romaji":"taiko","meaning":"genderang taiko"},
   {"word":"響く","reading":"ひびく","romaji":"hibiku","meaning":"bergema"},
   {"word":"花火","reading":"はなび","romaji":"hanabi","meaning":"kembang api"},
   {"word":"上がる","reading":"あがる","romaji":"agaru","meaning":"naik/diluncurkan"},
   {"word":"見上げる","reading":"みあげる","romaji":"miageru","meaning":"mendongak"},
   {"word":"伝統文化","reading":"でんとうぶんか","romaji":"dentou bunka","meaning":"budaya tradisional"},
   {"word":"思い出","reading":"おもいで","romaji":"omoide","meaning":"kenangan"},
   {"word":"一生","reading":"いっしょう","romaji":"isshou","meaning":"seumur hidup"}
 ]'::jsonb,
 '[
   {"q":"Kapan banyak festival diadakan di Jepang?","options":["Musim dingin","Musim panas","Musim semi","Musim gugur"],"answer":1,"explanation":"「夏になると…お祭りがあります」."},
   {"q":"Apa yang dikenakan banyak orang?","options":["Kimono formal","Yukata","Jas","Seragam"],"answer":1,"explanation":"「浴衣を着ていました」 = mengenakan yukata."},
   {"q":"Apa yang penulis makan?","options":["Ramen","Takoyaki dan es serut","Sushi","Onigiri"],"answer":1,"explanation":"「たこ焼きとかき氷を食べました」."},
   {"q":"Suara apa yang bergema ke seluruh kota?","options":["Lonceng","Taiko","Musik pop","Peluit"],"answer":1,"explanation":"「太鼓の音が…響いていました」."},
   {"q":"Apa yang terjadi saat malam?","options":["Hujan","Kembang api besar diluncurkan","Festival selesai","Parade"],"answer":1,"explanation":"「大きな花火が上がりました」."},
   {"q":"Bagaimana pendapat penulis tentang festival?","options":["Membosankan","Budaya tradisional yang penting","Terlalu ramai","Mahal"],"answer":1,"explanation":"「大切な伝統文化です」."}
 ]'::jsonb,
 false),
(2, 9, '引っ越し — Pindah Rumah',
 '来月、私は新しいアパートに引っ越します。今の部屋は狭くて、少し不便でした。新しいアパートは駅から近くて、便利です。引っ越しの前に、荷物を箱に詰めます。いらない物は捨てるか、友だちにあげます。引っ越しの日は、トラックで荷物を運びます。友だちが手伝いに来てくれました。大きな家具を運ぶのは大変でした。新しい部屋を掃除してから、荷物を片付けました。引っ越しの後で、近所の人に挨拶しました。新しい生活が始まって、とても楽しみです。早く新しい町に慣れたいです。',
 '[
   {"jp":"来月、私は新しいアパートに引っ越します。","furigana":"らいげつ、わたしはあたらしいアパートにひっこします。","romaji":"Raigetsu, watashi wa atarashii apaato ni hikkoshimasu.","id":"Bulan depan aku pindah ke apartemen baru."},
   {"jp":"今の部屋は狭くて、少し不便でした。","furigana":"いまのへやはせまくて、すこしふべんでした。","romaji":"Ima no heya wa semakute, sukoshi fuben deshita.","id":"Kamarku sekarang sempit dan agak tidak nyaman."},
   {"jp":"新しいアパートは駅から近くて、便利です。","furigana":"あたらしいアパートはえきからちかくて、べんりです。","romaji":"Atarashii apaato wa eki kara chikakute, benri desu.","id":"Apartemen baru dekat stasiun dan praktis."},
   {"jp":"引っ越しの前に、荷物を箱に詰めます。","furigana":"ひっこしのまえに、にもつをはこにつめます。","romaji":"Hikkoshi no mae ni, nimotsu o hako ni tsumemasu.","id":"Sebelum pindah, aku mengemas barang ke dalam kardus."},
   {"jp":"いらない物は捨てるか、友だちにあげます。","furigana":"いらないものはすてるか、ともだちにあげます。","romaji":"Iranai mono wa suteru ka, tomodachi ni agemasu.","id":"Barang yang tidak perlu dibuang atau diberikan ke teman."},
   {"jp":"引っ越しの日は、トラックで荷物を運びます。","furigana":"ひっこしのひは、トラックでにもつをはこびます。","romaji":"Hikkoshi no hi wa, torakku de nimotsu o hakobimasu.","id":"Pada hari pindah, barang diangkut dengan truk."},
   {"jp":"友だちが手伝いに来てくれました。","furigana":"ともだちがてつだいにきてくれました。","romaji":"Tomodachi ga tetsudai ni kite kuremashita.","id":"Teman datang untuk membantu."},
   {"jp":"大きな家具を運ぶのは大変でした。","furigana":"おおきなかぐをはこぶのはたいへんでした。","romaji":"Ooki na kagu o hakobu no wa taihen deshita.","id":"Mengangkut furnitur besar itu melelahkan."},
   {"jp":"新しい部屋を掃除してから、荷物を片付けました。","furigana":"あたらしいへやをそうじしてから、にもつをかたづけました。","romaji":"Atarashii heya o souji shite kara, nimotsu o katazukemashita.","id":"Setelah membersihkan kamar baru, aku merapikan barang."},
   {"jp":"引っ越しの後で、近所の人に挨拶しました。","furigana":"ひっこしのあとで、きんじょのひとにあいさつしました。","romaji":"Hikkoshi no ato de, kinjo no hito ni aisatsu shimashita.","id":"Setelah pindah, aku menyapa para tetangga."},
   {"jp":"新しい生活が始まって、とても楽しみです。","furigana":"あたらしいせいかつがはじまって、とてもたのしみです。","romaji":"Atarashii seikatsu ga hajimatte, totemo tanoshimi desu.","id":"Kehidupan baru dimulai, aku sangat menantikannya."},
   {"jp":"早く新しい町に慣れたいです。","furigana":"はやくあたらしいまちになれたいです。","romaji":"Hayaku atarashii machi ni naretai desu.","id":"Aku ingin cepat terbiasa dengan kota baru."}
 ]'::jsonb,
 '[
   {"word":"引っ越す","reading":"ひっこす","romaji":"hikkosu","meaning":"pindah rumah"},
   {"word":"アパート","reading":"アパート","romaji":"apaato","meaning":"apartemen"},
   {"word":"狭い","reading":"せまい","romaji":"semai","meaning":"sempit"},
   {"word":"不便","reading":"ふべん","romaji":"fuben","meaning":"tidak praktis"},
   {"word":"荷物","reading":"にもつ","romaji":"nimotsu","meaning":"barang"},
   {"word":"箱","reading":"はこ","romaji":"hako","meaning":"kotak/kardus"},
   {"word":"詰める","reading":"つめる","romaji":"tsumeru","meaning":"mengemas/mengisi"},
   {"word":"捨てる","reading":"すてる","romaji":"suteru","meaning":"membuang"},
   {"word":"運ぶ","reading":"はこぶ","romaji":"hakobu","meaning":"mengangkut"},
   {"word":"手伝い","reading":"てつだい","romaji":"tetsudai","meaning":"bantuan"},
   {"word":"家具","reading":"かぐ","romaji":"kagu","meaning":"furnitur"},
   {"word":"大変","reading":"たいへん","romaji":"taihen","meaning":"berat/melelahkan"},
   {"word":"片付ける","reading":"かたづける","romaji":"katazukeru","meaning":"merapikan"},
   {"word":"近所","reading":"きんじょ","romaji":"kinjo","meaning":"sekitar/tetangga"},
   {"word":"挨拶","reading":"あいさつ","romaji":"aisatsu","meaning":"salam/menyapa"}
 ]'::jsonb,
 '[
   {"q":"Kapan penulis pindah?","options":["Minggu depan","Bulan depan","Tahun depan","Besok"],"answer":1,"explanation":"「来月…引っ越します」 = bulan depan."},
   {"q":"Kenapa kamar sekarang kurang nyaman?","options":["Mahal","Sempit","Jauh","Berisik"],"answer":1,"explanation":"「狭くて、少し不便」 = sempit."},
   {"q":"Apa keunggulan apartemen baru?","options":["Murah","Luas","Dekat stasiun","Sepi"],"answer":2,"explanation":"「駅から近くて、便利」."},
   {"q":"Barang yang tidak perlu diapakan?","options":["Disimpan","Dijual","Dibuang atau diberikan teman","Dikirim"],"answer":2,"explanation":"「捨てるか、友だちにあげます」."},
   {"q":"Siapa yang datang membantu?","options":["Keluarga","Teman","Tetangga","Petugas"],"answer":1,"explanation":"「友だちが手伝いに来てくれました」."},
   {"q":"Apa yang dilakukan setelah pindah?","options":["Tidur","Menyapa tetangga","Belanja","Pesta"],"answer":1,"explanation":"「近所の人に挨拶しました」."}
 ]'::jsonb,
 false),
(2, 10, '料理に挑戦 — Mencoba Memasak',
 '先週末、私は初めてカレーを作ってみました。インターネットでレシピを調べました。まず、スーパーで材料を買いました。野菜と肉を小さく切りました。包丁を使う時は、指に気をつけました。鍋で野菜と肉をよく炒めました。水を入れて、三十分ぐらい煮込みました。最後にカレーのルーを入れました。少し焦がしてしまいましたが、味はよかったです。家族はおいしいと言ってくれました。自分で作った料理は、特別おいしく感じました。今度は別の料理にも挑戦したいです。',
 '[
   {"jp":"先週末、私は初めてカレーを作ってみました。","furigana":"せんしゅうまつ、わたしははじめてカレーをつくってみました。","romaji":"Senshuumatsu, watashi wa hajimete karee o tsukutte mimashita.","id":"Akhir pekan lalu, aku mencoba membuat kari untuk pertama kali."},
   {"jp":"インターネットでレシピを調べました。","furigana":"インターネットでレシピをしらべました。","romaji":"Intaanetto de reshipi o shirabemashita.","id":"Aku mencari resep di internet."},
   {"jp":"まず、スーパーで材料を買いました。","furigana":"まず、スーパーでざいりょうをかいました。","romaji":"Mazu, suupaa de zairyou o kaimashita.","id":"Pertama, aku membeli bahan di supermarket."},
   {"jp":"野菜と肉を小さく切りました。","furigana":"やさいとにくをちいさくきりました。","romaji":"Yasai to niku o chiisaku kirimashita.","id":"Aku memotong sayur dan daging kecil-kecil."},
   {"jp":"包丁を使う時は、指に気をつけました。","furigana":"ほうちょうをつかうときは、ゆびにきをつけました。","romaji":"Houchou o tsukau toki wa, yubi ni ki o tsukemashita.","id":"Saat memakai pisau, aku hati-hati dengan jariku."},
   {"jp":"鍋で野菜と肉をよく炒めました。","furigana":"なべでやさいとにくをよくいためました。","romaji":"Nabe de yasai to niku o yoku itamemashita.","id":"Aku menumis sayur dan daging di panci."},
   {"jp":"水を入れて、三十分ぐらい煮込みました。","furigana":"みずをいれて、さんじゅっぷんぐらいにこみました。","romaji":"Mizu o irete, sanjuppun gurai nikomimashita.","id":"Aku menambahkan air dan merebusnya sekitar tiga puluh menit."},
   {"jp":"最後にカレーのルーを入れました。","furigana":"さいごにカレーのルーをいれました。","romaji":"Saigo ni karee no ruu o iremashita.","id":"Terakhir aku memasukkan bumbu kari."},
   {"jp":"少し焦がしてしまいましたが、味はよかったです。","furigana":"すこしこがしてしまいましたが、あじはよかったです。","romaji":"Sukoshi kogashite shimaimashita ga, aji wa yokatta desu.","id":"Sedikit gosong, tapi rasanya enak."},
   {"jp":"家族はおいしいと言ってくれました。","furigana":"かぞくはおいしいといってくれました。","romaji":"Kazoku wa oishii to itte kuremashita.","id":"Keluargaku bilang itu enak."},
   {"jp":"自分で作った料理は、特別おいしく感じました。","furigana":"じぶんでつくったりょうりは、とくべつおいしくかんじました。","romaji":"Jibun de tsukutta ryouri wa, tokubetsu oishiku kanjimashita.","id":"Masakan buatan sendiri terasa istimewa enaknya."},
   {"jp":"今度は別の料理にも挑戦したいです。","furigana":"こんどはべつのりょうりにもちょうせんしたいです。","romaji":"Kondo wa betsu no ryouri ni mo chousen shitai desu.","id":"Lain kali aku ingin mencoba masakan lain juga."}
 ]'::jsonb,
 '[
   {"word":"料理","reading":"りょうり","romaji":"ryouri","meaning":"masakan"},
   {"word":"挑戦","reading":"ちょうせん","romaji":"chousen","meaning":"tantangan/mencoba"},
   {"word":"初めて","reading":"はじめて","romaji":"hajimete","meaning":"pertama kali"},
   {"word":"レシピ","reading":"レシピ","romaji":"reshipi","meaning":"resep"},
   {"word":"調べる","reading":"しらべる","romaji":"shiraberu","meaning":"mencari/memeriksa"},
   {"word":"材料","reading":"ざいりょう","romaji":"zairyou","meaning":"bahan"},
   {"word":"切る","reading":"きる","romaji":"kiru","meaning":"memotong"},
   {"word":"包丁","reading":"ほうちょう","romaji":"houchou","meaning":"pisau dapur"},
   {"word":"炒める","reading":"いためる","romaji":"itameru","meaning":"menumis"},
   {"word":"煮込む","reading":"にこむ","romaji":"nikomu","meaning":"merebus lama"},
   {"word":"最後に","reading":"さいごに","romaji":"saigo ni","meaning":"terakhir"},
   {"word":"焦がす","reading":"こがす","romaji":"kogasu","meaning":"menggosongkan"},
   {"word":"味","reading":"あじ","romaji":"aji","meaning":"rasa"},
   {"word":"特別","reading":"とくべつ","romaji":"tokubetsu","meaning":"istimewa/khusus"},
   {"word":"感じる","reading":"かんじる","romaji":"kanjiru","meaning":"merasakan"}
 ]'::jsonb,
 '[
   {"q":"Apa yang dibuat penulis pertama kali?","options":["Sushi","Kari","Ramen","Tempura"],"answer":1,"explanation":"「初めてカレーを作ってみました」."},
   {"q":"Di mana penulis mencari resep?","options":["Buku","Internet","TV","Teman"],"answer":1,"explanation":"「インターネットでレシピを調べました」."},
   {"q":"Saat memakai pisau, hati-hati dengan apa?","options":["Mata","Jari","Baju","Meja"],"answer":1,"explanation":"「指に気をつけました」 = hati-hati dengan jari."},
   {"q":"Berapa lama direbus?","options":["10 menit","20 menit","Sekitar 30 menit","1 jam"],"answer":2,"explanation":"「三十分ぐらい煮込みました」."},
   {"q":"Apa yang sedikit terjadi saat memasak?","options":["Terlalu asin","Sedikit gosong","Mentah","Tumpah"],"answer":1,"explanation":"「少し焦がしてしまいました」 = sedikit gosong."},
   {"q":"Apa kata keluarga tentang masakannya?","options":["Biasa saja","Enak","Terlalu pedas","Kurang matang"],"answer":1,"explanation":"「おいしいと言ってくれました」."}
 ]'::jsonb,
 false),
(2, 11, 'スポーツ大会 — Lomba Olahraga',
 '昨日、学校でスポーツ大会がありました。天気がよくて、運動場は学生でいっぱいでした。私は百メートル走に出ました。練習をたくさんしたので、自信がありました。スタートの合図で、みんな一斉に走り出しました。私は二位でゴールしました。少し悔しかったですが、満足しています。午後はクラス対抗のリレーがありました。私のクラスはみんなで力を合わせて勝ちました。応援の声が運動場に響きました。みんなで協力することの大切さが分かりました。とても疲れましたが、楽しい一日でした。',
 '[
   {"jp":"昨日、学校でスポーツ大会がありました。","furigana":"きのう、がっこうでスポーツたいかいがありました。","romaji":"Kinou, gakkou de supootsu taikai ga arimashita.","id":"Kemarin ada lomba olahraga di sekolah."},
   {"jp":"天気がよくて、運動場は学生でいっぱいでした。","furigana":"てんきがよくて、うんどうじょうはがくせいでいっぱいでした。","romaji":"Tenki ga yokute, undoujou wa gakusei de ippai deshita.","id":"Cuaca bagus, dan lapangan penuh dengan siswa."},
   {"jp":"私は百メートル走に出ました。","furigana":"わたしはひゃくメートルそうにでました。","romaji":"Watashi wa hyaku meetoru sou ni demashita.","id":"Aku ikut lari seratus meter."},
   {"jp":"練習をたくさんしたので、自信がありました。","furigana":"れんしゅうをたくさんしたので、じしんがありました。","romaji":"Renshuu o takusan shita node, jishin ga arimashita.","id":"Karena banyak berlatih, aku percaya diri."},
   {"jp":"スタートの合図で、みんな一斉に走り出しました。","furigana":"スタートのあいずで、みんないっせいにはしりだしました。","romaji":"Sutaato no aizu de, minna issei ni hashiri dashimashita.","id":"Pada aba-aba start, semua berlari serentak."},
   {"jp":"私は二位でゴールしました。","furigana":"わたしはにいでゴールしました。","romaji":"Watashi wa ni-i de gooru shimashita.","id":"Aku finis di posisi kedua."},
   {"jp":"少し悔しかったですが、満足しています。","furigana":"すこしくやしかったですが、まんぞくしています。","romaji":"Sukoshi kuyashikatta desu ga, manzoku shite imasu.","id":"Sedikit kesal, tapi aku puas."},
   {"jp":"午後はクラス対抗のリレーがありました。","furigana":"ごごはクラスたいこうのリレーがありました。","romaji":"Gogo wa kurasu taikou no riree ga arimashita.","id":"Sore ada lari estafet antar kelas."},
   {"jp":"私のクラスはみんなで力を合わせて勝ちました。","furigana":"わたしのクラスはみんなでちからをあわせてかちました。","romaji":"Watashi no kurasu wa minna de chikara o awasete kachimashita.","id":"Kelasku menang dengan menyatukan tenaga bersama."},
   {"jp":"応援の声が運動場に響きました。","furigana":"おうえんのこえがうんどうじょうにひびきました。","romaji":"Ouen no koe ga undoujou ni hibikimashita.","id":"Suara dukungan bergema di lapangan."},
   {"jp":"みんなで協力することの大切さが分かりました。","furigana":"みんなできょうりょくすることのたいせつさがわかりました。","romaji":"Minna de kyouryoku suru koto no taisetsusa ga wakarimashita.","id":"Aku mengerti pentingnya bekerja sama."},
   {"jp":"とても疲れましたが、楽しい一日でした。","furigana":"とてもつかれましたが、たのしいいちにちでした。","romaji":"Totemo tsukaremashita ga, tanoshii ichinichi deshita.","id":"Aku sangat lelah, tapi hari yang menyenangkan."}
 ]'::jsonb,
 '[
   {"word":"スポーツ大会","reading":"スポーツたいかい","romaji":"supootsu taikai","meaning":"lomba olahraga"},
   {"word":"運動場","reading":"うんどうじょう","romaji":"undoujou","meaning":"lapangan olahraga"},
   {"word":"百メートル走","reading":"ひゃくメートルそう","romaji":"hyaku meetoru sou","meaning":"lari 100 meter"},
   {"word":"練習","reading":"れんしゅう","romaji":"renshuu","meaning":"latihan"},
   {"word":"自信","reading":"じしん","romaji":"jishin","meaning":"percaya diri"},
   {"word":"合図","reading":"あいず","romaji":"aizu","meaning":"aba-aba/isyarat"},
   {"word":"一斉に","reading":"いっせいに","romaji":"issei ni","meaning":"serentak"},
   {"word":"二位","reading":"にい","romaji":"ni-i","meaning":"posisi kedua"},
   {"word":"悔しい","reading":"くやしい","romaji":"kuyashii","meaning":"kesal/menyesal"},
   {"word":"満足","reading":"まんぞく","romaji":"manzoku","meaning":"puas"},
   {"word":"リレー","reading":"リレー","romaji":"riree","meaning":"lari estafet"},
   {"word":"力を合わせる","reading":"ちからをあわせる","romaji":"chikara o awaseru","meaning":"menyatukan tenaga"},
   {"word":"勝つ","reading":"かつ","romaji":"katsu","meaning":"menang"},
   {"word":"応援","reading":"おうえん","romaji":"ouen","meaning":"dukungan/sorakan"},
   {"word":"協力","reading":"きょうりょく","romaji":"kyouryoku","meaning":"kerja sama"}
 ]'::jsonb,
 '[
   {"q":"Apa yang ada di sekolah kemarin?","options":["Ujian","Lomba olahraga","Festival","Wisata"],"answer":1,"explanation":"「スポーツ大会がありました」."},
   {"q":"Penulis ikut lomba apa?","options":["Renang","Lari 100 meter","Lompat jauh","Basket"],"answer":1,"explanation":"「百メートル走に出ました」."},
   {"q":"Kenapa penulis percaya diri?","options":["Beruntung","Banyak berlatih","Lawannya lemah","Diberi tahu"],"answer":1,"explanation":"「練習をたくさんしたので、自信がありました」."},
   {"q":"Penulis finis di posisi berapa?","options":["Pertama","Kedua","Ketiga","Terakhir"],"answer":1,"explanation":"「二位でゴールしました」 = posisi kedua."},
   {"q":"Bagaimana hasil estafet kelasnya?","options":["Kalah","Menang","Seri","Batal"],"answer":1,"explanation":"「力を合わせて勝ちました」 = menang."},
   {"q":"Apa yang dipahami penulis?","options":["Pentingnya menang","Pentingnya kerja sama","Pentingnya istirahat","Pentingnya hadiah"],"answer":1,"explanation":"「協力することの大切さが分かりました」."}
 ]'::jsonb,
 false),
(2, 12, '道に迷ったとき — Saat Tersesat',
 '先月、私は初めて東京に行きました。駅がとても大きくて、出口がたくさんありました。私は道に迷ってしまいました。地図を見ても、よく分かりませんでした。そこで、近くの人に道を聞きました。その人はとても親切に教えてくれました。「まっすぐ行って、二つ目の角を右に曲がってください」と言いました。私はお礼を言って、その通りに歩きました。おかげで、目的地に無事に着きました。スマホの地図アプリも役に立ちました。道に迷った時は、人に聞くのが一番です。日本人は本当に親切だと思いました。',
 '[
   {"jp":"先月、私は初めて東京に行きました。","furigana":"せんげつ、わたしははじめてとうきょうにいきました。","romaji":"Sengetsu, watashi wa hajimete toukyou ni ikimashita.","id":"Bulan lalu aku pergi ke Tokyo untuk pertama kali."},
   {"jp":"駅がとても大きくて、出口がたくさんありました。","furigana":"えきがとてもおおきくて、でぐちがたくさんありました。","romaji":"Eki ga totemo ookikute, deguchi ga takusan arimashita.","id":"Stasiunnya sangat besar dan punya banyak pintu keluar."},
   {"jp":"私は道に迷ってしまいました。","furigana":"わたしはみちにまよってしまいました。","romaji":"Watashi wa michi ni mayotte shimaimashita.","id":"Aku pun tersesat."},
   {"jp":"地図を見ても、よく分かりませんでした。","furigana":"ちずをみても、よくわかりませんでした。","romaji":"Chizu o mite mo, yoku wakarimasen deshita.","id":"Meski melihat peta, aku tetap tidak mengerti."},
   {"jp":"そこで、近くの人に道を聞きました。","furigana":"そこで、ちかくのひとにみちをききました。","romaji":"Soko de, chikaku no hito ni michi o kikimashita.","id":"Maka, aku bertanya jalan kepada orang di dekat situ."},
   {"jp":"その人はとても親切に教えてくれました。","furigana":"そのひとはとてもしんせつにおしえてくれました。","romaji":"Sono hito wa totemo shinsetsu ni oshiete kuremashita.","id":"Orang itu memberitahuku dengan sangat ramah."},
   {"jp":"「まっすぐ行って、二つ目の角を右に曲がってください」と言いました。","furigana":"「まっすぐいって、ふたつめのかどをみぎにまがってください」といいました。","romaji":"\"Massugu itte, futatsume no kado o migi ni magatte kudasai\" to iimashita.","id":"Dia bilang lurus saja, lalu belok kanan di tikungan kedua."},
   {"jp":"私はお礼を言って、その通りに歩きました。","furigana":"わたしはおれいをいって、そのとおりにあるきました。","romaji":"Watashi wa orei o itte, sono toori ni arukimashita.","id":"Aku berterima kasih dan berjalan sesuai petunjuknya."},
   {"jp":"おかげで、目的地に無事に着きました。","furigana":"おかげで、もくてきちにぶじにつきました。","romaji":"Okage de, mokutekichi ni buji ni tsukimashita.","id":"Berkat itu, aku tiba di tujuan dengan selamat."},
   {"jp":"スマホの地図アプリも役に立ちました。","furigana":"スマホのちずアプリもやくにたちました。","romaji":"Sumaho no chizu apuri mo yaku ni tachimashita.","id":"Aplikasi peta di ponsel juga berguna."},
   {"jp":"道に迷った時は、人に聞くのが一番です。","furigana":"みちにまよったときは、ひとにきくのがいちばんです。","romaji":"Michi ni mayotta toki wa, hito ni kiku no ga ichiban desu.","id":"Saat tersesat, bertanya pada orang adalah yang terbaik."},
   {"jp":"日本人は本当に親切だと思いました。","furigana":"にほんじんはほんとうにしんせつだとおもいました。","romaji":"Nihonjin wa hontou ni shinsetsu da to omoimashita.","id":"Aku merasa orang Jepang benar-benar ramah."}
 ]'::jsonb,
 '[
   {"word":"道に迷う","reading":"みちにまよう","romaji":"michi ni mayou","meaning":"tersesat"},
   {"word":"出口","reading":"でぐち","romaji":"deguchi","meaning":"pintu keluar"},
   {"word":"地図","reading":"ちず","romaji":"chizu","meaning":"peta"},
   {"word":"聞く","reading":"きく","romaji":"kiku","meaning":"bertanya"},
   {"word":"親切","reading":"しんせつ","romaji":"shinsetsu","meaning":"ramah/baik hati"},
   {"word":"教える","reading":"おしえる","romaji":"oshieru","meaning":"memberitahu/mengajari"},
   {"word":"まっすぐ","reading":"まっすぐ","romaji":"massugu","meaning":"lurus"},
   {"word":"角","reading":"かど","romaji":"kado","meaning":"sudut/tikungan"},
   {"word":"曲がる","reading":"まがる","romaji":"magaru","meaning":"berbelok"},
   {"word":"お礼","reading":"おれい","romaji":"orei","meaning":"ucapan terima kasih"},
   {"word":"その通り","reading":"そのとおり","romaji":"sono toori","meaning":"sesuai itu"},
   {"word":"目的地","reading":"もくてきち","romaji":"mokutekichi","meaning":"tempat tujuan"},
   {"word":"無事に","reading":"ぶじに","romaji":"buji ni","meaning":"dengan selamat"},
   {"word":"役に立つ","reading":"やくにたつ","romaji":"yaku ni tatsu","meaning":"berguna"},
   {"word":"思う","reading":"おもう","romaji":"omou","meaning":"berpikir/merasa"}
 ]'::jsonb,
 '[
   {"q":"Ke mana penulis pergi untuk pertama kali?","options":["Osaka","Tokyo","Kyoto","Nagoya"],"answer":1,"explanation":"「初めて東京に行きました」."},
   {"q":"Kenapa stasiunnya membingungkan?","options":["Gelap","Besar dan banyak pintu keluar","Sepi","Tutup"],"answer":1,"explanation":"「大きくて、出口がたくさん」."},
   {"q":"Apa yang dilakukan penulis saat tersesat?","options":["Menangis","Bertanya pada orang","Pulang","Diam"],"answer":1,"explanation":"「近くの人に道を聞きました」."},
   {"q":"Bagaimana petunjuk jalannya?","options":["Belok kiri","Lurus lalu belok kanan di tikungan kedua","Naik taksi","Putar balik"],"answer":1,"explanation":"「まっすぐ行って、二つ目の角を右に」."},
   {"q":"Apa yang juga berguna?","options":["Kompas","Aplikasi peta di ponsel","Buku","Papan petunjuk"],"answer":1,"explanation":"「地図アプリも役に立ちました」."},
   {"q":"Menurut penulis, saat tersesat yang terbaik adalah?","options":["Pakai peta","Bertanya pada orang","Menunggu","Menelepon"],"answer":1,"explanation":"「人に聞くのが一番」."}
 ]'::jsonb,
 false),
(2, 13, '携帯電話 — Telepon Genggam',
 '今、ほとんどの人が携帯電話を持っています。携帯電話はとても便利な道具です。電話やメールだけでなく、写真も撮れます。地図を見たり、ニュースを読んだりできます。私はよく友だちとメッセージを送り合います。でも、使いすぎると目が疲れます。歩きながらスマホを使うのは危ないです。電車の中では、マナーモードにします。寝る前にスマホを見ると、よく眠れません。だから、私は夜十時以降は使わないようにしています。携帯電話は便利ですが、使い方が大切です。上手に使えば、生活がもっと豊かになります。',
 '[
   {"jp":"今、ほとんどの人が携帯電話を持っています。","furigana":"いま、ほとんどのひとがけいたいでんわをもっています。","romaji":"Ima, hotondo no hito ga keitai denwa o motte imasu.","id":"Sekarang hampir semua orang punya ponsel."},
   {"jp":"携帯電話はとても便利な道具です。","furigana":"けいたいでんわはとてもべんりなどうぐです。","romaji":"Keitai denwa wa totemo benri na dougu desu.","id":"Ponsel adalah alat yang sangat praktis."},
   {"jp":"電話やメールだけでなく、写真も撮れます。","furigana":"でんわやメールだけでなく、しゃしんもとれます。","romaji":"Denwa ya meeru dake de naku, shashin mo toremasu.","id":"Tidak hanya telepon dan email, kita juga bisa memotret."},
   {"jp":"地図を見たり、ニュースを読んだりできます。","furigana":"ちずをみたり、ニュースをよんだりできます。","romaji":"Chizu o mitari, nyuusu o yondari dekimasu.","id":"Kita bisa melihat peta dan membaca berita."},
   {"jp":"私はよく友だちとメッセージを送り合います。","furigana":"わたしはよくともだちとメッセージをおくりあいます。","romaji":"Watashi wa yoku tomodachi to messeeji o okuri aimasu.","id":"Aku sering bertukar pesan dengan teman."},
   {"jp":"でも、使いすぎると目が疲れます。","furigana":"でも、つかいすぎるとめがつかれます。","romaji":"Demo, tsukai sugiru to me ga tsukaremasu.","id":"Tapi kalau berlebihan, mata jadi lelah."},
   {"jp":"歩きながらスマホを使うのは危ないです。","furigana":"あるきながらスマホをつかうのはあぶないです。","romaji":"Aruki nagara sumaho o tsukau no wa abunai desu.","id":"Memakai ponsel sambil berjalan itu berbahaya."},
   {"jp":"電車の中では、マナーモードにします。","furigana":"でんしゃのなかでは、マナーモードにします。","romaji":"Densha no naka de wa, manaa moodo ni shimasu.","id":"Di dalam kereta, aku setel ke mode senyap."},
   {"jp":"寝る前にスマホを見ると、よく眠れません。","furigana":"ねるまえにスマホをみると、よくねむれません。","romaji":"Neru mae ni sumaho o miru to, yoku nemuremasen.","id":"Kalau melihat ponsel sebelum tidur, sulit tidur nyenyak."},
   {"jp":"だから、私は夜十時以降は使わないようにしています。","furigana":"だから、わたしはよるじゅうじいこうはつかわないようにしています。","romaji":"Dakara, watashi wa yoru juuji ikou wa tsukawanai you ni shite imasu.","id":"Karena itu, aku berusaha tidak memakainya setelah jam sepuluh malam."},
   {"jp":"携帯電話は便利ですが、使い方が大切です。","furigana":"けいたいでんわはべんりですが、つかいかたがたいせつです。","romaji":"Keitai denwa wa benri desu ga, tsukaikata ga taisetsu desu.","id":"Ponsel praktis, tapi cara memakainya penting."},
   {"jp":"上手に使えば、生活がもっと豊かになります。","furigana":"じょうずにつかえば、せいかつがもっとゆたかになります。","romaji":"Jouzu ni tsukaeba, seikatsu ga motto yutaka ni narimasu.","id":"Kalau dipakai dengan bijak, hidup jadi lebih kaya."}
 ]'::jsonb,
 '[
   {"word":"携帯電話","reading":"けいたいでんわ","romaji":"keitai denwa","meaning":"ponsel"},
   {"word":"道具","reading":"どうぐ","romaji":"dougu","meaning":"alat"},
   {"word":"撮る","reading":"とる","romaji":"toru","meaning":"memotret/mengambil (foto)"},
   {"word":"メール","reading":"メール","romaji":"meeru","meaning":"email"},
   {"word":"メッセージ","reading":"メッセージ","romaji":"messeeji","meaning":"pesan"},
   {"word":"送る","reading":"おくる","romaji":"okuru","meaning":"mengirim"},
   {"word":"使いすぎる","reading":"つかいすぎる","romaji":"tsukai sugiru","meaning":"memakai berlebihan"},
   {"word":"疲れる","reading":"つかれる","romaji":"tsukareru","meaning":"lelah"},
   {"word":"危ない","reading":"あぶない","romaji":"abunai","meaning":"berbahaya"},
   {"word":"マナーモード","reading":"マナーモード","romaji":"manaa moodo","meaning":"mode senyap"},
   {"word":"眠る","reading":"ねむる","romaji":"nemuru","meaning":"tidur/terlelap"},
   {"word":"以降","reading":"いこう","romaji":"ikou","meaning":"setelah/sesudah"},
   {"word":"使い方","reading":"つかいかた","romaji":"tsukaikata","meaning":"cara pakai"},
   {"word":"上手に","reading":"じょうずに","romaji":"jouzu ni","meaning":"dengan mahir/bijak"},
   {"word":"豊か","reading":"ゆたか","romaji":"yutaka","meaning":"kaya/melimpah"}
 ]'::jsonb,
 '[
   {"q":"Sekarang siapa yang punya ponsel?","options":["Sedikit orang","Hampir semua orang","Hanya anak muda","Hanya pekerja"],"answer":1,"explanation":"「ほとんどの人が…持っています」."},
   {"q":"Selain telepon dan email, ponsel bisa apa?","options":["Memasak","Memotret","Mencuci","Terbang"],"answer":1,"explanation":"「写真も撮れます」 = bisa memotret."},
   {"q":"Apa akibat memakai ponsel berlebihan?","options":["Mata lelah","Lapar","Kebal","Lebih pintar"],"answer":0,"explanation":"「使いすぎると目が疲れます」."},
   {"q":"Apa yang berbahaya menurut penulis?","options":["Mengisi daya","Memakai ponsel sambil berjalan","Menelepon","Memotret"],"answer":1,"explanation":"「歩きながらスマホを使うのは危ない」."},
   {"q":"Kenapa tidak melihat ponsel sebelum tidur?","options":["Boros baterai","Sulit tidur nyenyak","Mata buta","Lupa waktu"],"answer":1,"explanation":"「よく眠れません」 = sulit tidur nyenyak."},
   {"q":"Setelah jam berapa penulis berusaha tidak memakai ponsel?","options":["Jam 8","Jam 9","Jam 10 malam","Jam 11"],"answer":2,"explanation":"「夜十時以降は使わないように」."}
 ]'::jsonb,
 false),
(2, 14, '冬の準備 — Persiapan Musim Dingin',
 '十一月になると、だんだん寒くなってきます。冬が来る前に、いろいろな準備をします。まず、厚いコートやセーターを出します。部屋には暖房やこたつを用意します。寒い日は、温かい飲み物が欲しくなります。北の地方では、雪がたくさん降ります。雪が降ると、道が滑りやすくなります。だから、滑らない靴を履きます。冬は風邪をひきやすいので、気をつけます。手洗いとうがいを忘れないようにしています。冬は寒いですが、温泉に入るのが楽しみです。しっかり準備をすれば、冬も快適に過ごせます。',
 '[
   {"jp":"十一月になると、だんだん寒くなってきます。","furigana":"じゅういちがつになると、だんだんさむくなってきます。","romaji":"Juuichigatsu ni naru to, dandan samuku natte kimasu.","id":"Begitu masuk November, lama-lama jadi dingin."},
   {"jp":"冬が来る前に、いろいろな準備をします。","furigana":"ふゆがくるまえに、いろいろなじゅんびをします。","romaji":"Fuyu ga kuru mae ni, iroiro na junbi o shimasu.","id":"Sebelum musim dingin datang, aku melakukan berbagai persiapan."},
   {"jp":"まず、厚いコートやセーターを出します。","furigana":"まず、あついコートやセーターをだします。","romaji":"Mazu, atsui kooto ya seetaa o dashimasu.","id":"Pertama, aku mengeluarkan mantel tebal dan sweter."},
   {"jp":"部屋には暖房やこたつを用意します。","furigana":"へやにはだんぼうやこたつをよういします。","romaji":"Heya ni wa danbou ya kotatsu o youi shimasu.","id":"Di kamar aku menyiapkan pemanas dan kotatsu."},
   {"jp":"寒い日は、温かい飲み物が欲しくなります。","furigana":"さむいひは、あたたかいのみものがほしくなります。","romaji":"Samui hi wa, atatakai nomimono ga hoshiku narimasu.","id":"Di hari dingin, jadi ingin minuman hangat."},
   {"jp":"北の地方では、雪がたくさん降ります。","furigana":"きたのちほうでは、ゆきがたくさんふります。","romaji":"Kita no chihou de wa, yuki ga takusan furimasu.","id":"Di daerah utara, salju turun banyak."},
   {"jp":"雪が降ると、道が滑りやすくなります。","furigana":"ゆきがふると、みちがすべりやすくなります。","romaji":"Yuki ga furu to, michi ga suberiyasuku narimasu.","id":"Kalau salju turun, jalan jadi mudah licin."},
   {"jp":"だから、滑らない靴を履きます。","furigana":"だから、すべらないくつをはきます。","romaji":"Dakara, suberanai kutsu o hakimasu.","id":"Karena itu, aku memakai sepatu anti licin."},
   {"jp":"冬は風邪をひきやすいので、気をつけます。","furigana":"ふゆはかぜをひきやすいので、きをつけます。","romaji":"Fuyu wa kaze o hikiyasui node, ki o tsukemasu.","id":"Musim dingin mudah masuk angin, jadi aku berhati-hati."},
   {"jp":"手洗いとうがいを忘れないようにしています。","furigana":"てあらいとうがいをわすれないようにしています。","romaji":"Tearai to ugai o wasurenai you ni shite imasu.","id":"Aku berusaha tidak lupa cuci tangan dan berkumur."},
   {"jp":"冬は寒いですが、温泉に入るのが楽しみです。","furigana":"ふゆはさむいですが、おんせんにはいるのがたのしみです。","romaji":"Fuyu wa samui desu ga, onsen ni hairu no ga tanoshimi desu.","id":"Musim dingin memang dingin, tapi aku menantikan berendam di onsen."},
   {"jp":"しっかり準備をすれば、冬も快適に過ごせます。","furigana":"しっかりじゅんびをすれば、ふゆもかいてきにすごせます。","romaji":"Shikkari junbi o sureba, fuyu mo kaiteki ni sugosemasu.","id":"Kalau persiapan matang, musim dingin pun bisa dilewati dengan nyaman."}
 ]'::jsonb,
 '[
   {"word":"準備","reading":"じゅんび","romaji":"junbi","meaning":"persiapan"},
   {"word":"だんだん","reading":"だんだん","romaji":"dandan","meaning":"lama-lama/berangsur"},
   {"word":"厚い","reading":"あつい","romaji":"atsui","meaning":"tebal"},
   {"word":"コート","reading":"コート","romaji":"kooto","meaning":"mantel"},
   {"word":"暖房","reading":"だんぼう","romaji":"danbou","meaning":"pemanas ruangan"},
   {"word":"こたつ","reading":"こたつ","romaji":"kotatsu","meaning":"kotatsu (meja penghangat)"},
   {"word":"用意","reading":"ようい","romaji":"youi","meaning":"menyiapkan"},
   {"word":"地方","reading":"ちほう","romaji":"chihou","meaning":"daerah/wilayah"},
   {"word":"滑る","reading":"すべる","romaji":"suberu","meaning":"licin/tergelincir"},
   {"word":"履く","reading":"はく","romaji":"haku","meaning":"memakai (alas kaki)"},
   {"word":"風邪をひく","reading":"かぜをひく","romaji":"kaze o hiku","meaning":"masuk angin/pilek"},
   {"word":"うがい","reading":"うがい","romaji":"ugai","meaning":"berkumur"},
   {"word":"温泉","reading":"おんせん","romaji":"onsen","meaning":"pemandian air panas"},
   {"word":"快適","reading":"かいてき","romaji":"kaiteki","meaning":"nyaman"},
   {"word":"過ごす","reading":"すごす","romaji":"sugosu","meaning":"melewati waktu"}
 ]'::jsonb,
 '[
   {"q":"Bulan apa mulai terasa dingin?","options":["September","Oktober","November","Desember"],"answer":2,"explanation":"「十一月になると…寒くなってきます」."},
   {"q":"Apa yang dikeluarkan lebih dulu?","options":["Kipas","Mantel tebal dan sweter","Payung","Topi pantai"],"answer":1,"explanation":"「厚いコートやセーターを出します」."},
   {"q":"Apa yang disiapkan di kamar?","options":["AC","Pemanas dan kotatsu","Kulkas","Kipas angin"],"answer":1,"explanation":"「暖房やこたつを用意します」."},
   {"q":"Kenapa memakai sepatu anti licin?","options":["Agar keren","Jalan mudah licin saat bersalju","Agar hangat","Karena murah"],"answer":1,"explanation":"「道が滑りやすくなります」."},
   {"q":"Apa yang dilakukan agar tidak masuk angin?","options":["Olahraga","Cuci tangan dan berkumur","Banyak tidur","Minum obat"],"answer":1,"explanation":"「手洗いとうがいを忘れないように」."},
   {"q":"Apa yang dinantikan penulis di musim dingin?","options":["Main salju","Berendam di onsen","Liburan","Tahun baru"],"answer":1,"explanation":"「温泉に入るのが楽しみ」."}
 ]'::jsonb,
 false),
(2, 15, 'ボランティア — Kegiatan Sukarela',
 '先月、私は初めてボランティア活動に参加しました。友だちに誘われて、海の掃除をしました。朝早く集まって、ゴミを拾いました。海にはプラスチックのゴミがたくさんありました。ゴミは海の動物にとって危険です。みんなで協力して、たくさんのゴミを集めました。三時間後、海はとてもきれいになりました。体は疲れましたが、心は気持ちよかったです。自分の行動が役に立って、嬉しかったです。環境を守ることはとても大切だと思いました。これからも、時々ボランティアに参加したいです。小さな行動が、大きな変化につながると信じています。',
 '[
   {"jp":"先月、私は初めてボランティア活動に参加しました。","furigana":"せんげつ、わたしははじめてボランティアかつどうにさんかしました。","romaji":"Sengetsu, watashi wa hajimete borantia katsudou ni sanka shimashita.","id":"Bulan lalu aku ikut kegiatan sukarela untuk pertama kali."},
   {"jp":"友だちに誘われて、海の掃除をしました。","furigana":"ともだちにさそわれて、うみのそうじをしました。","romaji":"Tomodachi ni sasowarete, umi no souji o shimashita.","id":"Diajak teman, aku membersihkan pantai."},
   {"jp":"朝早く集まって、ゴミを拾いました。","furigana":"あさはやくあつまって、ゴミをひろいました。","romaji":"Asa hayaku atsumatte, gomi o hiroimashita.","id":"Kami berkumpul pagi-pagi dan memungut sampah."},
   {"jp":"海にはプラスチックのゴミがたくさんありました。","furigana":"うみにはプラスチックのゴミがたくさんありました。","romaji":"Umi ni wa purasuchikku no gomi ga takusan arimashita.","id":"Di pantai ada banyak sampah plastik."},
   {"jp":"ゴミは海の動物にとって危険です。","furigana":"ゴミはうみのどうぶつにとってきけんです。","romaji":"Gomi wa umi no doubutsu ni totte kiken desu.","id":"Sampah berbahaya bagi hewan laut."},
   {"jp":"みんなで協力して、たくさんのゴミを集めました。","furigana":"みんなできょうりょくして、たくさんのゴミをあつめました。","romaji":"Minna de kyouryoku shite, takusan no gomi o atsumemashita.","id":"Dengan kerja sama, kami mengumpulkan banyak sampah."},
   {"jp":"三時間後、海はとてもきれいになりました。","furigana":"さんじかんご、うみはとてもきれいになりました。","romaji":"San-jikan go, umi wa totemo kirei ni narimashita.","id":"Tiga jam kemudian, pantai jadi sangat bersih."},
   {"jp":"体は疲れましたが、心は気持ちよかったです。","furigana":"からだはつかれましたが、こころはきもちよかったです。","romaji":"Karada wa tsukaremashita ga, kokoro wa kimochi yokatta desu.","id":"Badan lelah, tapi hati terasa lega."},
   {"jp":"自分の行動が役に立って、嬉しかったです。","furigana":"じぶんのこうどうがやくにたって、うれしかったです。","romaji":"Jibun no koudou ga yaku ni tatte, ureshikatta desu.","id":"Aku senang tindakanku berguna."},
   {"jp":"環境を守ることはとても大切だと思いました。","furigana":"かんきょうをまもることはとてもたいせつだとおもいました。","romaji":"Kankyou o mamoru koto wa totemo taisetsu da to omoimashita.","id":"Aku merasa menjaga lingkungan itu sangat penting."},
   {"jp":"これからも、時々ボランティアに参加したいです。","furigana":"これからも、ときどきボランティアにさんかしたいです。","romaji":"Korekara mo, tokidoki borantia ni sanka shitai desu.","id":"Ke depan pun, aku ingin sesekali ikut kegiatan sukarela."},
   {"jp":"小さな行動が、大きな変化につながると信じています。","furigana":"ちいさなこうどうが、おおきなへんかにつながるとしんじています。","romaji":"Chiisa na koudou ga, ooki na henka ni tsunagaru to shinjite imasu.","id":"Aku percaya tindakan kecil bisa membawa perubahan besar."}
 ]'::jsonb,
 '[
   {"word":"ボランティア","reading":"ボランティア","romaji":"borantia","meaning":"sukarelawan/kegiatan sukarela"},
   {"word":"活動","reading":"かつどう","romaji":"katsudou","meaning":"kegiatan"},
   {"word":"参加","reading":"さんか","romaji":"sanka","meaning":"ikut serta"},
   {"word":"誘う","reading":"さそう","romaji":"sasou","meaning":"mengajak"},
   {"word":"掃除","reading":"そうじ","romaji":"souji","meaning":"membersihkan"},
   {"word":"集まる","reading":"あつまる","romaji":"atsumaru","meaning":"berkumpul"},
   {"word":"拾う","reading":"ひろう","romaji":"hirou","meaning":"memungut"},
   {"word":"プラスチック","reading":"プラスチック","romaji":"purasuchikku","meaning":"plastik"},
   {"word":"危険","reading":"きけん","romaji":"kiken","meaning":"berbahaya"},
   {"word":"協力","reading":"きょうりょく","romaji":"kyouryoku","meaning":"kerja sama"},
   {"word":"集める","reading":"あつめる","romaji":"atsumeru","meaning":"mengumpulkan"},
   {"word":"行動","reading":"こうどう","romaji":"koudou","meaning":"tindakan"},
   {"word":"環境","reading":"かんきょう","romaji":"kankyou","meaning":"lingkungan"},
   {"word":"守る","reading":"まもる","romaji":"mamoru","meaning":"menjaga/melindungi"},
   {"word":"変化","reading":"へんか","romaji":"henka","meaning":"perubahan"}
 ]'::jsonb,
 '[
   {"q":"Kegiatan sukarela apa yang diikuti penulis?","options":["Mengajar","Membersihkan pantai","Menanam pohon","Donor darah"],"answer":1,"explanation":"「海の掃除をしました」."},
   {"q":"Siapa yang mengajak penulis?","options":["Guru","Teman","Keluarga","Tetangga"],"answer":1,"explanation":"「友だちに誘われて」 = diajak teman."},
   {"q":"Jenis sampah apa yang banyak?","options":["Kertas","Plastik","Logam","Kaca"],"answer":1,"explanation":"「プラスチックのゴミがたくさん」."},
   {"q":"Sampah berbahaya bagi siapa?","options":["Manusia","Hewan laut","Tumbuhan","Tidak ada"],"answer":1,"explanation":"「海の動物にとって危険」."},
   {"q":"Setelah berapa lama pantai jadi bersih?","options":["Satu jam","Dua jam","Tiga jam","Lima jam"],"answer":2,"explanation":"「三時間後…きれいになりました」."},
   {"q":"Apa yang penulis rasa penting?","options":["Mencari uang","Menjaga lingkungan","Berolahraga","Berteman"],"answer":1,"explanation":"「環境を守ることは…大切」."}
 ]'::jsonb,
 false);
