-- ============================================================
-- Koto no Ha — Seed Dokkai N3 (level_id=3) TAMBAHAN: 10 bacaan (order_index 6-15).
-- ~400-500 huruf, 14 kalimat. 15 kosakata + 6 soal per bacaan.
-- Hanya INSERT (tidak menghapus bacaan lama).
-- ============================================================
INSERT INTO public.dokkai_passages (level_id, order_index, title, text_content, content_json, vocab_notes, questions, is_premium) VALUES
(3, 6, '健康な生活 — Pola Hidup Sehat',
 '健康は誰にとっても一番大切なものです。健康な生活を送るためには、いくつかの習慣が必要です。まず、バランスの取れた食事をすることが大切です。野菜や果物をたくさん食べ、油や砂糖を取りすぎないようにします。また、規則正しい生活も欠かせません。毎日同じ時間に起きて、同じ時間に寝るといいです。睡眠が足りないと、集中力が下がってしまいます。適度な運動も健康にとって重要です。私は毎朝三十分ぐらいジョギングをしています。運動するとストレスが減り、気分もよくなります。それから、水をたくさん飲むことも忘れてはいけません。たばこやお酒は、体に悪い影響を与えます。小さな習慣の積み重ねが、健康な体を作ります。毎日の生活を見直して、健康に気をつけたいです。',
 '[
   {"jp":"健康は誰にとっても一番大切なものです。","furigana":"けんこうはだれにとってもいちばんたいせつなものです。","romaji":"Kenkou wa dare ni totte mo ichiban taisetsu na mono desu.","id":"Kesehatan adalah hal terpenting bagi siapa pun."},
   {"jp":"健康な生活を送るためには、いくつかの習慣が必要です。","furigana":"けんこうなせいかつをおくるためには、いくつかのしゅうかんがひつようです。","romaji":"Kenkou na seikatsu o okuru tame ni wa, ikutsuka no shuukan ga hitsuyou desu.","id":"Untuk menjalani hidup sehat, dibutuhkan beberapa kebiasaan."},
   {"jp":"まず、バランスの取れた食事をすることが大切です。","furigana":"まず、バランスのとれたしょくじをすることがたいせつです。","romaji":"Mazu, baransu no toreta shokuji o suru koto ga taisetsu desu.","id":"Pertama, penting untuk makan dengan gizi seimbang."},
   {"jp":"野菜や果物をたくさん食べ、油や砂糖を取りすぎないようにします。","furigana":"やさいやくだものをたくさんたべ、あぶらやさとうをとりすぎないようにします。","romaji":"Yasai ya kudamono o takusan tabe, abura ya satou o torisuginai you ni shimasu.","id":"Banyak makan sayur dan buah, serta tidak berlebihan mengonsumsi minyak dan gula."},
   {"jp":"また、規則正しい生活も欠かせません。","furigana":"また、きそくただしいせいかつもかかせません。","romaji":"Mata, kisoku tadashii seikatsu mo kakasemasen.","id":"Selain itu, pola hidup teratur juga tak boleh terlewat."},
   {"jp":"毎日同じ時間に起きて、同じ時間に寝るといいです。","furigana":"まいにちおなじじかんにおきて、おなじじかんにねるといいです。","romaji":"Mainichi onaji jikan ni okite, onaji jikan ni neru to ii desu.","id":"Baik kalau setiap hari bangun dan tidur pada jam yang sama."},
   {"jp":"睡眠が足りないと、集中力が下がってしまいます。","furigana":"すいみんがたりないと、しゅうちゅうりょくがさがってしまいます。","romaji":"Suimin ga tarinai to, shuuchuuryoku ga sagatte shimaimasu.","id":"Kalau kurang tidur, daya konsentrasi menurun."},
   {"jp":"適度な運動も健康にとって重要です。","furigana":"てきどなうんどうもけんこうにとってじゅうようです。","romaji":"Tekido na undou mo kenkou ni totte juuyou desu.","id":"Olahraga secukupnya juga penting bagi kesehatan."},
   {"jp":"私は毎朝三十分ぐらいジョギングをしています。","furigana":"わたしはまいあささんじゅっぷんぐらいジョギングをしています。","romaji":"Watashi wa maiasa sanjuppun gurai jogingu o shite imasu.","id":"Setiap pagi aku jogging sekitar tiga puluh menit."},
   {"jp":"運動するとストレスが減り、気分もよくなります。","furigana":"うんどうするとストレスがへり、きぶんもよくなります。","romaji":"Undou suru to sutoresu ga heri, kibun mo yoku narimasu.","id":"Dengan berolahraga, stres berkurang dan suasana hati membaik."},
   {"jp":"それから、水をたくさん飲むことも忘れてはいけません。","furigana":"それから、みずをたくさんのむこともわすれてはいけません。","romaji":"Sorekara, mizu o takusan nomu koto mo wasurete wa ikemasen.","id":"Lalu, jangan lupa juga minum banyak air."},
   {"jp":"たばこやお酒は、体に悪い影響を与えます。","furigana":"たばこやおさけは、からだにわるいえいきょうをあたえます。","romaji":"Tabako ya osake wa, karada ni warui eikyou o ataemasu.","id":"Rokok dan alkohol memberi pengaruh buruk bagi tubuh."},
   {"jp":"小さな習慣の積み重ねが、健康な体を作ります。","furigana":"ちいさなしゅうかんのつみかさねが、けんこうなからだをつくります。","romaji":"Chiisa na shuukan no tsumikasane ga, kenkou na karada o tsukurimasu.","id":"Penumpukan kebiasaan kecil membentuk tubuh yang sehat."},
   {"jp":"毎日の生活を見直して、健康に気をつけたいです。","furigana":"まいにちのせいかつをみなおして、けんこうにきをつけたいです。","romaji":"Mainichi no seikatsu o minaoshite, kenkou ni ki o tsuketai desu.","id":"Aku ingin meninjau ulang kehidupan sehari-hari dan menjaga kesehatan."}
 ]'::jsonb,
 '[
   {"word":"健康","reading":"けんこう","romaji":"kenkou","meaning":"kesehatan"},
   {"word":"習慣","reading":"しゅうかん","romaji":"shuukan","meaning":"kebiasaan"},
   {"word":"バランス","reading":"バランス","romaji":"baransu","meaning":"keseimbangan"},
   {"word":"食事","reading":"しょくじ","romaji":"shokuji","meaning":"makan/pola makan"},
   {"word":"砂糖","reading":"さとう","romaji":"satou","meaning":"gula"},
   {"word":"取りすぎる","reading":"とりすぎる","romaji":"torisugiru","meaning":"mengonsumsi berlebihan"},
   {"word":"規則正しい","reading":"きそくただしい","romaji":"kisoku tadashii","meaning":"teratur"},
   {"word":"睡眠","reading":"すいみん","romaji":"suimin","meaning":"tidur/istirahat"},
   {"word":"足りない","reading":"たりない","romaji":"tarinai","meaning":"kurang/tidak cukup"},
   {"word":"集中力","reading":"しゅうちゅうりょく","romaji":"shuuchuuryoku","meaning":"daya konsentrasi"},
   {"word":"適度","reading":"てきど","romaji":"tekido","meaning":"secukupnya/moderat"},
   {"word":"運動","reading":"うんどう","romaji":"undou","meaning":"olahraga"},
   {"word":"減る","reading":"へる","romaji":"heru","meaning":"berkurang"},
   {"word":"影響","reading":"えいきょう","romaji":"eikyou","meaning":"pengaruh"},
   {"word":"積み重ね","reading":"つみかさね","romaji":"tsumikasane","meaning":"penumpukan/akumulasi"}
 ]'::jsonb,
 '[
   {"q":"Menurut teks, hal terpenting bagi semua orang adalah?","options":["Uang","Kesehatan","Pekerjaan","Teman"],"answer":1,"explanation":"「健康は…一番大切なもの」."},
   {"q":"Pola makan yang baik seperti apa?","options":["Banyak gula","Seimbang, banyak sayur dan buah","Banyak minyak","Sangat sedikit"],"answer":1,"explanation":"「バランスの取れた食事」「野菜や果物をたくさん」."},
   {"q":"Apa akibat kurang tidur?","options":["Lapar","Daya konsentrasi menurun","Gemuk","Sakit kepala"],"answer":1,"explanation":"「集中力が下がってしまいます」."},
   {"q":"Apa yang penulis lakukan tiap pagi?","options":["Berenang","Jogging sekitar 30 menit","Yoga","Bersepeda"],"answer":1,"explanation":"「毎朝三十分ぐらいジョギング」."},
   {"q":"Apa manfaat berolahraga menurut teks?","options":["Lebih lapar","Stres berkurang dan mood membaik","Lebih lelah","Lebih boros"],"answer":1,"explanation":"「ストレスが減り、気分もよくなります」."},
   {"q":"Apa yang berdampak buruk bagi tubuh?","options":["Air putih","Rokok dan alkohol","Sayur","Tidur"],"answer":1,"explanation":"「たばこやお酒は、体に悪い影響」."}
 ]'::jsonb,
 false),
(3, 7, '時間の使い方 — Mengatur Waktu',
 '一日は二十四時間しかありません。時間は誰にとっても平等ですが、使い方は人によって違います。時間を上手に使う人は、たくさんのことを達成できます。まず、毎朝その日にやることをリストに書きます。大切なことから順番に片付けていきます。一つの作業に集中して、他のことは後回しにします。スマホを見すぎると、時間を無駄にしてしまいます。だから、勉強中はスマホを別の部屋に置いておきます。また、適度に休憩を取ることも大切です。疲れたまま続けても、効率が悪くなるだけです。締め切りを決めると、やる気が出ます。計画通りに進まない時もありますが、あきらめません。時間を大切にする習慣は、将来きっと役に立ちます。今日の時間を、後悔しないように使いたいです。',
 '[
   {"jp":"一日は二十四時間しかありません。","furigana":"いちにちはにじゅうよじかんしかありません。","romaji":"Ichinichi wa nijuuyo-jikan shika arimasen.","id":"Sehari hanya ada dua puluh empat jam."},
   {"jp":"時間は誰にとっても平等ですが、使い方は人によって違います。","furigana":"じかんはだれにとってもびょうどうですが、つかいかたはひとによってちがいます。","romaji":"Jikan wa dare ni totte mo byoudou desu ga, tsukaikata wa hito ni yotte chigaimasu.","id":"Waktu setara bagi semua orang, tapi cara memakainya berbeda-beda."},
   {"jp":"時間を上手に使う人は、たくさんのことを達成できます。","furigana":"じかんをじょうずにつかうひとは、たくさんのことをたっせいできます。","romaji":"Jikan o jouzu ni tsukau hito wa, takusan no koto o tassei dekimasu.","id":"Orang yang pandai memakai waktu bisa mencapai banyak hal."},
   {"jp":"まず、毎朝その日にやることをリストに書きます。","furigana":"まず、まいあさそのひにやることをリストにかきます。","romaji":"Mazu, maiasa sono hi ni yaru koto o risuto ni kakimasu.","id":"Pertama, tiap pagi aku menulis daftar hal yang akan dikerjakan hari itu."},
   {"jp":"大切なことから順番に片付けていきます。","furigana":"たいせつなことからじゅんばんにかたづけていきます。","romaji":"Taisetsu na koto kara junban ni katazukete ikimasu.","id":"Aku menyelesaikannya secara berurutan, dari yang penting."},
   {"jp":"一つの作業に集中して、他のことは後回しにします。","furigana":"ひとつのさぎょうにしゅうちゅうして、ほかのことはあとまわしにします。","romaji":"Hitotsu no sagyou ni shuuchuu shite, hoka no koto wa atomawashi ni shimasu.","id":"Aku fokus pada satu pekerjaan, dan menunda hal lainnya."},
   {"jp":"スマホを見すぎると、時間を無駄にしてしまいます。","furigana":"スマホをみすぎると、じかんをむだにしてしまいます。","romaji":"Sumaho o misugiru to, jikan o muda ni shite shimaimasu.","id":"Kalau terlalu sering melihat ponsel, waktu jadi terbuang."},
   {"jp":"だから、勉強中はスマホを別の部屋に置いておきます。","furigana":"だから、べんきょうちゅうはスマホをべつのへやにおいておきます。","romaji":"Dakara, benkyouchuu wa sumaho o betsu no heya ni oite okimasu.","id":"Karena itu, saat belajar aku menaruh ponsel di kamar lain."},
   {"jp":"また、適度に休憩を取ることも大切です。","furigana":"また、てきどにきゅうけいをとることもたいせつです。","romaji":"Mata, tekido ni kyuukei o toru koto mo taisetsu desu.","id":"Selain itu, mengambil istirahat secukupnya juga penting."},
   {"jp":"疲れたまま続けても、効率が悪くなるだけです。","furigana":"つかれたままつづけても、こうりつがわるくなるだけです。","romaji":"Tsukareta mama tsuzukete mo, kouritsu ga waruku naru dake desu.","id":"Kalau diteruskan dalam keadaan lelah, efisiensi malah memburuk."},
   {"jp":"締め切りを決めると、やる気が出ます。","furigana":"しめきりをきめると、やるきがでます。","romaji":"Shimekiri o kimeru to, yaruki ga demasu.","id":"Kalau menetapkan tenggat, motivasi muncul."},
   {"jp":"計画通りに進まない時もありますが、あきらめません。","furigana":"けいかくどおりにすすまないときもありますが、あきらめません。","romaji":"Keikaku doori ni susumanai toki mo arimasu ga, akiramemasen.","id":"Ada kalanya tidak berjalan sesuai rencana, tapi aku tidak menyerah."},
   {"jp":"時間を大切にする習慣は、将来きっと役に立ちます。","furigana":"じかんをたいせつにするしゅうかんは、しょうらいきっとやくにたちます。","romaji":"Jikan o taisetsu ni suru shuukan wa, shourai kitto yaku ni tachimasu.","id":"Kebiasaan menghargai waktu pasti berguna di masa depan."},
   {"jp":"今日の時間を、後悔しないように使いたいです。","furigana":"きょうのじかんを、こうかいしないようにつかいたいです。","romaji":"Kyou no jikan o, koukai shinai you ni tsukaitai desu.","id":"Aku ingin memakai waktu hari ini agar tidak menyesal."}
 ]'::jsonb,
 '[
   {"word":"平等","reading":"びょうどう","romaji":"byoudou","meaning":"setara/adil"},
   {"word":"達成","reading":"たっせい","romaji":"tassei","meaning":"mencapai"},
   {"word":"順番","reading":"じゅんばん","romaji":"junban","meaning":"urutan"},
   {"word":"片付ける","reading":"かたづける","romaji":"katazukeru","meaning":"menyelesaikan/merapikan"},
   {"word":"作業","reading":"さぎょう","romaji":"sagyou","meaning":"pekerjaan/tugas"},
   {"word":"集中","reading":"しゅうちゅう","romaji":"shuuchuu","meaning":"konsentrasi"},
   {"word":"後回し","reading":"あとまわし","romaji":"atomawashi","meaning":"ditunda/dikemudiankan"},
   {"word":"無駄","reading":"むだ","romaji":"muda","meaning":"sia-sia"},
   {"word":"休憩","reading":"きゅうけい","romaji":"kyuukei","meaning":"istirahat"},
   {"word":"効率","reading":"こうりつ","romaji":"kouritsu","meaning":"efisiensi"},
   {"word":"締め切り","reading":"しめきり","romaji":"shimekiri","meaning":"tenggat waktu"},
   {"word":"やる気","reading":"やるき","romaji":"yaruki","meaning":"motivasi/semangat"},
   {"word":"計画","reading":"けいかく","romaji":"keikaku","meaning":"rencana"},
   {"word":"あきらめる","reading":"あきらめる","romaji":"akirameru","meaning":"menyerah"},
   {"word":"後悔","reading":"こうかい","romaji":"koukai","meaning":"menyesal"}
 ]'::jsonb,
 '[
   {"q":"Berapa jam dalam sehari menurut teks?","options":["12 jam","20 jam","24 jam","36 jam"],"answer":2,"explanation":"「一日は二十四時間しかありません」."},
   {"q":"Apa yang ditulis penulis tiap pagi?","options":["Buku harian","Daftar hal yang akan dikerjakan","Surat","Resep"],"answer":1,"explanation":"「やることをリストに書きます」."},
   {"q":"Hal dikerjakan mulai dari mana?","options":["Dari yang mudah","Dari yang penting","Acak","Dari yang disukai"],"answer":1,"explanation":"「大切なことから順番に」."},
   {"q":"Apa yang membuang-buang waktu?","options":["Tidur","Terlalu sering melihat ponsel","Makan","Olahraga"],"answer":1,"explanation":"「スマホを見すぎると、時間を無駄に」."},
   {"q":"Saat belajar, ponsel ditaruh di mana?","options":["Di saku","Di meja","Di kamar lain","Di tas"],"answer":2,"explanation":"「スマホを別の部屋に置いておきます」."},
   {"q":"Apa yang memunculkan motivasi?","options":["Hadiah","Menetapkan tenggat","Istirahat","Musik"],"answer":1,"explanation":"「締め切りを決めると、やる気が出ます」."}
 ]'::jsonb,
 false),
(3, 8, '日本のマナー — Etika di Jepang',
 '日本には、独特なマナーがたくさんあります。外国から来た人は、最初に戸惑うかもしれません。例えば、家に入る時は靴を脱ぎます。電車の中では、大きな声で話さないのが普通です。食事の前には「いただきます」と言います。食べ終わったら「ごちそうさま」と言います。麺類を食べる時は、音を立てても失礼ではありません。お風呂に入る前に、体を洗うのが習慣です。ゴミは細かく分けて捨てなければなりません。約束の時間に遅れないことも、とても大切にされています。人に物を渡す時は、両手で渡すと丁寧です。これらのマナーは、相手を思いやる心から生まれました。マナーを守ると、人間関係がスムーズになります。文化を理解し、尊重することが大切だと思います。',
 '[
   {"jp":"日本には、独特なマナーがたくさんあります。","furigana":"にほんには、どくとくなマナーがたくさんあります。","romaji":"Nihon ni wa, dokutoku na manaa ga takusan arimasu.","id":"Di Jepang ada banyak etika yang khas."},
   {"jp":"外国から来た人は、最初に戸惑うかもしれません。","furigana":"がいこくからきたひとは、さいしょにとまどうかもしれません。","romaji":"Gaikoku kara kita hito wa, saisho ni tomadou kamoshiremasen.","id":"Orang yang datang dari luar negeri mungkin awalnya bingung."},
   {"jp":"例えば、家に入る時は靴を脱ぎます。","furigana":"たとえば、いえにはいるときはくつをぬぎます。","romaji":"Tatoeba, ie ni hairu toki wa kutsu o nugimasu.","id":"Misalnya, saat masuk rumah kita melepas sepatu."},
   {"jp":"電車の中では、大きな声で話さないのが普通です。","furigana":"でんしゃのなかでは、おおきなこえではなさないのがふつうです。","romaji":"Densha no naka de wa, ooki na koe de hanasanai no ga futsuu desu.","id":"Di dalam kereta, lazimnya tidak berbicara dengan suara keras."},
   {"jp":"食事の前には「いただきます」と言います。","furigana":"しょくじのまえには「いただきます」といいます。","romaji":"Shokuji no mae ni wa \"itadakimasu\" to iimasu.","id":"Sebelum makan kita mengucapkan itadakimasu."},
   {"jp":"食べ終わったら「ごちそうさま」と言います。","furigana":"たべおわったら「ごちそうさま」といいます。","romaji":"Tabeowattara \"gochisousama\" to iimasu.","id":"Setelah selesai makan kita mengucapkan gochisousama."},
   {"jp":"麺類を食べる時は、音を立てても失礼ではありません。","furigana":"めんるいをたべるときは、おとをたててもしつれいではありません。","romaji":"Menrui o taberu toki wa, oto o tatete mo shitsurei de wa arimasen.","id":"Saat makan mie, menimbulkan bunyi pun tidak dianggap tidak sopan."},
   {"jp":"お風呂に入る前に、体を洗うのが習慣です。","furigana":"おふろにはいるまえに、からだをあらうのがしゅうかんです。","romaji":"Ofuro ni hairu mae ni, karada o arau no ga shuukan desu.","id":"Sebelum berendam, mencuci badan adalah kebiasaan."},
   {"jp":"ゴミは細かく分けて捨てなければなりません。","furigana":"ゴミはこまかくわけてすてなければなりません。","romaji":"Gomi wa komakaku wakete sutenakereba narimasen.","id":"Sampah harus dipilah secara rinci sebelum dibuang."},
   {"jp":"約束の時間に遅れないことも、とても大切にされています。","furigana":"やくそくのじかんにおくれないことも、とてもたいせつにされています。","romaji":"Yakusoku no jikan ni okurenai koto mo, totemo taisetsu ni sarete imasu.","id":"Tidak terlambat dari waktu janji juga sangat dijunjung."},
   {"jp":"人に物を渡す時は、両手で渡すと丁寧です。","furigana":"ひとにものをわたすときは、りょうてでわたすとていねいです。","romaji":"Hito ni mono o watasu toki wa, ryoute de watasu to teinei desu.","id":"Saat menyerahkan barang kepada orang, lebih sopan jika dengan dua tangan."},
   {"jp":"これらのマナーは、相手を思いやる心から生まれました。","furigana":"これらのマナーは、あいてをおもいやるこころからうまれました。","romaji":"Korera no manaa wa, aite o omoiyaru kokoro kara umaremashita.","id":"Etika-etika ini lahir dari hati yang berempati pada orang lain."},
   {"jp":"マナーを守ると、人間関係がスムーズになります。","furigana":"マナーをまもると、にんげんかんけいがスムーズになります。","romaji":"Manaa o mamoru to, ningen kankei ga sumuuzu ni narimasu.","id":"Dengan menjaga etika, hubungan antarmanusia jadi lancar."},
   {"jp":"文化を理解し、尊重することが大切だと思います。","furigana":"ぶんかをりかいし、そんちょうすることがたいせつだとおもいます。","romaji":"Bunka o rikai shi, sonchou suru koto ga taisetsu da to omoimasu.","id":"Memahami dan menghormati budaya itu penting menurutku."}
 ]'::jsonb,
 '[
   {"word":"独特","reading":"どくとく","romaji":"dokutoku","meaning":"khas/unik"},
   {"word":"戸惑う","reading":"とまどう","romaji":"tomadou","meaning":"bingung"},
   {"word":"脱ぐ","reading":"ぬぐ","romaji":"nugu","meaning":"melepas (pakaian/sepatu)"},
   {"word":"普通","reading":"ふつう","romaji":"futsuu","meaning":"biasa/umum"},
   {"word":"麺類","reading":"めんるい","romaji":"menrui","meaning":"jenis mi"},
   {"word":"音を立てる","reading":"おとをたてる","romaji":"oto o tateru","meaning":"menimbulkan bunyi"},
   {"word":"失礼","reading":"しつれい","romaji":"shitsurei","meaning":"tidak sopan"},
   {"word":"習慣","reading":"しゅうかん","romaji":"shuukan","meaning":"kebiasaan"},
   {"word":"分ける","reading":"わける","romaji":"wakeru","meaning":"memilah/membagi"},
   {"word":"約束","reading":"やくそく","romaji":"yakusoku","meaning":"janji"},
   {"word":"遅れる","reading":"おくれる","romaji":"okureru","meaning":"terlambat"},
   {"word":"渡す","reading":"わたす","romaji":"watasu","meaning":"menyerahkan"},
   {"word":"思いやる","reading":"おもいやる","romaji":"omoiyaru","meaning":"berempati/memikirkan orang lain"},
   {"word":"人間関係","reading":"にんげんかんけい","romaji":"ningen kankei","meaning":"hubungan antarmanusia"},
   {"word":"尊重","reading":"そんちょう","romaji":"sonchou","meaning":"menghormati"}
 ]'::jsonb,
 '[
   {"q":"Apa yang dilakukan saat masuk rumah di Jepang?","options":["Mencuci tangan","Melepas sepatu","Membungkuk dalam","Berteriak"],"answer":1,"explanation":"「靴を脱ぎます」 = melepas sepatu."},
   {"q":"Apa yang diucapkan sebelum makan?","options":["Sayonara","Itadakimasu","Konnichiwa","Sumimasen"],"answer":1,"explanation":"「食事の前には『いただきます』」."},
   {"q":"Saat makan mie, menimbulkan bunyi itu?","options":["Dilarang keras","Tidak dianggap tidak sopan","Sangat kasar","Wajib"],"answer":1,"explanation":"「音を立てても失礼ではありません」."},
   {"q":"Sebelum berendam, apa yang dilakukan?","options":["Makan","Mencuci badan","Tidur","Berdoa"],"answer":1,"explanation":"「体を洗うのが習慣」."},
   {"q":"Saat menyerahkan barang, cara yang sopan?","options":["Satu tangan","Dengan dua tangan","Dilempar","Diletakkan di lantai"],"answer":1,"explanation":"「両手で渡すと丁寧」."},
   {"q":"Dari mana etika-etika ini lahir?","options":["Dari hukum","Dari hati yang berempati pada orang lain","Dari agama","Dari kebiasaan asing"],"answer":1,"explanation":"「相手を思いやる心から生まれました」."}
 ]'::jsonb,
 false),
(3, 9, 'お金の管理 — Mengelola Keuangan',
 'お金の管理は、大人になるために必要な技術です。私は大学生になってから、自分でお金を管理し始めました。毎月、決まった額のお小遣いをもらっています。まず、家計簿をつけて、何にいくら使ったか記録します。収入と支出のバランスを考えることが大切です。無駄な買い物を減らすために、本当に必要な物だけ買います。ほしい物があっても、すぐには買わず、よく考えます。安いからといって、たくさん買うのは無駄遣いです。毎月少しずつ貯金することも心がけています。急な出費に備えて、お金を残しておくと安心です。友だちと比べて、お金を使いすぎないように注意します。お金は使い方によって、価値が変わります。計画的にお金を使う習慣は、一生役に立ちます。今のうちに、お金の管理を学んでおきたいです。',
 '[
   {"jp":"お金の管理は、大人になるために必要な技術です。","furigana":"おかねのかんりは、おとなになるためにひつようなぎじゅつです。","romaji":"Okane no kanri wa, otona ni naru tame ni hitsuyou na gijutsu desu.","id":"Mengelola uang adalah keterampilan yang dibutuhkan untuk menjadi dewasa."},
   {"jp":"私は大学生になってから、自分でお金を管理し始めました。","furigana":"わたしはだいがくせいになってから、じぶんでおかねをかんりしはじめました。","romaji":"Watashi wa daigakusei ni natte kara, jibun de okane o kanri shihajimemashita.","id":"Sejak jadi mahasiswa, aku mulai mengelola uang sendiri."},
   {"jp":"毎月、決まった額のお小遣いをもらっています。","furigana":"まいつき、きまったがくのおこづかいをもらっています。","romaji":"Maitsuki, kimatta gaku no okozukai o moratte imasu.","id":"Setiap bulan aku menerima uang saku dengan jumlah tertentu."},
   {"jp":"まず、家計簿をつけて、何にいくら使ったか記録します。","furigana":"まず、かけいぼをつけて、なににいくらつかったかきろくします。","romaji":"Mazu, kakeibo o tsukete, nani ni ikura tsukatta ka kiroku shimasu.","id":"Pertama, aku membuat catatan keuangan dan mencatat untuk apa dan berapa uang dipakai."},
   {"jp":"収入と支出のバランスを考えることが大切です。","furigana":"しゅうにゅうとししゅつのバランスをかんがえることがたいせつです。","romaji":"Shuunyuu to shishutsu no baransu o kangaeru koto ga taisetsu desu.","id":"Penting untuk memikirkan keseimbangan pemasukan dan pengeluaran."},
   {"jp":"無駄な買い物を減らすために、本当に必要な物だけ買います。","furigana":"むだなかいものをへらすために、ほんとうにひつようなものだけかいます。","romaji":"Muda na kaimono o herasu tame ni, hontou ni hitsuyou na mono dake kaimasu.","id":"Untuk mengurangi belanja sia-sia, aku hanya membeli yang benar-benar perlu."},
   {"jp":"ほしい物があっても、すぐには買わず、よく考えます。","furigana":"ほしいものがあっても、すぐにはかわず、よくかんがえます。","romaji":"Hoshii mono ga atte mo, sugu ni wa kawazu, yoku kangaemasu.","id":"Meski ada barang yang diinginkan, aku tidak langsung membeli, tapi berpikir matang."},
   {"jp":"安いからといって、たくさん買うのは無駄遣いです。","furigana":"やすいからといって、たくさんかうのはむだづかいです。","romaji":"Yasui kara to itte, takusan kau no wa mudazukai desu.","id":"Membeli banyak hanya karena murah adalah pemborosan."},
   {"jp":"毎月少しずつ貯金することも心がけています。","furigana":"まいつきすこしずつちょきんすることもこころがけています。","romaji":"Maitsuki sukoshi zutsu chokin suru koto mo kokorogakete imasu.","id":"Aku juga berusaha menabung sedikit demi sedikit tiap bulan."},
   {"jp":"急な出費に備えて、お金を残しておくと安心です。","furigana":"きゅうなしゅっぴにそなえて、おかねをのこしておくとあんしんです。","romaji":"Kyuu na shuppi ni sonaete, okane o nokoshite oku to anshin desu.","id":"Menyisihkan uang untuk berjaga-jaga pengeluaran mendadak membuat tenang."},
   {"jp":"友だちと比べて、お金を使いすぎないように注意します。","furigana":"ともだちとくらべて、おかねをつかいすぎないようにちゅういします。","romaji":"Tomodachi to kurabete, okane o tsukai suginai you ni chuui shimasu.","id":"Aku berhati-hati agar tidak boros karena membandingkan diri dengan teman."},
   {"jp":"お金は使い方によって、価値が変わります。","furigana":"おかねはつかいかたによって、かちがかわります。","romaji":"Okane wa tsukaikata ni yotte, kachi ga kawarimasu.","id":"Nilai uang berubah tergantung cara memakainya."},
   {"jp":"計画的にお金を使う習慣は、一生役に立ちます。","furigana":"けいかくてきにおかねをつかうしゅうかんは、いっしょうやくにたちます。","romaji":"Keikakuteki ni okane o tsukau shuukan wa, isshou yaku ni tachimasu.","id":"Kebiasaan memakai uang secara terencana berguna seumur hidup."},
   {"jp":"今のうちに、お金の管理を学んでおきたいです。","furigana":"いまのうちに、おかねのかんりをまなんでおきたいです。","romaji":"Ima no uchi ni, okane no kanri o manande okitai desu.","id":"Aku ingin mempelajari pengelolaan uang selagi sekarang."}
 ]'::jsonb,
 '[
   {"word":"管理","reading":"かんり","romaji":"kanri","meaning":"pengelolaan"},
   {"word":"技術","reading":"ぎじゅつ","romaji":"gijutsu","meaning":"keterampilan/teknik"},
   {"word":"お小遣い","reading":"おこづかい","romaji":"okozukai","meaning":"uang saku"},
   {"word":"家計簿","reading":"かけいぼ","romaji":"kakeibo","meaning":"buku catatan keuangan"},
   {"word":"記録","reading":"きろく","romaji":"kiroku","meaning":"mencatat/rekam"},
   {"word":"収入","reading":"しゅうにゅう","romaji":"shuunyuu","meaning":"pemasukan"},
   {"word":"支出","reading":"ししゅつ","romaji":"shishutsu","meaning":"pengeluaran"},
   {"word":"無駄遣い","reading":"むだづかい","romaji":"mudazukai","meaning":"pemborosan"},
   {"word":"減らす","reading":"へらす","romaji":"herasu","meaning":"mengurangi"},
   {"word":"貯金","reading":"ちょきん","romaji":"chokin","meaning":"menabung"},
   {"word":"心がける","reading":"こころがける","romaji":"kokorogakeru","meaning":"berusaha membiasakan"},
   {"word":"出費","reading":"しゅっぴ","romaji":"shuppi","meaning":"pengeluaran"},
   {"word":"備える","reading":"そなえる","romaji":"sonaeru","meaning":"bersiap/berjaga"},
   {"word":"価値","reading":"かち","romaji":"kachi","meaning":"nilai"},
   {"word":"計画的","reading":"けいかくてき","romaji":"keikakuteki","meaning":"terencana"}
 ]'::jsonb,
 '[
   {"q":"Sejak kapan penulis mengelola uang sendiri?","options":["Sejak SD","Sejak SMA","Sejak jadi mahasiswa","Sejak bekerja"],"answer":2,"explanation":"「大学生になってから…管理し始めました」."},
   {"q":"Apa yang dicatat penulis dalam buku keuangan?","options":["Nilai ujian","Untuk apa dan berapa uang dipakai","Jadwal","Belanjaan teman"],"answer":1,"explanation":"「何にいくら使ったか記録します」."},
   {"q":"Agar tidak boros, penulis hanya membeli?","options":["Yang murah","Yang benar-benar perlu","Yang disukai","Yang baru"],"answer":1,"explanation":"「本当に必要な物だけ買います」."},
   {"q":"Apa yang penulis usahakan tiap bulan?","options":["Belanja besar","Menabung sedikit demi sedikit","Pinjam uang","Beli saham"],"answer":1,"explanation":"「少しずつ貯金することも心がけています」."},
   {"q":"Kenapa menyisihkan uang?","options":["Untuk liburan","Untuk berjaga pengeluaran mendadak","Untuk teman","Untuk hadiah"],"answer":1,"explanation":"「急な出費に備えて」."},
   {"q":"Nilai uang berubah tergantung apa?","options":["Jumlahnya","Cara memakainya","Tempatnya","Waktunya"],"answer":1,"explanation":"「使い方によって、価値が変わります」."}
 ]'::jsonb,
 false),
(3, 10, '一人暮らし — Hidup Mandiri',
 '大学に入学して、私は初めて一人暮らしを始めました。最初は、何もかも自分でやらなければならず、大変でした。料理、洗濯、掃除など、家事は思ったより時間がかかります。親のありがたさが、改めてよく分かりました。一人暮らしは寂しいと感じることもあります。特に、病気になった時は心細くなります。でも、自由な時間が増えたのは大きなメリットです。自分のペースで生活できるのが、とても気に入っています。お金の管理も、自分でしっかり考えるようになりました。失敗から学ぶことが、たくさんありました。近所の人や友だちとのつながりが、心の支えになります。一人暮らしを通して、私は少しずつ成長しています。自立することは、簡単ではありませんが、大切な経験です。この経験は、将来きっと役に立つと思います。',
 '[
   {"jp":"大学に入学して、私は初めて一人暮らしを始めました。","furigana":"だいがくににゅうがくして、わたしははじめてひとりぐらしをはじめました。","romaji":"Daigaku ni nyuugaku shite, watashi wa hajimete hitorigurashi o hajimemashita.","id":"Masuk universitas, aku mulai hidup sendiri untuk pertama kali."},
   {"jp":"最初は、何もかも自分でやらなければならず、大変でした。","furigana":"さいしょは、なにもかもじぶんでやらなければならず、たいへんでした。","romaji":"Saisho wa, nani mo kamo jibun de yaranakereba narazu, taihen deshita.","id":"Awalnya segalanya harus kulakukan sendiri, dan itu berat."},
   {"jp":"料理、洗濯、掃除など、家事は思ったより時間がかかります。","furigana":"りょうり、せんたく、そうじなど、かじはおもったよりじかんがかかります。","romaji":"Ryouri, sentaku, souji nado, kaji wa omotta yori jikan ga kakarimasu.","id":"Memasak, mencuci, membersihkan, dan pekerjaan rumah memakan waktu lebih dari dugaan."},
   {"jp":"親のありがたさが、改めてよく分かりました。","furigana":"おやのありがたさが、あらためてよくわかりました。","romaji":"Oya no arigatasa ga, aratamete yoku wakarimashita.","id":"Aku jadi benar-benar menyadari kembali jasa orang tua."},
   {"jp":"一人暮らしは寂しいと感じることもあります。","furigana":"ひとりぐらしはさびしいとかんじることもあります。","romaji":"Hitorigurashi wa sabishii to kanjiru koto mo arimasu.","id":"Kadang hidup sendiri terasa kesepian."},
   {"jp":"特に、病気になった時は心細くなります。","furigana":"とくに、びょうきになったときはこころぼそくなります。","romaji":"Toku ni, byouki ni natta toki wa kokorobosoku narimasu.","id":"Terutama saat sakit, aku jadi merasa cemas dan rapuh."},
   {"jp":"でも、自由な時間が増えたのは大きなメリットです。","furigana":"でも、じゆうなじかんがふえたのはおおきなメリットです。","romaji":"Demo, jiyuu na jikan ga fueta no wa ooki na meritto desu.","id":"Tapi bertambahnya waktu bebas adalah kelebihan besar."},
   {"jp":"自分のペースで生活できるのが、とても気に入っています。","furigana":"じぶんのペースでせいかつできるのが、とてもきにいっています。","romaji":"Jibun no peesu de seikatsu dekiru no ga, totemo ki ni itte imasu.","id":"Aku sangat menyukai bisa hidup dengan tempo sendiri."},
   {"jp":"お金の管理も、自分でしっかり考えるようになりました。","furigana":"おかねのかんりも、じぶんでしっかりかんがえるようになりました。","romaji":"Okane no kanri mo, jibun de shikkari kangaeru you ni narimashita.","id":"Aku jadi memikirkan pengelolaan uang dengan serius sendiri."},
   {"jp":"失敗から学ぶことが、たくさんありました。","furigana":"しっぱいからまなぶことが、たくさんありました。","romaji":"Shippai kara manabu koto ga, takusan arimashita.","id":"Ada banyak hal yang kupelajari dari kegagalan."},
   {"jp":"近所の人や友だちとのつながりが、心の支えになります。","furigana":"きんじょのひとやともだちとのつながりが、こころのささえになります。","romaji":"Kinjo no hito ya tomodachi to no tsunagari ga, kokoro no sasae ni narimasu.","id":"Ikatan dengan tetangga dan teman menjadi penopang hati."},
   {"jp":"一人暮らしを通して、私は少しずつ成長しています。","furigana":"ひとりぐらしをとおして、わたしはすこしずつせいちょうしています。","romaji":"Hitorigurashi o tooshite, watashi wa sukoshi zutsu seichou shite imasu.","id":"Melalui hidup sendiri, aku sedikit demi sedikit bertumbuh."},
   {"jp":"自立することは、簡単ではありませんが、大切な経験です。","furigana":"じりつすることは、かんたんではありませんが、たいせつなけいけんです。","romaji":"Jiritsu suru koto wa, kantan de wa arimasen ga, taisetsu na keiken desu.","id":"Menjadi mandiri tidaklah mudah, tapi merupakan pengalaman berharga."},
   {"jp":"この経験は、将来きっと役に立つと思います。","furigana":"このけいけんは、しょうらいきっとやくにたつとおもいます。","romaji":"Kono keiken wa, shourai kitto yaku ni tatsu to omoimasu.","id":"Pengalaman ini pasti berguna di masa depan."}
 ]'::jsonb,
 '[
   {"word":"一人暮らし","reading":"ひとりぐらし","romaji":"hitorigurashi","meaning":"hidup sendiri"},
   {"word":"入学","reading":"にゅうがく","romaji":"nyuugaku","meaning":"masuk sekolah/kuliah"},
   {"word":"家事","reading":"かじ","romaji":"kaji","meaning":"pekerjaan rumah"},
   {"word":"洗濯","reading":"せんたく","romaji":"sentaku","meaning":"mencuci pakaian"},
   {"word":"ありがたさ","reading":"ありがたさ","romaji":"arigatasa","meaning":"rasa syukur/jasa"},
   {"word":"改めて","reading":"あらためて","romaji":"aratamete","meaning":"sekali lagi/baru menyadari"},
   {"word":"寂しい","reading":"さびしい","romaji":"sabishii","meaning":"kesepian"},
   {"word":"心細い","reading":"こころぼそい","romaji":"kokorobosoi","meaning":"merasa cemas/rapuh"},
   {"word":"自由","reading":"じゆう","romaji":"jiyuu","meaning":"bebas"},
   {"word":"メリット","reading":"メリット","romaji":"meritto","meaning":"kelebihan"},
   {"word":"ペース","reading":"ペース","romaji":"peesu","meaning":"tempo/laju"},
   {"word":"失敗","reading":"しっぱい","romaji":"shippai","meaning":"kegagalan"},
   {"word":"つながり","reading":"つながり","romaji":"tsunagari","meaning":"ikatan/koneksi"},
   {"word":"支え","reading":"ささえ","romaji":"sasae","meaning":"penopang"},
   {"word":"自立","reading":"じりつ","romaji":"jiritsu","meaning":"mandiri/berdiri sendiri"}
 ]'::jsonb,
 '[
   {"q":"Kapan penulis mulai hidup sendiri?","options":["Saat SMA","Saat masuk kuliah","Saat bekerja","Saat menikah"],"answer":1,"explanation":"「大学に入学して…一人暮らしを始めました」."},
   {"q":"Apa yang ternyata memakan waktu lebih dari dugaan?","options":["Belajar","Pekerjaan rumah","Tidur","Perjalanan"],"answer":1,"explanation":"「家事は思ったより時間がかかります」."},
   {"q":"Apa yang baru disadari penulis?","options":["Pentingnya uang","Jasa orang tua","Pentingnya teman","Pentingnya sekolah"],"answer":1,"explanation":"「親のありがたさが…分かりました」."},
   {"q":"Kapan penulis merasa cemas/rapuh?","options":["Saat ujian","Saat sakit","Saat libur","Saat hujan"],"answer":1,"explanation":"「病気になった時は心細くなります」."},
   {"q":"Apa kelebihan besar hidup sendiri?","options":["Lebih hemat","Bertambahnya waktu bebas","Lebih banyak teman","Lebih aman"],"answer":1,"explanation":"「自由な時間が増えた」."},
   {"q":"Apa yang menjadi penopang hati?","options":["Uang","Ikatan dengan tetangga dan teman","Pekerjaan","Hobi"],"answer":1,"explanation":"「近所の人や友だちとのつながり」."}
 ]'::jsonb,
 false),
(3, 11, '防災の備え — Kesiapsiagaan Bencana',
 '日本は地震や台風が多い国です。だから、災害に備えることがとても大切です。私の家では、非常用の持ち出し袋を用意しています。袋の中には、水や食料、懐中電灯などを入れておきます。地震が起きたら、まず机の下に隠れて、頭を守ります。揺れがおさまったら、火を消して、ドアを開けます。慌てて外に飛び出すのは、かえって危険です。家族と避難場所をあらかじめ決めておくといいです。学校でも、定期的に避難訓練を行っています。訓練のおかげで、いざという時に落ち着いて行動できます。ラジオで正しい情報を集めることも重要です。近所の人と助け合うことも、防災の一つです。「備えあれば憂いなし」という言葉があります。日頃からの準備が、命を守ることにつながります。',
 '[
   {"jp":"日本は地震や台風が多い国です。","furigana":"にほんはじしんやたいふうがおおいくにです。","romaji":"Nihon wa jishin ya taifuu ga ooi kuni desu.","id":"Jepang adalah negara yang sering dilanda gempa dan topan."},
   {"jp":"だから、災害に備えることがとても大切です。","furigana":"だから、さいがいにそなえることがとてもたいせつです。","romaji":"Dakara, saigai ni sonaeru koto ga totemo taisetsu desu.","id":"Karena itu, bersiap menghadapi bencana sangat penting."},
   {"jp":"私の家では、非常用の持ち出し袋を用意しています。","furigana":"わたしのいえでは、ひじょうようのもちだしぶくろをよういしています。","romaji":"Watashi no ie de wa, hijouyou no mochidashibukuro o youi shite imasu.","id":"Di rumahku, kami menyiapkan tas siaga darurat."},
   {"jp":"袋の中には、水や食料、懐中電灯などを入れておきます。","furigana":"ふくろのなかには、みずやしょくりょう、かいちゅうでんとうなどをいれておきます。","romaji":"Fukuro no naka ni wa, mizu ya shokuryou, kaichuu dentou nado o irete okimasu.","id":"Di dalam tas kami siapkan air, makanan, senter, dan lainnya."},
   {"jp":"地震が起きたら、まず机の下に隠れて、頭を守ります。","furigana":"じしんがおきたら、まずつくえのしたにかくれて、あたまをまもります。","romaji":"Jishin ga okitara, mazu tsukue no shita ni kakurete, atama o mamorimasu.","id":"Kalau gempa terjadi, pertama bersembunyi di bawah meja dan melindungi kepala."},
   {"jp":"揺れがおさまったら、火を消して、ドアを開けます。","furigana":"ゆれがおさまったら、ひをけして、ドアをあけます。","romaji":"Yure ga osamattara, hi o keshite, doa o akemasu.","id":"Setelah guncangan reda, matikan api dan buka pintu."},
   {"jp":"慌てて外に飛び出すのは、かえって危険です。","furigana":"あわててそとにとびだすのは、かえってきけんです。","romaji":"Awatete soto ni tobidasu no wa, kaette kiken desu.","id":"Panik lari ke luar justru berbahaya."},
   {"jp":"家族と避難場所をあらかじめ決めておくといいです。","furigana":"かぞくとひなんばしょをあらかじめきめておくといいです。","romaji":"Kazoku to hinan basho o arakajime kimete oku to ii desu.","id":"Sebaiknya menentukan tempat pengungsian bersama keluarga sejak awal."},
   {"jp":"学校でも、定期的に避難訓練を行っています。","furigana":"がっこうでも、ていきてきにひなんくんれんをおこなっています。","romaji":"Gakkou de mo, teikiteki ni hinan kunren o okonatte imasu.","id":"Di sekolah pun, latihan evakuasi diadakan secara berkala."},
   {"jp":"訓練のおかげで、いざという時に落ち着いて行動できます。","furigana":"くんれんのおかげで、いざというときにおちついてこうどうできます。","romaji":"Kunren no okage de, iza to iu toki ni ochitsuite koudou dekimasu.","id":"Berkat latihan, kita bisa bertindak tenang saat keadaan genting."},
   {"jp":"ラジオで正しい情報を集めることも重要です。","furigana":"ラジオでただしいじょうほうをあつめることもじゅうようです。","romaji":"Rajio de tadashii jouhou o atsumeru koto mo juuyou desu.","id":"Mengumpulkan informasi yang benar lewat radio juga penting."},
   {"jp":"近所の人と助け合うことも、防災の一つです。","furigana":"きんじょのひととたすけあうことも、ぼうさいのひとつです。","romaji":"Kinjo no hito to tasukeau koto mo, bousai no hitotsu desu.","id":"Saling membantu dengan tetangga juga bagian dari mitigasi bencana."},
   {"jp":"「備えあれば憂いなし」という言葉があります。","furigana":"「そなえあればうれいなし」ということばがあります。","romaji":"\"Sonae areba urei nashi\" to iu kotoba ga arimasu.","id":"Ada pepatah sonae areba urei nashi (sedia payung sebelum hujan)."},
   {"jp":"日頃からの準備が、命を守ることにつながります。","furigana":"ひごろからのじゅんびが、いのちをまもることにつながります。","romaji":"Higoro kara no junbi ga, inochi o mamoru koto ni tsunagarimasu.","id":"Persiapan sehari-hari berujung pada melindungi nyawa."}
 ]'::jsonb,
 '[
   {"word":"防災","reading":"ぼうさい","romaji":"bousai","meaning":"mitigasi bencana"},
   {"word":"地震","reading":"じしん","romaji":"jishin","meaning":"gempa bumi"},
   {"word":"台風","reading":"たいふう","romaji":"taifuu","meaning":"topan"},
   {"word":"災害","reading":"さいがい","romaji":"saigai","meaning":"bencana"},
   {"word":"備える","reading":"そなえる","romaji":"sonaeru","meaning":"bersiap/berjaga"},
   {"word":"非常用","reading":"ひじょうよう","romaji":"hijouyou","meaning":"untuk keadaan darurat"},
   {"word":"持ち出し袋","reading":"もちだしぶくろ","romaji":"mochidashibukuro","meaning":"tas siaga"},
   {"word":"懐中電灯","reading":"かいちゅうでんとう","romaji":"kaichuu dentou","meaning":"senter"},
   {"word":"隠れる","reading":"かくれる","romaji":"kakureru","meaning":"bersembunyi"},
   {"word":"揺れ","reading":"ゆれ","romaji":"yure","meaning":"guncangan"},
   {"word":"慌てる","reading":"あわてる","romaji":"awateru","meaning":"panik/gugup"},
   {"word":"避難","reading":"ひなん","romaji":"hinan","meaning":"mengungsi"},
   {"word":"訓練","reading":"くんれん","romaji":"kunren","meaning":"latihan"},
   {"word":"落ち着く","reading":"おちつく","romaji":"ochitsuku","meaning":"tenang"},
   {"word":"助け合う","reading":"たすけあう","romaji":"tasukeau","meaning":"saling membantu"}
 ]'::jsonb,
 '[
   {"q":"Jepang sering dilanda bencana apa?","options":["Banjir dan kekeringan","Gempa dan topan","Badai pasir","Letusan gunung saja"],"answer":1,"explanation":"「地震や台風が多い国」."},
   {"q":"Apa isi tas siaga darurat?","options":["Buku dan mainan","Air, makanan, senter","Baju pesta","Peralatan masak"],"answer":1,"explanation":"「水や食料、懐中電灯など」."},
   {"q":"Saat gempa terjadi, apa yang dilakukan dulu?","options":["Lari ke luar","Bersembunyi di bawah meja dan lindungi kepala","Berteriak","Menelepon"],"answer":1,"explanation":"「机の下に隠れて、頭を守ります」."},
   {"q":"Apa yang justru berbahaya?","options":["Mematikan api","Panik lari ke luar","Membuka pintu","Diam tenang"],"answer":1,"explanation":"「慌てて外に飛び出すのは、かえって危険」."},
   {"q":"Apa yang dilakukan di sekolah?","options":["Ujian","Latihan evakuasi berkala","Libur","Senam pagi"],"answer":1,"explanation":"「定期的に避難訓練を行っています」."},
   {"q":"Pepatah 「備えあれば憂いなし」 berarti?","options":["Sesal kemudian tak berguna","Kalau ada persiapan, tak ada kekhawatiran","Bersatu kita teguh","Sedikit demi sedikit menjadi bukit"],"answer":1,"explanation":"Artinya: jika sudah siap, tak perlu cemas."}
 ]'::jsonb,
 false),
(3, 12, '田舎と都会 — Desa dan Kota',
 '田舎と都会には、それぞれいいところと悪いところがあります。私は田舎で生まれ、今は都会に住んでいます。都会は便利で、買い物や交通に困りません。仕事や勉強の機会も、都会のほうが多いです。しかし、都会は人が多く、いつも込んでいます。家賃も高く、生活費がたくさんかかります。一方、田舎は自然が豊かで、空気がきれいです。近所の人との関係が深く、温かい雰囲気があります。でも、田舎は交通が不便で、車がないと生活が難しいです。仕事の種類も少なく、若い人が都会へ出て行きます。そのため、田舎では人口が減り続けています。どちらがいいかは、人の価値観によって違います。私は、いつか田舎に戻って暮らしたいと思っています。都会の便利さと田舎の自然、両方が大切だと感じます。',
 '[
   {"jp":"田舎と都会には、それぞれいいところと悪いところがあります。","furigana":"いなかととかいには、それぞれいいところとわるいところがあります。","romaji":"Inaka to tokai ni wa, sorezore ii tokoro to warui tokoro ga arimasu.","id":"Desa dan kota masing-masing punya kelebihan dan kekurangan."},
   {"jp":"私は田舎で生まれ、今は都会に住んでいます。","furigana":"わたしはいなかでうまれ、いまはとかいにすんでいます。","romaji":"Watashi wa inaka de umare, ima wa tokai ni sunde imasu.","id":"Aku lahir di desa, dan sekarang tinggal di kota."},
   {"jp":"都会は便利で、買い物や交通に困りません。","furigana":"とかいはべんりで、かいものやこうつうにこまりません。","romaji":"Tokai wa benri de, kaimono ya koutsuu ni komarimasen.","id":"Kota praktis, tidak kesulitan soal belanja dan transportasi."},
   {"jp":"仕事や勉強の機会も、都会のほうが多いです。","furigana":"しごとやべんきょうのきかいも、とかいのほうがおおいです。","romaji":"Shigoto ya benkyou no kikai mo, tokai no hou ga ooi desu.","id":"Kesempatan kerja dan belajar pun lebih banyak di kota."},
   {"jp":"しかし、都会は人が多く、いつも込んでいます。","furigana":"しかし、とかいはひとがおおく、いつもこんでいます。","romaji":"Shikashi, tokai wa hito ga ooku, itsumo konde imasu.","id":"Namun, kota penuh orang dan selalu padat."},
   {"jp":"家賃も高く、生活費がたくさんかかります。","furigana":"やちんもたかく、せいかつひがたくさんかかります。","romaji":"Yachin mo takaku, seikatsuhi ga takusan kakarimasu.","id":"Sewa juga mahal dan biaya hidup besar."},
   {"jp":"一方、田舎は自然が豊かで、空気がきれいです。","furigana":"いっぽう、いなかはしぜんがゆたかで、くうきがきれいです。","romaji":"Ippou, inaka wa shizen ga yutaka de, kuuki ga kirei desu.","id":"Di sisi lain, desa kaya alam dan udaranya bersih."},
   {"jp":"近所の人との関係が深く、温かい雰囲気があります。","furigana":"きんじょのひととのかんけいがふかく、あたたかいふんいきがあります。","romaji":"Kinjo no hito to no kankei ga fukaku, atatakai fun-iki ga arimasu.","id":"Hubungan dengan tetangga erat, dan suasananya hangat."},
   {"jp":"でも、田舎は交通が不便で、車がないと生活が難しいです。","furigana":"でも、いなかはこうつうがふべんで、くるまがないとせいかつがむずかしいです。","romaji":"Demo, inaka wa koutsuu ga fuben de, kuruma ga nai to seikatsu ga muzukashii desu.","id":"Tapi transportasi desa tidak praktis, dan hidup susah tanpa mobil."},
   {"jp":"仕事の種類も少なく、若い人が都会へ出て行きます。","furigana":"しごとのしゅるいもすくなく、わかいひとがとかいへでていきます。","romaji":"Shigoto no shurui mo sukunaku, wakai hito ga tokai e dete ikimasu.","id":"Jenis pekerjaan pun sedikit, sehingga anak muda pergi ke kota."},
   {"jp":"そのため、田舎では人口が減り続けています。","furigana":"そのため、いなかではじんこうがへりつづけています。","romaji":"Sono tame, inaka de wa jinkou ga heritsuzukete imasu.","id":"Akibatnya, populasi di desa terus berkurang."},
   {"jp":"どちらがいいかは、人の価値観によって違います。","furigana":"どちらがいいかは、ひとのかちかんによってちがいます。","romaji":"Dochira ga ii ka wa, hito no kachikan ni yotte chigaimasu.","id":"Mana yang lebih baik tergantung nilai/pandangan tiap orang."},
   {"jp":"私は、いつか田舎に戻って暮らしたいと思っています。","furigana":"わたしは、いつかいなかにもどってくらしたいとおもっています。","romaji":"Watashi wa, itsuka inaka ni modotte kurashitai to omotte imasu.","id":"Aku berpikir suatu saat ingin kembali tinggal di desa."},
   {"jp":"都会の便利さと田舎の自然、両方が大切だと感じます。","furigana":"とかいのべんりさといなかのしぜん、りょうほうがたいせつだとかんじます。","romaji":"Tokai no benrisa to inaka no shizen, ryouhou ga taisetsu da to kanjimasu.","id":"Aku merasa kepraktisan kota dan alam desa, keduanya penting."}
 ]'::jsonb,
 '[
   {"word":"田舎","reading":"いなか","romaji":"inaka","meaning":"desa/kampung"},
   {"word":"都会","reading":"とかい","romaji":"tokai","meaning":"kota besar"},
   {"word":"便利","reading":"べんり","romaji":"benri","meaning":"praktis"},
   {"word":"交通","reading":"こうつう","romaji":"koutsuu","meaning":"transportasi/lalu lintas"},
   {"word":"機会","reading":"きかい","romaji":"kikai","meaning":"kesempatan"},
   {"word":"家賃","reading":"やちん","romaji":"yachin","meaning":"sewa (tempat tinggal)"},
   {"word":"生活費","reading":"せいかつひ","romaji":"seikatsuhi","meaning":"biaya hidup"},
   {"word":"自然","reading":"しぜん","romaji":"shizen","meaning":"alam"},
   {"word":"豊か","reading":"ゆたか","romaji":"yutaka","meaning":"kaya/melimpah"},
   {"word":"雰囲気","reading":"ふんいき","romaji":"fun-iki","meaning":"suasana"},
   {"word":"不便","reading":"ふべん","romaji":"fuben","meaning":"tidak praktis"},
   {"word":"種類","reading":"しゅるい","romaji":"shurui","meaning":"jenis"},
   {"word":"人口","reading":"じんこう","romaji":"jinkou","meaning":"populasi/jumlah penduduk"},
   {"word":"価値観","reading":"かちかん","romaji":"kachikan","meaning":"nilai/pandangan hidup"},
   {"word":"戻る","reading":"もどる","romaji":"modoru","meaning":"kembali"}
 ]'::jsonb,
 '[
   {"q":"Penulis lahir di mana dan tinggal di mana sekarang?","options":["Lahir kota, tinggal desa","Lahir desa, tinggal kota","Keduanya di kota","Keduanya di desa"],"answer":1,"explanation":"「田舎で生まれ、今は都会に住んでいます」."},
   {"q":"Apa kelebihan kota?","options":["Udara bersih","Praktis dan banyak kesempatan","Sewa murah","Sangat sepi"],"answer":1,"explanation":"「便利で…機会も…多い」."},
   {"q":"Apa kekurangan kota?","options":["Sepi","Ramai dan biaya hidup tinggi","Tidak ada pekerjaan","Hanya udara buruk"],"answer":1,"explanation":"「人が多く…生活費がたくさんかかります」."},
   {"q":"Apa kelebihan desa?","options":["Banyak pekerjaan","Alam melimpah dan udara bersih","Transportasi murah","Banyak hiburan"],"answer":1,"explanation":"「自然が豊かで、空気がきれい」."},
   {"q":"Kenapa anak muda pindah ke kota?","options":["Bosan","Jenis pekerjaan di desa sedikit","Tidak suka alam","Karena cuaca"],"answer":1,"explanation":"「仕事の種類も少なく…都会へ出て行きます」."},
   {"q":"Apa yang terjadi pada populasi desa?","options":["Bertambah","Terus berkurang","Tetap","Berlipat ganda"],"answer":1,"explanation":"「人口が減り続けています」."}
 ]'::jsonb,
 false),
(3, 13, '在宅勤務 — Kerja dari Rumah',
 '最近、在宅勤務をする人が増えています。インターネットの発達で、家でも仕事ができるようになりました。在宅勤務には、いろいろなメリットがあります。まず、通勤の時間が要らないので、時間を有効に使えます。満員電車のストレスからも解放されます。自分の好きな環境で、集中して働くこともできます。家族と過ごす時間が増えるのも、いい点です。一方で、デメリットもあります。家にいると、仕事とプライベートの区別が難しくなります。一人で作業するので、孤独を感じることもあります。同僚と直接会えないため、連絡が取りにくいこともあります。在宅勤務をうまく続けるには、自己管理が必要です。仕事の時間と休む時間を、しっかり分けることが大切です。これからは、働き方がもっと多様になっていくでしょう。',
 '[
   {"jp":"最近、在宅勤務をする人が増えています。","furigana":"さいきん、ざいたくきんむをするひとがふえています。","romaji":"Saikin, zaitaku kinmu o suru hito ga fuete imasu.","id":"Akhir-akhir ini, orang yang bekerja dari rumah semakin banyak."},
   {"jp":"インターネットの発達で、家でも仕事ができるようになりました。","furigana":"インターネットのはったつで、いえでもしごとができるようになりました。","romaji":"Intaanetto no hattatsu de, ie de mo shigoto ga dekiru you ni narimashita.","id":"Berkat perkembangan internet, bekerja di rumah pun jadi mungkin."},
   {"jp":"在宅勤務には、いろいろなメリットがあります。","furigana":"ざいたくきんむには、いろいろなメリットがあります。","romaji":"Zaitaku kinmu ni wa, iroiro na meritto ga arimasu.","id":"Kerja dari rumah punya berbagai kelebihan."},
   {"jp":"まず、通勤の時間が要らないので、時間を有効に使えます。","furigana":"まず、つうきんのじかんがいらないので、じかんをゆうこうにつかえます。","romaji":"Mazu, tsuukin no jikan ga iranai node, jikan o yuukou ni tsukaemasu.","id":"Pertama, karena tidak perlu waktu komuting, waktu bisa dipakai efektif."},
   {"jp":"満員電車のストレスからも解放されます。","furigana":"まんいんでんしゃのストレスからもかいほうされます。","romaji":"Man-in densha no sutoresu kara mo kaihou saremasu.","id":"Kita juga terbebas dari stres kereta yang penuh sesak."},
   {"jp":"自分の好きな環境で、集中して働くこともできます。","furigana":"じぶんのすきなかんきょうで、しゅうちゅうしてはたらくこともできます。","romaji":"Jibun no suki na kankyou de, shuuchuu shite hataraku koto mo dekimasu.","id":"Kita juga bisa bekerja dengan fokus di lingkungan yang kita sukai."},
   {"jp":"家族と過ごす時間が増えるのも、いい点です。","furigana":"かぞくとすごすじかんがふえるのも、いいてんです。","romaji":"Kazoku to sugosu jikan ga fueru no mo, ii ten desu.","id":"Bertambahnya waktu bersama keluarga juga sisi positifnya."},
   {"jp":"一方で、デメリットもあります。","furigana":"いっぽうで、デメリットもあります。","romaji":"Ippou de, demeritto mo arimasu.","id":"Di sisi lain, ada juga kekurangannya."},
   {"jp":"家にいると、仕事とプライベートの区別が難しくなります。","furigana":"いえにいると、しごととプライベートのくべつがむずかしくなります。","romaji":"Ie ni iru to, shigoto to puraibeeto no kubetsu ga muzukashiku narimasu.","id":"Saat di rumah, membedakan kerja dan kehidupan pribadi jadi sulit."},
   {"jp":"一人で作業するので、孤独を感じることもあります。","furigana":"ひとりでさぎょうするので、こどくをかんじることもあります。","romaji":"Hitori de sagyou suru node, kodoku o kanjiru koto mo arimasu.","id":"Karena bekerja sendiri, kadang merasa kesepian."},
   {"jp":"同僚と直接会えないため、連絡が取りにくいこともあります。","furigana":"どうりょうとちょくせつあえないため、れんらくがとりにくいこともあります。","romaji":"Douryou to chokusetsu aenai tame, renraku ga torinikui koto mo arimasu.","id":"Karena tak bisa bertemu rekan langsung, kadang sulit berkomunikasi."},
   {"jp":"在宅勤務をうまく続けるには、自己管理が必要です。","furigana":"ざいたくきんむをうまくつづけるには、じこかんりがひつようです。","romaji":"Zaitaku kinmu o umaku tsuzukeru ni wa, jiko kanri ga hitsuyou desu.","id":"Untuk berhasil terus bekerja dari rumah, dibutuhkan manajemen diri."},
   {"jp":"仕事の時間と休む時間を、しっかり分けることが大切です。","furigana":"しごとのじかんとやすむじかんを、しっかりわけることがたいせつです。","romaji":"Shigoto no jikan to yasumu jikan o, shikkari wakeru koto ga taisetsu desu.","id":"Penting untuk membedakan jelas waktu kerja dan waktu istirahat."},
   {"jp":"これからは、働き方がもっと多様になっていくでしょう。","furigana":"これからは、はたらきかたがもっとたようになっていくでしょう。","romaji":"Korekara wa, hatarakikata ga motto tayou ni natte iku deshou.","id":"Ke depan, cara bekerja akan semakin beragam."}
 ]'::jsonb,
 '[
   {"word":"在宅勤務","reading":"ざいたくきんむ","romaji":"zaitaku kinmu","meaning":"kerja dari rumah"},
   {"word":"発達","reading":"はったつ","romaji":"hattatsu","meaning":"perkembangan"},
   {"word":"メリット","reading":"メリット","romaji":"meritto","meaning":"kelebihan"},
   {"word":"通勤","reading":"つうきん","romaji":"tsuukin","meaning":"perjalanan ke tempat kerja"},
   {"word":"有効","reading":"ゆうこう","romaji":"yuukou","meaning":"efektif/berguna"},
   {"word":"満員電車","reading":"まんいんでんしゃ","romaji":"man-in densha","meaning":"kereta penuh sesak"},
   {"word":"解放","reading":"かいほう","romaji":"kaihou","meaning":"terbebas/pembebasan"},
   {"word":"環境","reading":"かんきょう","romaji":"kankyou","meaning":"lingkungan"},
   {"word":"集中","reading":"しゅうちゅう","romaji":"shuuchuu","meaning":"konsentrasi"},
   {"word":"デメリット","reading":"デメリット","romaji":"demeritto","meaning":"kekurangan"},
   {"word":"区別","reading":"くべつ","romaji":"kubetsu","meaning":"pembedaan/batas"},
   {"word":"孤独","reading":"こどく","romaji":"kodoku","meaning":"kesepian/kesendirian"},
   {"word":"同僚","reading":"どうりょう","romaji":"douryou","meaning":"rekan kerja"},
   {"word":"自己管理","reading":"じこかんり","romaji":"jiko kanri","meaning":"manajemen diri"},
   {"word":"多様","reading":"たよう","romaji":"tayou","meaning":"beragam"}
 ]'::jsonb,
 '[
   {"q":"Apa yang meningkat akhir-akhir ini?","options":["Pengangguran","Orang yang bekerja dari rumah","Orang pindah ke desa","Jumlah pelancong"],"answer":1,"explanation":"「在宅勤務をする人が増えています」."},
   {"q":"Berkat apa orang bisa bekerja di rumah?","options":["Mobil","Perkembangan internet","Kereta cepat","Robot"],"answer":1,"explanation":"「インターネットの発達で」."},
   {"q":"Kelebihan: tidak perlu waktu apa?","options":["Makan","Komuting (perjalanan kerja)","Tidur","Rapat"],"answer":1,"explanation":"「通勤の時間が要らない」."},
   {"q":"Kekurangan: apa yang jadi sulit?","options":["Makan","Membedakan kerja dan kehidupan pribadi","Tidur","Belanja"],"answer":1,"explanation":"「仕事とプライベートの区別が難しく」."},
   {"q":"Perasaan apa yang bisa muncul saat bekerja sendiri?","options":["Selalu senang","Kesepian","Lapar","Marah"],"answer":1,"explanation":"「孤独を感じることもあります」."},
   {"q":"Agar berhasil kerja dari rumah, apa yang dibutuhkan?","options":["Banyak uang","Manajemen diri","Mobil","Banyak rekan"],"answer":1,"explanation":"「自己管理が必要です」."}
 ]'::jsonb,
 false),
(3, 14, '食文化の違い — Perbedaan Budaya Kuliner',
 '世界には、国によってさまざまな食文化があります。食べ物は、その国の気候や歴史と深い関係があります。例えば、日本では米を主食としています。一方、ヨーロッパではパンがよく食べられています。暑い国では、辛い料理が多い傾向があります。辛い物を食べると汗をかき、体温が下がるからです。宗教によって、食べられない物がある場合もあります。食事のマナーも、国によって大きく異なります。日本では箸を使いますが、手で食べる文化もあります。どの食べ方が正しいということはありません。海外旅行をすると、新しい味に出会えます。最初は驚いても、慣れると好きになることが多いです。食文化を知ることは、その国を理解する第一歩です。違いを楽しむ気持ちが、大切だと思います。',
 '[
   {"jp":"世界には、国によってさまざまな食文化があります。","furigana":"せかいには、くにによってさまざまなしょくぶんかがあります。","romaji":"Sekai ni wa, kuni ni yotte samazama na shokubunka ga arimasu.","id":"Di dunia, terdapat beragam budaya kuliner menurut negaranya."},
   {"jp":"食べ物は、その国の気候や歴史と深い関係があります。","furigana":"たべものは、そのくにのきこうやれきしとふかいかんけいがあります。","romaji":"Tabemono wa, sono kuni no kikou ya rekishi to fukai kankei ga arimasu.","id":"Makanan punya hubungan erat dengan iklim dan sejarah negaranya."},
   {"jp":"例えば、日本では米を主食としています。","furigana":"たとえば、にほんではこめをしゅしょくとしています。","romaji":"Tatoeba, nihon de wa kome o shushoku to shite imasu.","id":"Misalnya, di Jepang nasi dijadikan makanan pokok."},
   {"jp":"一方、ヨーロッパではパンがよく食べられています。","furigana":"いっぽう、ヨーロッパではパンがよくたべられています。","romaji":"Ippou, yooroppa de wa pan ga yoku taberarete imasu.","id":"Di sisi lain, di Eropa roti sering dimakan."},
   {"jp":"暑い国では、辛い料理が多い傾向があります。","furigana":"あついくにでは、からいりょうりがおおいけいこうがあります。","romaji":"Atsui kuni de wa, karai ryouri ga ooi keikou ga arimasu.","id":"Di negara panas, ada kecenderungan banyak masakan pedas."},
   {"jp":"辛い物を食べると汗をかき、体温が下がるからです。","furigana":"からいものをたべるとあせをかき、たいおんがさがるからです。","romaji":"Karai mono o taberu to ase o kaki, taion ga sagaru kara desu.","id":"Sebab makan pedas membuat berkeringat sehingga suhu tubuh turun."},
   {"jp":"宗教によって、食べられない物がある場合もあります。","furigana":"しゅうきょうによって、たべられないものがあるばあいもあります。","romaji":"Shuukyou ni yotte, taberarenai mono ga aru baai mo arimasu.","id":"Tergantung agama, ada kalanya terdapat makanan yang tidak boleh dimakan."},
   {"jp":"食事のマナーも、国によって大きく異なります。","furigana":"しょくじのマナーも、くにによっておおきくことなります。","romaji":"Shokuji no manaa mo, kuni ni yotte ookiku kotonarimasu.","id":"Etika makan pun sangat berbeda menurut negaranya."},
   {"jp":"日本では箸を使いますが、手で食べる文化もあります。","furigana":"にほんでははしをつかいますが、てでたべるぶんかもあります。","romaji":"Nihon de wa hashi o tsukaimasu ga, te de taberu bunka mo arimasu.","id":"Di Jepang memakai sumpit, tapi ada juga budaya makan dengan tangan."},
   {"jp":"どの食べ方が正しいということはありません。","furigana":"どのたべかたがただしいということはありません。","romaji":"Dono tabekata ga tadashii to iu koto wa arimasen.","id":"Tidak ada cara makan yang dianggap paling benar."},
   {"jp":"海外旅行をすると、新しい味に出会えます。","furigana":"かいがいりょこうをすると、あたらしいあじにであえます。","romaji":"Kaigai ryokou o suru to, atarashii aji ni deaemasu.","id":"Saat bepergian ke luar negeri, kita bisa menemukan rasa baru."},
   {"jp":"最初は驚いても、慣れると好きになることが多いです。","furigana":"さいしょはおどろいても、なれるとすきになることがおおいです。","romaji":"Saisho wa odoroite mo, nareru to suki ni naru koto ga ooi desu.","id":"Meski awalnya terkejut, sering kali jadi suka setelah terbiasa."},
   {"jp":"食文化を知ることは、その国を理解する第一歩です。","furigana":"しょくぶんかをしることは、そのくにをりかいするだいいっぽです。","romaji":"Shokubunka o shiru koto wa, sono kuni o rikai suru daiippo desu.","id":"Mengenal budaya kuliner adalah langkah pertama memahami negara itu."},
   {"jp":"違いを楽しむ気持ちが、大切だと思います。","furigana":"ちがいをたのしむきもちが、たいせつだとおもいます。","romaji":"Chigai o tanoshimu kimochi ga, taisetsu da to omoimasu.","id":"Sikap menikmati perbedaan itu penting menurutku."}
 ]'::jsonb,
 '[
   {"word":"食文化","reading":"しょくぶんか","romaji":"shokubunka","meaning":"budaya kuliner"},
   {"word":"気候","reading":"きこう","romaji":"kikou","meaning":"iklim"},
   {"word":"歴史","reading":"れきし","romaji":"rekishi","meaning":"sejarah"},
   {"word":"主食","reading":"しゅしょく","romaji":"shushoku","meaning":"makanan pokok"},
   {"word":"傾向","reading":"けいこう","romaji":"keikou","meaning":"kecenderungan"},
   {"word":"汗をかく","reading":"あせをかく","romaji":"ase o kaku","meaning":"berkeringat"},
   {"word":"体温","reading":"たいおん","romaji":"taion","meaning":"suhu tubuh"},
   {"word":"宗教","reading":"しゅうきょう","romaji":"shuukyou","meaning":"agama"},
   {"word":"場合","reading":"ばあい","romaji":"baai","meaning":"kasus/situasi"},
   {"word":"異なる","reading":"ことなる","romaji":"kotonaru","meaning":"berbeda"},
   {"word":"箸","reading":"はし","romaji":"hashi","meaning":"sumpit"},
   {"word":"出会う","reading":"であう","romaji":"deau","meaning":"bertemu/menemukan"},
   {"word":"驚く","reading":"おどろく","romaji":"odoroku","meaning":"terkejut"},
   {"word":"理解","reading":"りかい","romaji":"rikai","meaning":"memahami"},
   {"word":"第一歩","reading":"だいいっぽ","romaji":"daiippo","meaning":"langkah pertama"}
 ]'::jsonb,
 '[
   {"q":"Makanan berkaitan erat dengan apa?","options":["Politik","Iklim dan sejarah negara","Olahraga","Bahasa"],"answer":1,"explanation":"「気候や歴史と深い関係」."},
   {"q":"Apa makanan pokok Jepang?","options":["Roti","Nasi/beras","Mie","Kentang"],"answer":1,"explanation":"「日本では米を主食」."},
   {"q":"Di negara panas, banyak masakan jenis apa?","options":["Manis","Pedas","Asam","Asin"],"answer":1,"explanation":"「辛い料理が多い傾向」."},
   {"q":"Kenapa makanan pedas dimakan di negara panas?","options":["Lebih murah","Berkeringat menurunkan suhu tubuh","Lebih awet","Hanya tradisi"],"answer":1,"explanation":"「汗をかき、体温が下がるから」."},
   {"q":"Apa yang kadang membatasi makanan?","options":["Cuaca","Agama","Harga","Usia"],"answer":1,"explanation":"「宗教によって、食べられない物がある」."},
   {"q":"Mengenal budaya kuliner adalah?","options":["Buang waktu","Langkah pertama memahami negara itu","Hal sepele","Untuk turis saja"],"answer":1,"explanation":"「その国を理解する第一歩」."}
 ]'::jsonb,
 false),
(3, 15, '運動の習慣 — Kebiasaan Berolahraga',
 '運動は、体だけでなく心にもいい影響を与えます。私は一年前から、運動する習慣を身につけました。きっかけは、健康診断で医者に注意されたことです。最初は、近所を軽く散歩することから始めました。慣れてきたら、少しずつ走る距離を伸ばしました。今では、週に三回ジョギングをしています。運動をすると、夜よく眠れるようになりました。体が軽くなり、風邪もひきにくくなりました。それに、運動はストレス解消にも効果があります。汗をかいた後は、気分がとてもすっきりします。続けるためには、無理をしないことが大切です。友だちと一緒にやると、楽しく続けられます。運動の習慣は、一生の宝物になると思います。これからも、健康のために運動を続けたいです。',
 '[
   {"jp":"運動は、体だけでなく心にもいい影響を与えます。","furigana":"うんどうは、からだだけでなくこころにもいいえいきょうをあたえます。","romaji":"Undou wa, karada dake de naku kokoro ni mo ii eikyou o ataemasu.","id":"Olahraga memberi pengaruh baik tidak hanya pada tubuh, tapi juga pada hati."},
   {"jp":"私は一年前から、運動する習慣を身につけました。","furigana":"わたしはいちねんまえから、うんどうするしゅうかんをみにつけました。","romaji":"Watashi wa ichinen mae kara, undou suru shuukan o mi ni tsukemashita.","id":"Sejak setahun lalu, aku membiasakan diri berolahraga."},
   {"jp":"きっかけは、健康診断で医者に注意されたことです。","furigana":"きっかけは、けんこうしんだんでいしゃにちゅういされたことです。","romaji":"Kikkake wa, kenkou shindan de isha ni chuui sareta koto desu.","id":"Pemicunya adalah ditegur dokter saat pemeriksaan kesehatan."},
   {"jp":"最初は、近所を軽く散歩することから始めました。","furigana":"さいしょは、きんじょをかるくさんぽすることからはじめました。","romaji":"Saisho wa, kinjo o karuku sanpo suru koto kara hajimemashita.","id":"Awalnya aku mulai dari jalan santai ringan di sekitar rumah."},
   {"jp":"慣れてきたら、少しずつ走る距離を伸ばしました。","furigana":"なれてきたら、すこしずつはしるきょりをのばしました。","romaji":"Narete kitara, sukoshi zutsu hashiru kyori o nobashimashita.","id":"Setelah terbiasa, aku perlahan menambah jarak lari."},
   {"jp":"今では、週に三回ジョギングをしています。","furigana":"いまでは、しゅうにさんかいジョギングをしています。","romaji":"Ima de wa, shuu ni sankai jogingu o shite imasu.","id":"Sekarang aku jogging tiga kali seminggu."},
   {"jp":"運動をすると、夜よく眠れるようになりました。","furigana":"うんどうをすると、よるよくねむれるようになりました。","romaji":"Undou o suru to, yoru yoku nemureru you ni narimashita.","id":"Dengan berolahraga, aku jadi bisa tidur nyenyak di malam hari."},
   {"jp":"体が軽くなり、風邪もひきにくくなりました。","furigana":"からだがかるくなり、かぜもひきにくくなりました。","romaji":"Karada ga karuku nari, kaze mo hikinikuku narimashita.","id":"Badan jadi ringan dan tidak mudah masuk angin."},
   {"jp":"それに、運動はストレス解消にも効果があります。","furigana":"それに、うんどうはストレスかいしょうにもこうかがあります。","romaji":"Soreni, undou wa sutoresu kaishou ni mo kouka ga arimasu.","id":"Lagi pula, olahraga juga efektif untuk melepas stres."},
   {"jp":"汗をかいた後は、気分がとてもすっきりします。","furigana":"あせをかいたあとは、きぶんがとてもすっきりします。","romaji":"Ase o kaita ato wa, kibun ga totemo sukkiri shimasu.","id":"Setelah berkeringat, perasaan jadi sangat segar."},
   {"jp":"続けるためには、無理をしないことが大切です。","furigana":"つづけるためには、むりをしないことがたいせつです。","romaji":"Tsuzukeru tame ni wa, muri o shinai koto ga taisetsu desu.","id":"Untuk bisa terus, penting agar tidak memaksakan diri."},
   {"jp":"友だちと一緒にやると、楽しく続けられます。","furigana":"ともだちといっしょにやると、たのしくつづけられます。","romaji":"Tomodachi to issho ni yaru to, tanoshiku tsuzukeraremasu.","id":"Kalau dilakukan bersama teman, bisa diteruskan dengan menyenangkan."},
   {"jp":"運動の習慣は、一生の宝物になると思います。","furigana":"うんどうのしゅうかんは、いっしょうのたからものになるとおもいます。","romaji":"Undou no shuukan wa, isshou no takaramono ni naru to omoimasu.","id":"Kebiasaan berolahraga akan menjadi harta seumur hidup menurutku."},
   {"jp":"これからも、健康のために運動を続けたいです。","furigana":"これからも、けんこうのためにうんどうをつづけたいです。","romaji":"Korekara mo, kenkou no tame ni undou o tsuzuketai desu.","id":"Ke depan pun, aku ingin terus berolahraga demi kesehatan."}
 ]'::jsonb,
 '[
   {"word":"運動","reading":"うんどう","romaji":"undou","meaning":"olahraga"},
   {"word":"影響","reading":"えいきょう","romaji":"eikyou","meaning":"pengaruh"},
   {"word":"身につける","reading":"みにつける","romaji":"mi ni tsukeru","meaning":"membiasakan/menguasai"},
   {"word":"きっかけ","reading":"きっかけ","romaji":"kikkake","meaning":"pemicu/awal mula"},
   {"word":"健康診断","reading":"けんこうしんだん","romaji":"kenkou shindan","meaning":"pemeriksaan kesehatan"},
   {"word":"医者","reading":"いしゃ","romaji":"isha","meaning":"dokter"},
   {"word":"距離","reading":"きょり","romaji":"kyori","meaning":"jarak"},
   {"word":"伸ばす","reading":"のばす","romaji":"nobasu","meaning":"memperpanjang/menambah"},
   {"word":"眠れる","reading":"ねむれる","romaji":"nemureru","meaning":"bisa tidur"},
   {"word":"風邪をひく","reading":"かぜをひく","romaji":"kaze o hiku","meaning":"masuk angin"},
   {"word":"ストレス解消","reading":"ストレスかいしょう","romaji":"sutoresu kaishou","meaning":"pelepasan stres"},
   {"word":"効果","reading":"こうか","romaji":"kouka","meaning":"efek/khasiat"},
   {"word":"すっきり","reading":"すっきり","romaji":"sukkiri","meaning":"segar/lega"},
   {"word":"無理","reading":"むり","romaji":"muri","meaning":"memaksakan diri"},
   {"word":"宝物","reading":"たからもの","romaji":"takaramono","meaning":"harta berharga"}
 ]'::jsonb,
 '[
   {"q":"Olahraga berpengaruh baik pada apa?","options":["Hanya tubuh","Tubuh dan hati","Hanya pikiran","Hanya berat badan"],"answer":1,"explanation":"「体だけでなく心にもいい影響」."},
   {"q":"Apa pemicu penulis mulai berolahraga?","options":["Ajakan teman","Ditegur dokter saat cek kesehatan","Menonton TV","Ikut lomba"],"answer":1,"explanation":"「健康診断で医者に注意された」."},
   {"q":"Penulis mulai dari apa?","options":["Lari jarak jauh","Jalan santai ringan di sekitar rumah","Angkat beban","Renang"],"answer":1,"explanation":"「近所を軽く散歩することから」."},
   {"q":"Sekarang berapa kali jogging seminggu?","options":["Sekali","Dua kali","Tiga kali","Setiap hari"],"answer":2,"explanation":"「週に三回ジョギング」."},
   {"q":"Apa manfaat setelah rutin berolahraga?","options":["Lebih boros","Bisa tidur lebih nyenyak","Lebih lapar","Lebih malas"],"answer":1,"explanation":"「夜よく眠れるようになりました」."},
   {"q":"Agar bisa terus, apa yang penting?","options":["Latihan berat","Tidak memaksakan diri","Sendirian saja","Cepat-cepat"],"answer":1,"explanation":"「無理をしないことが大切」."}
 ]'::jsonb,
 false);
