-- ============================================================
-- Koto no Ha — Seed Dokkai N2 (level_id=4) TAMBAHAN: 10 bacaan (order_index 6-15).
-- ~500-600 huruf, 16 kalimat. Tema sosial/abstrak. 15 kosakata + 6 soal per bacaan.
-- Hanya INSERT (tidak menghapus bacaan lama).
-- ============================================================
INSERT INTO public.dokkai_passages (level_id, order_index, title, text_content, content_json, vocab_notes, questions, is_premium) VALUES
(4, 6, '観光公害 — Overtourism',
 '近年、日本を訪れる外国人観光客が急激に増えています。観光は地域の経済にとって、大きな利益をもたらします。しかし、観光客が増えすぎることで、さまざまな問題も生じています。これは「観光公害」と呼ばれています。例えば、有名な観光地では、道路や電車が非常に混雑します。ゴミのポイ捨てやマナー違反も、地元の人々を悩ませています。静かな住宅街に観光客が入り込み、騒音が問題になることもあります。一部の地域では、住民の生活が脅かされていると言われています。また、宿泊施設の不足や、物価の上昇も起きています。こうした問題を解決するために、各地でさまざまな対策が取られています。例えば、観光客の数を制限したり、入場料を設けたりしています。観光客にマナーを守ってもらうための呼びかけも行われています。観光地を守りながら、経済の利益も保つのは簡単ではありません。地元の人と観光客の双方が、満足できる方法が求められています。持続可能な観光の在り方を、真剣に考える必要があります。観光の魅力を未来に残すために、私たち一人一人の意識が大切です。',
 '[
   {"jp":"近年、日本を訪れる外国人観光客が急激に増えています。","furigana":"きんねん、にほんをおとずれるがいこくじんかんこうきゃくがきゅうげきにふえています。","romaji":"Kinnen, nihon o otozureru gaikokujin kankoukyaku ga kyuugeki ni fuete imasu.","id":"Beberapa tahun terakhir, wisatawan asing yang mengunjungi Jepang meningkat drastis."},
   {"jp":"観光は地域の経済にとって、大きな利益をもたらします。","furigana":"かんこうはちいきのけいざいにとって、おおきなりえきをもたらします。","romaji":"Kankou wa chiiki no keizai ni totte, ooki na rieki o motarashimasu.","id":"Pariwisata membawa keuntungan besar bagi ekonomi daerah."},
   {"jp":"しかし、観光客が増えすぎることで、さまざまな問題も生じています。","furigana":"しかし、かんこうきゃくがふえすぎることで、さまざまなもんだいもしょうじています。","romaji":"Shikashi, kankoukyaku ga fuesugiru koto de, samazama na mondai mo shoujite imasu.","id":"Namun, karena turis bertambah terlalu banyak, berbagai masalah pun timbul."},
   {"jp":"これは「観光公害」と呼ばれています。","furigana":"これは「かんこうこうがい」とよばれています。","romaji":"Kore wa \"kankou kougai\" to yobarete imasu.","id":"Hal ini disebut overtourism (kankou kougai)."},
   {"jp":"例えば、有名な観光地では、道路や電車が非常に混雑します。","furigana":"たとえば、ゆうめいなかんこうちでは、どうろやでんしゃがひじょうにこんざつします。","romaji":"Tatoeba, yuumei na kankouchi de wa, douro ya densha ga hijou ni konzatsu shimasu.","id":"Misalnya, di objek wisata terkenal, jalan dan kereta menjadi sangat padat."},
   {"jp":"ゴミのポイ捨てやマナー違反も、地元の人々を悩ませています。","furigana":"ゴミのポイすてやマナーいはんも、じもとのひとびとをなやませています。","romaji":"Gomi no poisute ya manaa ihan mo, jimoto no hitobito o nayamasete imasu.","id":"Membuang sampah sembarangan dan pelanggaran etika juga merisaukan warga lokal."},
   {"jp":"静かな住宅街に観光客が入り込み、騒音が問題になることもあります。","furigana":"しずかなじゅうたくがいにかんこうきゃくがはいりこみ、そうおんがもんだいになることもあります。","romaji":"Shizuka na juutakugai ni kankoukyaku ga hairikomi, souon ga mondai ni naru koto mo arimasu.","id":"Turis masuk ke permukiman yang tenang, dan kebisingan pun jadi masalah."},
   {"jp":"一部の地域では、住民の生活が脅かされていると言われています。","furigana":"いちぶのちいきでは、じゅうみんのせいかつがおびやかされているといわれています。","romaji":"Ichibu no chiiki de wa, juumin no seikatsu ga obiyakasarete iru to iwarete imasu.","id":"Di sebagian daerah, dikatakan kehidupan warga menjadi terancam."},
   {"jp":"また、宿泊施設の不足や、物価の上昇も起きています。","furigana":"また、しゅくはくしせつのふそくや、ぶっかのじょうしょうもおきています。","romaji":"Mata, shukuhaku shisetsu no fusoku ya, bukka no joushou mo okite imasu.","id":"Selain itu, kekurangan akomodasi dan kenaikan harga juga terjadi."},
   {"jp":"こうした問題を解決するために、各地でさまざまな対策が取られています。","furigana":"こうしたもんだいをかいけつするために、かくちでさまざまなたいさくがとられています。","romaji":"Koushita mondai o kaiketsu suru tame ni, kakuchi de samazama na taisaku ga torarete imasu.","id":"Untuk menyelesaikan masalah ini, berbagai langkah diambil di berbagai tempat."},
   {"jp":"例えば、観光客の数を制限したり、入場料を設けたりしています。","furigana":"たとえば、かんこうきゃくのかずをせいげんしたり、にゅうじょうりょうをもうけたりしています。","romaji":"Tatoeba, kankoukyaku no kazu o seigen shitari, nyuujouryou o mouketari shite imasu.","id":"Misalnya, membatasi jumlah turis atau menetapkan tiket masuk."},
   {"jp":"観光客にマナーを守ってもらうための呼びかけも行われています。","furigana":"かんこうきゃくにマナーをまもってもらうためのよびかけもおこなわれています。","romaji":"Kankoukyaku ni manaa o mamotte morau tame no yobikake mo okonawarete imasu.","id":"Imbauan agar turis menjaga etika pun dilakukan."},
   {"jp":"観光地を守りながら、経済の利益も保つのは簡単ではありません。","furigana":"かんこうちをまもりながら、けいざいのりえきもたもつのはかんたんではありません。","romaji":"Kankouchi o mamorinagara, keizai no rieki mo tamotsu no wa kantan de wa arimasen.","id":"Menjaga objek wisata sambil mempertahankan keuntungan ekonomi tidaklah mudah."},
   {"jp":"地元の人と観光客の双方が、満足できる方法が求められています。","furigana":"じもとのひととかんこうきゃくのそうほうが、まんぞくできるほうほうがもとめられています。","romaji":"Jimoto no hito to kankoukyaku no souhou ga, manzoku dekiru houhou ga motomerarete imasu.","id":"Dibutuhkan cara yang dapat memuaskan warga lokal maupun turis."},
   {"jp":"持続可能な観光の在り方を、真剣に考える必要があります。","furigana":"じぞくかのうなかんこうのありかたを、しんけんにかんがえるひつようがあります。","romaji":"Jizoku kanou na kankou no arikata o, shinken ni kangaeru hitsuyou ga arimasu.","id":"Kita perlu memikirkan secara serius bentuk pariwisata yang berkelanjutan."},
   {"jp":"観光の魅力を未来に残すために、私たち一人一人の意識が大切です。","furigana":"かんこうのみりょくをみらいにのこすために、わたしたちひとりひとりのいしきがたいせつです。","romaji":"Kankou no miryoku o mirai ni nokosu tame ni, watashitachi hitori hitori no ishiki ga taisetsu desu.","id":"Untuk mewariskan daya tarik wisata ke masa depan, kesadaran tiap orang penting."}
 ]'::jsonb,
 '[
   {"word":"観光客","reading":"かんこうきゃく","romaji":"kankoukyaku","meaning":"wisatawan"},
   {"word":"急激に","reading":"きゅうげきに","romaji":"kyuugeki ni","meaning":"drastis/mendadak"},
   {"word":"利益","reading":"りえき","romaji":"rieki","meaning":"keuntungan"},
   {"word":"生じる","reading":"しょうじる","romaji":"shoujiru","meaning":"timbul/muncul"},
   {"word":"公害","reading":"こうがい","romaji":"kougai","meaning":"pencemaran/dampak buruk"},
   {"word":"混雑","reading":"こんざつ","romaji":"konzatsu","meaning":"kepadatan/keramaian"},
   {"word":"ポイ捨て","reading":"ポイすて","romaji":"poisute","meaning":"membuang sampah sembarangan"},
   {"word":"悩ます","reading":"なやます","romaji":"nayamasu","meaning":"merisaukan/mengganggu"},
   {"word":"騒音","reading":"そうおん","romaji":"souon","meaning":"kebisingan"},
   {"word":"脅かす","reading":"おびやかす","romaji":"obiyakasu","meaning":"mengancam"},
   {"word":"宿泊施設","reading":"しゅくはくしせつ","romaji":"shukuhaku shisetsu","meaning":"akomodasi/penginapan"},
   {"word":"制限","reading":"せいげん","romaji":"seigen","meaning":"pembatasan"},
   {"word":"対策","reading":"たいさく","romaji":"taisaku","meaning":"langkah penanggulangan"},
   {"word":"持続可能","reading":"じぞくかのう","romaji":"jizoku kanou","meaning":"berkelanjutan"},
   {"word":"意識","reading":"いしき","romaji":"ishiki","meaning":"kesadaran"}
 ]'::jsonb,
 '[
   {"q":"Apa yang meningkat drastis belakangan ini?","options":["Penduduk lokal","Wisatawan asing","Mahasiswa","Pekerja pabrik"],"answer":1,"explanation":"「外国人観光客が急激に増えています」."},
   {"q":"Apa nama masalah akibat terlalu banyak turis?","options":["Polusi udara","Overtourism (観光公害)","Inflasi","Pengangguran"],"answer":1,"explanation":"「これは『観光公害』と呼ばれています」."},
   {"q":"Masalah apa yang muncul di kawasan permukiman tenang?","options":["Banjir","Kebisingan","Kebakaran","Kekeringan"],"answer":1,"explanation":"「騒音が問題になることもあります」."},
   {"q":"Selain itu, apa lagi yang terjadi?","options":["Harga turun","Kekurangan penginapan dan kenaikan harga","Banyak pengangguran","Kekurangan air"],"answer":1,"explanation":"「宿泊施設の不足や、物価の上昇」."},
   {"q":"Apa contoh langkah penanggulangan?","options":["Menggratiskan semuanya","Membatasi jumlah turis dan menetapkan tiket masuk","Melarang foto","Menutup kota"],"answer":1,"explanation":"「観光客の数を制限したり、入場料を設けたり」."},
   {"q":"Apa yang perlu dipikirkan secara serius?","options":["Menambah turis tanpa batas","Bentuk pariwisata berkelanjutan","Menutup objek wisata","Menaikkan pajak"],"answer":1,"explanation":"「持続可能な観光の在り方」."}
 ]'::jsonb,
 false),
(4, 7, 'キャッシュレス社会 — Masyarakat Nontunai',
 '最近、現金を使わずに買い物をする人が増えています。クレジットカードやスマホ決済が、急速に広まっています。このような社会は「キャッシュレス社会」と呼ばれています。キャッシュレス決済には、多くのメリットがあります。まず、財布から小銭を出す手間が省けます。支払いが速くなり、レジの行列も短くなります。お金の流れがデータとして記録されるので、管理が簡単になります。お店にとっても、現金を数える作業が減るという利点があります。一方で、いくつかの課題も指摘されています。システムに障害が起きると、支払いができなくなる恐れがあります。また、高齢者の中には、操作が難しいと感じる人もいます。お金を使っている感覚が薄れ、使いすぎてしまう人もいます。個人情報が漏れる危険についても、注意が必要です。日本は他の国に比べて、キャッシュレス化が遅れていると言われています。しかし、政府もキャッシュレス化を積極的に進めています。便利さと安全性のバランスを保つことが、これからの課題です。',
 '[
   {"jp":"最近、現金を使わずに買い物をする人が増えています。","furigana":"さいきん、げんきんをつかわずにかいものをするひとがふえています。","romaji":"Saikin, genkin o tsukawazu ni kaimono o suru hito ga fuete imasu.","id":"Akhir-akhir ini, orang yang berbelanja tanpa uang tunai semakin banyak."},
   {"jp":"クレジットカードやスマホ決済が、急速に広まっています。","furigana":"クレジットカードやスマホけっさいが、きゅうそくにひろまっています。","romaji":"Kurejitto kaado ya sumaho kessai ga, kyuusoku ni hiromatte imasu.","id":"Kartu kredit dan pembayaran lewat ponsel menyebar dengan cepat."},
   {"jp":"このような社会は「キャッシュレス社会」と呼ばれています。","furigana":"このようなしゃかいは「キャッシュレスしゃかい」とよばれています。","romaji":"Kono you na shakai wa \"kyasshuresu shakai\" to yobarete imasu.","id":"Masyarakat seperti ini disebut masyarakat nontunai."},
   {"jp":"キャッシュレス決済には、多くのメリットがあります。","furigana":"キャッシュレスけっさいには、おおくのメリットがあります。","romaji":"Kyasshuresu kessai ni wa, ooku no meritto ga arimasu.","id":"Pembayaran nontunai memiliki banyak kelebihan."},
   {"jp":"まず、財布から小銭を出す手間が省けます。","furigana":"まず、さいふからこぜにをだすてまがはぶけます。","romaji":"Mazu, saifu kara kozeni o dasu tema ga habukemasu.","id":"Pertama, repot mengeluarkan uang receh dari dompet bisa dihindari."},
   {"jp":"支払いが速くなり、レジの行列も短くなります。","furigana":"しはらいがはやくなり、レジのぎょうれつもみじかくなります。","romaji":"Shiharai ga hayaku nari, reji no gyouretsu mo mijikaku narimasu.","id":"Pembayaran jadi cepat, dan antrean kasir pun memendek."},
   {"jp":"お金の流れがデータとして記録されるので、管理が簡単になります。","furigana":"おかねのながれがデータとしてきろくされるので、かんりがかんたんになります。","romaji":"Okane no nagare ga deeta to shite kiroku sareru node, kanri ga kantan ni narimasu.","id":"Karena arus uang tercatat sebagai data, pengelolaannya jadi mudah."},
   {"jp":"お店にとっても、現金を数える作業が減るという利点があります。","furigana":"おみせにとっても、げんきんをかぞえるさぎょうがへるというりてんがあります。","romaji":"Omise ni totte mo, genkin o kazoeru sagyou ga heru to iu riten ga arimasu.","id":"Bagi toko pun, ada kelebihan berkurangnya pekerjaan menghitung uang tunai."},
   {"jp":"一方で、いくつかの課題も指摘されています。","furigana":"いっぽうで、いくつかのかだいもしてきされています。","romaji":"Ippou de, ikutsuka no kadai mo shiteki sarete imasu.","id":"Di sisi lain, beberapa tantangan juga ditunjukkan."},
   {"jp":"システムに障害が起きると、支払いができなくなる恐れがあります。","furigana":"システムにしょうがいがおきると、しはらいができなくなるおそれがあります。","romaji":"Shisutemu ni shougai ga okiru to, shiharai ga dekinaku naru osore ga arimasu.","id":"Kalau sistem bermasalah, ada kemungkinan tak bisa membayar."},
   {"jp":"また、高齢者の中には、操作が難しいと感じる人もいます。","furigana":"また、こうれいしゃのなかには、そうさがむずかしいとかんじるひともいます。","romaji":"Mata, koureisha no naka ni wa, sousa ga muzukashii to kanjiru hito mo imasu.","id":"Selain itu, ada lansia yang merasa pengoperasiannya sulit."},
   {"jp":"お金を使っている感覚が薄れ、使いすぎてしまう人もいます。","furigana":"おかねをつかっているかんかくがうすれ、つかいすぎてしまうひともいます。","romaji":"Okane o tsukatte iru kankaku ga usure, tsukai sugite shimau hito mo imasu.","id":"Ada juga yang sensasi memakai uangnya memudar sehingga jadi boros."},
   {"jp":"個人情報が漏れる危険についても、注意が必要です。","furigana":"こじんじょうほうがもれるきけんについても、ちゅういがひつようです。","romaji":"Kojin jouhou ga moreru kiken ni tsuite mo, chuui ga hitsuyou desu.","id":"Perlu juga waspada terhadap risiko bocornya data pribadi."},
   {"jp":"日本は他の国に比べて、キャッシュレス化が遅れていると言われています。","furigana":"にほんはほかのくににくらべて、キャッシュレスかがおくれているといわれています。","romaji":"Nihon wa hoka no kuni ni kurabete, kyasshuresu-ka ga okurete iru to iwarete imasu.","id":"Dibanding negara lain, Jepang dikatakan tertinggal dalam nontunai."},
   {"jp":"しかし、政府もキャッシュレス化を積極的に進めています。","furigana":"しかし、せいふもキャッシュレスかをせっきょくてきにすすめています。","romaji":"Shikashi, seifu mo kyasshuresu-ka o sekkyokuteki ni susumete imasu.","id":"Namun, pemerintah pun aktif mendorong nontunai."},
   {"jp":"便利さと安全性のバランスを保つことが、これからの課題です。","furigana":"べんりさとあんぜんせいのバランスをたもつことが、これからのかだいです。","romaji":"Benrisa to anzensei no baransu o tamotsu koto ga, korekara no kadai desu.","id":"Menjaga keseimbangan kepraktisan dan keamanan adalah tantangan ke depan."}
 ]'::jsonb,
 '[
   {"word":"現金","reading":"げんきん","romaji":"genkin","meaning":"uang tunai"},
   {"word":"決済","reading":"けっさい","romaji":"kessai","meaning":"pembayaran/penyelesaian"},
   {"word":"急速に","reading":"きゅうそくに","romaji":"kyuusoku ni","meaning":"dengan cepat"},
   {"word":"広まる","reading":"ひろまる","romaji":"hiromaru","meaning":"menyebar"},
   {"word":"手間","reading":"てま","romaji":"tema","meaning":"kerepotan/usaha"},
   {"word":"省く","reading":"はぶく","romaji":"habuku","meaning":"menghemat/menghilangkan"},
   {"word":"行列","reading":"ぎょうれつ","romaji":"gyouretsu","meaning":"antrean"},
   {"word":"記録","reading":"きろく","romaji":"kiroku","meaning":"pencatatan"},
   {"word":"利点","reading":"りてん","romaji":"riten","meaning":"kelebihan"},
   {"word":"課題","reading":"かだい","romaji":"kadai","meaning":"tantangan/PR"},
   {"word":"障害","reading":"しょうがい","romaji":"shougai","meaning":"gangguan/kerusakan"},
   {"word":"操作","reading":"そうさ","romaji":"sousa","meaning":"pengoperasian"},
   {"word":"感覚","reading":"かんかく","romaji":"kankaku","meaning":"sensasi/perasaan"},
   {"word":"個人情報","reading":"こじんじょうほう","romaji":"kojin jouhou","meaning":"data pribadi"},
   {"word":"漏れる","reading":"もれる","romaji":"moreru","meaning":"bocor"}
 ]'::jsonb,
 '[
   {"q":"Apa yang menyebar dengan cepat?","options":["Uang tunai","Kartu kredit dan pembayaran ponsel","Cek","Emas"],"answer":1,"explanation":"「クレジットカードやスマホ決済が、急速に広まっています」."},
   {"q":"Kelebihan: apa yang dihemat?","options":["Waktu tidur","Repot mengeluarkan uang receh","Pajak","Listrik"],"answer":1,"explanation":"「小銭を出す手間が省けます」."},
   {"q":"Bagi toko, apa keuntungannya?","options":["Lebih banyak pelanggan","Pekerjaan menghitung uang tunai berkurang","Pajak turun","Sewa murah"],"answer":1,"explanation":"「現金を数える作業が減る」."},
   {"q":"Apa risiko bila sistem bermasalah?","options":["Harga naik","Tidak bisa membayar","Toko tutup","Uang fisik hilang"],"answer":1,"explanation":"「支払いができなくなる恐れ」."},
   {"q":"Siapa yang merasa pengoperasiannya sulit?","options":["Anak-anak","Sebagian lansia","Turis","Pelajar"],"answer":1,"explanation":"「高齢者の中には、操作が難しいと感じる人も」."},
   {"q":"Dibanding negara lain, bagaimana kondisi Jepang?","options":["Paling maju","Tertinggal dalam nontunai","Sama saja","Menolak nontunai"],"answer":1,"explanation":"「キャッシュレス化が遅れていると言われています」."}
 ]'::jsonb,
 false),
(4, 8, '地球温暖化 — Pemanasan Global',
 '地球温暖化は、現代の世界が直面する最も深刻な問題の一つです。産業の発展とともに、二酸化炭素の排出量が増え続けています。その結果、地球全体の平均気温が少しずつ上昇しています。温暖化は、さまざまな形で私たちの生活に影響を与えています。例えば、夏の暑さが年々厳しくなっています。大雨や台風などの異常気象も、増えていると言われています。氷河が溶けることで、海面が上昇し、低い土地が水没する恐れがあります。また、動物や植物の生息環境も、大きく変化しています。温暖化を止めるためには、世界中の国々の協力が欠かせません。各国は、二酸化炭素の排出を減らす目標を立てています。再生可能エネルギーへの転換も、急がれています。私たち一人一人にも、できることがたくさんあります。電気を無駄に使わない、ゴミを減らすなどの小さな努力が大切です。公共交通機関を利用することも、効果的な方法の一つです。未来の世代に美しい地球を残すのは、今を生きる私たちの責任です。手遅れになる前に、行動を起こさなければなりません。',
 '[
   {"jp":"地球温暖化は、現代の世界が直面する最も深刻な問題の一つです。","furigana":"ちきゅうおんだんかは、げんだいのせかいがちょくめんするもっともしんこくなもんだいのひとつです。","romaji":"Chikyuu ondanka wa, gendai no sekai ga chokumen suru mottomo shinkoku na mondai no hitotsu desu.","id":"Pemanasan global adalah salah satu masalah paling serius yang dihadapi dunia modern."},
   {"jp":"産業の発展とともに、二酸化炭素の排出量が増え続けています。","furigana":"さんぎょうのはってんとともに、にさんかたんそのはいしゅつりょうがふえつづけています。","romaji":"Sangyou no hatten to tomo ni, nisanka tanso no haishutsuryou ga fuetsuzukete imasu.","id":"Seiring perkembangan industri, jumlah emisi karbon dioksida terus bertambah."},
   {"jp":"その結果、地球全体の平均気温が少しずつ上昇しています。","furigana":"そのけっか、ちきゅうぜんたいのへいきんきおんがすこしずつじょうしょうしています。","romaji":"Sono kekka, chikyuu zentai no heikin kion ga sukoshi zutsu joushou shite imasu.","id":"Akibatnya, suhu rata-rata seluruh bumi naik sedikit demi sedikit."},
   {"jp":"温暖化は、さまざまな形で私たちの生活に影響を与えています。","furigana":"おんだんかは、さまざまなかたちでわたしたちのせいかつにえいきょうをあたえています。","romaji":"Ondanka wa, samazama na katachi de watashitachi no seikatsu ni eikyou o ataete imasu.","id":"Pemanasan memberi pengaruh pada hidup kita dalam berbagai bentuk."},
   {"jp":"例えば、夏の暑さが年々厳しくなっています。","furigana":"たとえば、なつのあつさがねんねんきびしくなっています。","romaji":"Tatoeba, natsu no atsusa ga nennen kibishiku natte imasu.","id":"Misalnya, panas musim panas makin parah dari tahun ke tahun."},
   {"jp":"大雨や台風などの異常気象も、増えていると言われています。","furigana":"おおあめやたいふうなどのいじょうきしょうも、ふえているといわれています。","romaji":"Ooame ya taifuu nado no ijou kishou mo, fuete iru to iwarete imasu.","id":"Cuaca ekstrem seperti hujan deras dan topan pun dikatakan bertambah."},
   {"jp":"氷河が溶けることで、海面が上昇し、低い土地が水没する恐れがあります。","furigana":"ひょうががとけることで、かいめんがじょうしょうし、ひくいとちがすいぼつするおそれがあります。","romaji":"Hyouga ga tokeru koto de, kaimen ga joushou shi, hikui tochi ga suibotsu suru osore ga arimasu.","id":"Mencairnya gletser membuat permukaan laut naik, dan daratan rendah berisiko tenggelam."},
   {"jp":"また、動物や植物の生息環境も、大きく変化しています。","furigana":"また、どうぶつやしょくぶつのせいそくかんきょうも、おおきくへんかしています。","romaji":"Mata, doubutsu ya shokubutsu no seisoku kankyou mo, ookiku henka shite imasu.","id":"Selain itu, habitat hewan dan tumbuhan pun berubah besar-besaran."},
   {"jp":"温暖化を止めるためには、世界中の国々の協力が欠かせません。","furigana":"おんだんかをとめるためには、せかいじゅうのくにぐにのきょうりょくがかかせません。","romaji":"Ondanka o tomeru tame ni wa, sekaijuu no kuniguni no kyouryoku ga kakasemasen.","id":"Untuk menghentikan pemanasan, kerja sama negara-negara di seluruh dunia tak boleh terlewat."},
   {"jp":"各国は、二酸化炭素の排出を減らす目標を立てています。","furigana":"かっこくは、にさんかたんそのはいしゅつをへらすもくひょうをたてています。","romaji":"Kakkoku wa, nisanka tanso no haishutsu o herasu mokuhyou o tatete imasu.","id":"Tiap negara menetapkan target mengurangi emisi karbon dioksida."},
   {"jp":"再生可能エネルギーへの転換も、急がれています。","furigana":"さいせいかのうエネルギーへのてんかんも、いそがれています。","romaji":"Saisei kanou enerugii e no tenkan mo, isogarete imasu.","id":"Peralihan ke energi terbarukan pun didesak untuk dipercepat."},
   {"jp":"私たち一人一人にも、できることがたくさんあります。","furigana":"わたしたちひとりひとりにも、できることがたくさんあります。","romaji":"Watashitachi hitori hitori ni mo, dekiru koto ga takusan arimasu.","id":"Kita masing-masing pun punya banyak hal yang bisa dilakukan."},
   {"jp":"電気を無駄に使わない、ゴミを減らすなどの小さな努力が大切です。","furigana":"でんきをむだにつかわない、ゴミをへらすなどのちいさなどりょくがたいせつです。","romaji":"Denki o muda ni tsukawanai, gomi o herasu nado no chiisa na doryoku ga taisetsu desu.","id":"Usaha kecil seperti tidak boros listrik dan mengurangi sampah itu penting."},
   {"jp":"公共交通機関を利用することも、効果的な方法の一つです。","furigana":"こうきょうこうつうきかんをりようすることも、こうかてきなほうほうのひとつです。","romaji":"Koukyou koutsuu kikan o riyou suru koto mo, koukateki na houhou no hitotsu desu.","id":"Memanfaatkan transportasi umum juga salah satu cara yang efektif."},
   {"jp":"未来の世代に美しい地球を残すのは、今を生きる私たちの責任です。","furigana":"みらいのせだいにうつくしいちきゅうをのこすのは、いまをいきるわたしたちのせきにんです。","romaji":"Mirai no sedai ni utsukushii chikyuu o nokosu no wa, ima o ikiru watashitachi no sekinin desu.","id":"Mewariskan bumi yang indah ke generasi mendatang adalah tanggung jawab kita yang hidup sekarang."},
   {"jp":"手遅れになる前に、行動を起こさなければなりません。","furigana":"ておくれになるまえに、こうどうをおこさなければなりません。","romaji":"Teokure ni naru mae ni, koudou o okosanakereba narimasen.","id":"Sebelum terlambat, kita harus mengambil tindakan."}
 ]'::jsonb,
 '[
   {"word":"地球温暖化","reading":"ちきゅうおんだんか","romaji":"chikyuu ondanka","meaning":"pemanasan global"},
   {"word":"直面","reading":"ちょくめん","romaji":"chokumen","meaning":"menghadapi (langsung)"},
   {"word":"深刻","reading":"しんこく","romaji":"shinkoku","meaning":"serius/gawat"},
   {"word":"二酸化炭素","reading":"にさんかたんそ","romaji":"nisanka tanso","meaning":"karbon dioksida"},
   {"word":"排出","reading":"はいしゅつ","romaji":"haishutsu","meaning":"emisi/pembuangan"},
   {"word":"平均気温","reading":"へいきんきおん","romaji":"heikin kion","meaning":"suhu rata-rata"},
   {"word":"上昇","reading":"じょうしょう","romaji":"joushou","meaning":"kenaikan"},
   {"word":"異常気象","reading":"いじょうきしょう","romaji":"ijou kishou","meaning":"cuaca ekstrem"},
   {"word":"氷河","reading":"ひょうが","romaji":"hyouga","meaning":"gletser"},
   {"word":"溶ける","reading":"とける","romaji":"tokeru","meaning":"mencair"},
   {"word":"海面","reading":"かいめん","romaji":"kaimen","meaning":"permukaan laut"},
   {"word":"水没","reading":"すいぼつ","romaji":"suibotsu","meaning":"tenggelam (terendam)"},
   {"word":"生息環境","reading":"せいそくかんきょう","romaji":"seisoku kankyou","meaning":"habitat"},
   {"word":"転換","reading":"てんかん","romaji":"tenkan","meaning":"peralihan"},
   {"word":"責任","reading":"せきにん","romaji":"sekinin","meaning":"tanggung jawab"}
 ]'::jsonb,
 '[
   {"q":"Apa salah satu masalah paling serius dunia modern?","options":["Pengangguran","Pemanasan global","Inflasi","Kepadatan kota"],"answer":1,"explanation":"「地球温暖化は…最も深刻な問題の一つ」."},
   {"q":"Apa yang terus meningkat seiring perkembangan industri?","options":["Hujan","Emisi karbon dioksida","Jumlah pohon","Populasi hewan"],"answer":1,"explanation":"「二酸化炭素の排出量が増え続けています」."},
   {"q":"Apa akibat mencairnya gletser?","options":["Kekeringan","Permukaan laut naik dan daratan rendah tenggelam","Udara dingin","Gempa"],"answer":1,"explanation":"「海面が上昇し、低い土地が水没する恐れ」."},
   {"q":"Untuk menghentikan pemanasan, apa yang penting?","options":["Satu negara saja","Kerja sama negara-negara dunia","Tidak ada cara","Menambah industri"],"answer":1,"explanation":"「世界中の国々の協力が欠かせません」."},
   {"q":"Usaha kecil apa yang disebut?","options":["Banyak bepergian","Tidak boros listrik dan mengurangi sampah","Membeli mobil","Menanam padi"],"answer":1,"explanation":"「電気を無駄に使わない、ゴミを減らす」."},
   {"q":"Mewariskan bumi indah ke generasi mendatang adalah?","options":["Tugas pemerintah saja","Tanggung jawab kita yang hidup sekarang","Mustahil","Tugas ilmuwan"],"answer":1,"explanation":"「今を生きる私たちの責任」."}
 ]'::jsonb,
 false),
(4, 9, '少子化 — Penurunan Angka Kelahiran',
 '日本では、少子化が大きな社会問題となっています。少子化とは、生まれてくる子どもの数が減ることを意味します。一人の女性が一生に産む子どもの数は、年々減少しています。この傾向が続くと、将来、人口が大幅に減ってしまいます。少子化には、さまざまな原因があると考えられています。まず、結婚しない人や、結婚が遅い人が増えています。子育てにかかる費用が高いことも、大きな理由の一つです。仕事と育児を両立することが難しいという問題もあります。特に、働く女性にとって、その負担は大きいです。少子化が進むと、社会にさまざまな影響が出ます。働く人が減り、経済の成長が止まる恐れがあります。高齢者を支える若い世代の負担も、重くなります。政府は、子育てを支援するさまざまな政策を行っています。育児休暇の制度を整えたり、保育園を増やしたりしています。しかし、問題の解決は簡単ではありません。社会全体で、子どもを育てやすい環境を作ることが求められています。',
 '[
   {"jp":"日本では、少子化が大きな社会問題となっています。","furigana":"にほんでは、しょうしかがおおきなしゃかいもんだいとなっています。","romaji":"Nihon de wa, shoushika ga ooki na shakai mondai to natte imasu.","id":"Di Jepang, penurunan angka kelahiran menjadi masalah sosial besar."},
   {"jp":"少子化とは、生まれてくる子どもの数が減ることを意味します。","furigana":"しょうしかとは、うまれてくるこどものかずがへることをいみします。","romaji":"Shoushika to wa, umarete kuru kodomo no kazu ga heru koto o imi shimasu.","id":"Shoushika berarti berkurangnya jumlah anak yang lahir."},
   {"jp":"一人の女性が一生に産む子どもの数は、年々減少しています。","furigana":"ひとりのじょせいがいっしょうにうむこどものかずは、ねんねんげんしょうしています。","romaji":"Hitori no josei ga isshou ni umu kodomo no kazu wa, nennen genshou shite imasu.","id":"Jumlah anak yang dilahirkan seorang perempuan seumur hidupnya menurun tiap tahun."},
   {"jp":"この傾向が続くと、将来、人口が大幅に減ってしまいます。","furigana":"このけいこうがつづくと、しょうらい、じんこうがおおはばにへってしまいます。","romaji":"Kono keikou ga tsuzuku to, shourai, jinkou ga oohaba ni hette shimaimasu.","id":"Kalau kecenderungan ini berlanjut, populasi akan menyusut drastis di masa depan."},
   {"jp":"少子化には、さまざまな原因があると考えられています。","furigana":"しょうしかには、さまざまなげんいんがあるとかんがえられています。","romaji":"Shoushika ni wa, samazama na gen-in ga aru to kangaerarete imasu.","id":"Penurunan kelahiran dianggap memiliki berbagai penyebab."},
   {"jp":"まず、結婚しない人や、結婚が遅い人が増えています。","furigana":"まず、けっこんしないひとや、けっこんがおそいひとがふえています。","romaji":"Mazu, kekkon shinai hito ya, kekkon ga osoi hito ga fuete imasu.","id":"Pertama, orang yang tidak menikah atau menikah terlambat semakin banyak."},
   {"jp":"子育てにかかる費用が高いことも、大きな理由の一つです。","furigana":"こそだてにかかるひようがたかいことも、おおきなりゆうのひとつです。","romaji":"Kosodate ni kakaru hiyou ga takai koto mo, ooki na riyuu no hitotsu desu.","id":"Tingginya biaya membesarkan anak juga salah satu alasan besar."},
   {"jp":"仕事と育児を両立することが難しいという問題もあります。","furigana":"しごとといくじをりょうりつすることがむずかしいというもんだいもあります。","romaji":"Shigoto to ikuji o ryouritsu suru koto ga muzukashii to iu mondai mo arimasu.","id":"Ada juga masalah sulitnya menyeimbangkan pekerjaan dan pengasuhan anak."},
   {"jp":"特に、働く女性にとって、その負担は大きいです。","furigana":"とくに、はたらくじょせいにとって、そのふたんはおおきいです。","romaji":"Toku ni, hataraku josei ni totte, sono futan wa ookii desu.","id":"Terutama bagi perempuan yang bekerja, bebannya besar."},
   {"jp":"少子化が進むと、社会にさまざまな影響が出ます。","furigana":"しょうしかがすすむと、しゃかいにさまざまなえいきょうがでます。","romaji":"Shoushika ga susumu to, shakai ni samazama na eikyou ga demasu.","id":"Kalau penurunan kelahiran berlanjut, muncul berbagai dampak pada masyarakat."},
   {"jp":"働く人が減り、経済の成長が止まる恐れがあります。","furigana":"はたらくひとがへり、けいざいのせいちょうがとまるおそれがあります。","romaji":"Hataraku hito ga heri, keizai no seichou ga tomaru osore ga arimasu.","id":"Pekerja berkurang, dan pertumbuhan ekonomi berisiko berhenti."},
   {"jp":"高齢者を支える若い世代の負担も、重くなります。","furigana":"こうれいしゃをささえるわかいせだいのふたんも、おもくなります。","romaji":"Koureisha o sasaeru wakai sedai no futan mo, omoku narimasu.","id":"Beban generasi muda yang menopang lansia pun menjadi berat."},
   {"jp":"政府は、子育てを支援するさまざまな政策を行っています。","furigana":"せいふは、こそだてをしえんするさまざまなせいさくをおこなっています。","romaji":"Seifu wa, kosodate o shien suru samazama na seisaku o okonatte imasu.","id":"Pemerintah menjalankan berbagai kebijakan untuk mendukung pengasuhan anak."},
   {"jp":"育児休暇の制度を整えたり、保育園を増やしたりしています。","furigana":"いくじきゅうかのせいどをととのえたり、ほいくえんをふやしたりしています。","romaji":"Ikuji kyuuka no seido o totonoetari, hoikuen o fuyashitari shite imasu.","id":"Menata sistem cuti pengasuhan anak dan menambah tempat penitipan anak."},
   {"jp":"しかし、問題の解決は簡単ではありません。","furigana":"しかし、もんだいのかいけつはかんたんではありません。","romaji":"Shikashi, mondai no kaiketsu wa kantan de wa arimasen.","id":"Namun, penyelesaian masalah ini tidaklah mudah."},
   {"jp":"社会全体で、子どもを育てやすい環境を作ることが求められています。","furigana":"しゃかいぜんたいで、こどもをそだてやすいかんきょうをつくることがもとめられています。","romaji":"Shakai zentai de, kodomo o sodateyasui kankyou o tsukuru koto ga motomerarete imasu.","id":"Diperlukan menciptakan lingkungan yang memudahkan membesarkan anak, oleh seluruh masyarakat."}
 ]'::jsonb,
 '[
   {"word":"少子化","reading":"しょうしか","romaji":"shoushika","meaning":"penurunan angka kelahiran"},
   {"word":"減少","reading":"げんしょう","romaji":"genshou","meaning":"penurunan/pengurangan"},
   {"word":"傾向","reading":"けいこう","romaji":"keikou","meaning":"kecenderungan"},
   {"word":"大幅","reading":"おおはば","romaji":"oohaba","meaning":"secara besar/signifikan"},
   {"word":"原因","reading":"げんいん","romaji":"gen-in","meaning":"penyebab"},
   {"word":"結婚","reading":"けっこん","romaji":"kekkon","meaning":"pernikahan"},
   {"word":"子育て","reading":"こそだて","romaji":"kosodate","meaning":"membesarkan anak"},
   {"word":"費用","reading":"ひよう","romaji":"hiyou","meaning":"biaya"},
   {"word":"両立","reading":"りょうりつ","romaji":"ryouritsu","meaning":"menyeimbangkan dua hal"},
   {"word":"負担","reading":"ふたん","romaji":"futan","meaning":"beban"},
   {"word":"成長","reading":"せいちょう","romaji":"seichou","meaning":"pertumbuhan"},
   {"word":"世代","reading":"せだい","romaji":"sedai","meaning":"generasi"},
   {"word":"支援","reading":"しえん","romaji":"shien","meaning":"dukungan"},
   {"word":"政策","reading":"せいさく","romaji":"seisaku","meaning":"kebijakan"},
   {"word":"育児休暇","reading":"いくじきゅうか","romaji":"ikuji kyuuka","meaning":"cuti mengasuh anak"}
 ]'::jsonb,
 '[
   {"q":"Apa arti shoushika?","options":["Penuaan penduduk","Berkurangnya jumlah anak yang lahir","Urbanisasi","Pengangguran"],"answer":1,"explanation":"「生まれてくる子どもの数が減ること」."},
   {"q":"Salah satu penyebab utama?","options":["Cuaca","Tingginya biaya membesarkan anak","Banyak hiburan","Sekolah gratis"],"answer":1,"explanation":"「子育てにかかる費用が高い」."},
   {"q":"Bagi siapa beban menyeimbangkan kerja dan asuh anak besar?","options":["Lansia","Perempuan yang bekerja","Anak-anak","Turis"],"answer":1,"explanation":"「働く女性にとって、その負担は大きい」."},
   {"q":"Apa akibat bila kelahiran terus menurun?","options":["Harga turun","Pekerja berkurang dan ekonomi terancam berhenti","Kota makin ramai","Tidak ada dampak"],"answer":1,"explanation":"「働く人が減り、経済の成長が止まる恐れ」."},
   {"q":"Apa yang dilakukan pemerintah?","options":["Menaikkan pajak","Kebijakan dukungan pengasuhan anak","Melarang menikah","Tidak ada"],"answer":1,"explanation":"「子育てを支援する…政策」."},
   {"q":"Apa yang dibutuhkan menurut teks?","options":["Lebih banyak pabrik","Lingkungan ramah pengasuhan anak oleh seluruh masyarakat","Mengurangi sekolah","Membatasi pernikahan"],"answer":1,"explanation":"「子どもを育てやすい環境を作ること」."}
 ]'::jsonb,
 false),
(4, 10, 'メンタルヘルス — Kesehatan Mental',
 '現代社会では、心の健康、つまりメンタルヘルスが注目されています。仕事や勉強、人間関係など、私たちは多くのストレスにさらされています。ストレスがたまりすぎると、心も体も疲れてしまいます。眠れなくなったり、やる気がなくなったりすることもあります。重い場合には、うつ病などの病気になることもあります。以前は、心の問題について話すことは難しいとされていました。しかし、最近では、その大切さが広く理解されるようになりました。心の不調は、誰にでも起こりうるものです。大切なのは、無理をせず、早めに休むことです。信頼できる人に悩みを話すだけでも、気持ちが楽になります。必要なときには、専門家に相談することも大切です。趣味や運動で気分転換をすることも、効果的です。十分な睡眠とバランスの良い食事も、心の健康を支えます。周りの人の小さな変化に気づき、声をかけることも重要です。一人で抱え込まず、助けを求める勇気を持ちましょう。心の健康を大切にすることは、豊かな人生を送るための基本です。',
 '[
   {"jp":"現代社会では、心の健康、つまりメンタルヘルスが注目されています。","furigana":"げんだいしゃかいでは、こころのけんこう、つまりメンタルヘルスがちゅうもくされています。","romaji":"Gendai shakai de wa, kokoro no kenkou, tsumari mentaru herusu ga chuumoku sarete imasu.","id":"Dalam masyarakat modern, kesehatan jiwa, yakni kesehatan mental, menjadi sorotan."},
   {"jp":"仕事や勉強、人間関係など、私たちは多くのストレスにさらされています。","furigana":"しごとやべんきょう、にんげんかんけいなど、わたしたちはおおくのストレスにさらされています。","romaji":"Shigoto ya benkyou, ningen kankei nado, watashitachi wa ooku no sutoresu ni sarasarete imasu.","id":"Pekerjaan, belajar, hubungan antarmanusia; kita terpapar banyak stres."},
   {"jp":"ストレスがたまりすぎると、心も体も疲れてしまいます。","furigana":"ストレスがたまりすぎると、こころもからだもつかれてしまいます。","romaji":"Sutoresu ga tamari sugiru to, kokoro mo karada mo tsukarete shimaimasu.","id":"Kalau stres menumpuk berlebihan, hati maupun tubuh jadi lelah."},
   {"jp":"眠れなくなったり、やる気がなくなったりすることもあります。","furigana":"ねむれなくなったり、やるきがなくなったりすることもあります。","romaji":"Nemurenaku nattari, yaruki ga nakunattari suru koto mo arimasu.","id":"Bisa juga jadi sulit tidur atau kehilangan motivasi."},
   {"jp":"重い場合には、うつ病などの病気になることもあります。","furigana":"おもいばあいには、うつびょうなどのびょうきになることもあります。","romaji":"Omoi baai ni wa, utsubyou nado no byouki ni naru koto mo arimasu.","id":"Dalam kasus berat, bisa menjadi penyakit seperti depresi."},
   {"jp":"以前は、心の問題について話すことは難しいとされていました。","furigana":"いぜんは、こころのもんだいについてはなすことはむずかしいとされていました。","romaji":"Izen wa, kokoro no mondai ni tsuite hanasu koto wa muzukashii to sarete imashita.","id":"Dulu, berbicara tentang masalah kejiwaan dianggap sulit."},
   {"jp":"しかし、最近では、その大切さが広く理解されるようになりました。","furigana":"しかし、さいきんでは、そのたいせつさがひろくりかいされるようになりました。","romaji":"Shikashi, saikin de wa, sono taisetsusa ga hiroku rikai sareru you ni narimashita.","id":"Namun, belakangan, pentingnya hal itu mulai dipahami secara luas."},
   {"jp":"心の不調は、誰にでも起こりうるものです。","furigana":"こころのふちょうは、だれにでもおこりうるものです。","romaji":"Kokoro no fuchou wa, dare ni demo okoriuru mono desu.","id":"Gangguan kejiwaan adalah hal yang bisa terjadi pada siapa pun."},
   {"jp":"大切なのは、無理をせず、早めに休むことです。","furigana":"たいせつなのは、むりをせず、はやめにやすむことです。","romaji":"Taisetsu na no wa, muri o sezu, hayame ni yasumu koto desu.","id":"Yang penting adalah tidak memaksakan diri dan beristirahat lebih awal."},
   {"jp":"信頼できる人に悩みを話すだけでも、気持ちが楽になります。","furigana":"しんらいできるひとになやみをはなすだけでも、きもちがらくになります。","romaji":"Shinrai dekiru hito ni nayami o hanasu dake de mo, kimochi ga raku ni narimasu.","id":"Sekadar menceritakan kegelisahan pada orang yang dipercaya pun membuat hati lega."},
   {"jp":"必要なときには、専門家に相談することも大切です。","furigana":"ひつようなときには、せんもんかにそうだんすることもたいせつです。","romaji":"Hitsuyou na toki ni wa, senmonka ni soudan suru koto mo taisetsu desu.","id":"Saat dibutuhkan, berkonsultasi dengan ahli juga penting."},
   {"jp":"趣味や運動で気分転換をすることも、効果的です。","furigana":"しゅみやうんどうできぶんてんかんをすることも、こうかてきです。","romaji":"Shumi ya undou de kibun tenkan o suru koto mo, koukateki desu.","id":"Menyegarkan suasana hati lewat hobi atau olahraga juga efektif."},
   {"jp":"十分な睡眠とバランスの良い食事も、心の健康を支えます。","furigana":"じゅうぶんなすいみんとバランスのよいしょくじも、こころのけんこうをささえます。","romaji":"Juubun na suimin to baransu no yoi shokuji mo, kokoro no kenkou o sasaemasu.","id":"Tidur cukup dan pola makan seimbang juga menopang kesehatan mental."},
   {"jp":"周りの人の小さな変化に気づき、声をかけることも重要です。","furigana":"まわりのひとのちいさなへんかにきづき、こえをかけることもじゅうようです。","romaji":"Mawari no hito no chiisa na henka ni kizuki, koe o kakeru koto mo juuyou desu.","id":"Menyadari perubahan kecil pada orang di sekitar dan menyapa mereka juga penting."},
   {"jp":"一人で抱え込まず、助けを求める勇気を持ちましょう。","furigana":"ひとりでかかえこまず、たすけをもとめるゆうきをもちましょう。","romaji":"Hitori de kakaekomazu, tasuke o motomeru yuuki o mochimashou.","id":"Jangan memikul sendiri; milikilah keberanian untuk meminta bantuan."},
   {"jp":"心の健康を大切にすることは、豊かな人生を送るための基本です。","furigana":"こころのけんこうをたいせつにすることは、ゆたかなじんせいをおくるためのきほんです。","romaji":"Kokoro no kenkou o taisetsu ni suru koto wa, yutaka na jinsei o okuru tame no kihon desu.","id":"Menjaga kesehatan mental adalah dasar untuk menjalani hidup yang kaya."}
 ]'::jsonb,
 '[
   {"word":"メンタルヘルス","reading":"メンタルヘルス","romaji":"mentaru herusu","meaning":"kesehatan mental"},
   {"word":"注目","reading":"ちゅうもく","romaji":"chuumoku","meaning":"perhatian/sorotan"},
   {"word":"さらされる","reading":"さらされる","romaji":"sarasareru","meaning":"terpapar"},
   {"word":"たまる","reading":"たまる","romaji":"tamaru","meaning":"menumpuk"},
   {"word":"やる気","reading":"やるき","romaji":"yaruki","meaning":"motivasi/semangat"},
   {"word":"うつ病","reading":"うつびょう","romaji":"utsubyou","meaning":"depresi"},
   {"word":"不調","reading":"ふちょう","romaji":"fuchou","meaning":"kondisi tidak sehat"},
   {"word":"起こりうる","reading":"おこりうる","romaji":"okoriuru","meaning":"bisa terjadi"},
   {"word":"無理","reading":"むり","romaji":"muri","meaning":"memaksakan diri"},
   {"word":"信頼","reading":"しんらい","romaji":"shinrai","meaning":"kepercayaan"},
   {"word":"専門家","reading":"せんもんか","romaji":"senmonka","meaning":"ahli/pakar"},
   {"word":"気分転換","reading":"きぶんてんかん","romaji":"kibun tenkan","meaning":"penyegaran suasana hati"},
   {"word":"抱え込む","reading":"かかえこむ","romaji":"kakaekomu","meaning":"memikul/memendam sendiri"},
   {"word":"勇気","reading":"ゆうき","romaji":"yuuki","meaning":"keberanian"},
   {"word":"基本","reading":"きほん","romaji":"kihon","meaning":"dasar/fundamental"}
 ]'::jsonb,
 '[
   {"q":"Apa yang menjadi sorotan di masyarakat modern?","options":["Kesehatan fisik","Kesehatan mental","Ekonomi","Olahraga"],"answer":1,"explanation":"「メンタルヘルスが注目されています」."},
   {"q":"Apa akibat stres yang menumpuk berlebihan?","options":["Lebih kuat","Hati dan tubuh jadi lelah","Lebih kaya","Lebih ramah"],"answer":1,"explanation":"「心も体も疲れてしまいます」."},
   {"q":"Dalam kasus berat, bisa menjadi penyakit apa?","options":["Flu","Depresi (utsubyou)","Diabetes","Patah tulang"],"answer":1,"explanation":"「うつ病などの病気になることも」."},
   {"q":"Apa yang penting menurut teks?","options":["Bekerja lebih keras","Tidak memaksakan diri dan istirahat lebih awal","Menyendiri","Diam saja"],"answer":1,"explanation":"「無理をせず、早めに休むこと」."},
   {"q":"Hanya dengan apa perasaan bisa lega?","options":["Belanja","Bercerita pada orang yang dipercaya","Tidur seharian","Makan banyak"],"answer":1,"explanation":"「信頼できる人に悩みを話すだけでも」."},
   {"q":"Apa yang sebaiknya dimiliki?","options":["Memendam sendiri","Keberanian meminta bantuan","Mengabaikan masalah","Pura-pura kuat"],"answer":1,"explanation":"「助けを求める勇気を持ちましょう」."}
 ]'::jsonb,
 false),
(4, 11, '再生可能エネルギー — Energi Terbarukan',
 'エネルギー問題は、世界が抱える重要な課題の一つです。これまで、私たちは主に石油や石炭などの化石燃料に頼ってきました。しかし、化石燃料には限りがあり、いつかは無くなってしまいます。また、燃やすときに二酸化炭素を出し、地球温暖化の原因にもなります。そこで注目されているのが、再生可能エネルギーです。太陽光や風力、水力などは、自然の力を利用したエネルギーです。これらは何度でも使うことができ、環境を汚しません。例えば、太陽光発電は、屋根にパネルを置くだけで電気を作れます。風力発電は、大きな風車を回して電気を生み出します。多くの国が、再生可能エネルギーの導入を進めています。しかし、課題も残されています。天気によって、発電量が変わってしまうという弱点があります。また、設備を作るのに、多くの費用がかかります。それでも、技術は年々進歩しています。持続可能な社会を作るために、再生可能エネルギーは欠かせません。クリーンなエネルギーへの転換は、未来への大切な投資です。',
 '[
   {"jp":"エネルギー問題は、世界が抱える重要な課題の一つです。","furigana":"エネルギーもんだいは、せかいがかかえるじゅうようなかだいのひとつです。","romaji":"Enerugii mondai wa, sekai ga kakaeru juuyou na kadai no hitotsu desu.","id":"Masalah energi adalah salah satu tantangan penting yang dihadapi dunia."},
   {"jp":"これまで、私たちは主に石油や石炭などの化石燃料に頼ってきました。","furigana":"これまで、わたしたちはおもにせきゆやせきたんなどのかせきねんりょうにたよってきました。","romaji":"Kore made, watashitachi wa omo ni sekiyu ya sekitan nado no kaseki nenryou ni tayotte kimashita.","id":"Selama ini, kita terutama mengandalkan bahan bakar fosil seperti minyak dan batu bara."},
   {"jp":"しかし、化石燃料には限りがあり、いつかは無くなってしまいます。","furigana":"しかし、かせきねんりょうにはかぎりがあり、いつかはなくなってしまいます。","romaji":"Shikashi, kaseki nenryou ni wa kagiri ga ari, itsuka wa nakunatte shimaimasu.","id":"Namun, bahan bakar fosil ada batasnya dan suatu saat akan habis."},
   {"jp":"また、燃やすときに二酸化炭素を出し、地球温暖化の原因にもなります。","furigana":"また、もやすときににさんかたんそをだし、ちきゅうおんだんかのげんいんにもなります。","romaji":"Mata, moyasu toki ni nisanka tanso o dashi, chikyuu ondanka no gen-in ni mo narimasu.","id":"Selain itu, saat dibakar menghasilkan CO2 dan menjadi penyebab pemanasan global."},
   {"jp":"そこで注目されているのが、再生可能エネルギーです。","furigana":"そこでちゅうもくされているのが、さいせいかのうエネルギーです。","romaji":"Soko de chuumoku sarete iru no ga, saisei kanou enerugii desu.","id":"Karena itu, yang menjadi sorotan adalah energi terbarukan."},
   {"jp":"太陽光や風力、水力などは、自然の力を利用したエネルギーです。","furigana":"たいようこうやふうりょく、すいりょくなどは、しぜんのちからをりようしたエネルギーです。","romaji":"Taiyoukou ya fuuryoku, suiryoku nado wa, shizen no chikara o riyou shita enerugii desu.","id":"Tenaga surya, angin, dan air adalah energi yang memanfaatkan kekuatan alam."},
   {"jp":"これらは何度でも使うことができ、環境を汚しません。","furigana":"これらはなんどでもつかうことができ、かんきょうをよごしません。","romaji":"Korera wa nando demo tsukau koto ga deki, kankyou o yogoshimasen.","id":"Energi ini bisa dipakai berkali-kali dan tidak mencemari lingkungan."},
   {"jp":"例えば、太陽光発電は、屋根にパネルを置くだけで電気を作れます。","furigana":"たとえば、たいようこうはつでんは、やねにパネルをおくだけでんきをつくれます。","romaji":"Tatoeba, taiyoukou hatsuden wa, yane ni paneru o oku dake de denki o tsukuremasu.","id":"Misalnya, panel surya bisa menghasilkan listrik hanya dengan memasang panel di atap."},
   {"jp":"風力発電は、大きな風車を回して電気を生み出します。","furigana":"ふうりょくはつでんは、おおきなふうしゃをまわしてでんきをうみだします。","romaji":"Fuuryoku hatsuden wa, ooki na fuusha o mawashite denki o umidashimasu.","id":"Pembangkit angin menghasilkan listrik dengan memutar kincir besar."},
   {"jp":"多くの国が、再生可能エネルギーの導入を進めています。","furigana":"おおくのくにが、さいせいかのうエネルギーのどうにゅうをすすめています。","romaji":"Ooku no kuni ga, saisei kanou enerugii no dounyuu o susumete imasu.","id":"Banyak negara mendorong penerapan energi terbarukan."},
   {"jp":"しかし、課題も残されています。","furigana":"しかし、かだいものこされています。","romaji":"Shikashi, kadai mo nokosarete imasu.","id":"Namun, masih tersisa tantangan."},
   {"jp":"天気によって、発電量が変わってしまうという弱点があります。","furigana":"てんきによって、はつでんりょうがかわってしまうというじゃくてんがあります。","romaji":"Tenki ni yotte, hatsudenryou ga kawatte shimau to iu jakuten ga arimasu.","id":"Ada kelemahan: jumlah listrik yang dihasilkan berubah tergantung cuaca."},
   {"jp":"また、設備を作るのに、多くの費用がかかります。","furigana":"また、せつびをつくるのに、おおくのひようがかかります。","romaji":"Mata, setsubi o tsukuru no ni, ooku no hiyou ga kakarimasu.","id":"Selain itu, membangun fasilitasnya memakan banyak biaya."},
   {"jp":"それでも、技術は年々進歩しています。","furigana":"それでも、ぎじゅつはねんねんしんぽしています。","romaji":"Soredemo, gijutsu wa nennen shinpo shite imasu.","id":"Meski begitu, teknologinya maju dari tahun ke tahun."},
   {"jp":"持続可能な社会を作るために、再生可能エネルギーは欠かせません。","furigana":"じぞくかのうなしゃかいをつくるために、さいせいかのうエネルギーはかかせません。","romaji":"Jizoku kanou na shakai o tsukuru tame ni, saisei kanou enerugii wa kakasemasen.","id":"Untuk membangun masyarakat berkelanjutan, energi terbarukan tak tergantikan."},
   {"jp":"クリーンなエネルギーへの転換は、未来への大切な投資です。","furigana":"クリーンなエネルギーへのてんかんは、みらいへのたいせつなとうしです。","romaji":"Kuriin na enerugii e no tenkan wa, mirai e no taisetsu na toushi desu.","id":"Peralihan ke energi bersih adalah investasi penting bagi masa depan."}
 ]'::jsonb,
 '[
   {"word":"再生可能エネルギー","reading":"さいせいかのうエネルギー","romaji":"saisei kanou enerugii","meaning":"energi terbarukan"},
   {"word":"化石燃料","reading":"かせきねんりょう","romaji":"kaseki nenryou","meaning":"bahan bakar fosil"},
   {"word":"頼る","reading":"たよる","romaji":"tayoru","meaning":"mengandalkan"},
   {"word":"限り","reading":"かぎり","romaji":"kagiri","meaning":"batas"},
   {"word":"燃やす","reading":"もやす","romaji":"moyasu","meaning":"membakar"},
   {"word":"太陽光","reading":"たいようこう","romaji":"taiyoukou","meaning":"tenaga surya/cahaya matahari"},
   {"word":"風力","reading":"ふうりょく","romaji":"fuuryoku","meaning":"tenaga angin"},
   {"word":"水力","reading":"すいりょく","romaji":"suiryoku","meaning":"tenaga air"},
   {"word":"汚す","reading":"よごす","romaji":"yogosu","meaning":"mencemari/mengotori"},
   {"word":"発電","reading":"はつでん","romaji":"hatsuden","meaning":"pembangkitan listrik"},
   {"word":"導入","reading":"どうにゅう","romaji":"dounyuu","meaning":"penerapan/pengadopsian"},
   {"word":"弱点","reading":"じゃくてん","romaji":"jakuten","meaning":"kelemahan"},
   {"word":"設備","reading":"せつび","romaji":"setsubi","meaning":"fasilitas/instalasi"},
   {"word":"進歩","reading":"しんぽ","romaji":"shinpo","meaning":"kemajuan"},
   {"word":"投資","reading":"とうし","romaji":"toushi","meaning":"investasi"}
 ]'::jsonb,
 '[
   {"q":"Selama ini kita bergantung pada apa?","options":["Energi surya","Bahan bakar fosil (minyak, batu bara)","Tenaga angin","Tenaga air"],"answer":1,"explanation":"「石油や石炭などの化石燃料に頼ってきました」."},
   {"q":"Apa masalah bahan bakar fosil?","options":["Tak terbatas","Terbatas dan menghasilkan CO2","Gratis","Bersih"],"answer":1,"explanation":"「限りがあり…二酸化炭素を出し」."},
   {"q":"Apa contoh energi terbarukan?","options":["Minyak dan gas","Surya, angin, air","Batu bara","Nuklir saja"],"answer":1,"explanation":"「太陽光や風力、水力など」."},
   {"q":"Apa kelemahan energi terbarukan?","options":["Terlalu murah","Jumlah listrik bergantung cuaca","Tidak bisa dipakai","Mencemari udara"],"answer":1,"explanation":"「天気によって、発電量が変わってしまう」."},
   {"q":"Selain itu, apa kendalanya?","options":["Tidak ada lahan","Biaya membangun fasilitas besar","Dilarang","Tidak ada teknologi"],"answer":1,"explanation":"「設備を作るのに、多くの費用がかかります」."},
   {"q":"Peralihan ke energi bersih disebut sebagai?","options":["Pemborosan","Investasi penting bagi masa depan","Hal sia-sia","Kemunduran"],"answer":1,"explanation":"「未来への大切な投資」."}
 ]'::jsonb,
 false),
(4, 12, 'フェイクニュース — Berita Palsu',
 'インターネットの普及で、私たちは簡単に情報を手に入れられるようになりました。しかし、その中には、間違った情報や嘘の情報も含まれています。このような偽の情報を「フェイクニュース」と呼びます。フェイクニュースは、SNSを通じて、あっという間に広がります。多くの人が、内容を確かめずに、それを信じてしまいます。嘘の情報が広がると、社会が混乱することがあります。例えば、災害のときに誤った情報が流れると、人々がパニックになります。特定の人を傷つけたり、差別を生んだりすることもあります。では、私たちはどうすればよいのでしょうか。まず、情報をすぐに信じないことが大切です。その情報が、信頼できる場所から出ているか確認しましょう。一つの情報だけでなく、複数の情報源を比べることも有効です。怪しい情報を、軽い気持ちで他の人に広めてはいけません。正しい情報を見分ける力を、メディアリテラシーと言います。これからの時代、その力はますます重要になります。情報に振り回されず、冷静に判断する習慣を身につけたいものです。',
 '[
   {"jp":"インターネットの普及で、私たちは簡単に情報を手に入れられるようになりました。","furigana":"インターネットのふきゅうで、わたしたちはかんたんにじょうほうをてにいれられるようになりました。","romaji":"Intaanetto no fukyuu de, watashitachi wa kantan ni jouhou o te ni irerareru you ni narimashita.","id":"Berkat penyebaran internet, kita jadi mudah memperoleh informasi."},
   {"jp":"しかし、その中には、間違った情報や嘘の情報も含まれています。","furigana":"しかし、そのなかには、まちがったじょうほうやうそのじょうほうもふくまれています。","romaji":"Shikashi, sono naka ni wa, machigatta jouhou ya uso no jouhou mo fukumarete imasu.","id":"Namun, di antaranya termasuk pula informasi keliru dan bohong."},
   {"jp":"このような偽の情報を「フェイクニュース」と呼びます。","furigana":"このようなにせのじょうほうを「フェイクニュース」とよびます。","romaji":"Kono you na nise no jouhou o \"feiku nyuusu\" to yobimasu.","id":"Informasi palsu seperti ini disebut berita palsu (fake news)."},
   {"jp":"フェイクニュースは、SNSを通じて、あっという間に広がります。","furigana":"フェイクニュースは、エスエヌエスをつうじて、あっというまにひろがります。","romaji":"Feiku nyuusu wa, esuenuesu o tsuujite, attoiumani hirogarimasu.","id":"Berita palsu menyebar dalam sekejap lewat media sosial."},
   {"jp":"多くの人が、内容を確かめずに、それを信じてしまいます。","furigana":"おおくのひとが、ないようをたしかめずに、それをしんじてしまいます。","romaji":"Ooku no hito ga, naiyou o tashikamezu ni, sore o shinjite shimaimasu.","id":"Banyak orang mempercayainya tanpa memastikan isinya."},
   {"jp":"嘘の情報が広がると、社会が混乱することがあります。","furigana":"うそのじょうほうがひろがると、しゃかいがこんらんすることがあります。","romaji":"Uso no jouhou ga hirogaru to, shakai ga konran suru koto ga arimasu.","id":"Kalau informasi bohong menyebar, masyarakat bisa kacau."},
   {"jp":"例えば、災害のときに誤った情報が流れると、人々がパニックになります。","furigana":"たとえば、さいがいのときにあやまったじょうほうがながれると、ひとびとがパニックになります。","romaji":"Tatoeba, saigai no toki ni ayamatta jouhou ga nagareru to, hitobito ga panikku ni narimasu.","id":"Misalnya, kalau informasi keliru beredar saat bencana, orang-orang jadi panik."},
   {"jp":"特定の人を傷つけたり、差別を生んだりすることもあります。","furigana":"とくていのひとをきずつけたり、さべつをうんだりすることもあります。","romaji":"Tokutei no hito o kizutsuketari, sabetsu o undari suru koto mo arimasu.","id":"Bisa juga melukai orang tertentu atau menimbulkan diskriminasi."},
   {"jp":"では、私たちはどうすればよいのでしょうか。","furigana":"では、わたしたちはどうすればよいのでしょうか。","romaji":"Dewa, watashitachi wa dou sureba yoi no deshou ka.","id":"Lalu, apa yang sebaiknya kita lakukan?"},
   {"jp":"まず、情報をすぐに信じないことが大切です。","furigana":"まず、じょうほうをすぐにしんじないことがたいせつです。","romaji":"Mazu, jouhou o sugu ni shinjinai koto ga taisetsu desu.","id":"Pertama, penting untuk tidak langsung percaya pada informasi."},
   {"jp":"その情報が、信頼できる場所から出ているか確認しましょう。","furigana":"そのじょうほうが、しんらいできるばしょからでているかかくにんしましょう。","romaji":"Sono jouhou ga, shinrai dekiru basho kara dete iru ka kakunin shimashou.","id":"Mari pastikan apakah informasi itu berasal dari sumber yang terpercaya."},
   {"jp":"一つの情報だけでなく、複数の情報源を比べることも有効です。","furigana":"ひとつのじょうほうだけでなく、ふくすうのじょうほうげんをくらべることもゆうこうです。","romaji":"Hitotsu no jouhou dake de naku, fukusuu no jouhougen o kuraberu koto mo yuukou desu.","id":"Membandingkan beberapa sumber, bukan hanya satu informasi, juga efektif."},
   {"jp":"怪しい情報を、軽い気持ちで他の人に広めてはいけません。","furigana":"あやしいじょうほうを、かるいきもちでほかのひとにひろめてはいけません。","romaji":"Ayashii jouhou o, karui kimochi de hoka no hito ni hiromete wa ikemasen.","id":"Jangan menyebarkan informasi mencurigakan ke orang lain dengan enteng."},
   {"jp":"正しい情報を見分ける力を、メディアリテラシーと言います。","furigana":"ただしいじょうほうをみわけるちからを、メディアリテラシーといいます。","romaji":"Tadashii jouhou o miwakeru chikara o, media riterashii to iimasu.","id":"Kemampuan membedakan informasi yang benar disebut literasi media."},
   {"jp":"これからの時代、その力はますます重要になります。","furigana":"これからのじだい、そのちからはますますじゅうようになります。","romaji":"Korekara no jidai, sono chikara wa masumasu juuyou ni narimasu.","id":"Di era mendatang, kemampuan itu akan semakin penting."},
   {"jp":"情報に振り回されず、冷静に判断する習慣を身につけたいものです。","furigana":"じょうほうにふりまわされず、れいせいにはんだんするしゅうかんをみにつけたいものです。","romaji":"Jouhou ni furimawasarezu, reisei ni handan suru shuukan o mi ni tsuketai mono desu.","id":"Kita ingin membiasakan diri menilai dengan tenang, tanpa terombang-ambing informasi."}
 ]'::jsonb,
 '[
   {"word":"普及","reading":"ふきゅう","romaji":"fukyuu","meaning":"penyebaran/pemasyarakatan"},
   {"word":"手に入れる","reading":"てにいれる","romaji":"te ni ireru","meaning":"memperoleh"},
   {"word":"含む","reading":"ふくむ","romaji":"fukumu","meaning":"mengandung/termasuk"},
   {"word":"偽","reading":"にせ","romaji":"nise","meaning":"palsu"},
   {"word":"あっという間","reading":"あっというま","romaji":"attoiuma","meaning":"dalam sekejap"},
   {"word":"確かめる","reading":"たしかめる","romaji":"tashikameru","meaning":"memastikan"},
   {"word":"混乱","reading":"こんらん","romaji":"konran","meaning":"kekacauan"},
   {"word":"誤った","reading":"あやまった","romaji":"ayamatta","meaning":"yang keliru"},
   {"word":"差別","reading":"さべつ","romaji":"sabetsu","meaning":"diskriminasi"},
   {"word":"信頼できる","reading":"しんらいできる","romaji":"shinrai dekiru","meaning":"dapat dipercaya"},
   {"word":"情報源","reading":"じょうほうげん","romaji":"jouhougen","meaning":"sumber informasi"},
   {"word":"怪しい","reading":"あやしい","romaji":"ayashii","meaning":"mencurigakan"},
   {"word":"見分ける","reading":"みわける","romaji":"miwakeru","meaning":"membedakan/mengenali"},
   {"word":"メディアリテラシー","reading":"メディアリテラシー","romaji":"media riterashii","meaning":"literasi media"},
   {"word":"冷静","reading":"れいせい","romaji":"reisei","meaning":"tenang/berkepala dingin"}
 ]'::jsonb,
 '[
   {"q":"Berkat apa kita mudah memperoleh informasi?","options":["TV","Penyebaran internet","Koran","Radio"],"answer":1,"explanation":"「インターネットの普及で」."},
   {"q":"Apa sebutan informasi palsu?","options":["Iklan","Berita palsu (fake news)","Gosip biasa","Editorial"],"answer":1,"explanation":"「偽の情報を『フェイクニュース』と呼びます」."},
   {"q":"Lewat apa berita palsu menyebar cepat?","options":["Buku","Media sosial (SNS)","Surat","Sekolah"],"answer":1,"explanation":"「SNSを通じて、あっという間に広がります」."},
   {"q":"Apa yang bisa terjadi saat info keliru beredar ketika bencana?","options":["Tenang","Orang-orang panik","Bahagia","Tidur"],"answer":1,"explanation":"「人々がパニックになります」."},
   {"q":"Apa yang penting dilakukan?","options":["Langsung percaya","Tidak langsung percaya dan memverifikasi sumber","Sebar segera","Abaikan semua"],"answer":1,"explanation":"「すぐに信じない」「信頼できる場所から出ているか確認」."},
   {"q":"Kemampuan membedakan informasi benar disebut?","options":["Literasi keuangan","Literasi media","Kemampuan bahasa","Logika"],"answer":1,"explanation":"「メディアリテラシーと言います」."}
 ]'::jsonb,
 false),
(4, 13, '食の安全 — Keamanan Pangan',
 '毎日口にする食べ物の安全は、誰にとっても大きな関心事です。私たちは、スーパーやレストランで様々な食品を手に入れます。しかし、その食べ物がどこで、どのように作られたのか、知らないことが多いです。食の安全を守るために、さまざまな仕組みが作られています。例えば、食品には、原材料や賞味期限が表示されています。これを見れば、消費者は安心して商品を選ぶことができます。農薬や添加物の使用についても、厳しい基準が定められています。しかし、時には、食品に関する事件や問題が起こることもあります。産地を偽ったり、期限を書き換えたりする不正もあります。このような問題は、消費者の信頼を大きく損ないます。私たち消費者も、正しい知識を持つことが大切です。表示をよく確認し、信頼できる店で買うように心がけましょう。また、家庭でも、食材を清潔に扱うことが重要です。手をよく洗い、食品を適切な温度で保存しなければなりません。食の安全は、生産者と消費者の両方で守るものです。安心して食事ができる社会を、みんなで作っていきたいです。',
 '[
   {"jp":"毎日口にする食べ物の安全は、誰にとっても大きな関心事です。","furigana":"まいにちくちにするたべもののあんぜんは、だれにとってもおおきなかんしんじです。","romaji":"Mainichi kuchi ni suru tabemono no anzen wa, dare ni totte mo ooki na kanshinji desu.","id":"Keamanan makanan yang kita santap tiap hari menjadi perhatian besar bagi siapa pun."},
   {"jp":"私たちは、スーパーやレストランで様々な食品を手に入れます。","furigana":"わたしたちは、スーパーやレストランでさまざまなしょくひんをてにいれます。","romaji":"Watashitachi wa, suupaa ya resutoran de samazama na shokuhin o te ni iremasu.","id":"Kita memperoleh berbagai produk pangan di supermarket dan restoran."},
   {"jp":"しかし、その食べ物がどこで、どのように作られたのか、知らないことが多いです。","furigana":"しかし、そのたべものがどこで、どのようにつくられたのか、しらないことがおおいです。","romaji":"Shikashi, sono tabemono ga doko de, dono you ni tsukurareta no ka, shiranai koto ga ooi desu.","id":"Namun, sering kali kita tak tahu di mana dan bagaimana makanan itu dibuat."},
   {"jp":"食の安全を守るために、さまざまな仕組みが作られています。","furigana":"しょくのあんぜんをまもるために、さまざまなしくみがつくられています。","romaji":"Shoku no anzen o mamoru tame ni, samazama na shikumi ga tsukurarete imasu.","id":"Untuk menjaga keamanan pangan, dibuat berbagai mekanisme."},
   {"jp":"例えば、食品には、原材料や賞味期限が表示されています。","furigana":"たとえば、しょくひんには、げんざいりょうやしょうみきげんがひょうじされています。","romaji":"Tatoeba, shokuhin ni wa, genzairyou ya shoumi kigen ga hyouji sarete imasu.","id":"Misalnya, pada produk pangan tertera bahan baku dan tanggal kedaluwarsa."},
   {"jp":"これを見れば、消費者は安心して商品を選ぶことができます。","furigana":"これをみれば、しょうひしゃはあんしんしてしょうひんをえらぶことができます。","romaji":"Kore o mireba, shouhisha wa anshin shite shouhin o erabu koto ga dekimasu.","id":"Dengan melihat ini, konsumen bisa memilih produk dengan tenang."},
   {"jp":"農薬や添加物の使用についても、厳しい基準が定められています。","furigana":"のうやくやてんかぶつのしようについても、きびしいきじゅんがさだめられています。","romaji":"Nouyaku ya tenkabutsu no shiyou ni tsuite mo, kibishii kijun ga sadamerarete imasu.","id":"Penggunaan pestisida dan zat aditif pun diatur dengan standar yang ketat."},
   {"jp":"しかし、時には、食品に関する事件や問題が起こることもあります。","furigana":"しかし、ときには、しょくひんにかんするじけんやもんだいがおこることもあります。","romaji":"Shikashi, toki ni wa, shokuhin ni kansuru jiken ya mondai ga okoru koto mo arimasu.","id":"Namun, kadang terjadi juga kasus dan masalah terkait pangan."},
   {"jp":"産地を偽ったり、期限を書き換えたりする不正もあります。","furigana":"さんちをいつわったり、きげんをかきかえたりするふせいもあります。","romaji":"Sanchi o itsuwattari, kigen o kakikaetari suru fusei mo arimasu.","id":"Ada pula kecurangan seperti memalsukan asal produk atau mengubah tanggal."},
   {"jp":"このような問題は、消費者の信頼を大きく損ないます。","furigana":"このようなもんだいは、しょうひしゃのしんらいをおおきくそこないます。","romaji":"Kono you na mondai wa, shouhisha no shinrai o ookiku sokonaimasu.","id":"Masalah seperti ini sangat mencederai kepercayaan konsumen."},
   {"jp":"私たち消費者も、正しい知識を持つことが大切です。","furigana":"わたしたちしょうひしゃも、ただしいちしきをもつことがたいせつです。","romaji":"Watashitachi shouhisha mo, tadashii chishiki o motsu koto ga taisetsu desu.","id":"Kita sebagai konsumen pun penting memiliki pengetahuan yang benar."},
   {"jp":"表示をよく確認し、信頼できる店で買うように心がけましょう。","furigana":"ひょうじをよくかくにんし、しんらいできるみせでかうようにこころがけましょう。","romaji":"Hyouji o yoku kakunin shi, shinrai dekiru mise de kau you ni kokorogakemashou.","id":"Mari biasakan memeriksa label dan membeli di toko yang terpercaya."},
   {"jp":"また、家庭でも、食材を清潔に扱うことが重要です。","furigana":"また、かていでも、しょくざいをせいけつにあつかうことがじゅうようです。","romaji":"Mata, katei de mo, shokuzai o seiketsu ni atsukau koto ga juuyou desu.","id":"Selain itu, di rumah pun penting menangani bahan makanan secara higienis."},
   {"jp":"手をよく洗い、食品を適切な温度で保存しなければなりません。","furigana":"てをよくあらい、しょくひんをてきせつなおんどでほぞんしなければなりません。","romaji":"Te o yoku arai, shokuhin o tekisetsu na ondo de hozon shinakereba narimasen.","id":"Kita harus mencuci tangan dengan bersih dan menyimpan makanan pada suhu yang tepat."},
   {"jp":"食の安全は、生産者と消費者の両方で守るものです。","furigana":"しょくのあんぜんは、せいさんしゃとしょうひしゃのりょうほうでまもるものです。","romaji":"Shoku no anzen wa, seisansha to shouhisha no ryouhou de mamoru mono desu.","id":"Keamanan pangan adalah hal yang dijaga oleh produsen dan konsumen kedua-duanya."},
   {"jp":"安心して食事ができる社会を、みんなで作っていきたいです。","furigana":"あんしんしてしょくじができるしゃかいを、みんなでつくっていきたいです。","romaji":"Anshin shite shokuji ga dekiru shakai o, minna de tsukutte ikitai desu.","id":"Kita ingin bersama-sama membangun masyarakat di mana orang bisa makan dengan tenang."}
 ]'::jsonb,
 '[
   {"word":"関心事","reading":"かんしんじ","romaji":"kanshinji","meaning":"hal yang menjadi perhatian"},
   {"word":"食品","reading":"しょくひん","romaji":"shokuhin","meaning":"produk pangan"},
   {"word":"仕組み","reading":"しくみ","romaji":"shikumi","meaning":"mekanisme/sistem"},
   {"word":"原材料","reading":"げんざいりょう","romaji":"genzairyou","meaning":"bahan baku"},
   {"word":"賞味期限","reading":"しょうみきげん","romaji":"shoumi kigen","meaning":"tanggal kedaluwarsa (kualitas)"},
   {"word":"消費者","reading":"しょうひしゃ","romaji":"shouhisha","meaning":"konsumen"},
   {"word":"農薬","reading":"のうやく","romaji":"nouyaku","meaning":"pestisida"},
   {"word":"添加物","reading":"てんかぶつ","romaji":"tenkabutsu","meaning":"zat aditif"},
   {"word":"基準","reading":"きじゅん","romaji":"kijun","meaning":"standar/kriteria"},
   {"word":"偽る","reading":"いつわる","romaji":"itsuwaru","meaning":"memalsukan/membohongi"},
   {"word":"不正","reading":"ふせい","romaji":"fusei","meaning":"kecurangan"},
   {"word":"損なう","reading":"そこなう","romaji":"sokonau","meaning":"merusak/mencederai"},
   {"word":"清潔","reading":"せいけつ","romaji":"seiketsu","meaning":"bersih/higienis"},
   {"word":"保存","reading":"ほぞん","romaji":"hozon","meaning":"penyimpanan"},
   {"word":"生産者","reading":"せいさんしゃ","romaji":"seisansha","meaning":"produsen"}
 ]'::jsonb,
 '[
   {"q":"Apa yang menjadi perhatian besar semua orang?","options":["Harga","Keamanan makanan sehari-hari","Rasa","Kemasan"],"answer":1,"explanation":"「食べ物の安全は…大きな関心事」."},
   {"q":"Apa yang ditampilkan pada produk pangan?","options":["Harga saja","Bahan baku dan tanggal kedaluwarsa","Nama toko","Berat pengirim"],"answer":1,"explanation":"「原材料や賞味期限が表示されています」."},
   {"q":"Untuk apa standar ketat penggunaan pestisida dan aditif?","options":["Menaikkan harga","Menjaga keamanan pangan","Mempercantik kemasan","Menambah rasa"],"answer":1,"explanation":"「食の安全を守るために…厳しい基準」."},
   {"q":"Apa contoh kecurangan?","options":["Memberi diskon","Memalsukan asal produk dan mengubah tanggal","Memberi sampel","Membersihkan toko"],"answer":1,"explanation":"「産地を偽ったり、期限を書き換えたり」."},
   {"q":"Apa yang penting bagi konsumen?","options":["Membeli sebanyak mungkin","Memiliki pengetahuan yang benar","Mengabaikan label","Selalu makan di luar"],"answer":1,"explanation":"「正しい知識を持つことが大切」."},
   {"q":"Keamanan pangan dijaga oleh?","options":["Pemerintah saja","Produsen dan konsumen kedua-duanya","Konsumen saja","Toko saja"],"answer":1,"explanation":"「生産者と消費者の両方で守るもの」."}
 ]'::jsonb,
 false),
(4, 14, '外国人労働者 — Pekerja Asing',
 '近年、日本で働く外国人が増えています。その背景には、日本の深刻な人手不足があります。少子高齢化によって、働く若い世代が減っているのです。特に、農業や介護、建設などの分野で、人手が足りません。そこで、多くの外国人労働者が、日本の社会を支えています。彼らは、日本の経済にとって、なくてはならない存在です。しかし、外国人が働く上で、さまざまな問題もあります。まず、言葉の壁が大きな課題です。日本語が十分に話せないと、仕事や生活で苦労します。文化や習慣の違いから、誤解が生まれることもあります。また、不当に低い賃金で働かされる例も報告されています。外国人が安心して働ける環境を整えることが必要です。日本語を学ぶ機会を増やすことも、その一つです。地域社会が、外国人を温かく受け入れることも大切です。お互いの文化を理解し、尊重し合うことが求められています。多様な人々が共に生きる社会こそ、これからの日本の姿でしょう。',
 '[
   {"jp":"近年、日本で働く外国人が増えています。","furigana":"きんねん、にほんではたらくがいこくじんがふえています。","romaji":"Kinnen, nihon de hataraku gaikokujin ga fuete imasu.","id":"Beberapa tahun terakhir, orang asing yang bekerja di Jepang bertambah."},
   {"jp":"その背景には、日本の深刻な人手不足があります。","furigana":"そのはいけいには、にほんのしんこくなひとでぶそくがあります。","romaji":"Sono haikei ni wa, nihon no shinkoku na hitode busoku ga arimasu.","id":"Di baliknya ada kekurangan tenaga kerja yang serius di Jepang."},
   {"jp":"少子高齢化によって、働く若い世代が減っているのです。","furigana":"しょうしこうれいかによって、はたらくわかいせだいがへっているのです。","romaji":"Shoushi koureika ni yotte, hataraku wakai sedai ga hette iru no desu.","id":"Akibat penurunan kelahiran dan penuaan, generasi muda pekerja berkurang."},
   {"jp":"特に、農業や介護、建設などの分野で、人手が足りません。","furigana":"とくに、のうぎょうやかいご、けんせつなどのぶんやで、ひとでがたりません。","romaji":"Toku ni, nougyou ya kaigo, kensetsu nado no bunya de, hitode ga tarimasen.","id":"Terutama di bidang pertanian, perawatan lansia, dan konstruksi, tenaga kerja kurang."},
   {"jp":"そこで、多くの外国人労働者が、日本の社会を支えています。","furigana":"そこで、おおくのがいこくじんろうどうしゃが、にほんのしゃかいをささえています。","romaji":"Soko de, ooku no gaikokujin roudousha ga, nihon no shakai o sasaete imasu.","id":"Karena itu, banyak pekerja asing menopang masyarakat Jepang."},
   {"jp":"彼らは、日本の経済にとって、なくてはならない存在です。","furigana":"かれらは、にほんのけいざいにとって、なくてはならないそんざいです。","romaji":"Karera wa, nihon no keizai ni totte, nakute wa naranai sonzai desu.","id":"Mereka adalah keberadaan yang tak tergantikan bagi ekonomi Jepang."},
   {"jp":"しかし、外国人が働く上で、さまざまな問題もあります。","furigana":"しかし、がいこくじんがはたらくうえで、さまざまなもんだいもあります。","romaji":"Shikashi, gaikokujin ga hataraku ue de, samazama na mondai mo arimasu.","id":"Namun, dalam bekerja, orang asing pun menghadapi berbagai masalah."},
   {"jp":"まず、言葉の壁が大きな課題です。","furigana":"まず、ことばのかべがおおきなかだいです。","romaji":"Mazu, kotoba no kabe ga ooki na kadai desu.","id":"Pertama, tembok bahasa adalah tantangan besar."},
   {"jp":"日本語が十分に話せないと、仕事や生活で苦労します。","furigana":"にほんごがじゅうぶんにはなせないと、しごとやせいかつでくろうします。","romaji":"Nihongo ga juubun ni hanasenai to, shigoto ya seikatsu de kurou shimasu.","id":"Kalau tidak cukup lancar berbahasa Jepang, kesulitan dalam kerja dan kehidupan."},
   {"jp":"文化や習慣の違いから、誤解が生まれることもあります。","furigana":"ぶんかやしゅうかんのちがいから、ごかいがうまれることもあります。","romaji":"Bunka ya shuukan no chigai kara, gokai ga umareru koto mo arimasu.","id":"Dari perbedaan budaya dan kebiasaan, kadang muncul kesalahpahaman."},
   {"jp":"また、不当に低い賃金で働かされる例も報告されています。","furigana":"また、ふとうにひくいちんぎんではたらかされるれいもほうこくされています。","romaji":"Mata, futou ni hikui chingin de hatarakasareru rei mo houkoku sarete imasu.","id":"Selain itu, dilaporkan pula kasus dipekerjakan dengan upah rendah yang tidak adil."},
   {"jp":"外国人が安心して働ける環境を整えることが必要です。","furigana":"がいこくじんがあんしんしてはたらけるかんきょうをととのえることがひつようです。","romaji":"Gaikokujin ga anshin shite hatarakeru kankyou o totonoeru koto ga hitsuyou desu.","id":"Diperlukan menata lingkungan agar orang asing bisa bekerja dengan tenang."},
   {"jp":"日本語を学ぶ機会を増やすことも、その一つです。","furigana":"にほんごをまなぶきかいをふやすことも、そのひとつです。","romaji":"Nihongo o manabu kikai o fuyasu koto mo, sono hitotsu desu.","id":"Menambah kesempatan belajar bahasa Jepang juga salah satunya."},
   {"jp":"地域社会が、外国人を温かく受け入れることも大切です。","furigana":"ちいきしゃかいが、がいこくじんをあたたかくうけいれることもたいせつです。","romaji":"Chiiki shakai ga, gaikokujin o atatakaku ukeireru koto mo taisetsu desu.","id":"Penting pula bagi masyarakat setempat untuk menerima orang asing dengan hangat."},
   {"jp":"お互いの文化を理解し、尊重し合うことが求められています。","furigana":"おたがいのぶんかをりかいし、そんちょうしあうことがもとめられています。","romaji":"Otagai no bunka o rikai shi, sonchou shiau koto ga motomerarete imasu.","id":"Dituntut untuk saling memahami dan menghormati budaya masing-masing."},
   {"jp":"多様な人々が共に生きる社会こそ、これからの日本の姿でしょう。","furigana":"たようなひとびとがともにいきるしゃかいこそ、これからのにほんのすがたでしょう。","romaji":"Tayou na hitobito ga tomo ni ikiru shakai koso, korekara no nihon no sugata deshou.","id":"Masyarakat tempat beragam orang hidup bersama itulah wujud Jepang ke depan."}
 ]'::jsonb,
 '[
   {"word":"労働者","reading":"ろうどうしゃ","romaji":"roudousha","meaning":"pekerja/buruh"},
   {"word":"背景","reading":"はいけい","romaji":"haikei","meaning":"latar belakang"},
   {"word":"人手不足","reading":"ひとでぶそく","romaji":"hitode busoku","meaning":"kekurangan tenaga kerja"},
   {"word":"少子高齢化","reading":"しょうしこうれいか","romaji":"shoushi koureika","meaning":"penurunan kelahiran & penuaan"},
   {"word":"分野","reading":"ぶんや","romaji":"bunya","meaning":"bidang"},
   {"word":"介護","reading":"かいご","romaji":"kaigo","meaning":"perawatan lansia"},
   {"word":"建設","reading":"けんせつ","romaji":"kensetsu","meaning":"konstruksi"},
   {"word":"支える","reading":"ささえる","romaji":"sasaeru","meaning":"menopang/menyokong"},
   {"word":"存在","reading":"そんざい","romaji":"sonzai","meaning":"keberadaan"},
   {"word":"壁","reading":"かべ","romaji":"kabe","meaning":"tembok/hambatan"},
   {"word":"苦労","reading":"くろう","romaji":"kurou","meaning":"kesulitan/jerih payah"},
   {"word":"誤解","reading":"ごかい","romaji":"gokai","meaning":"kesalahpahaman"},
   {"word":"不当","reading":"ふとう","romaji":"futou","meaning":"tidak adil"},
   {"word":"賃金","reading":"ちんぎん","romaji":"chingin","meaning":"upah"},
   {"word":"受け入れる","reading":"うけいれる","romaji":"ukeireru","meaning":"menerima"}
 ]'::jsonb,
 '[
   {"q":"Apa latar belakang bertambahnya pekerja asing?","options":["Pariwisata","Kekurangan tenaga kerja yang serius","Banyaknya turis","Cuaca"],"answer":1,"explanation":"「深刻な人手不足があります」."},
   {"q":"Di bidang apa terutama kekurangan tenaga?","options":["Hiburan","Pertanian, perawatan lansia, konstruksi","Keuangan","Olahraga"],"answer":1,"explanation":"「農業や介護、建設などの分野」."},
   {"q":"Apa tantangan terbesar bagi pekerja asing?","options":["Cuaca","Tembok bahasa","Makanan","Transportasi"],"answer":1,"explanation":"「言葉の壁が大きな課題」."},
   {"q":"Masalah apa yang dilaporkan terkait upah?","options":["Upah terlalu tinggi","Dipekerjakan dengan upah rendah yang tidak adil","Tanpa upah libur","Bonus besar"],"answer":1,"explanation":"「不当に低い賃金で働かされる例」."},
   {"q":"Salah satu hal yang perlu dilakukan?","options":["Mengurangi pekerja","Menambah kesempatan belajar bahasa Jepang","Melarang mereka","Menutup bidang itu"],"answer":1,"explanation":"「日本語を学ぶ機会を増やすこと」."},
   {"q":"Apa wujud Jepang ke depan menurut teks?","options":["Masyarakat tertutup","Masyarakat beragam yang hidup bersama","Hanya orang Jepang","Tanpa pekerja asing"],"answer":1,"explanation":"「多様な人々が共に生きる社会」."}
 ]'::jsonb,
 false),
(4, 15, 'プラスチックごみ — Sampah Plastik',
 'プラスチックは、私たちの生活に欠かせない便利な素材です。軽くて丈夫で、安く作れるという利点があります。しかし、その便利さの一方で、大きな問題を引き起こしています。使い終わったプラスチックの多くは、ゴミになります。プラスチックは、自然の中でほとんど分解されません。そのため、長い間、環境に残り続けます。特に深刻なのが、海に流れ込むプラスチックごみです。海の生き物が、それを餌と間違えて食べてしまいます。その結果、多くの生き物が命を落としています。さらに、細かく砕けたプラスチックは、私たちの体にも入る恐れがあります。この問題を解決するために、世界中で取り組みが始まっています。例えば、レジ袋を有料にする店が増えました。プラスチックの代わりに、紙や再利用できる素材を使う動きもあります。私たち一人一人にも、できることがあります。マイバッグを持ち歩いたり、ゴミを正しく分別したりすることです。美しい海と地球を守るために、今すぐ行動を始めましょう。',
 '[
   {"jp":"プラスチックは、私たちの生活に欠かせない便利な素材です。","furigana":"プラスチックは、わたしたちのせいかつにかかせないべんりなそざいです。","romaji":"Purasuchikku wa, watashitachi no seikatsu ni kakasenai benri na sozai desu.","id":"Plastik adalah material praktis yang tak terpisahkan dari hidup kita."},
   {"jp":"軽くて丈夫で、安く作れるという利点があります。","furigana":"かるくてじょうぶで、やすくつくれるというりてんがあります。","romaji":"Karukute joubu de, yasuku tsukureru to iu riten ga arimasu.","id":"Plastik punya kelebihan: ringan, kuat, dan murah dibuat."},
   {"jp":"しかし、その便利さの一方で、大きな問題を引き起こしています。","furigana":"しかし、そのべんりさのいっぽうで、おおきなもんだいをひきおこしています。","romaji":"Shikashi, sono benrisa no ippou de, ooki na mondai o hikiokoshite imasu.","id":"Namun, di balik kepraktisannya, ia menimbulkan masalah besar."},
   {"jp":"使い終わったプラスチックの多くは、ゴミになります。","furigana":"つかいおわったプラスチックのおおくは、ゴミになります。","romaji":"Tsukai owatta purasuchikku no ooku wa, gomi ni narimasu.","id":"Sebagian besar plastik yang sudah dipakai menjadi sampah."},
   {"jp":"プラスチックは、自然の中でほとんど分解されません。","furigana":"プラスチックは、しぜんのなかでほとんどぶんかいされません。","romaji":"Purasuchikku wa, shizen no naka de hotondo bunkai saremasen.","id":"Plastik hampir tidak terurai di alam."},
   {"jp":"そのため、長い間、環境に残り続けます。","furigana":"そのため、ながいあいだ、かんきょうにのこりつづけます。","romaji":"Sono tame, nagai aida, kankyou ni nokoritsuzukemasu.","id":"Karena itu, ia terus tertinggal di lingkungan dalam waktu lama."},
   {"jp":"特に深刻なのが、海に流れ込むプラスチックごみです。","furigana":"とくにしんこくなのが、うみにながれこむプラスチックごみです。","romaji":"Toku ni shinkoku na no ga, umi ni nagarekomu purasuchikku gomi desu.","id":"Yang terutama serius adalah sampah plastik yang mengalir ke laut."},
   {"jp":"海の生き物が、それを餌と間違えて食べてしまいます。","furigana":"うみのいきものが、それをえさとまちがえてたべてしまいます。","romaji":"Umi no ikimono ga, sore o esa to machigaete tabete shimaimasu.","id":"Makhluk laut memakannya karena mengiranya sebagai makanan."},
   {"jp":"その結果、多くの生き物が命を落としています。","furigana":"そのけっか、おおくのいきものがいのちをおとしています。","romaji":"Sono kekka, ooku no ikimono ga inochi o otoshite imasu.","id":"Akibatnya, banyak makhluk hidup yang kehilangan nyawa."},
   {"jp":"さらに、細かく砕けたプラスチックは、私たちの体にも入る恐れがあります。","furigana":"さらに、こまかくくだけたプラスチックは、わたしたちのからだにもはいるおそれがあります。","romaji":"Sara ni, komakaku kudaketa purasuchikku wa, watashitachi no karada ni mo hairu osore ga arimasu.","id":"Lebih jauh, plastik yang hancur halus berisiko masuk ke tubuh kita juga."},
   {"jp":"この問題を解決するために、世界中で取り組みが始まっています。","furigana":"このもんだいをかいけつするために、せかいじゅうでとりくみがはじまっています。","romaji":"Kono mondai o kaiketsu suru tame ni, sekaijuu de torikumi ga hajimatte imasu.","id":"Untuk menyelesaikan masalah ini, upaya mulai dilakukan di seluruh dunia."},
   {"jp":"例えば、レジ袋を有料にする店が増えました。","furigana":"たとえば、レジぶくろをゆうりょうにするみせがふえました。","romaji":"Tatoeba, reji bukuro o yuuryou ni suru mise ga fuemashita.","id":"Misalnya, toko yang mengenakan biaya untuk kantong plastik bertambah."},
   {"jp":"プラスチックの代わりに、紙や再利用できる素材を使う動きもあります。","furigana":"プラスチックのかわりに、かみやさいりようできるそざいをつかううごきもあります。","romaji":"Purasuchikku no kawari ni, kami ya sairiyou dekiru sozai o tsukau ugoki mo arimasu.","id":"Ada juga gerakan memakai kertas atau bahan yang bisa didaur ulang sebagai ganti plastik."},
   {"jp":"私たち一人一人にも、できることがあります。","furigana":"わたしたちひとりひとりにも、できることがあります。","romaji":"Watashitachi hitori hitori ni mo, dekiru koto ga arimasu.","id":"Kita masing-masing pun punya hal yang bisa dilakukan."},
   {"jp":"マイバッグを持ち歩いたり、ゴミを正しく分別したりすることです。","furigana":"マイバッグをもちあるいたり、ゴミをただしくぶんべつしたりすることです。","romaji":"Mai baggu o mochiaruitari, gomi o tadashiku bunbetsu shitari suru koto desu.","id":"Yaitu membawa tas belanja sendiri dan memilah sampah dengan benar."},
   {"jp":"美しい海と地球を守るために、今すぐ行動を始めましょう。","furigana":"うつくしいうみとちきゅうをまもるために、いますぐこうどうをはじめましょう。","romaji":"Utsukushii umi to chikyuu o mamoru tame ni, ima sugu koudou o hajimemashou.","id":"Demi menjaga laut dan bumi yang indah, mari mulai bertindak sekarang juga."}
 ]'::jsonb,
 '[
   {"word":"素材","reading":"そざい","romaji":"sozai","meaning":"material/bahan"},
   {"word":"丈夫","reading":"じょうぶ","romaji":"joubu","meaning":"kuat/awet"},
   {"word":"引き起こす","reading":"ひきおこす","romaji":"hikiokosu","meaning":"menyebabkan/menimbulkan"},
   {"word":"分解","reading":"ぶんかい","romaji":"bunkai","meaning":"penguraian/terurai"},
   {"word":"残り続ける","reading":"のこりつづける","romaji":"nokoritsuzukeru","meaning":"terus tersisa"},
   {"word":"流れ込む","reading":"ながれこむ","romaji":"nagarekomu","meaning":"mengalir masuk"},
   {"word":"餌","reading":"えさ","romaji":"esa","meaning":"umpan/pakan"},
   {"word":"間違える","reading":"まちがえる","romaji":"machigaeru","meaning":"salah mengira"},
   {"word":"命を落とす","reading":"いのちをおとす","romaji":"inochi o otosu","meaning":"kehilangan nyawa"},
   {"word":"砕ける","reading":"くだける","romaji":"kudakeru","meaning":"hancur/pecah"},
   {"word":"取り組み","reading":"とりくみ","romaji":"torikumi","meaning":"upaya/usaha"},
   {"word":"レジ袋","reading":"レジぶくろ","romaji":"reji bukuro","meaning":"kantong plastik belanja"},
   {"word":"有料","reading":"ゆうりょう","romaji":"yuuryou","meaning":"berbayar"},
   {"word":"代わり","reading":"かわり","romaji":"kawari","meaning":"pengganti"},
   {"word":"分別","reading":"ぶんべつ","romaji":"bunbetsu","meaning":"pemilahan (sampah)"}
 ]'::jsonb,
 '[
   {"q":"Kenapa plastik praktis?","options":["Mahal","Ringan, kuat, murah dibuat","Berat","Sulit dibuat"],"answer":1,"explanation":"「軽くて丈夫で、安く作れる」."},
   {"q":"Apa masalah plastik di alam?","options":["Cepat terurai","Hampir tidak terurai","Menguap","Larut dalam air"],"answer":1,"explanation":"「ほとんど分解されません」."},
   {"q":"Apa yang paling serius?","options":["Sampah di gunung","Sampah plastik yang mengalir ke laut","Asap","Kebisingan"],"answer":1,"explanation":"「海に流れ込むプラスチックごみ」."},
   {"q":"Kenapa makhluk laut mati?","options":["Kedinginan","Salah mengira plastik sebagai makanan","Kepanasan","Kelaparan alami"],"answer":1,"explanation":"「餌と間違えて食べてしまいます」."},
   {"q":"Apa contoh upaya yang dilakukan?","options":["Menggratiskan plastik","Mengenakan biaya kantong plastik","Membakar sampah","Membuang ke laut"],"answer":1,"explanation":"「レジ袋を有料にする店が増えました」."},
   {"q":"Apa yang bisa kita lakukan?","options":["Membeli lebih banyak plastik","Membawa tas sendiri dan memilah sampah","Mengabaikannya","Membuang sembarangan"],"answer":1,"explanation":"「マイバッグを持ち歩いたり、ゴミを正しく分別したり」."}
 ]'::jsonb,
 false);
