-- ============================================================
-- Koto no Ha — Seed Dokkai N1 (level_id=5) TAMBAHAN: 10 bacaan (order_index 6-15).
-- ~600-800 huruf, 18 kalimat. Tema akademis/abstrak. 15 kosakata + 6 soal per bacaan.
-- Hanya INSERT (tidak menghapus bacaan lama).
-- ============================================================
INSERT INTO public.dokkai_passages (level_id, order_index, title, text_content, content_json, vocab_notes, questions, is_premium) VALUES
(5, 6, '遺伝子工学の倫理 — Etika Rekayasa Genetika',
 '近年、遺伝子工学は目覚ましい発展を遂げています。科学者たちは、生物の遺伝子を自由に操作できるようになりつつあります。この技術は、私たちに大きな恩恵をもたらす可能性を秘めています。例えば、これまで治せなかった病気の治療法が見つかるかもしれません。農作物の品種改良によって、食糧問題の解決も期待されています。しかし、その一方で、深刻な倫理的問題も指摘されています。特に議論を呼んでいるのが、人間の遺伝子を操作することの是非です。親が子どもの容姿や能力を、生まれる前に選べるとしたらどうでしょうか。このような「デザイナーベビー」には、強い反対の声があります。命を人工的に操作することは、許されるのかという根本的な問いが残ります。また、遺伝子情報が、差別に利用される恐れも否定できません。技術が進歩するほど、それを使う人間の責任は重くなります。科学の進歩そのものを、止めることはできないでしょう。だからこそ、明確なルールと社会的な合意が不可欠です。私たちは、何ができるかだけでなく、何をすべきかを問わなければなりません。科学技術を、人類の幸福のために正しく使う知恵が求められています。倫理を伴わない技術は、時に危険な結果を招きます。未来の世代のためにも、慎重な議論を重ねていく必要があります。',
 '[
   {"jp":"近年、遺伝子工学は目覚ましい発展を遂げています。","furigana":"きんねん、いでんしこうがくはめざましいはってんをとげています。","romaji":"Kinnen, idenshi kougaku wa mezamashii hatten o togete imasu.","id":"Beberapa tahun terakhir, rekayasa genetika mengalami perkembangan yang luar biasa."},
   {"jp":"科学者たちは、生物の遺伝子を自由に操作できるようになりつつあります。","furigana":"かがくしゃたちは、せいぶつのいでんしをじゆうにそうさできるようになりつつあります。","romaji":"Kagakusha-tachi wa, seibutsu no idenshi o jiyuu ni sousa dekiru you ni naritsutsu arimasu.","id":"Para ilmuwan kian mampu memanipulasi gen makhluk hidup dengan bebas."},
   {"jp":"この技術は、私たちに大きな恩恵をもたらす可能性を秘めています。","furigana":"このぎじゅつは、わたしたちにおおきなおんけいをもたらすかのうせいをひめています。","romaji":"Kono gijutsu wa, watashitachi ni ooki na onkei o motarasu kanousei o himete imasu.","id":"Teknologi ini menyimpan kemungkinan membawa manfaat besar bagi kita."},
   {"jp":"例えば、これまで治せなかった病気の治療法が見つかるかもしれません。","furigana":"たとえば、これまでなおせなかったびょうきのちりょうほうがみつかるかもしれません。","romaji":"Tatoeba, kore made naosenakatta byouki no chiryouhou ga mitsukaru kamoshiremasen.","id":"Misalnya, mungkin ditemukan pengobatan bagi penyakit yang selama ini tak tersembuhkan."},
   {"jp":"農作物の品種改良によって、食糧問題の解決も期待されています。","furigana":"のうさくぶつのひんしゅかいりょうによって、しょくりょうもんだいのかいけつもきたいされています。","romaji":"Nousakubutsu no hinshu kairyou ni yotte, shokuryou mondai no kaiketsu mo kitai sarete imasu.","id":"Lewat pemuliaan varietas tanaman, penyelesaian masalah pangan pun diharapkan."},
   {"jp":"しかし、その一方で、深刻な倫理的問題も指摘されています。","furigana":"しかし、そのいっぽうで、しんこくなりんりてきもんだいもしてきされています。","romaji":"Shikashi, sono ippou de, shinkoku na rinriteki mondai mo shiteki sarete imasu.","id":"Namun di sisi lain, masalah etis yang serius pun ditunjukkan."},
   {"jp":"特に議論を呼んでいるのが、人間の遺伝子を操作することの是非です。","furigana":"とくにぎろんをよんでいるのが、にんげんのいでんしをそうさすることのぜひです。","romaji":"Toku ni giron o yonde iru no ga, ningen no idenshi o sousa suru koto no zehi desu.","id":"Yang terutama memicu perdebatan adalah boleh-tidaknya memanipulasi gen manusia."},
   {"jp":"親が子どもの容姿や能力を、生まれる前に選べるとしたらどうでしょうか。","furigana":"おやがこどものようしやのうりょくを、うまれるまえにえらべるとしたらどうでしょうか。","romaji":"Oya ga kodomo no youshi ya nouryoku o, umareru mae ni eraberu to shitara dou deshou ka.","id":"Bagaimana jika orang tua bisa memilih penampilan dan kemampuan anaknya sebelum lahir?"},
   {"jp":"このような「デザイナーベビー」には、強い反対の声があります。","furigana":"このような「デザイナーベビー」には、つよいはんたいのこえがあります。","romaji":"Kono you na \"dezainaa bebii\" ni wa, tsuyoi hantai no koe ga arimasu.","id":"Terhadap \"designer baby\" semacam ini, ada suara penolakan yang kuat."},
   {"jp":"命を人工的に操作することは、許されるのかという根本的な問いが残ります。","furigana":"いのちをじんこうてきにそうさすることは、ゆるされるのかというこんぽんてきなといがのこります。","romaji":"Inochi o jinkouteki ni sousa suru koto wa, yurusareru no ka to iu konponteki na toi ga nokorimasu.","id":"Tersisa pertanyaan mendasar: bolehkah memanipulasi kehidupan secara buatan?"},
   {"jp":"また、遺伝子情報が、差別に利用される恐れも否定できません。","furigana":"また、いでんしじょうほうが、さべつにりようされるおそれもひていできません。","romaji":"Mata, idenshi jouhou ga, sabetsu ni riyou sareru osore mo hitei dekimasen.","id":"Selain itu, tak bisa disangkal risiko data genetik dipakai untuk diskriminasi."},
   {"jp":"技術が進歩するほど、それを使う人間の責任は重くなります。","furigana":"ぎじゅつがしんぽするほど、それをつかうにんげんのせきにんはおもくなります。","romaji":"Gijutsu ga shinpo suru hodo, sore o tsukau ningen no sekinin wa omoku narimasu.","id":"Makin maju teknologinya, makin berat tanggung jawab manusia yang memakainya."},
   {"jp":"科学の進歩そのものを、止めることはできないでしょう。","furigana":"かがくのしんぽそのものを、とめることはできないでしょう。","romaji":"Kagaku no shinpo sono mono o, tomeru koto wa dekinai deshou.","id":"Kemajuan sains itu sendiri agaknya tak mungkin dihentikan."},
   {"jp":"だからこそ、明確なルールと社会的な合意が不可欠です。","furigana":"だからこそ、めいかくなルールとしゃかいてきなごういがふかけつです。","romaji":"Dakara koso, meikaku na ruuru to shakaiteki na goui ga fukaketsu desu.","id":"Justru karena itu, aturan yang jelas dan kesepakatan sosial mutlak diperlukan."},
   {"jp":"私たちは、何ができるかだけでなく、何をすべきかを問わなければなりません。","furigana":"わたしたちは、なにができるかだけでなく、なにをすべきかをとわなければなりません。","romaji":"Watashitachi wa, nani ga dekiru ka dake de naku, nani o subeki ka o towanakereba narimasen.","id":"Kita harus mempertanyakan bukan hanya apa yang bisa, tapi apa yang seharusnya dilakukan."},
   {"jp":"科学技術を、人類の幸福のために正しく使う知恵が求められています。","furigana":"かがくぎじゅつを、じんるいのこうふくのためにただしくつかうちえがもとめられています。","romaji":"Kagaku gijutsu o, jinrui no koufuku no tame ni tadashiku tsukau chie ga motomerarete imasu.","id":"Dibutuhkan kebijaksanaan memakai iptek dengan benar demi kebahagiaan umat manusia."},
   {"jp":"倫理を伴わない技術は、時に危険な結果を招きます。","furigana":"りんりをともなわないぎじゅつは、ときにきけんなけっかをまねきます。","romaji":"Rinri o tomonawanai gijutsu wa, toki ni kiken na kekka o manekimasu.","id":"Teknologi tanpa disertai etika kadang mengundang akibat yang berbahaya."},
   {"jp":"未来の世代のためにも、慎重な議論を重ねていく必要があります。","furigana":"みらいのせだいのためにも、しんちょうなぎろんをかさねていくひつようがあります。","romaji":"Mirai no sedai no tame ni mo, shinchou na giron o kasanete iku hitsuyou ga arimasu.","id":"Demi generasi mendatang pun, kita perlu terus menumpuk diskusi yang cermat."}
 ]'::jsonb,
 '[
   {"word":"遺伝子工学","reading":"いでんしこうがく","romaji":"idenshi kougaku","meaning":"rekayasa genetika"},
   {"word":"目覚ましい","reading":"めざましい","romaji":"mezamashii","meaning":"luar biasa/mencolok"},
   {"word":"操作","reading":"そうさ","romaji":"sousa","meaning":"memanipulasi/mengoperasikan"},
   {"word":"恩恵","reading":"おんけい","romaji":"onkei","meaning":"manfaat/anugerah"},
   {"word":"秘める","reading":"ひめる","romaji":"himeru","meaning":"menyimpan (potensi)"},
   {"word":"品種改良","reading":"ひんしゅかいりょう","romaji":"hinshu kairyou","meaning":"pemuliaan varietas"},
   {"word":"倫理的","reading":"りんりてき","romaji":"rinriteki","meaning":"etis"},
   {"word":"是非","reading":"ぜひ","romaji":"zehi","meaning":"baik-buruk/boleh-tidaknya"},
   {"word":"容姿","reading":"ようし","romaji":"youshi","meaning":"penampilan fisik"},
   {"word":"根本的","reading":"こんぽんてき","romaji":"konponteki","meaning":"fundamental/mendasar"},
   {"word":"否定","reading":"ひてい","romaji":"hitei","meaning":"menyangkal/negasi"},
   {"word":"合意","reading":"ごうい","romaji":"goui","meaning":"kesepakatan"},
   {"word":"不可欠","reading":"ふかけつ","romaji":"fukaketsu","meaning":"mutlak diperlukan"},
   {"word":"知恵","reading":"ちえ","romaji":"chie","meaning":"kebijaksanaan/akal"},
   {"word":"慎重","reading":"しんちょう","romaji":"shinchou","meaning":"hati-hati/cermat"}
 ]'::jsonb,
 '[
   {"q":"Apa yang berkembang pesat menurut teks?","options":["Robotika","Rekayasa genetika","Eksplorasi antariksa","Internet"],"answer":1,"explanation":"「遺伝子工学は目覚ましい発展を遂げています」."},
   {"q":"Apa contoh manfaatnya?","options":["Mobil terbang","Pengobatan penyakit yang dulu tak tersembuhkan","Energi gratis","Teleportasi"],"answer":1,"explanation":"「治せなかった病気の治療法が見つかるかも」."},
   {"q":"Apa yang paling memicu perdebatan?","options":["Harga teknologi","Boleh-tidaknya memanipulasi gen manusia","Kecepatan internet","Polusi"],"answer":1,"explanation":"「人間の遺伝子を操作することの是非」."},
   {"q":"Apa istilah memilih ciri anak sebelum lahir?","options":["Cloning","Designer baby","Robot baby","Bayi tabung"],"answer":1,"explanation":"「『デザイナーベビー』」."},
   {"q":"Apa risiko data genetik yang tak bisa disangkal?","options":["Untuk hiburan","Dipakai untuk diskriminasi","Untuk olahraga","Tidak berguna"],"answer":1,"explanation":"「差別に利用される恐れ」."},
   {"q":"Apa yang harus kita tanyakan menurut teks?","options":["Apa yang murah","Bukan hanya apa yang bisa, tapi apa yang seharusnya dilakukan","Apa yang cepat","Siapa yang untung"],"answer":1,"explanation":"「何ができるかだけでなく、何をすべきか」."}
 ]'::jsonb,
 false),
(5, 7, '表現の自由 — Kebebasan Berekspresi',
 '表現の自由は、民主主義社会の根幹をなす重要な権利です。人々が自由に意見を述べ、情報を発信できることは、社会の発展に欠かせません。権力を批判する自由がなければ、健全な社会は成り立ちません。多様な意見がぶつかり合うことで、より良い結論が生まれます。しかし、表現の自由は、決して無制限のものではありません。自分の自由が、他人の権利を侵害してはならないのです。例えば、特定の個人や集団を傷つける発言は、許されません。根拠のない噂や差別的な言葉は、人を深く傷つけることがあります。インターネットの登場で、誰もが簡単に発信できるようになりました。その反面、無責任な発言や誹謗中傷も増えています。匿名性に隠れて、他人を攻撃する人も少なくありません。自由には、常に責任が伴うということを忘れてはなりません。何を言ってもいいということと、何を言っても許されるということは違います。私たちは、自分の言葉が持つ力を、十分に自覚すべきです。表現の自由を守りつつ、その乱用を防ぐことは難しい課題です。このバランスをどう取るかは、社会全体で考えるべき問題です。互いの違いを認め、尊重する姿勢が、何よりも大切でしょう。自由と責任の調和こそが、成熟した社会の証なのです。',
 '[
   {"jp":"表現の自由は、民主主義社会の根幹をなす重要な権利です。","furigana":"ひょうげんのじゆうは、みんしゅしゅぎしゃかいのこんかんをなすじゅうようなけんりです。","romaji":"Hyougen no jiyuu wa, minshu shugi shakai no konkan o nasu juuyou na kenri desu.","id":"Kebebasan berekspresi adalah hak penting yang menjadi pondasi masyarakat demokrasi."},
   {"jp":"人々が自由に意見を述べ、情報を発信できることは、社会の発展に欠かせません。","furigana":"ひとびとがじゆうにいけんをのべ、じょうほうをはっしんできることは、しゃかいのはってんにかかせません。","romaji":"Hitobito ga jiyuu ni iken o nobe, jouhou o hasshin dekiru koto wa, shakai no hatten ni kakasemasen.","id":"Bahwa orang bisa bebas menyatakan pendapat dan menyiarkan informasi tak terpisahkan dari kemajuan masyarakat."},
   {"jp":"権力を批判する自由がなければ、健全な社会は成り立ちません。","furigana":"けんりょくをひはんするじゆうがなければ、けんぜんなしゃかいはなりたちません。","romaji":"Kenryoku o hihan suru jiyuu ga nakereba, kenzen na shakai wa naritachimasen.","id":"Tanpa kebebasan mengkritik kekuasaan, masyarakat yang sehat tak akan terbentuk."},
   {"jp":"多様な意見がぶつかり合うことで、より良い結論が生まれます。","furigana":"たようないけんがぶつかりあうことで、よりよいけつろんがうまれます。","romaji":"Tayou na iken ga butsukariau koto de, yori yoi ketsuron ga umaremasu.","id":"Dengan benturan beragam pendapat, lahirlah kesimpulan yang lebih baik."},
   {"jp":"しかし、表現の自由は、決して無制限のものではありません。","furigana":"しかし、ひょうげんのじゆうは、けっしてむせいげんのものではありません。","romaji":"Shikashi, hyougen no jiyuu wa, kesshite museigen no mono de wa arimasen.","id":"Namun, kebebasan berekspresi sama sekali bukan tanpa batas."},
   {"jp":"自分の自由が、他人の権利を侵害してはならないのです。","furigana":"じぶんのじゆうが、たにんのけんりをしんがいしてはならないのです。","romaji":"Jibun no jiyuu ga, tanin no kenri o shingai shite wa naranai no desu.","id":"Kebebasan diri sendiri tidak boleh melanggar hak orang lain."},
   {"jp":"例えば、特定の個人や集団を傷つける発言は、許されません。","furigana":"たとえば、とくていのこじんやしゅうだんをきずつけるはつげんは、ゆるされません。","romaji":"Tatoeba, tokutei no kojin ya shuudan o kizutsukeru hatsugen wa, yurusaremasen.","id":"Misalnya, ucapan yang melukai individu atau kelompok tertentu tidak diperbolehkan."},
   {"jp":"根拠のない噂や差別的な言葉は、人を深く傷つけることがあります。","furigana":"こんきょのないうわさやさべつてきなことばは、ひとをふかくきずつけることがあります。","romaji":"Konkyo no nai uwasa ya sabetsuteki na kotoba wa, hito o fukaku kizutsukeru koto ga arimasu.","id":"Rumor tak berdasar dan kata-kata diskriminatif dapat melukai orang secara mendalam."},
   {"jp":"インターネットの登場で、誰もが簡単に発信できるようになりました。","furigana":"インターネットのとうじょうで、だれもがかんたんにはっしんできるようになりました。","romaji":"Intaanetto no toujou de, dare mo ga kantan ni hasshin dekiru you ni narimashita.","id":"Dengan hadirnya internet, siapa pun jadi mudah menyiarkan informasi."},
   {"jp":"その反面、無責任な発言や誹謗中傷も増えています。","furigana":"そのはんめん、むせきにんなはつげんやひぼうちゅうしょうもふえています。","romaji":"Sono hanmen, musekinin na hatsugen ya hibou chuushou mo fuete imasu.","id":"Sebaliknya, ucapan tak bertanggung jawab dan fitnah pun bertambah."},
   {"jp":"匿名性に隠れて、他人を攻撃する人も少なくありません。","furigana":"とくめいせいにかくれて、たにんをこうげきするひともすくなくありません。","romaji":"Tokumeisei ni kakurete, tanin o kougeki suru hito mo sukunaku arimasen.","id":"Tak sedikit orang yang menyerang orang lain dengan bersembunyi di balik anonimitas."},
   {"jp":"自由には、常に責任が伴うということを忘れてはなりません。","furigana":"じゆうには、つねにせきにんがともなうということをわすれてはなりません。","romaji":"Jiyuu ni wa, tsune ni sekinin ga tomonau to iu koto o wasurete wa narimasen.","id":"Kita tak boleh lupa bahwa kebebasan selalu disertai tanggung jawab."},
   {"jp":"何を言ってもいいということと、何を言っても許されるということは違います。","furigana":"なにをいってもいいということと、なにをいってもゆるされるということはちがいます。","romaji":"Nani o itte mo ii to iu koto to, nani o itte mo yurusareru to iu koto wa chigaimasu.","id":"Boleh mengatakan apa saja berbeda dengan apa saja yang dikatakan boleh saja."},
   {"jp":"私たちは、自分の言葉が持つ力を、十分に自覚すべきです。","furigana":"わたしたちは、じぶんのことばがもつちからを、じゅうぶんにじかくすべきです。","romaji":"Watashitachi wa, jibun no kotoba ga motsu chikara o, juubun ni jikaku subeki desu.","id":"Kita seharusnya cukup menyadari kekuatan yang dimiliki kata-kata kita."},
   {"jp":"表現の自由を守りつつ、その乱用を防ぐことは難しい課題です。","furigana":"ひょうげんのじゆうをまもりつつ、そのらんようをふせぐことはむずかしいかだいです。","romaji":"Hyougen no jiyuu o mamoritsutsu, sono ran-you o fusegu koto wa muzukashii kadai desu.","id":"Menjaga kebebasan berekspresi sambil mencegah penyalahgunaannya adalah tantangan sulit."},
   {"jp":"このバランスをどう取るかは、社会全体で考えるべき問題です。","furigana":"このバランスをどうとるかは、しゃかいぜんたいでかんがえるべきもんだいです。","romaji":"Kono baransu o dou toru ka wa, shakai zentai de kangaeru beki mondai desu.","id":"Bagaimana mengambil keseimbangan ini adalah masalah yang harus dipikirkan seluruh masyarakat."},
   {"jp":"互いの違いを認め、尊重する姿勢が、何よりも大切でしょう。","furigana":"たがいのちがいをみとめ、そんちょうするしせいが、なによりもたいせつでしょう。","romaji":"Tagai no chigai o mitome, sonchou suru shisei ga, nani yori mo taisetsu deshou.","id":"Sikap mengakui dan menghormati perbedaan satu sama lain agaknya yang terpenting."},
   {"jp":"自由と責任の調和こそが、成熟した社会の証なのです。","furigana":"じゆうとせきにんのちょうわこそが、せいじゅくしたしゃかいのあかしなのです。","romaji":"Jiyuu to sekinin no chouwa koso ga, seijuku shita shakai no akashi na no desu.","id":"Keselarasan kebebasan dan tanggung jawab itulah bukti masyarakat yang matang."}
 ]'::jsonb,
 '[
   {"word":"表現の自由","reading":"ひょうげんのじゆう","romaji":"hyougen no jiyuu","meaning":"kebebasan berekspresi"},
   {"word":"民主主義","reading":"みんしゅしゅぎ","romaji":"minshu shugi","meaning":"demokrasi"},
   {"word":"根幹","reading":"こんかん","romaji":"konkan","meaning":"pondasi/inti"},
   {"word":"権利","reading":"けんり","romaji":"kenri","meaning":"hak"},
   {"word":"発信","reading":"はっしん","romaji":"hasshin","meaning":"menyiarkan/mengirim info"},
   {"word":"批判","reading":"ひはん","romaji":"hihan","meaning":"kritik"},
   {"word":"健全","reading":"けんぜん","romaji":"kenzen","meaning":"sehat/wajar"},
   {"word":"侵害","reading":"しんがい","romaji":"shingai","meaning":"pelanggaran"},
   {"word":"根拠","reading":"こんきょ","romaji":"konkyo","meaning":"dasar/bukti"},
   {"word":"誹謗中傷","reading":"ひぼうちゅうしょう","romaji":"hibou chuushou","meaning":"fitnah/pencemaran nama"},
   {"word":"匿名性","reading":"とくめいせい","romaji":"tokumeisei","meaning":"anonimitas"},
   {"word":"自覚","reading":"じかく","romaji":"jikaku","meaning":"kesadaran diri"},
   {"word":"乱用","reading":"らんよう","romaji":"ran-you","meaning":"penyalahgunaan"},
   {"word":"調和","reading":"ちょうわ","romaji":"chouwa","meaning":"keselarasan/harmoni"},
   {"word":"成熟","reading":"せいじゅく","romaji":"seijuku","meaning":"kematangan"}
 ]'::jsonb,
 '[
   {"q":"Kebebasan berekspresi mendasari apa?","options":["Ekonomi pasar","Masyarakat demokrasi","Militer","Agama"],"answer":1,"explanation":"「民主主義社会の根幹をなす」."},
   {"q":"Tanpa kebebasan apa masyarakat tidak sehat?","options":["Kebebasan belanja","Kebebasan mengkritik kekuasaan","Kebebasan bepergian","Kebebasan beragama"],"answer":1,"explanation":"「権力を批判する自由がなければ」."},
   {"q":"Kebebasan berekspresi bersifat?","options":["Tanpa batas","Tidak tanpa batas","Hanya untuk pejabat","Dilarang"],"answer":1,"explanation":"「決して無制限のものではありません」."},
   {"q":"Apa yang tidak diperbolehkan?","options":["Memuji orang","Ucapan yang melukai individu/kelompok tertentu","Bertanya","Berdiskusi"],"answer":1,"explanation":"「特定の個人や集団を傷つける発言は、許されません」."},
   {"q":"Apa yang meningkat seiring internet?","options":["Kesopanan","Ucapan tak bertanggung jawab dan fitnah","Literasi","Diskusi ilmiah"],"answer":1,"explanation":"「無責任な発言や誹謗中傷も増えています」."},
   {"q":"Apa bukti masyarakat yang matang?","options":["Banyak hukum","Keselarasan kebebasan dan tanggung jawab","Kekuasaan yang kuat","Tidak ada media"],"answer":1,"explanation":"「自由と責任の調和こそが、成熟した社会の証」."}
 ]'::jsonb,
 false),
(5, 8, '都市化と孤独 — Urbanisasi dan Kesepian',
 '現代社会において、都市化は世界的に進行しています。多くの人々が、仕事や便利さを求めて都市に集まってきます。都市には、あらゆるものが揃っており、生活は確かに便利です。しかし、人が密集する都市の中で、皮肉にも孤独を感じる人が増えています。かつての地域社会には、近所付き合いという温かいつながりがありました。ところが、都市では、隣に誰が住んでいるのかさえ知らないことも珍しくありません。人間関係が希薄になり、人々は孤立しがちです。特に、一人暮らしの高齢者の孤独は、深刻な社会問題となっています。誰にも気づかれずに亡くなる「孤独死」という言葉も生まれました。また、SNSでつながっていても、心の底では孤独を感じる若者も少なくありません。表面的なつながりは、必ずしも心の充足をもたらすとは限らないのです。人間は、本来、他者とのつながりの中で生きる存在です。孤独は、心身の健康に深刻な影響を及ぼすと指摘されています。この問題を解決するには、地域での新たなつながりづくりが求められます。例えば、住民が交流できる場を設ける取り組みが、各地で始まっています。一人一人が、周囲の人に関心を持つことも大切です。便利さと引き換えに、私たちは何を失ったのかを考える必要があります。真の豊かさとは、人と人との温かいつながりの中にあるのかもしれません。',
 '[
   {"jp":"現代社会において、都市化は世界的に進行しています。","furigana":"げんだいしゃかいにおいて、としかはせかいてきにしんこうしています。","romaji":"Gendai shakai ni oite, toshika wa sekaiteki ni shinkou shite imasu.","id":"Dalam masyarakat modern, urbanisasi berlangsung secara global."},
   {"jp":"多くの人々が、仕事や便利さを求めて都市に集まってきます。","furigana":"おおくのひとびとが、しごとやべんりさをもとめてとしにあつまってきます。","romaji":"Ooku no hitobito ga, shigoto ya benrisa o motomete toshi ni atsumatte kimasu.","id":"Banyak orang berkumpul ke kota demi pekerjaan dan kepraktisan."},
   {"jp":"都市には、あらゆるものが揃っており、生活は確かに便利です。","furigana":"としには、あらゆるものがそろっており、せいかつはたしかにべんりです。","romaji":"Toshi ni wa, arayuru mono ga sorotte ori, seikatsu wa tashika ni benri desu.","id":"Di kota tersedia segala hal, dan hidup memang praktis."},
   {"jp":"しかし、人が密集する都市の中で、皮肉にも孤独を感じる人が増えています。","furigana":"しかし、ひとがみっしゅうするとしのなかで、ひにくにもこどくをかんじるひとがふえています。","romaji":"Shikashi, hito ga misshuu suru toshi no naka de, hiniku ni mo kodoku o kanjiru hito ga fuete imasu.","id":"Namun, di kota yang padat manusia, ironisnya orang yang merasa kesepian justru bertambah."},
   {"jp":"かつての地域社会には、近所付き合いという温かいつながりがありました。","furigana":"かつてのちいきしゃかいには、きんじょづきあいというあたたかいつながりがありました。","romaji":"Katsute no chiiki shakai ni wa, kinjo zukiai to iu atatakai tsunagari ga arimashita.","id":"Dulu di masyarakat lokal ada ikatan hangat berupa pergaulan ketetanggaan."},
   {"jp":"ところが、都市では、隣に誰が住んでいるのかさえ知らないことも珍しくありません。","furigana":"ところが、としでは、となりにだれがすんでいるのかさえしらないこともめずらしくありません。","romaji":"Tokoroga, toshi de wa, tonari ni dare ga sunde iru no ka sae shiranai koto mo mezurashiku arimasen.","id":"Namun di kota, tidak jarang orang bahkan tak tahu siapa yang tinggal di sebelahnya."},
   {"jp":"人間関係が希薄になり、人々は孤立しがちです。","furigana":"にんげんかんけいがきはくになり、ひとびとはこりつしがちです。","romaji":"Ningen kankei ga kihaku ni nari, hitobito wa koritsu shigachi desu.","id":"Hubungan antarmanusia menjadi renggang, dan orang cenderung terisolasi."},
   {"jp":"特に、一人暮らしの高齢者の孤独は、深刻な社会問題となっています。","furigana":"とくに、ひとりぐらしのこうれいしゃのこどくは、しんこくなしゃかいもんだいとなっています。","romaji":"Toku ni, hitorigurashi no koureisha no kodoku wa, shinkoku na shakai mondai to natte imasu.","id":"Terutama, kesepian lansia yang hidup sendiri menjadi masalah sosial yang serius."},
   {"jp":"誰にも気づかれずに亡くなる「孤独死」という言葉も生まれました。","furigana":"だれにもきづかれずになくなる「こどくし」ということばもうまれました。","romaji":"Dare ni mo kizukarezu ni nakunaru \"kodokushi\" to iu kotoba mo umaremashita.","id":"Lahir pula istilah \"kodokushi\", yaitu meninggal tanpa diketahui siapa pun."},
   {"jp":"また、SNSでつながっていても、心の底では孤独を感じる若者も少なくありません。","furigana":"また、エスエヌエスでつながっていても、こころのそこではこどくをかんじるわかものもすくなくありません。","romaji":"Mata, esuenuesu de tsunagatte ite mo, kokoro no soko de wa kodoku o kanjiru wakamono mo sukunaku arimasen.","id":"Selain itu, tak sedikit anak muda yang meski terhubung di SNS, di lubuk hatinya merasa kesepian."},
   {"jp":"表面的なつながりは、必ずしも心の充足をもたらすとは限らないのです。","furigana":"ひょうめんてきなつながりは、かならずしもこころのじゅうそくをもたらすとはかぎらないのです。","romaji":"Hyoumenteki na tsunagari wa, kanarazu shimo kokoro no juusoku o motarasu to wa kagiranai no desu.","id":"Hubungan yang sekadar di permukaan belum tentu membawa kepuasan batin."},
   {"jp":"人間は、本来、他者とのつながりの中で生きる存在です。","furigana":"にんげんは、ほんらい、たしゃとのつながりのなかでいきるそんざいです。","romaji":"Ningen wa, honrai, tasha to no tsunagari no naka de ikiru sonzai desu.","id":"Manusia pada hakikatnya adalah makhluk yang hidup dalam ikatan dengan sesama."},
   {"jp":"孤独は、心身の健康に深刻な影響を及ぼすと指摘されています。","furigana":"こどくは、しんしんのけんこうにしんこくなえいきょうをおよぼすとしてきされています。","romaji":"Kodoku wa, shinshin no kenkou ni shinkoku na eikyou o oyobosu to shiteki sarete imasu.","id":"Kesepian ditunjukkan dapat memberi dampak serius pada kesehatan jiwa dan raga."},
   {"jp":"この問題を解決するには、地域での新たなつながりづくりが求められます。","furigana":"このもんだいをかいけつするには、ちいきでのあらたなつながりづくりがもとめられます。","romaji":"Kono mondai o kaiketsu suru ni wa, chiiki de no arata na tsunagari zukuri ga motomeraremasu.","id":"Untuk menyelesaikan masalah ini, dibutuhkan penciptaan ikatan baru di lingkungan."},
   {"jp":"例えば、住民が交流できる場を設ける取り組みが、各地で始まっています。","furigana":"たとえば、じゅうみんがこうりゅうできるばをもうけるとりくみが、かくちではじまっています。","romaji":"Tatoeba, juumin ga kouryuu dekiru ba o moukeru torikumi ga, kakuchi de hajimatte imasu.","id":"Misalnya, upaya menyediakan tempat agar warga bisa berinteraksi mulai dilakukan di berbagai tempat."},
   {"jp":"一人一人が、周囲の人に関心を持つことも大切です。","furigana":"ひとりひとりが、しゅういのひとにかんしんをもつこともたいせつです。","romaji":"Hitori hitori ga, shuui no hito ni kanshin o motsu koto mo taisetsu desu.","id":"Penting pula bagi tiap orang untuk menaruh perhatian pada orang di sekitarnya."},
   {"jp":"便利さと引き換えに、私たちは何を失ったのかを考える必要があります。","furigana":"べんりさとひきかえに、わたしたちはなにをうしなったのかをかんがえるひつようがあります。","romaji":"Benrisa to hikikae ni, watashitachi wa nani o ushinatta no ka o kangaeru hitsuyou ga arimasu.","id":"Kita perlu memikirkan apa yang telah kita hilangkan sebagai ganti kepraktisan."},
   {"jp":"真の豊かさとは、人と人との温かいつながりの中にあるのかもしれません。","furigana":"しんのゆたかさとは、ひととひとのあたたかいつながりのなかにあるのかもしれません。","romaji":"Shin no yutakasa to wa, hito to hito to no atatakai tsunagari no naka ni aru no kamoshiremasen.","id":"Kekayaan sejati mungkin terletak di dalam ikatan hangat antarmanusia."}
 ]'::jsonb,
 '[
   {"word":"都市化","reading":"としか","romaji":"toshika","meaning":"urbanisasi"},
   {"word":"進行","reading":"しんこう","romaji":"shinkou","meaning":"berlangsung/maju"},
   {"word":"密集","reading":"みっしゅう","romaji":"misshuu","meaning":"padat/berkerumun"},
   {"word":"皮肉","reading":"ひにく","romaji":"hiniku","meaning":"ironi/sindiran"},
   {"word":"近所付き合い","reading":"きんじょづきあい","romaji":"kinjo zukiai","meaning":"pergaulan ketetanggaan"},
   {"word":"希薄","reading":"きはく","romaji":"kihaku","meaning":"tipis/renggang"},
   {"word":"孤立","reading":"こりつ","romaji":"koritsu","meaning":"terisolasi"},
   {"word":"孤独死","reading":"こどくし","romaji":"kodokushi","meaning":"kematian dalam kesepian"},
   {"word":"表面的","reading":"ひょうめんてき","romaji":"hyoumenteki","meaning":"di permukaan/dangkal"},
   {"word":"充足","reading":"じゅうそく","romaji":"juusoku","meaning":"pemenuhan/kepuasan"},
   {"word":"本来","reading":"ほんらい","romaji":"honrai","meaning":"pada hakikatnya"},
   {"word":"及ぼす","reading":"およぼす","romaji":"oyobosu","meaning":"memberikan (dampak)"},
   {"word":"交流","reading":"こうりゅう","romaji":"kouryuu","meaning":"interaksi/pertukaran"},
   {"word":"引き換え","reading":"ひきかえ","romaji":"hikikae","meaning":"sebagai ganti/imbalan"},
   {"word":"豊かさ","reading":"ゆたかさ","romaji":"yutakasa","meaning":"kekayaan/kemakmuran"}
 ]'::jsonb,
 '[
   {"q":"Apa yang berlangsung secara global?","options":["Deurbanisasi","Urbanisasi","Migrasi ke desa","Migrasi ke gunung"],"answer":1,"explanation":"「都市化は世界的に進行しています」."},
   {"q":"Ironisnya, di kota yang padat banyak orang merasa?","options":["Bahagia","Kesepian","Kaya","Aman"],"answer":1,"explanation":"「皮肉にも孤独を感じる人が増えています」."},
   {"q":"Apa yang dulu ada di masyarakat lokal?","options":["Persaingan","Ikatan hangat ketetanggaan","Kemacetan","Pasar besar"],"answer":1,"explanation":"「近所付き合いという温かいつながり」."},
   {"q":"Apa istilah meninggal tanpa diketahui siapa pun?","options":["Karoshi","Kodokushi","Shinjuu","Hikikomori"],"answer":1,"explanation":"「『孤独死』という言葉」."},
   {"q":"Terhubung di SNS, tetapi banyak anak muda?","options":["Selalu bahagia","Tetap merasa kesepian","Jadi kaya","Jadi sehat"],"answer":1,"explanation":"「心の底では孤独を感じる若者も少なくありません」."},
   {"q":"Kekayaan sejati menurut teks ada di mana?","options":["Dalam uang","Dalam ikatan hangat antarmanusia","Dalam teknologi","Dalam kota besar"],"answer":1,"explanation":"「人と人との温かいつながりの中に」."}
 ]'::jsonb,
 false),
(5, 9, '伝統文化の継承 — Pewarisan Budaya Tradisional',
 'どの国にも、長い歴史の中で育まれてきた伝統文化があります。日本には、茶道や歌舞伎、和食など、世界に誇る文化が数多く存在します。これらの伝統は、先人たちの知恵と工夫の結晶です。しかし今、多くの伝統文化が、消滅の危機に直面しています。その大きな原因の一つが、後継者の不足です。若い世代が、伝統的な仕事に魅力を感じなくなっているのです。厳しい修業や、収入の不安定さが、その背景にあります。また、生活様式の変化によって、伝統文化に触れる機会も減りました。一度失われた技術や芸能を、再び取り戻すことは極めて困難です。それは、その国の貴重なアイデンティティが失われることを意味します。伝統を守るためには、社会全体での支援が必要です。国や自治体が、後継者の育成に資金を提供する取り組みもあります。同時に、伝統を現代の生活に合わせて変化させる工夫も求められます。古いものをただ守るだけでなく、新しい価値を加えることが大切です。例えば、伝統工芸を現代のデザインと融合させる試みも見られます。そうすることで、若い世代の関心を引くことができるでしょう。伝統文化は、過去から未来へと受け継がれるべき大切な財産です。私たち一人一人が、その価値を再認識する必要があるのではないでしょうか。',
 '[
   {"jp":"どの国にも、長い歴史の中で育まれてきた伝統文化があります。","furigana":"どのくににも、ながいれきしのなかではぐくまれてきたでんとうぶんかがあります。","romaji":"Dono kuni ni mo, nagai rekishi no naka de hagukumarete kita dentou bunka ga arimasu.","id":"Setiap negara memiliki budaya tradisional yang dibina dalam sejarah panjangnya."},
   {"jp":"日本には、茶道や歌舞伎、和食など、世界に誇る文化が数多く存在します。","furigana":"にほんには、さどうやかぶき、わしょくなど、せかいにほこるぶんかがかずおおくそんざいします。","romaji":"Nihon ni wa, sadou ya kabuki, washoku nado, sekai ni hokoru bunka ga kazuooku sonzai shimasu.","id":"Jepang punya banyak budaya yang dibanggakan dunia, seperti chadou, kabuki, dan washoku."},
   {"jp":"これらの伝統は、先人たちの知恵と工夫の結晶です。","furigana":"これらのでんとうは、せんじんたちのちえとくふうのけっしょうです。","romaji":"Korera no dentou wa, senjin-tachi no chie to kufuu no kesshou desu.","id":"Tradisi-tradisi ini adalah buah dari kebijaksanaan dan kreativitas para pendahulu."},
   {"jp":"しかし今、多くの伝統文化が、消滅の危機に直面しています。","furigana":"しかしいま、おおくのでんとうぶんかが、しょうめつのききにちょくめんしています。","romaji":"Shikashi ima, ooku no dentou bunka ga, shoumetsu no kiki ni chokumen shite imasu.","id":"Namun kini, banyak budaya tradisional menghadapi ancaman kepunahan."},
   {"jp":"その大きな原因の一つが、後継者の不足です。","furigana":"そのおおきなげんいんのひとつが、こうけいしゃのふそくです。","romaji":"Sono ooki na gen-in no hitotsu ga, koukeisha no fusoku desu.","id":"Salah satu penyebab besarnya adalah kekurangan penerus."},
   {"jp":"若い世代が、伝統的な仕事に魅力を感じなくなっているのです。","furigana":"わかいせだいが、でんとうてきなしごとにみりょくをかんじなくなっているのです。","romaji":"Wakai sedai ga, dentouteki na shigoto ni miryoku o kanjinaku natte iru no desu.","id":"Generasi muda tak lagi merasakan daya tarik pada pekerjaan tradisional."},
   {"jp":"厳しい修業や、収入の不安定さが、その背景にあります。","furigana":"きびしいしゅぎょうや、しゅうにゅうのふあんていさが、そのはいけいにあります。","romaji":"Kibishii shugyou ya, shuunyuu no fuanteisa ga, sono haikei ni arimasu.","id":"Latihan yang keras dan penghasilan yang tidak stabil ada di latar belakangnya."},
   {"jp":"また、生活様式の変化によって、伝統文化に触れる機会も減りました。","furigana":"また、せいかつようしきのへんかによって、でんとうぶんかにふれるきかいもへりました。","romaji":"Mata, seikatsu youshiki no henka ni yotte, dentou bunka ni fureru kikai mo herimashita.","id":"Selain itu, akibat perubahan gaya hidup, kesempatan bersentuhan dengan budaya tradisional pun berkurang."},
   {"jp":"一度失われた技術や芸能を、再び取り戻すことは極めて困難です。","furigana":"いちどうしなわれたぎじゅつやげいのうを、ふたたびとりもどすことはきわめてこんなんです。","romaji":"Ichido ushinawareta gijutsu ya geinou o, futatabi torimodosu koto wa kiwamete konnan desu.","id":"Merebut kembali teknik atau seni yang sekali hilang sangatlah sulit."},
   {"jp":"それは、その国の貴重なアイデンティティが失われることを意味します。","furigana":"それは、そのくにのきちょうなアイデンティティがうしなわれることをいみします。","romaji":"Sore wa, sono kuni no kichou na aidentitii ga ushinawareru koto o imi shimasu.","id":"Itu berarti hilangnya identitas berharga negara tersebut."},
   {"jp":"伝統を守るためには、社会全体での支援が必要です。","furigana":"でんとうをまもるためには、しゃかいぜんたいでのしえんがひつようです。","romaji":"Dentou o mamoru tame ni wa, shakai zentai de no shien ga hitsuyou desu.","id":"Untuk menjaga tradisi, dibutuhkan dukungan seluruh masyarakat."},
   {"jp":"国や自治体が、後継者の育成に資金を提供する取り組みもあります。","furigana":"くにやじちたいが、こうけいしゃのいくせいにしきんをていきょうするとりくみもあります。","romaji":"Kuni ya jichitai ga, koukeisha no ikusei ni shikin o teikyou suru torikumi mo arimasu.","id":"Ada juga upaya negara dan pemerintah daerah menyediakan dana untuk membina penerus."},
   {"jp":"同時に、伝統を現代の生活に合わせて変化させる工夫も求められます。","furigana":"どうじに、でんとうをげんだいのせいかつにあわせてへんかさせるくふうももとめられます。","romaji":"Douji ni, dentou o gendai no seikatsu ni awasete henka saseru kufuu mo motomeraremasu.","id":"Sekaligus, dibutuhkan pula kreativitas mengubah tradisi agar sesuai kehidupan modern."},
   {"jp":"古いものをただ守るだけでなく、新しい価値を加えることが大切です。","furigana":"ふるいものをただまもるだけでなく、あたらしいかちをくわえることがたいせつです。","romaji":"Furui mono o tada mamoru dake de naku, atarashii kachi o kuwaeru koto ga taisetsu desu.","id":"Bukan hanya menjaga yang lama, tapi menambahkan nilai baru itu penting."},
   {"jp":"例えば、伝統工芸を現代のデザインと融合させる試みも見られます。","furigana":"たとえば、でんとうこうげいをげんだいのデザインとゆうごうさせるこころみもみられます。","romaji":"Tatoeba, dentou kougei o gendai no dezain to yuugou saseru kokoromi mo miraremasu.","id":"Misalnya, terlihat pula upaya memadukan kriya tradisional dengan desain modern."},
   {"jp":"そうすることで、若い世代の関心を引くことができるでしょう。","furigana":"そうすることで、わかいせだいのかんしんをひくことができるでしょう。","romaji":"Sou suru koto de, wakai sedai no kanshin o hiku koto ga dekiru deshou.","id":"Dengan begitu, agaknya bisa menarik minat generasi muda."},
   {"jp":"伝統文化は、過去から未来へと受け継がれるべき大切な財産です。","furigana":"でんとうぶんかは、かこからみらいへとうけつがれるべきたいせつなざいさんです。","romaji":"Dentou bunka wa, kako kara mirai e to uketsugareru beki taisetsu na zaisan desu.","id":"Budaya tradisional adalah aset berharga yang seharusnya diwariskan dari masa lalu ke masa depan."},
   {"jp":"私たち一人一人が、その価値を再認識する必要があるのではないでしょうか。","furigana":"わたしたちひとりひとりが、そのかちをさいにんしきするひつようがあるのではないでしょうか。","romaji":"Watashitachi hitori hitori ga, sono kachi o sainin shiki suru hitsuyou ga aru no de wa nai deshou ka.","id":"Bukankah kita masing-masing perlu menyadari kembali nilainya?"}
 ]'::jsonb,
 '[
   {"word":"継承","reading":"けいしょう","romaji":"keishou","meaning":"pewarisan"},
   {"word":"育む","reading":"はぐくむ","romaji":"hagukumu","meaning":"memupuk/membina"},
   {"word":"茶道","reading":"さどう","romaji":"sadou","meaning":"upacara minum teh"},
   {"word":"誇る","reading":"ほこる","romaji":"hokoru","meaning":"membanggakan"},
   {"word":"結晶","reading":"けっしょう","romaji":"kesshou","meaning":"kristalisasi/buah dari"},
   {"word":"消滅","reading":"しょうめつ","romaji":"shoumetsu","meaning":"kepunahan/lenyap"},
   {"word":"後継者","reading":"こうけいしゃ","romaji":"koukeisha","meaning":"penerus/pewaris"},
   {"word":"修業","reading":"しゅぎょう","romaji":"shugyou","meaning":"penggemblengan/latihan"},
   {"word":"不安定","reading":"ふあんてい","romaji":"fuantei","meaning":"tidak stabil"},
   {"word":"様式","reading":"ようしき","romaji":"youshiki","meaning":"gaya/corak"},
   {"word":"取り戻す","reading":"とりもどす","romaji":"torimodosu","meaning":"merebut kembali"},
   {"word":"自治体","reading":"じちたい","romaji":"jichitai","meaning":"pemerintah daerah"},
   {"word":"融合","reading":"ゆうごう","romaji":"yuugou","meaning":"perpaduan/fusi"},
   {"word":"財産","reading":"ざいさん","romaji":"zaisan","meaning":"harta/aset"},
   {"word":"再認識","reading":"さいにんしき","romaji":"sainin shiki","meaning":"menyadari kembali"}
 ]'::jsonb,
 '[
   {"q":"Apa yang dimiliki setiap negara dalam sejarah panjangnya?","options":["Teknologi","Budaya tradisional","Tentara","Pasar saham"],"answer":1,"explanation":"「育まれてきた伝統文化があります」."},
   {"q":"Apa penyebab besar krisis budaya tradisional?","options":["Kelebihan dana","Kekurangan penerus","Terlalu populer","Larangan pemerintah"],"answer":1,"explanation":"「後継者の不足です」."},
   {"q":"Apa latar belakang anak muda enggan?","options":["Terlalu mudah","Latihan keras dan penghasilan tak stabil","Tidak menarik secara visual","Terlalu modern"],"answer":1,"explanation":"「厳しい修業や、収入の不安定さ」."},
   {"q":"Apa arti hilangnya budaya tradisional?","options":["Hemat biaya","Hilangnya identitas berharga negara itu","Sebuah kemajuan","Tidak ada artinya"],"answer":1,"explanation":"「貴重なアイデンティティが失われる」."},
   {"q":"Selain melestarikan, apa yang penting?","options":["Membuangnya","Menambahkan nilai baru","Menjualnya","Menyembunyikannya"],"answer":1,"explanation":"「新しい価値を加えることが大切」."},
   {"q":"Contoh upaya menarik minat anak muda?","options":["Menaikkan harga","Memadukan kriya tradisional dengan desain modern","Melarang foto","Menutup workshop"],"answer":1,"explanation":"「伝統工芸を現代のデザインと融合させる試み」."}
 ]'::jsonb,
 false),
(5, 10, '格差社会 — Masyarakat dengan Kesenjangan',
 '「格差社会」という言葉を、近年よく耳にするようになりました。これは、人々の間の経済的な差が拡大した社会を指します。一部の富裕層に富が集中する一方で、貧困に苦しむ人々も増えています。かつて日本は、「一億総中流」と言われた時代がありました。多くの人が、自分は中流階級だと感じていたのです。しかし、その状況は大きく変わってしまいました。格差が広がる原因の一つに、雇用形態の変化があります。安定した正社員に対し、不安定な非正規雇用が増加したのです。同じ仕事をしても、待遇に大きな差が生じることがあります。特に深刻なのが、子どもの貧困問題です。親の経済状況によって、子どもが受けられる教育に差が出てしまいます。その結果、貧困が次の世代へと連鎖する恐れがあります。これは「貧困の連鎖」と呼ばれ、社会全体の損失につながります。努力が報われる社会であるべきだという考えは、もっともです。しかし、出発点に大きな差があるとすれば、公平とは言えません。格差の是正は、政治の重要な役割の一つです。教育の機会を平等に保障することが、特に求められています。誰もが希望を持てる社会を築くことが、私たちの課題なのです。',
 '[
   {"jp":"「格差社会」という言葉を、近年よく耳にするようになりました。","furigana":"「かくさしゃかい」ということばを、きんねんよくみみにするようになりました。","romaji":"\"Kakusa shakai\" to iu kotoba o, kinnen yoku mimi ni suru you ni narimashita.","id":"Istilah \"masyarakat berkesenjangan\" makin sering kita dengar belakangan ini."},
   {"jp":"これは、人々の間の経済的な差が拡大した社会を指します。","furigana":"これは、ひとびとのあいだのけいざいてきなさがかくだいしたしゃかいをさします。","romaji":"Kore wa, hitobito no aida no keizaiteki na sa ga kakudai shita shakai o sashimasu.","id":"Ini merujuk pada masyarakat di mana selisih ekonomi antarwarga melebar."},
   {"jp":"一部の富裕層に富が集中する一方で、貧困に苦しむ人々も増えています。","furigana":"いちぶのふゆうそうにとみがしゅうちゅうするいっぽうで、ひんこんにくるしむひとびともふえています。","romaji":"Ichibu no fuyuusou ni tomi ga shuuchuu suru ippou de, hinkon ni kurushimu hitobito mo fuete imasu.","id":"Sementara kekayaan terpusat pada segelintir kalangan kaya, orang yang menderita kemiskinan pun bertambah."},
   {"jp":"かつて日本は、「一億総中流」と言われた時代がありました。","furigana":"かつてにほんは、「いちおくそうちゅうりゅう」といわれたじだいがありました。","romaji":"Katsute nihon wa, \"ichioku sou chuuryuu\" to iwareta jidai ga arimashita.","id":"Dulu Jepang pernah punya masa yang disebut \"seratus juta semua kelas menengah\"."},
   {"jp":"多くの人が、自分は中流階級だと感じていたのです。","furigana":"おおくのひとが、じぶんはちゅうりゅうかいきゅうだとかんじていたのです。","romaji":"Ooku no hito ga, jibun wa chuuryuu kaikyuu da to kanjite ita no desu.","id":"Banyak orang merasa dirinya termasuk kelas menengah."},
   {"jp":"しかし、その状況は大きく変わってしまいました。","furigana":"しかし、そのじょうきょうはおおきくかわってしまいました。","romaji":"Shikashi, sono joukyou wa ookiku kawatte shimaimashita.","id":"Namun, keadaan itu telah berubah besar-besaran."},
   {"jp":"格差が広がる原因の一つに、雇用形態の変化があります。","furigana":"かくさがひろがるげんいんのひとつに、こようけいたいのへんかがあります。","romaji":"Kakusa ga hirogaru gen-in no hitotsu ni, koyou keitai no henka ga arimasu.","id":"Salah satu penyebab melebarnya kesenjangan adalah perubahan bentuk ketenagakerjaan."},
   {"jp":"安定した正社員に対し、不安定な非正規雇用が増加したのです。","furigana":"あんていしたせいしゃいんにたいし、ふあんていなひせいきこようがぞうかしたのです。","romaji":"Antei shita seishain ni taishi, fuantei na hiseiki koyou ga zouka shita no desu.","id":"Berbeda dengan karyawan tetap yang stabil, ketenagakerjaan nonreguler yang tak stabil meningkat."},
   {"jp":"同じ仕事をしても、待遇に大きな差が生じることがあります。","furigana":"おなじしごとをしても、たいぐうにおおきなさがしょうじることがあります。","romaji":"Onaji shigoto o shite mo, taiguu ni ooki na sa ga shoujiru koto ga arimasu.","id":"Meski melakukan pekerjaan yang sama, kadang timbul selisih besar dalam perlakuan/imbalan."},
   {"jp":"特に深刻なのが、子どもの貧困問題です。","furigana":"とくにしんこくなのが、こどものひんこんもんだいです。","romaji":"Toku ni shinkoku na no ga, kodomo no hinkon mondai desu.","id":"Yang terutama serius adalah masalah kemiskinan anak."},
   {"jp":"親の経済状況によって、子どもが受けられる教育に差が出てしまいます。","furigana":"おやのけいざいじょうきょうによって、こどもがうけられるきょういくにさがでてしまいます。","romaji":"Oya no keizai joukyou ni yotte, kodomo ga ukerareru kyouiku ni sa ga dete shimaimasu.","id":"Tergantung kondisi ekonomi orang tua, muncul selisih pada pendidikan yang bisa diterima anak."},
   {"jp":"その結果、貧困が次の世代へと連鎖する恐れがあります。","furigana":"そのけっか、ひんこんがつぎのせだいへとれんさするおそれがあります。","romaji":"Sono kekka, hinkon ga tsugi no sedai e to rensa suru osore ga arimasu.","id":"Akibatnya, kemiskinan berisiko berantai ke generasi berikutnya."},
   {"jp":"これは「貧困の連鎖」と呼ばれ、社会全体の損失につながります。","furigana":"これは「ひんこんのれんさ」とよばれ、しゃかいぜんたいのそんしつにつながります。","romaji":"Kore wa \"hinkon no rensa\" to yobare, shakai zentai no sonshitsu ni tsunagarimasu.","id":"Ini disebut \"rantai kemiskinan\" dan berujung pada kerugian seluruh masyarakat."},
   {"jp":"努力が報われる社会であるべきだという考えは、もっともです。","furigana":"どりょくがむくわれるしゃかいであるべきだというかんがえは、もっともです。","romaji":"Doryoku ga mukuwareru shakai de aru beki da to iu kangae wa, mottomo desu.","id":"Pandangan bahwa masyarakat seharusnya menghargai usaha itu masuk akal."},
   {"jp":"しかし、出発点に大きな差があるとすれば、公平とは言えません。","furigana":"しかし、しゅっぱつてんにおおきなさがあるとすれば、こうへいとはいえません。","romaji":"Shikashi, shuppatsuten ni ooki na sa ga aru to sureba, kouhei to wa iemasen.","id":"Namun, jika titik berangkatnya berselisih besar, itu tak bisa disebut adil."},
   {"jp":"格差の是正は、政治の重要な役割の一つです。","furigana":"かくさのぜせいは、せいじのじゅうようなやくわりのひとつです。","romaji":"Kakusa no zesei wa, seiji no juuyou na yakuwari no hitotsu desu.","id":"Mengoreksi kesenjangan adalah salah satu peran penting politik."},
   {"jp":"教育の機会を平等に保障することが、特に求められています。","furigana":"きょういくのきかいをびょうどうにほしょうすることが、とくにもとめられています。","romaji":"Kyouiku no kikai o byoudou ni hoshou suru koto ga, toku ni motomerarete imasu.","id":"Menjamin kesempatan pendidikan secara setara terutama sangat dituntut."},
   {"jp":"誰もが希望を持てる社会を築くことが、私たちの課題なのです。","furigana":"だれもがきぼうをもてるしゃかいをきずくことが、わたしたちのかだいなのです。","romaji":"Dare mo ga kibou o moteru shakai o kizuku koto ga, watashitachi no kadai na no desu.","id":"Membangun masyarakat di mana siapa pun bisa memiliki harapan adalah tugas kita."}
 ]'::jsonb,
 '[
   {"word":"格差","reading":"かくさ","romaji":"kakusa","meaning":"kesenjangan/disparitas"},
   {"word":"拡大","reading":"かくだい","romaji":"kakudai","meaning":"perluasan/melebar"},
   {"word":"富裕層","reading":"ふゆうそう","romaji":"fuyuusou","meaning":"kalangan kaya"},
   {"word":"貧困","reading":"ひんこん","romaji":"hinkon","meaning":"kemiskinan"},
   {"word":"中流","reading":"ちゅうりゅう","romaji":"chuuryuu","meaning":"kelas menengah"},
   {"word":"雇用形態","reading":"こようけいたい","romaji":"koyou keitai","meaning":"bentuk ketenagakerjaan"},
   {"word":"正社員","reading":"せいしゃいん","romaji":"seishain","meaning":"karyawan tetap"},
   {"word":"非正規","reading":"ひせいき","romaji":"hiseiki","meaning":"nonreguler/kontrak"},
   {"word":"待遇","reading":"たいぐう","romaji":"taiguu","meaning":"perlakuan/imbalan"},
   {"word":"連鎖","reading":"れんさ","romaji":"rensa","meaning":"rantai/mata rantai"},
   {"word":"損失","reading":"そんしつ","romaji":"sonshitsu","meaning":"kerugian"},
   {"word":"報われる","reading":"むくわれる","romaji":"mukuwareru","meaning":"terbayar/dihargai"},
   {"word":"公平","reading":"こうへい","romaji":"kouhei","meaning":"adil/setara"},
   {"word":"是正","reading":"ぜせい","romaji":"zesei","meaning":"koreksi/pembenahan"},
   {"word":"保障","reading":"ほしょう","romaji":"hoshou","meaning":"jaminan"}
 ]'::jsonb,
 '[
   {"q":"Apa yang dimaksud masyarakat berkesenjangan?","options":["Masyarakat damai","Masyarakat dengan selisih ekonomi yang melebar","Masyarakat maju","Masyarakat desa"],"answer":1,"explanation":"「経済的な差が拡大した社会」."},
   {"q":"Dulu Jepang disebut apa?","options":["Negara miskin","Seratus juta semua kelas menengah","Negara petani","Negara industri"],"answer":1,"explanation":"「『一億総中流』と言われた時代」."},
   {"q":"Salah satu penyebab melebarnya kesenjangan?","options":["Cuaca","Perubahan bentuk ketenagakerjaan","Pariwisata","Olahraga"],"answer":1,"explanation":"「雇用形態の変化」."},
   {"q":"Apa yang terutama serius?","options":["Masalah kemiskinan anak","Polusi","Kemacetan","Inflasi"],"answer":0,"explanation":"「子どもの貧困問題」."},
   {"q":"Apa itu \"rantai kemiskinan\"?","options":["Kemiskinan hilang","Kemiskinan menurun ke generasi berikutnya","Kemiskinan musiman","Kemiskinan sementara"],"answer":1,"explanation":"「貧困が次の世代へと連鎖する」."},
   {"q":"Apa yang terutama dituntut?","options":["Menaikkan pajak","Menjamin kesempatan pendidikan yang setara","Mengurangi sekolah","Membatasi pekerjaan"],"answer":1,"explanation":"「教育の機会を平等に保障すること」."}
 ]'::jsonb,
 false),
(5, 11, '持続可能な開発 — Pembangunan Berkelanjutan',
 '「持続可能な開発」という考え方が、世界中で重視されています。これは、将来の世代の必要を損なうことなく、現在の世代の欲求を満たす開発を意味します。言い換えれば、地球の資源を使い果たさずに、発展を続けることです。二十世紀、人類は経済成長を最優先して発展してきました。その結果、私たちは豊かで便利な生活を手に入れました。しかし、その代償として、環境破壊や資源の枯渇を招きました。このままの発展を続ければ、地球は限界を迎えてしまうでしょう。そこで生まれたのが、持続可能性という概念です。国連は、二〇一五年に「持続可能な開発目標」、いわゆるSDGsを定めました。これには、貧困の撲滅や環境の保護など、十七の目標が含まれています。経済の発展と環境の保護を、両立させることが目指されています。これは、決して簡単なことではありません。時には、経済的な利益を犠牲にしなければならない場合もあります。企業も、利益だけでなく、社会的な責任を問われるようになりました。消費者である私たちの選択も、社会を変える力を持っています。環境に配慮した商品を選ぶことも、その一つです。持続可能な社会の実現は、すべての人の協力なしには成し得ません。私たちは、未来に対する責任を、一人一人が自覚すべき時を迎えています。',
 '[
   {"jp":"「持続可能な開発」という考え方が、世界中で重視されています。","furigana":"「じぞくかのうなかいはつ」というかんがえかたが、せかいじゅうでじゅうしされています。","romaji":"\"Jizoku kanou na kaihatsu\" to iu kangaekata ga, sekaijuu de juushi sarete imasu.","id":"Gagasan \"pembangunan berkelanjutan\" diutamakan di seluruh dunia."},
   {"jp":"これは、将来の世代の必要を損なうことなく、現在の世代の欲求を満たす開発を意味します。","furigana":"これは、しょうらいのせだいのひつようをそこなうことなく、げんざいのせだいのよっきゅうをみたすかいはつをいみします。","romaji":"Kore wa, shourai no sedai no hitsuyou o sokonau koto naku, genzai no sedai no yokkyuu o mitasu kaihatsu o imi shimasu.","id":"Ini berarti pembangunan yang memenuhi kebutuhan generasi kini tanpa merusak kebutuhan generasi mendatang."},
   {"jp":"言い換えれば、地球の資源を使い果たさずに、発展を続けることです。","furigana":"いいかえれば、ちきゅうのしげんをつかいはたさずに、はってんをつづけることです。","romaji":"Iikaereba, chikyuu no shigen o tsukaihatasazu ni, hatten o tsuzukeru koto desu.","id":"Dengan kata lain, melanjutkan kemajuan tanpa menghabiskan sumber daya bumi."},
   {"jp":"二十世紀、人類は経済成長を最優先して発展してきました。","furigana":"にじゅっせいき、じんるいはけいざいせいちょうをさいゆうせんしてはってんしてきました。","romaji":"Nijusseiki, jinrui wa keizai seichou o saiyuusen shite hatten shite kimashita.","id":"Pada abad ke-20, manusia berkembang dengan mengutamakan pertumbuhan ekonomi."},
   {"jp":"その結果、私たちは豊かで便利な生活を手に入れました。","furigana":"そのけっか、わたしたちはゆたかでべんりなせいかつをてにいれました。","romaji":"Sono kekka, watashitachi wa yutaka de benri na seikatsu o te ni iremashita.","id":"Akibatnya, kita memperoleh kehidupan yang makmur dan praktis."},
   {"jp":"しかし、その代償として、環境破壊や資源の枯渇を招きました。","furigana":"しかし、そのだいしょうとして、かんきょうはかいやしげんのこかつをまねきました。","romaji":"Shikashi, sono daishou to shite, kankyou hakai ya shigen no kokatsu o manekimashita.","id":"Namun, sebagai harganya, kita mengundang kerusakan lingkungan dan penipisan sumber daya."},
   {"jp":"このままの発展を続ければ、地球は限界を迎えてしまうでしょう。","furigana":"このままのはってんをつづければ、ちきゅうはげんかいをむかえてしまうでしょう。","romaji":"Kono mama no hatten o tsuzukereba, chikyuu wa genkai o mukaete shimau deshou.","id":"Jika pembangunan diteruskan seperti ini, bumi agaknya akan mencapai batasnya."},
   {"jp":"そこで生まれたのが、持続可能性という概念です。","furigana":"そこでうまれたのが、じぞくかのうせいというがいねんです。","romaji":"Soko de umareta no ga, jizoku kanousei to iu gainen desu.","id":"Di situlah lahir konsep keberlanjutan."},
   {"jp":"国連は、二〇一五年に「持続可能な開発目標」、いわゆるSDGsを定めました。","furigana":"こくれんは、にせんじゅうごねんに「じぞくかのうなかいはつもくひょう」、いわゆるエスディージーズをさだめました。","romaji":"Kokuren wa, nisen juugo-nen ni \"jizoku kanou na kaihatsu mokuhyou\", iwayuru SDGs o sadamemashita.","id":"PBB pada tahun 2015 menetapkan \"Tujuan Pembangunan Berkelanjutan\", yang dikenal sebagai SDGs."},
   {"jp":"これには、貧困の撲滅や環境の保護など、十七の目標が含まれています。","furigana":"これには、ひんこんのぼくめつやかんきょうのほごなど、じゅうななのもくひょうがふくまれています。","romaji":"Kore ni wa, hinkon no bokumetsu ya kankyou no hogo nado, juunana no mokuhyou ga fukumarete imasu.","id":"Di dalamnya tercakup tujuh belas tujuan, seperti pemberantasan kemiskinan dan perlindungan lingkungan."},
   {"jp":"経済の発展と環境の保護を、両立させることが目指されています。","furigana":"けいざいのはってんとかんきょうのほごを、りょうりつさせることがめざされています。","romaji":"Keizai no hatten to kankyou no hogo o, ryouritsu saseru koto ga mezasarete imasu.","id":"Diupayakan menyelaraskan pembangunan ekonomi dengan perlindungan lingkungan."},
   {"jp":"これは、決して簡単なことではありません。","furigana":"これは、けっしてかんたんなことではありません。","romaji":"Kore wa, kesshite kantan na koto de wa arimasen.","id":"Ini sama sekali bukan hal yang mudah."},
   {"jp":"時には、経済的な利益を犠牲にしなければならない場合もあります。","furigana":"ときには、けいざいてきなりえきをぎせいにしなければならないばあいもあります。","romaji":"Toki ni wa, keizaiteki na rieki o gisei ni shinakereba naranai baai mo arimasu.","id":"Kadang ada kalanya keuntungan ekonomi harus dikorbankan."},
   {"jp":"企業も、利益だけでなく、社会的な責任を問われるようになりました。","furigana":"きぎょうも、りえきだけでなく、しゃかいてきなせきにんをとわれるようになりました。","romaji":"Kigyou mo, rieki dake de naku, shakaiteki na sekinin o towareru you ni narimashita.","id":"Perusahaan pun kini dituntut tanggung jawab sosial, bukan hanya keuntungan."},
   {"jp":"消費者である私たちの選択も、社会を変える力を持っています。","furigana":"しょうひしゃであるわたしたちのせんたくも、しゃかいをかえるちからをもっています。","romaji":"Shouhisha de aru watashitachi no sentaku mo, shakai o kaeru chikara o motte imasu.","id":"Pilihan kita sebagai konsumen pun punya kekuatan mengubah masyarakat."},
   {"jp":"環境に配慮した商品を選ぶことも、その一つです。","furigana":"かんきょうにはいりょしたしょうひんをえらぶことも、そのひとつです。","romaji":"Kankyou ni hairyo shita shouhin o erabu koto mo, sono hitotsu desu.","id":"Memilih produk yang peduli lingkungan juga salah satunya."},
   {"jp":"持続可能な社会の実現は、すべての人の協力なしには成し得ません。","furigana":"じぞくかのうなしゃかいのじつげんは、すべてのひとのきょうりょくなしにはなしえません。","romaji":"Jizoku kanou na shakai no jitsugen wa, subete no hito no kyouryoku nashi ni wa nashiemasen.","id":"Perwujudan masyarakat berkelanjutan tak dapat dicapai tanpa kerja sama semua orang."},
   {"jp":"私たちは、未来に対する責任を、一人一人が自覚すべき時を迎えています。","furigana":"わたしたちは、みらいにたいするせきにんを、ひとりひとりがじかくすべきときをむかえています。","romaji":"Watashitachi wa, mirai ni taisuru sekinin o, hitori hitori ga jikaku subeki toki o mukaete imasu.","id":"Kita telah tiba pada saat di mana setiap orang harus menyadari tanggung jawab terhadap masa depan."}
 ]'::jsonb,
 '[
   {"word":"持続可能","reading":"じぞくかのう","romaji":"jizoku kanou","meaning":"berkelanjutan"},
   {"word":"損なう","reading":"そこなう","romaji":"sokonau","meaning":"merusak/mengurangi"},
   {"word":"欲求","reading":"よっきゅう","romaji":"yokkyuu","meaning":"kebutuhan/hasrat"},
   {"word":"使い果たす","reading":"つかいはたす","romaji":"tsukaihatasu","meaning":"menghabiskan (sampai habis)"},
   {"word":"最優先","reading":"さいゆうせん","romaji":"saiyuusen","meaning":"prioritas utama"},
   {"word":"代償","reading":"だいしょう","romaji":"daishou","meaning":"harga/tebusan"},
   {"word":"枯渇","reading":"こかつ","romaji":"kokatsu","meaning":"penipisan/kering"},
   {"word":"概念","reading":"がいねん","romaji":"gainen","meaning":"konsep"},
   {"word":"国連","reading":"こくれん","romaji":"kokuren","meaning":"PBB"},
   {"word":"撲滅","reading":"ぼくめつ","romaji":"bokumetsu","meaning":"pemberantasan"},
   {"word":"両立","reading":"りょうりつ","romaji":"ryouritsu","meaning":"menyelaraskan keduanya"},
   {"word":"犠牲","reading":"ぎせい","romaji":"gisei","meaning":"pengorbanan"},
   {"word":"配慮","reading":"はいりょ","romaji":"hairyo","meaning":"pertimbangan/kepedulian"},
   {"word":"実現","reading":"じつげん","romaji":"jitsugen","meaning":"perwujudan"},
   {"word":"成し得る","reading":"なしうる","romaji":"nashiuru","meaning":"dapat dicapai"}
 ]'::jsonb,
 '[
   {"q":"Apa arti pembangunan berkelanjutan?","options":["Pertumbuhan secepat mungkin","Memenuhi kebutuhan kini tanpa merusak kebutuhan generasi mendatang","Berhenti membangun","Hanya menjaga alam"],"answer":1,"explanation":"「将来の世代の必要を損なうことなく…満たす開発」."},
   {"q":"Pada abad ke-20, apa yang diprioritaskan manusia?","options":["Lingkungan","Pertumbuhan ekonomi","Seni","Kesehatan"],"answer":1,"explanation":"「経済成長を最優先して」."},
   {"q":"Apa harga dari pembangunan itu?","options":["Kekayaan","Kerusakan lingkungan dan penipisan sumber daya","Perdamaian","Pendidikan"],"answer":1,"explanation":"「環境破壊や資源の枯渇を招きました」."},
   {"q":"Apa yang ditetapkan PBB tahun 2015?","options":["Perjanjian dagang","SDGs (tujuan pembangunan berkelanjutan)","Larangan industri","Mata uang baru"],"answer":1,"explanation":"「いわゆるSDGsを定めました」."},
   {"q":"Apa yang ingin diselaraskan?","options":["Perang dan damai","Pembangunan ekonomi dan perlindungan lingkungan","Kota dan desa","Tua dan muda"],"answer":1,"explanation":"「経済の発展と環境の保護を、両立」."},
   {"q":"Pilihan siapa yang juga berkekuatan mengubah masyarakat?","options":["Hanya pemerintah","Kita sebagai konsumen","Hanya perusahaan","Hanya ilmuwan"],"answer":1,"explanation":"「消費者である私たちの選択も…力を持っています」."}
 ]'::jsonb,
 false),
(5, 12, '記憶とアイデンティティ — Memori dan Identitas',
 '私たちは、自分が誰であるかを、どのように認識しているのでしょうか。その答えの鍵を握っているのが、「記憶」です。過去の経験の積み重ねが、今の自分を形作っています。楽しかったこと、つらかったこと、そのすべてが私たちの一部です。もし記憶を完全に失ってしまったら、人はどうなるのでしょうか。おそらく、自分が何者であるかさえ、分からなくなってしまうでしょう。つまり、記憶とアイデンティティは、深く結びついているのです。しかし、人間の記憶は、決して正確なものではありません。時が経つにつれて、記憶は薄れ、時には変化することもあります。同じ出来事を経験しても、人によって覚えていることは異なります。私たちは、無意識のうちに、都合の良いように記憶を作り変えているのです。また、記憶は個人だけのものではありません。家族や民族が共有する「集合的記憶」というものも存在します。歴史もまた、社会が共有する記憶の一つだと言えるでしょう。その記憶をどう解釈するかは、その社会のあり方を左右します。過去を正しく記憶し、未来へ伝えていくことは重要な営みです。なぜなら、過去を忘れた者は、同じ過ちを繰り返すからです。記憶とは、私たちが過去とつながり、未来を築くための土台なのです。',
 '[
   {"jp":"私たちは、自分が誰であるかを、どのように認識しているのでしょうか。","furigana":"わたしたちは、じぶんがだれであるかを、どのようににんしきしているのでしょうか。","romaji":"Watashitachi wa, jibun ga dare de aru ka o, dono you ni ninshiki shite iru no deshou ka.","id":"Bagaimana kita mengenali siapa diri kita sebenarnya?"},
   {"jp":"その答えの鍵を握っているのが、「記憶」です。","furigana":"そのこたえのかぎをにぎっているのが、「きおく」です。","romaji":"Sono kotae no kagi o nigitte iru no ga, \"kioku\" desu.","id":"Yang memegang kunci jawabannya adalah \"memori\"."},
   {"jp":"過去の経験の積み重ねが、今の自分を形作っています。","furigana":"かこのけいけんのつみかさねが、いまのじぶんをかたちづくっています。","romaji":"Kako no keiken no tsumikasane ga, ima no jibun o katachizukutte imasu.","id":"Penumpukan pengalaman masa lalu membentuk diri kita yang sekarang."},
   {"jp":"楽しかったこと、つらかったこと、そのすべてが私たちの一部です。","furigana":"たのしかったこと、つらかったこと、そのすべてがわたしたちのいちぶです。","romaji":"Tanoshikatta koto, tsurakatta koto, sono subete ga watashitachi no ichibu desu.","id":"Hal yang menyenangkan maupun yang pahit, semuanya adalah bagian dari kita."},
   {"jp":"もし記憶を完全に失ってしまったら、人はどうなるのでしょうか。","furigana":"もしきおくをかんぜんにうしなってしまったら、ひとはどうなるのでしょうか。","romaji":"Moshi kioku o kanzen ni ushinatte shimattara, hito wa dou naru no deshou ka.","id":"Seandainya kehilangan ingatan sepenuhnya, apa jadinya seseorang?"},
   {"jp":"おそらく、自分が何者であるかさえ、分からなくなってしまうでしょう。","furigana":"おそらく、じぶんがなにものであるかさえ、わからなくなってしまうでしょう。","romaji":"Osoraku, jibun ga nanimono de aru ka sae, wakaranaku natte shimau deshou.","id":"Kemungkinan, ia bahkan tak lagi tahu dirinya itu siapa."},
   {"jp":"つまり、記憶とアイデンティティは、深く結びついているのです。","furigana":"つまり、きおくとアイデンティティは、ふかくむすびついているのです。","romaji":"Tsumari, kioku to aidentitii wa, fukaku musubitsuite iru no desu.","id":"Artinya, memori dan identitas terhubung secara mendalam."},
   {"jp":"しかし、人間の記憶は、決して正確なものではありません。","furigana":"しかし、にんげんのきおくは、けっしてせいかくなものではありません。","romaji":"Shikashi, ningen no kioku wa, kesshite seikaku na mono de wa arimasen.","id":"Namun, ingatan manusia sama sekali bukan sesuatu yang akurat."},
   {"jp":"時が経つにつれて、記憶は薄れ、時には変化することもあります。","furigana":"ときがたつにつれて、きおくはうすれ、ときにはへんかすることもあります。","romaji":"Toki ga tatsu ni tsurete, kioku wa usure, toki ni wa henka suru koto mo arimasu.","id":"Seiring berjalannya waktu, ingatan memudar dan kadang bahkan berubah."},
   {"jp":"同じ出来事を経験しても、人によって覚えていることは異なります。","furigana":"おなじできごとをけいけんしても、ひとによっておぼえていることはことなります。","romaji":"Onaji dekigoto o keiken shite mo, hito ni yotte oboete iru koto wa kotonarimasu.","id":"Meski mengalami peristiwa yang sama, apa yang diingat berbeda-beda tiap orang."},
   {"jp":"私たちは、無意識のうちに、都合の良いように記憶を作り変えているのです。","furigana":"わたしたちは、むいしきのうちに、つごうのよいようにきおくをつくりかえているのです。","romaji":"Watashitachi wa, muishiki no uchi ni, tsugou no yoi you ni kioku o tsukurikaete iru no desu.","id":"Tanpa sadar, kita membentuk ulang ingatan agar sesuai kepentingan kita."},
   {"jp":"また、記憶は個人だけのものではありません。","furigana":"また、きおくはこじんだけのものではありません。","romaji":"Mata, kioku wa kojin dake no mono de wa arimasen.","id":"Selain itu, memori bukan hanya milik individu."},
   {"jp":"家族や民族が共有する「集合的記憶」というものも存在します。","furigana":"かぞくやみんぞくがきょうゆうする「しゅうごうてききおく」というものもそんざいします。","romaji":"Kazoku ya minzoku ga kyouyuu suru \"shuugouteki kioku\" to iu mono mo sonzai shimasu.","id":"Ada pula yang disebut \"memori kolektif\", yang dibagi oleh keluarga atau bangsa."},
   {"jp":"歴史もまた、社会が共有する記憶の一つだと言えるでしょう。","furigana":"れきしもまた、しゃかいがきょうゆうするきおくのひとつだといえるでしょう。","romaji":"Rekishi mo mata, shakai ga kyouyuu suru kioku no hitotsu da to ieru deshou.","id":"Sejarah pun agaknya dapat disebut salah satu memori yang dibagi masyarakat."},
   {"jp":"その記憶をどう解釈するかは、その社会のあり方を左右します。","furigana":"そのきおくをどうかいしゃくするかは、そのしゃかいのありかたをさゆうします。","romaji":"Sono kioku o dou kaishaku suru ka wa, sono shakai no arikata o sayuu shimasu.","id":"Bagaimana memori itu ditafsirkan menentukan wujud masyarakat tersebut."},
   {"jp":"過去を正しく記憶し、未来へ伝えていくことは重要な営みです。","furigana":"かこをただしくきおくし、みらいへつたえていくことはじゅうようないとなみです。","romaji":"Kako o tadashiku kioku shi, mirai e tsutaete iku koto wa juuyou na itonami desu.","id":"Mengingat masa lalu dengan benar dan mewariskannya ke masa depan adalah kegiatan yang penting."},
   {"jp":"なぜなら、過去を忘れた者は、同じ過ちを繰り返すからです。","furigana":"なぜなら、かこをわすれたものは、おなじあやまちをくりかえすからです。","romaji":"Nazenara, kako o wasureta mono wa, onaji ayamachi o kurikaesu kara desu.","id":"Sebab, mereka yang melupakan masa lalu akan mengulangi kesalahan yang sama."},
   {"jp":"記憶とは、私たちが過去とつながり、未来を築くための土台なのです。","furigana":"きおくとは、わたしたちがかことつながり、みらいをきずくためのどだいなのです。","romaji":"Kioku to wa, watashitachi ga kako to tsunagari, mirai o kizuku tame no dodai na no desu.","id":"Memori adalah fondasi bagi kita untuk terhubung dengan masa lalu dan membangun masa depan."}
 ]'::jsonb,
 '[
   {"word":"認識","reading":"にんしき","romaji":"ninshiki","meaning":"pengenalan/kesadaran"},
   {"word":"鍵を握る","reading":"かぎをにぎる","romaji":"kagi o nigiru","meaning":"memegang kunci"},
   {"word":"形作る","reading":"かたちづくる","romaji":"katachizukuru","meaning":"membentuk"},
   {"word":"結びつく","reading":"むすびつく","romaji":"musubitsuku","meaning":"terhubung/terkait"},
   {"word":"正確","reading":"せいかく","romaji":"seikaku","meaning":"akurat"},
   {"word":"薄れる","reading":"うすれる","romaji":"usureru","meaning":"memudar"},
   {"word":"無意識","reading":"むいしき","romaji":"muishiki","meaning":"tak sadar/bawah sadar"},
   {"word":"都合","reading":"つごう","romaji":"tsugou","meaning":"kepentingan/kemudahan"},
   {"word":"作り変える","reading":"つくりかえる","romaji":"tsukurikaeru","meaning":"membentuk ulang"},
   {"word":"集合的","reading":"しゅうごうてき","romaji":"shuugouteki","meaning":"kolektif"},
   {"word":"民族","reading":"みんぞく","romaji":"minzoku","meaning":"etnis/bangsa"},
   {"word":"解釈","reading":"かいしゃく","romaji":"kaishaku","meaning":"penafsiran"},
   {"word":"左右","reading":"さゆう","romaji":"sayuu","meaning":"memengaruhi/menentukan"},
   {"word":"過ち","reading":"あやまち","romaji":"ayamachi","meaning":"kesalahan"},
   {"word":"土台","reading":"どだい","romaji":"dodai","meaning":"fondasi/dasar"}
 ]'::jsonb,
 '[
   {"q":"Apa yang memegang kunci pengenalan diri kita?","options":["Uang","Memori/ingatan","Nama","Wajah"],"answer":1,"explanation":"「その答えの鍵を握っているのが、『記憶』」."},
   {"q":"Apa yang membentuk diri kita sekarang?","options":["Masa depan","Akumulasi pengalaman masa lalu","Pendapat orang","Mimpi"],"answer":1,"explanation":"「過去の経験の積み重ねが、今の自分を形作って」."},
   {"q":"Bagaimana sifat memori manusia?","options":["Selalu akurat","Tidak akurat","Sempurna","Abadi"],"answer":1,"explanation":"「決して正確なものではありません」."},
   {"q":"Apa itu \"memori kolektif\"?","options":["Memori pribadi","Memori yang dibagi keluarga atau bangsa","Memori komputer","Memori palsu"],"answer":1,"explanation":"「家族や民族が共有する『集合的記憶』」."},
   {"q":"Sejarah dapat disebut sebagai?","options":["Fiksi","Salah satu memori yang dibagi masyarakat","Dongeng","Data ekonomi"],"answer":1,"explanation":"「社会が共有する記憶の一つ」."},
   {"q":"Kenapa mengingat masa lalu penting?","options":["Untuk hiburan","Yang melupakan masa lalu mengulang kesalahan yang sama","Tidak penting","Untuk ujian"],"answer":1,"explanation":"「過去を忘れた者は、同じ過ちを繰り返す」."}
 ]'::jsonb,
 false),
(5, 13, 'メディアと世論 — Media dan Opini Publik',
 '現代社会において、メディアは絶大な影響力を持っています。私たちは、日々、テレビや新聞、インターネットから情報を得ています。それらの情報をもとに、社会の出来事に対する意見を形成します。多くの人が共有するこうした意見を、「世論」と呼びます。世論は、政治や社会を動かす大きな力となります。それゆえ、メディアの果たす役割は非常に重要です。しかし、ここで注意しなければならないことがあります。メディアが伝える情報は、必ずしも中立とは限らないのです。どの出来事を、どのように報じるかは、メディアの判断に委ねられています。同じ事実でも、伝え方によって、受け手の印象は大きく変わります。時には、特定の意見へと世論を誘導しようとする場合さえあります。また、視聴率や注目を集めるために、刺激的な報道に偏ることもあります。私たちは、メディアの情報を、ただ鵜呑みにしてはいけません。複数のメディアを比較し、多角的に物事を見ることが大切です。一つの情報源だけに頼ると、偏った見方に陥る危険があります。情報を批判的に読み解く力が、現代を生きる私たちには不可欠です。健全な世論は、賢明な市民によって支えられています。メディアと適切に向き合う姿勢が、民主主義を守ることにつながるのです。',
 '[
   {"jp":"現代社会において、メディアは絶大な影響力を持っています。","furigana":"げんだいしゃかいにおいて、メディアはぜつだいなえいきょうりょくをもっています。","romaji":"Gendai shakai ni oite, media wa zetsudai na eikyouryoku o motte imasu.","id":"Dalam masyarakat modern, media memiliki pengaruh yang sangat besar."},
   {"jp":"私たちは、日々、テレビや新聞、インターネットから情報を得ています。","furigana":"わたしたちは、ひび、テレビやしんぶん、インターネットからじょうほうをえています。","romaji":"Watashitachi wa, hibi, terebi ya shinbun, intaanetto kara jouhou o ete imasu.","id":"Setiap hari kita memperoleh informasi dari televisi, koran, dan internet."},
   {"jp":"それらの情報をもとに、社会の出来事に対する意見を形成します。","furigana":"それらのじょうほうをもとに、しゃかいのできごとにたいするいけんをけいせいします。","romaji":"Sorera no jouhou o moto ni, shakai no dekigoto ni taisuru iken o keisei shimasu.","id":"Berdasarkan informasi itu, kita membentuk opini terhadap peristiwa sosial."},
   {"jp":"多くの人が共有するこうした意見を、「世論」と呼びます。","furigana":"おおくのひとがきょうゆうするこうしたいけんを、「よろん」とよびます。","romaji":"Ooku no hito ga kyouyuu suru koushita iken o, \"yoron\" to yobimasu.","id":"Opini semacam ini yang dibagi banyak orang disebut \"opini publik\"."},
   {"jp":"世論は、政治や社会を動かす大きな力となります。","furigana":"よろんは、せいじやしゃかいをうごかすおおきなちからとなります。","romaji":"Yoron wa, seiji ya shakai o ugokasu ooki na chikara to narimasu.","id":"Opini publik menjadi kekuatan besar yang menggerakkan politik dan masyarakat."},
   {"jp":"それゆえ、メディアの果たす役割は非常に重要です。","furigana":"それゆえ、メディアのはたすやくわりはひじょうにじゅうようです。","romaji":"Sore yue, media no hatasu yakuwari wa hijou ni juuyou desu.","id":"Oleh karena itu, peran yang dijalankan media sangatlah penting."},
   {"jp":"しかし、ここで注意しなければならないことがあります。","furigana":"しかし、ここでちゅういしなければならないことがあります。","romaji":"Shikashi, koko de chuui shinakereba naranai koto ga arimasu.","id":"Namun, ada hal yang harus kita waspadai di sini."},
   {"jp":"メディアが伝える情報は、必ずしも中立とは限らないのです。","furigana":"メディアがつたえるじょうほうは、かならずしもちゅうりつとはかぎらないのです。","romaji":"Media ga tsutaeru jouhou wa, kanarazu shimo chuuritsu to wa kagiranai no desu.","id":"Informasi yang disampaikan media belum tentu netral."},
   {"jp":"どの出来事を、どのように報じるかは、メディアの判断に委ねられています。","furigana":"どのできごとを、どのようにほうじるかは、メディアのはんだんにゆだねられています。","romaji":"Dono dekigoto o, dono you ni houjiru ka wa, media no handan ni yudanerarete imasu.","id":"Peristiwa mana yang diberitakan dan bagaimana caranya, diserahkan pada pertimbangan media."},
   {"jp":"同じ事実でも、伝え方によって、受け手の印象は大きく変わります。","furigana":"おなじじじつでも、つたえかたによって、うけてのいんしょうはおおきくかわります。","romaji":"Onaji jijitsu de mo, tsutaekata ni yotte, ukete no inshou wa ookiku kawarimasu.","id":"Meski faktanya sama, kesan penerima sangat berubah tergantung cara menyampaikannya."},
   {"jp":"時には、特定の意見へと世論を誘導しようとする場合さえあります。","furigana":"ときには、とくていのいけんへとよろんをゆうどうしようとするばあいさえあります。","romaji":"Toki ni wa, tokutei no iken e to yoron o yuudou shiyou to suru baai sae arimasu.","id":"Kadang bahkan ada kasus berupaya menggiring opini publik ke pendapat tertentu."},
   {"jp":"また、視聴率や注目を集めるために、刺激的な報道に偏ることもあります。","furigana":"また、しちょうりつやちゅうもくをあつめるために、しげきてきなほうどうにかたよることもあります。","romaji":"Mata, shichouritsu ya chuumoku o atsumeru tame ni, shigekiteki na houdou ni katayoru koto mo arimasu.","id":"Selain itu, demi meraih rating dan perhatian, pemberitaan bisa condong ke yang sensasional."},
   {"jp":"私たちは、メディアの情報を、ただ鵜呑みにしてはいけません。","furigana":"わたしたちは、メディアのじょうほうを、ただうのみにしてはいけません。","romaji":"Watashitachi wa, media no jouhou o, tada unomi ni shite wa ikemasen.","id":"Kita tidak boleh sekadar menelan mentah-mentah informasi media."},
   {"jp":"複数のメディアを比較し、多角的に物事を見ることが大切です。","furigana":"ふくすうのメディアをひかくし、たかくてきにものごとをみることがたいせつです。","romaji":"Fukusuu no media o hikaku shi, takakuteki ni monogoto o miru koto ga taisetsu desu.","id":"Penting untuk membandingkan beberapa media dan melihat persoalan dari berbagai sudut."},
   {"jp":"一つの情報源だけに頼ると、偏った見方に陥る危険があります。","furigana":"ひとつのじょうほうげんだけにたよると、かたよったみかたにおちいるきけんがあります。","romaji":"Hitotsu no jouhougen dake ni tayoru to, katayotta mikata ni ochiiru kiken ga arimasu.","id":"Bila hanya mengandalkan satu sumber, ada bahaya terjerumus ke pandangan yang berat sebelah."},
   {"jp":"情報を批判的に読み解く力が、現代を生きる私たちには不可欠です。","furigana":"じょうほうをひはんてきによみとくちからが、げんだいをいきるわたしたちにはふかけつです。","romaji":"Jouhou o hihanteki ni yomitoku chikara ga, gendai o ikiru watashitachi ni wa fukaketsu desu.","id":"Kemampuan membaca informasi secara kritis mutlak diperlukan bagi kita yang hidup di zaman modern."},
   {"jp":"健全な世論は、賢明な市民によって支えられています。","furigana":"けんぜんなよろんは、けんめいなしみんによってささえられています。","romaji":"Kenzen na yoron wa, kenmei na shimin ni yotte sasaerarete imasu.","id":"Opini publik yang sehat ditopang oleh warga yang bijak."},
   {"jp":"メディアと適切に向き合う姿勢が、民主主義を守ることにつながるのです。","furigana":"メディアとてきせつにむきあうしせいが、みんしゅしゅぎをまもることにつながるのです。","romaji":"Media to tekisetsu ni mukiau shisei ga, minshu shugi o mamoru koto ni tsunagaru no desu.","id":"Sikap menghadapi media secara tepat berujung pada menjaga demokrasi."}
 ]'::jsonb,
 '[
   {"word":"絶大","reading":"ぜつだい","romaji":"zetsudai","meaning":"sangat besar/luar biasa"},
   {"word":"形成","reading":"けいせい","romaji":"keisei","meaning":"pembentukan"},
   {"word":"世論","reading":"よろん","romaji":"yoron","meaning":"opini publik"},
   {"word":"中立","reading":"ちゅうりつ","romaji":"chuuritsu","meaning":"netral"},
   {"word":"報じる","reading":"ほうじる","romaji":"houjiru","meaning":"memberitakan"},
   {"word":"委ねる","reading":"ゆだねる","romaji":"yudaneru","meaning":"menyerahkan/mempercayakan"},
   {"word":"受け手","reading":"うけて","romaji":"ukete","meaning":"penerima"},
   {"word":"誘導","reading":"ゆうどう","romaji":"yuudou","meaning":"mengarahkan/menggiring"},
   {"word":"視聴率","reading":"しちょうりつ","romaji":"shichouritsu","meaning":"rating siaran"},
   {"word":"偏る","reading":"かたよる","romaji":"katayoru","meaning":"berat sebelah/bias"},
   {"word":"鵜呑み","reading":"うのみ","romaji":"unomi","meaning":"menelan mentah-mentah"},
   {"word":"多角的","reading":"たかくてき","romaji":"takakuteki","meaning":"multidimensi/berbagai sudut"},
   {"word":"陥る","reading":"おちいる","romaji":"ochiiru","meaning":"terjerumus"},
   {"word":"賢明","reading":"けんめい","romaji":"kenmei","meaning":"bijak/bijaksana"},
   {"word":"向き合う","reading":"むきあう","romaji":"mukiau","meaning":"menghadapi/berhadapan"}
 ]'::jsonb,
 '[
   {"q":"Apa yang punya pengaruh besar di masyarakat modern?","options":["Cuaca","Media","Olahraga","Musik"],"answer":1,"explanation":"「メディアは絶大な影響力を持っています」."},
   {"q":"Apa istilah opini yang dibagi banyak orang?","options":["Rumor","Opini publik (yoron)","Iklan","Sensus"],"answer":1,"explanation":"「『世論』と呼びます」."},
   {"q":"Informasi yang disampaikan media bersifat?","options":["Selalu netral","Belum tentu netral","Selalu benar","Tidak berguna"],"answer":1,"explanation":"「必ずしも中立とは限らない」."},
   {"q":"Dengan cara penyampaian berbeda, apa yang berubah?","options":["Faktanya","Kesan penerima","Tanggalnya","Harganya"],"answer":1,"explanation":"「受け手の印象は大きく変わります」."},
   {"q":"Apa yang sebaiknya tidak kita lakukan?","options":["Membandingkan sumber","Menelan informasi mentah-mentah","Berpikir kritis","Membaca banyak sumber"],"answer":1,"explanation":"「ただ鵜呑みにしてはいけません」."},
   {"q":"Opini publik yang sehat ditopang oleh?","options":["Pemerintah","Warga yang bijak","Pemodal","Media saja"],"answer":1,"explanation":"「賢明な市民によって支えられています」."}
 ]'::jsonb,
 false),
(5, 14, '労働観の変化 — Perubahan Pandangan Kerja',
 '働くことに対する人々の考え方、すなわち労働観は、時代とともに変化しています。かつての日本では、一つの会社に定年まで勤めるのが一般的でした。終身雇用と年功序列が、長らく日本の働き方を支えてきました。多くの人にとって、会社は家族のような存在でした。仕事のために、自分の生活を犠牲にすることも珍しくありませんでした。しかし、経済の停滞とともに、こうした仕組みは崩れ始めました。現代では、転職をすることが、ごく当たり前になっています。一つの会社に縛られず、自分の能力を生かす道を選ぶ人が増えました。また、働く目的も多様化しています。単にお金を稼ぐためだけでなく、自己実現を求める人も少なくありません。仕事と私生活の調和、いわゆるワークライフバランスも重視されています。長時間労働を見直し、効率を上げようとする動きも広がっています。リモートワークの普及は、働く場所の自由をもたらしました。もはや、働き方に唯一の正解はありません。それぞれが、自分に合った働き方を模索する時代になったのです。この変化は、私たちに自由をもたらすと同時に、責任も求めます。自分の人生をどう生きるか、主体的に考えなければならないのです。働くことの意味を問い直すことは、より良く生きることにつながるでしょう。',
 '[
   {"jp":"働くことに対する人々の考え方、すなわち労働観は、時代とともに変化しています。","furigana":"はたらくことにたいするひとびとのかんがえかた、すなわちろうどうかんは、じだいとともにへんかしています。","romaji":"Hataraku koto ni taisuru hitobito no kangaekata, sunawachi roudoukan wa, jidai to tomo ni henka shite imasu.","id":"Cara pandang orang terhadap bekerja, yakni pandangan kerja, berubah seiring zaman."},
   {"jp":"かつての日本では、一つの会社に定年まで勤めるのが一般的でした。","furigana":"かつてのにほんでは、ひとつのかいしゃにていねんまでつとめるのがいっぱんてきでした。","romaji":"Katsute no nihon de wa, hitotsu no kaisha ni teinen made tsutomeru no ga ippanteki deshita.","id":"Dulu di Jepang, bekerja di satu perusahaan sampai pensiun adalah hal yang umum."},
   {"jp":"終身雇用と年功序列が、長らく日本の働き方を支えてきました。","furigana":"しゅうしんこようとねんこうじょれつが、ながらくにほんのはたらきかたをささえてきました。","romaji":"Shuushin koyou to nenkou joretsu ga, nagaraku nihon no hatarakikata o sasaete kimashita.","id":"Pekerjaan seumur hidup dan sistem senioritas lama menopang cara kerja Jepang."},
   {"jp":"多くの人にとって、会社は家族のような存在でした。","furigana":"おおくのひとにとって、かいしゃはかぞくのようなそんざいでした。","romaji":"Ooku no hito ni totte, kaisha wa kazoku no you na sonzai deshita.","id":"Bagi banyak orang, perusahaan adalah sesuatu yang seperti keluarga."},
   {"jp":"仕事のために、自分の生活を犠牲にすることも珍しくありませんでした。","furigana":"しごとのために、じぶんのせいかつをぎせいにすることもめずらしくありませんでした。","romaji":"Shigoto no tame ni, jibun no seikatsu o gisei ni suru koto mo mezurashiku arimasen deshita.","id":"Mengorbankan kehidupan sendiri demi pekerjaan pun bukan hal yang langka."},
   {"jp":"しかし、経済の停滞とともに、こうした仕組みは崩れ始めました。","furigana":"しかし、けいざいのていたいとともに、こうしたしくみはくずれはじめました。","romaji":"Shikashi, keizai no teitai to tomo ni, koushita shikumi wa kuzurehajimemashita.","id":"Namun, seiring stagnasi ekonomi, sistem seperti ini mulai runtuh."},
   {"jp":"現代では、転職をすることが、ごく当たり前になっています。","furigana":"げんだいでは、てんしょくをすることが、ごくあたりまえになっています。","romaji":"Gendai de wa, tenshoku o suru koto ga, goku atarimae ni natte imasu.","id":"Di masa kini, pindah kerja menjadi hal yang sangat lumrah."},
   {"jp":"一つの会社に縛られず、自分の能力を生かす道を選ぶ人が増えました。","furigana":"ひとつのかいしゃにしばられず、じぶんのうりょくをいかすみちをえらぶひとがふえました。","romaji":"Hitotsu no kaisha ni shibararezu, jibun no nouryoku o ikasu michi o erabu hito ga fuemashita.","id":"Makin banyak orang yang tak terikat satu perusahaan dan memilih jalan yang memanfaatkan kemampuannya."},
   {"jp":"また、働く目的も多様化しています。","furigana":"また、はたらくもくてきもたようかしています。","romaji":"Mata, hataraku mokuteki mo tayouka shite imasu.","id":"Selain itu, tujuan bekerja pun makin beragam."},
   {"jp":"単にお金を稼ぐためだけでなく、自己実現を求める人も少なくありません。","furigana":"たんにおかねをかせぐためだけでなく、じこじつげんをもとめるひともすくなくありません。","romaji":"Tan ni okane o kasegu tame dake de naku, jiko jitsugen o motomeru hito mo sukunaku arimasen.","id":"Tak sedikit orang yang mencari aktualisasi diri, bukan sekadar menghasilkan uang."},
   {"jp":"仕事と私生活の調和、いわゆるワークライフバランスも重視されています。","furigana":"しごととしせいかつのちょうわ、いわゆるワークライフバランスもじゅうしされています。","romaji":"Shigoto to shiseikatsu no chouwa, iwayuru waaku raifu baransu mo juushi sarete imasu.","id":"Keselarasan kerja dan kehidupan pribadi, yang disebut work-life balance, juga diutamakan."},
   {"jp":"長時間労働を見直し、効率を上げようとする動きも広がっています。","furigana":"ちょうじかんろうどうをみなおし、こうりつをあげようとするうごきもひろがっています。","romaji":"Choujikan roudou o minaoshi, kouritsu o ageyou to suru ugoki mo hirogatte imasu.","id":"Gerakan meninjau ulang kerja berjam-jam dan meningkatkan efisiensi pun meluas."},
   {"jp":"リモートワークの普及は、働く場所の自由をもたらしました。","furigana":"リモートワークのふきゅうは、はたらくばしょのじゆうをもたらしました。","romaji":"Rimooto waaku no fukyuu wa, hataraku basho no jiyuu o motarashimashita.","id":"Penyebaran kerja jarak jauh membawa kebebasan dalam memilih tempat bekerja."},
   {"jp":"もはや、働き方に唯一の正解はありません。","furigana":"もはや、はたらきかたにゆいいつのせいかいはありません。","romaji":"Mohaya, hatarakikata ni yuiitsu no seikai wa arimasen.","id":"Kini tak ada lagi satu jawaban yang benar tentang cara bekerja."},
   {"jp":"それぞれが、自分に合った働き方を模索する時代になったのです。","furigana":"それぞれが、じぶんにあったはたらきかたをもさくするじだいになったのです。","romaji":"Sorezore ga, jibun ni atta hatarakikata o mosaku suru jidai ni natta no desu.","id":"Telah tiba zaman di mana masing-masing mencari cara kerja yang cocok untuknya."},
   {"jp":"この変化は、私たちに自由をもたらすと同時に、責任も求めます。","furigana":"このへんかは、わたしたちにじゆうをもたらすとどうじに、せきにんももとめます。","romaji":"Kono henka wa, watashitachi ni jiyuu o motarasu to douji ni, sekinin mo motomemasu.","id":"Perubahan ini membawa kebebasan bagi kita, sekaligus menuntut tanggung jawab."},
   {"jp":"自分の人生をどう生きるか、主体的に考えなければならないのです。","furigana":"じぶんのじんせいをどういきるか、しゅたいてきにかんがえなければならないのです。","romaji":"Jibun no jinsei o dou ikiru ka, shutaiteki ni kangaenakereba naranai no desu.","id":"Kita harus memikirkan secara mandiri bagaimana menjalani hidup kita sendiri."},
   {"jp":"働くことの意味を問い直すことは、より良く生きることにつながるでしょう。","furigana":"はたらくことのいみをといなおすことは、よりよくいきることにつながるでしょう。","romaji":"Hataraku koto no imi o toinaosu koto wa, yori yoku ikiru koto ni tsunagaru deshou.","id":"Mempertanyakan ulang makna bekerja agaknya berujung pada hidup yang lebih baik."}
 ]'::jsonb,
 '[
   {"word":"労働観","reading":"ろうどうかん","romaji":"roudoukan","meaning":"pandangan tentang kerja"},
   {"word":"定年","reading":"ていねん","romaji":"teinen","meaning":"usia pensiun"},
   {"word":"終身雇用","reading":"しゅうしんこよう","romaji":"shuushin koyou","meaning":"pekerjaan seumur hidup"},
   {"word":"年功序列","reading":"ねんこうじょれつ","romaji":"nenkou joretsu","meaning":"sistem senioritas"},
   {"word":"犠牲","reading":"ぎせい","romaji":"gisei","meaning":"pengorbanan"},
   {"word":"停滞","reading":"ていたい","romaji":"teitai","meaning":"stagnasi"},
   {"word":"崩れる","reading":"くずれる","romaji":"kuzureru","meaning":"runtuh"},
   {"word":"転職","reading":"てんしょく","romaji":"tenshoku","meaning":"pindah kerja"},
   {"word":"縛る","reading":"しばる","romaji":"shibaru","meaning":"mengikat/membelenggu"},
   {"word":"多様化","reading":"たようか","romaji":"tayouka","meaning":"diversifikasi"},
   {"word":"自己実現","reading":"じこじつげん","romaji":"jiko jitsugen","meaning":"aktualisasi diri"},
   {"word":"模索","reading":"もさく","romaji":"mosaku","meaning":"meraba-raba/mencari"},
   {"word":"主体的","reading":"しゅたいてき","romaji":"shutaiteki","meaning":"secara mandiri/proaktif"},
   {"word":"問い直す","reading":"といなおす","romaji":"toinaosu","meaning":"mempertanyakan ulang"},
   {"word":"もはや","reading":"もはや","romaji":"mohaya","meaning":"sudah tidak lagi"}
 ]'::jsonb,
 '[
   {"q":"Apa yang berubah seiring zaman?","options":["Cuaca","Pandangan tentang kerja (roudoukan)","Mata uang","Bahasa"],"answer":1,"explanation":"「労働観は、時代とともに変化しています」."},
   {"q":"Dulu di Jepang umumnya orang bekerja?","options":["Pindah-pindah kerja","Di satu perusahaan sampai pensiun","Tanpa bekerja","Wirausaha"],"answer":1,"explanation":"「一つの会社に定年まで勤める」."},
   {"q":"Dua sistem yang menopang cara kerja Jepang?","options":["Kontrak dan lembur","Pekerjaan seumur hidup dan senioritas","Outsourcing","Magang"],"answer":1,"explanation":"「終身雇用と年功序列」."},
   {"q":"Apa yang kini menjadi hal lumrah?","options":["Pensiun dini","Pindah kerja (tenshoku)","Kerja seumur hidup","Tidak bekerja"],"answer":1,"explanation":"「転職をすることが、ごく当たり前」."},
   {"q":"Selain mencari uang, apa yang dicari orang?","options":["Ketenaran","Aktualisasi diri","Kekuasaan","Liburan"],"answer":1,"explanation":"「自己実現を求める人も少なくありません」."},
   {"q":"Tentang cara bekerja, sekarang bagaimana?","options":["Ada satu jawaban benar","Tidak ada satu jawaban yang benar","Harus ikut perusahaan","Dilarang pindah"],"answer":1,"explanation":"「もはや、働き方に唯一の正解はありません」."}
 ]'::jsonb,
 false),
(5, 15, '生命倫理 — Bioetika',
 '医療技術の急速な進歩は、私たちに多くの恩恵をもたらしました。かつては助からなかった命が、今では救えるようになっています。しかし、その進歩は、同時に難しい問題を私たちに突きつけています。それが、生命の尊厳をめぐる「生命倫理」の問題です。例えば、回復の見込みがない患者の延命治療について考えてみましょう。機械によって、ただ命を長らえさせることが、本当に幸せなのでしょうか。「尊厳死」を望む人々の声も、近年高まっています。一方で、命を人為的に終わらせることへの反対も根強くあります。また、臓器移植も、難しい倫理的問題を含んでいます。一人の死が、他の誰かの命を救うという側面があるからです。誰の命を優先するのかという、重い判断が求められます。これらの問いに、唯一の正しい答えは存在しません。人によって、また文化や宗教によって、考え方は大きく異なります。だからこそ、私たちは、これらの問題から目を背けてはいけません。一人一人が、命とは何かを真剣に考える必要があります。科学技術の進歩に、私たちの倫理観が追いついていないのが現状です。技術をどう使うべきか、社会全体で議論を深めなければなりません。生命の尊さを忘れないことこそ、すべての出発点となるはずです。',
 '[
   {"jp":"医療技術の急速な進歩は、私たちに多くの恩恵をもたらしました。","furigana":"いりょうぎじゅつのきゅうそくなしんぽは、わたしたちにおおくのおんけいをもたらしました。","romaji":"Iryou gijutsu no kyuusoku na shinpo wa, watashitachi ni ooku no onkei o motarashimashita.","id":"Kemajuan pesat teknologi medis telah membawa banyak manfaat bagi kita."},
   {"jp":"かつては助からなかった命が、今では救えるようになっています。","furigana":"かつてはたすからなかったいのちが、いまではすくえるようになっています。","romaji":"Katsute wa tasukaranakatta inochi ga, ima de wa sukueru you ni natte imasu.","id":"Nyawa yang dulu tak terselamatkan, kini bisa diselamatkan."},
   {"jp":"しかし、その進歩は、同時に難しい問題を私たちに突きつけています。","furigana":"しかし、そのしんぽは、どうじにむずかしいもんだいをわたしたちにつきつけています。","romaji":"Shikashi, sono shinpo wa, douji ni muzukashii mondai o watashitachi ni tsukitsukete imasu.","id":"Namun, kemajuan itu sekaligus menyodorkan masalah yang sulit kepada kita."},
   {"jp":"それが、生命の尊厳をめぐる「生命倫理」の問題です。","furigana":"それが、せいめいのそんげんをめぐる「せいめいりんり」のもんだいです。","romaji":"Sore ga, seimei no songen o meguru \"seimei rinri\" no mondai desu.","id":"Itulah masalah \"bioetika\" yang berkisar pada martabat kehidupan."},
   {"jp":"例えば、回復の見込みがない患者の延命治療について考えてみましょう。","furigana":"たとえば、かいふくのみこみがないかんじゃのえんめいちりょうについてかんがえてみましょう。","romaji":"Tatoeba, kaifuku no mikomi ga nai kanja no enmei chiryou ni tsuite kangaete mimashou.","id":"Misalnya, mari pikirkan tentang perawatan memperpanjang hidup pasien yang tak ada harapan sembuh."},
   {"jp":"機械によって、ただ命を長らえさせることが、本当に幸せなのでしょうか。","furigana":"きかいによって、ただいのちをながらえさせることが、ほんとうにしあわせなのでしょうか。","romaji":"Kikai ni yotte, tada inochi o nagaraesaseru koto ga, hontou ni shiawase na no deshou ka.","id":"Apakah sekadar memperpanjang hidup dengan mesin benar-benar membahagiakan?"},
   {"jp":"「尊厳死」を望む人々の声も、近年高まっています。","furigana":"「そんげんし」をのぞむひとびとのこえも、きんねんたかまっています。","romaji":"\"Songenshi\" o nozomu hitobito no koe mo, kinnen takamatte imasu.","id":"Suara orang-orang yang menginginkan \"kematian yang bermartabat\" pun meningkat belakangan ini."},
   {"jp":"一方で、命を人為的に終わらせることへの反対も根強くあります。","furigana":"いっぽうで、いのちをじんいてきにおわらせることへのはんたいもねづよくあります。","romaji":"Ippou de, inochi o jin-iteki ni owaraseru koto e no hantai mo nezuyoku arimasu.","id":"Di sisi lain, penolakan terhadap mengakhiri kehidupan secara buatan pun mengakar kuat."},
   {"jp":"また、臓器移植も、難しい倫理的問題を含んでいます。","furigana":"また、ぞうきいしょくも、むずかしいりんりてきもんだいをふくんでいます。","romaji":"Mata, zouki ishoku mo, muzukashii rinriteki mondai o fukunde imasu.","id":"Selain itu, transplantasi organ pun mengandung masalah etis yang sulit."},
   {"jp":"一人の死が、他の誰かの命を救うという側面があるからです。","furigana":"ひとりのしが、ほかのだれかのいのちをすくうというそくめんがあるからです。","romaji":"Hitori no shi ga, hoka no dareka no inochi o sukuu to iu sokumen ga aru kara desu.","id":"Sebab ada sisi di mana kematian satu orang menyelamatkan nyawa orang lain."},
   {"jp":"誰の命を優先するのかという、重い判断が求められます。","furigana":"だれのいのちをゆうせんするのかという、おもいはんだんがもとめられます。","romaji":"Dare no inochi o yuusen suru no ka to iu, omoi handan ga motomeraremasu.","id":"Dituntut keputusan berat tentang nyawa siapa yang harus diprioritaskan."},
   {"jp":"これらの問いに、唯一の正しい答えは存在しません。","furigana":"これらのといに、ゆいいつのただしいこたえはそんざいしません。","romaji":"Korera no toi ni, yuiitsu no tadashii kotae wa sonzai shimasen.","id":"Untuk pertanyaan-pertanyaan ini, tidak ada satu jawaban yang benar."},
   {"jp":"人によって、また文化や宗教によって、考え方は大きく異なります。","furigana":"ひとによって、またぶんかやしゅうきょうによって、かんがえかたはおおきくことなります。","romaji":"Hito ni yotte, mata bunka ya shuukyou ni yotte, kangaekata wa ookiku kotonarimasu.","id":"Tergantung orangnya, juga budaya dan agama, cara pandang sangat berbeda."},
   {"jp":"だからこそ、私たちは、これらの問題から目を背けてはいけません。","furigana":"だからこそ、わたしたちは、これらのもんだいからめをそむけてはいけません。","romaji":"Dakara koso, watashitachi wa, korera no mondai kara me o somukete wa ikemasen.","id":"Justru karena itu, kita tak boleh memalingkan mata dari masalah-masalah ini."},
   {"jp":"一人一人が、命とは何かを真剣に考える必要があります。","furigana":"ひとりひとりが、いのちとはなにかをしんけんにかんがえるひつようがあります。","romaji":"Hitori hitori ga, inochi to wa nani ka o shinken ni kangaeru hitsuyou ga arimasu.","id":"Setiap orang perlu memikirkan secara serius apa itu kehidupan."},
   {"jp":"科学技術の進歩に、私たちの倫理観が追いついていないのが現状です。","furigana":"かがくぎじゅつのしんぽに、わたしたちのりんりかんがおいついていないのがげんじょうです。","romaji":"Kagaku gijutsu no shinpo ni, watashitachi no rinrikan ga oitsuite inai no ga genjou desu.","id":"Kenyataannya, pandangan etika kita belum menyusul kemajuan iptek."},
   {"jp":"技術をどう使うべきか、社会全体で議論を深めなければなりません。","furigana":"ぎじゅつをどうつかうべきか、しゃかいぜんたいでぎろんをふかめなければなりません。","romaji":"Gijutsu o dou tsukau beki ka, shakai zentai de giron o fukamenakereba narimasen.","id":"Kita harus memperdalam diskusi seluruh masyarakat tentang bagaimana teknologi seharusnya dipakai."},
   {"jp":"生命の尊さを忘れないことこそ、すべての出発点となるはずです。","furigana":"せいめいのとうとさをわすれないことこそ、すべてのしゅっぱつてんとなるはずです。","romaji":"Seimei no toutosa o wasurenai koto koso, subete no shuppatsuten to naru hazu desu.","id":"Tidak melupakan keluhuran kehidupan itulah yang seharusnya menjadi titik tolak segalanya."}
 ]'::jsonb,
 '[
   {"word":"生命倫理","reading":"せいめいりんり","romaji":"seimei rinri","meaning":"bioetika"},
   {"word":"恩恵","reading":"おんけい","romaji":"onkei","meaning":"manfaat/anugerah"},
   {"word":"突きつける","reading":"つきつける","romaji":"tsukitsukeru","meaning":"menyodorkan/menghadapkan"},
   {"word":"尊厳","reading":"そんげん","romaji":"songen","meaning":"martabat/keluhuran"},
   {"word":"見込み","reading":"みこみ","romaji":"mikomi","meaning":"harapan/prospek"},
   {"word":"延命治療","reading":"えんめいちりょう","romaji":"enmei chiryou","meaning":"perawatan memperpanjang hidup"},
   {"word":"長らえる","reading":"ながらえる","romaji":"nagaraeru","meaning":"bertahan hidup lama"},
   {"word":"尊厳死","reading":"そんげんし","romaji":"songenshi","meaning":"kematian yang bermartabat"},
   {"word":"人為的","reading":"じんいてき","romaji":"jin-iteki","meaning":"buatan/oleh manusia"},
   {"word":"根強い","reading":"ねづよい","romaji":"nezuyoi","meaning":"mengakar kuat"},
   {"word":"臓器移植","reading":"ぞうきいしょく","romaji":"zouki ishoku","meaning":"transplantasi organ"},
   {"word":"側面","reading":"そくめん","romaji":"sokumen","meaning":"sisi/aspek"},
   {"word":"優先","reading":"ゆうせん","romaji":"yuusen","meaning":"memprioritaskan"},
   {"word":"目を背ける","reading":"めをそむける","romaji":"me o somukeru","meaning":"memalingkan mata/menghindar"},
   {"word":"尊さ","reading":"とうとさ","romaji":"toutosa","meaning":"keluhuran/keberhargaan"}
 ]'::jsonb,
 '[
   {"q":"Apa yang dibawa kemajuan teknologi medis?","options":["Kerugian","Banyak manfaat","Kemiskinan","Perang"],"answer":1,"explanation":"「多くの恩恵をもたらしました」."},
   {"q":"Masalah seputar martabat kehidupan disebut?","options":["Ekonomi","Bioetika (seimei rinri)","Hukum pidana","Politik"],"answer":1,"explanation":"「『生命倫理』の問題」."},
   {"q":"Apa contoh masalah yang dibahas?","options":["Operasi plastik","Perawatan memperpanjang hidup pasien tanpa harapan sembuh","Vaksinasi","Cek darah"],"answer":1,"explanation":"「回復の見込みがない患者の延命治療」."},
   {"q":"Apa yang suaranya meningkat belakangan ini?","options":["Hidup abadi","Keinginan akan kematian yang bermartabat","Operasi gratis","Robot dokter"],"answer":1,"explanation":"「『尊厳死』を望む人々の声」."},
   {"q":"Transplantasi organ punya sisi apa?","options":["Tidak berguna","Kematian satu orang menyelamatkan nyawa orang lain","Selalu gagal","Murah"],"answer":1,"explanation":"「一人の死が、他の誰かの命を救うという側面」."},
   {"q":"Apa yang menjadi titik tolak segalanya?","options":["Mengejar teknologi","Tidak melupakan keluhuran kehidupan","Mencari untung","Mengabaikan etika"],"answer":1,"explanation":"「生命の尊さを忘れないことこそ、すべての出発点」."}
 ]'::jsonb,
 false);
