-- 041: Pass bahasa luwes #1 — pola B (parentetikal register), C ("Anda" formal),
-- dan D (kaigo klinis: "klien"/"tindakan..."). UPDATE via natural key (level_id, word)
-- agar valid di DB live maupun re-seed. Nada: natural, register "kamu", makna tetap akurat.

-- ── Pola B & C ────────────────────────────────────────────────────────────────
UPDATE public.vocab SET meaning = 'kamu / Anda', full_meaning = 'Orang Jepang jarang bilang あなた — biasanya langsung panggil nama. Kalau dipakai terus-terusan, kedengarannya kaku.', example_meaning = 'Siapa namamu?' WHERE level_id = 1 AND word = 'あなた';
UPDATE public.vocab SET example_meaning = 'Anakmu umur berapa?' WHERE level_id = 1 AND word = 'いくつ';
UPDATE public.vocab SET example_meaning = 'Kapan kamu datang?' WHERE level_id = 1 AND word = 'いつ';
UPDATE public.vocab SET example_meaning = 'Kenapa kamu menangis?' WHERE level_id = 1 AND word = 'なぜ';
UPDATE public.vocab SET meaning = 'kakak laki-laki', usage_id = 'Dipakai saat cerita soal kakakmu sendiri ke orang lain.', full_meaning = 'Buat kakakmu sendiri. Kalau kakak orang lain: お兄さん.' WHERE level_id = 1 AND word = '兄';
UPDATE public.vocab SET example_meaning = 'Siapa namamu?' WHERE level_id = 1 AND word = '名前';
UPDATE public.vocab SET meaning = 'kakak perempuan', usage_id = 'Dipakai saat cerita soal kakakmu sendiri ke orang lain.', full_meaning = 'Buat kakakmu sendiri. Kalau kakak orang lain: お姉さん.' WHERE level_id = 1 AND word = '姉';
UPDATE public.vocab SET meaning = 'ibu', usage_id = 'Dipakai saat cerita soal ibumu sendiri ke orang lain.', full_meaning = 'Buat ibumu sendiri. Kalau ibu orang lain: お母さん.' WHERE level_id = 1 AND word = '母';
UPDATE public.vocab SET meaning = 'ayah', usage_id = 'Dipakai saat cerita soal ayahmu sendiri ke orang lain.', full_meaning = 'Buat ayahmu sendiri. Kalau ayah orang lain: お父さん.' WHERE level_id = 1 AND word = '父';
UPDATE public.vocab SET example_meaning = 'Kamu bisa bahasa Inggris?' WHERE level_id = 1 AND word = '英語';
UPDATE public.vocab SET example_meaning = 'Kamu bilang apa?' WHERE level_id = 1 AND word = '言う';
UPDATE public.vocab SET example_meaning = 'Pekerjaanmu apa?' WHERE level_id = 2 AND word = '仕事';
UPDATE public.vocab SET example_meaning = 'Kamu dari negara mana?' WHERE level_id = 2 AND word = '国';
UPDATE public.vocab SET meaning = 'suami', usage_id = 'Dipakai saat cerita soal suamimu sendiri.', full_meaning = 'Buat suamimu sendiri. Kalau suami orang lain: ご主人 (ごしゅじん).' WHERE level_id = 2 AND word = '夫';
UPDATE public.vocab SET meaning = 'istri', usage_id = 'Dipakai saat cerita soal istrimu sendiri.', full_meaning = 'Buat istrimu sendiri. Kalau istri orang lain: 奥さん (おくさん).' WHERE level_id = 2 AND word = '妻';
UPDATE public.vocab SET example_meaning = 'Kamu suka warna apa?' WHERE level_id = 2 AND word = '色';
UPDATE public.vocab SET example_meaning = 'Berkat kamu, aku tertolong.' WHERE level_id = 3 AND word = '助かる';
UPDATE public.vocab SET example_meaning = 'Tolong sebutkan namamu di resepsionis.' WHERE level_id = 3 AND word = '受付';
UPDATE public.vocab SET example_meaning = 'Tolong berikan kartu namamu.' WHERE level_id = 3 AND word = '名刺';
UPDATE public.vocab SET example_meaning = 'Tolong siapkan CV-mu.' WHERE level_id = 3 AND word = '履歴書';
UPDATE public.vocab SET example_meaning = 'Berapa pendapatan tahunanmu?' WHERE level_id = 3 AND word = '年収';
UPDATE public.vocab SET example_meaning = 'Tolong sebutkan usiamu.' WHERE level_id = 3 AND word = '年齢';
UPDATE public.vocab SET full_meaning = 'kesan atau tanggapan — pendapatmu setelah mengalami sesuatu', example_meaning = 'Ceritakan kesanmu setelah nonton film itu.' WHERE level_id = 3 AND word = '感想';
UPDATE public.vocab SET example_meaning = 'Selamat atas kenaikan jabatanmu!' WHERE level_id = 3 AND word = '昇進';
UPDATE public.vocab SET usage_id = 'Tanggal lahir lengkap — yang dipakai di dokumen resmi.', example_meaning = 'Tolong isi tanggal lahirmu.' WHERE level_id = 3 AND word = '生年月日';
UPDATE public.vocab SET meaning = 'nenek', usage_id = 'Dipakai saat cerita soal nenekmu sendiri.', full_meaning = 'Buat nenekmu sendiri. Kalau nenek orang lain: おばあさん.' WHERE level_id = 3 AND word = '祖母';
UPDATE public.vocab SET meaning = 'kakek', usage_id = 'Dipakai saat cerita soal kakekmu sendiri.', full_meaning = 'Buat kakekmu sendiri. Kalau kakek orang lain: おじいさん.' WHERE level_id = 3 AND word = '祖父';
UPDATE public.vocab SET example_meaning = 'Tolong cek slip gajimu.' WHERE level_id = 3 AND word = '給与';
UPDATE public.vocab SET example_meaning = 'Tolong tulis riwayat pekerjaanmu dengan detail.' WHERE level_id = 3 AND word = '職歴';
UPDATE public.vocab SET example_meaning = 'Tolong sebutkan jenis pekerjaan yang kamu mau.' WHERE level_id = 3 AND word = '職種';
UPDATE public.vocab SET example_meaning = 'Bisa kirimkan estimasi harganya?' WHERE level_id = 3 AND word = '見積もり';
UPDATE public.vocab SET full_meaning = 'mengisi formulir atau mencatat di kolom yang tersedia', example_meaning = 'Tolong tulis namamu di sini.' WHERE level_id = 3 AND word = '記入';
UPDATE public.vocab SET full_meaning = 'kunci — juga bisa berarti gembok', example_meaning = 'Kamu sudah kunci pintu sebelum keluar?' WHERE level_id = 3 AND word = '鍵';
UPDATE public.vocab SET example_meaning = 'Jangan pendam perasaanmu.' WHERE level_id = 5 AND word = '抑圧する';

-- ── Pola D: kaigo (level_id = 6) ─────────────────────────────────────────────
UPDATE public.vocab SET full_meaning = 'bantuan berpindah tempat — misalnya dari ranjang ke kursi roda' WHERE level_id = 6 AND word = '移乗介助';
UPDATE public.vocab SET full_meaning = 'mengubah posisi tubuh lansia yang berbaring supaya tidak kena luka tekan (dekubitus)' WHERE level_id = 6 AND word = '体位変換';
UPDATE public.vocab SET full_meaning = 'menyeka tubuh lansia dengan handuk hangat kalau mandi tidak memungkinkan' WHERE level_id = 6 AND word = '清拭';
UPDATE public.vocab SET full_meaning = 'membantu lansia makan kalau sulit makan sendiri' WHERE level_id = 6 AND word = '食事介助';
UPDATE public.vocab SET full_meaning = 'membantu lansia saat buang air kecil atau besar' WHERE level_id = 6 AND word = '排泄介助';
UPDATE public.vocab SET full_meaning = 'membantu lansia mandi — masuk-keluar bak sampai membersihkan tubuh' WHERE level_id = 6 AND word = '入浴介助';
UPDATE public.vocab SET full_meaning = 'menjaga kebersihan mulut dan gigi lansia supaya tidak infeksi' WHERE level_id = 6 AND word = '口腔ケア';
UPDATE public.vocab SET full_meaning = 'membantu lansia merapikan diri — rambut, wajah, dan penampilan' WHERE level_id = 6 AND word = '整容';
UPDATE public.vocab SET full_meaning = 'membantu lansia memakai dan melepas pakaian' WHERE level_id = 6 AND word = '更衣介助';
UPDATE public.vocab SET full_meaning = 'membantu lansia berpindah dari satu tempat ke tempat lain' WHERE level_id = 6 AND word = '移動介助';
UPDATE public.vocab SET full_meaning = 'menopang lansia saat berjalan supaya tidak jatuh' WHERE level_id = 6 AND word = '歩行介助';
UPDATE public.vocab SET full_meaning = 'membantu lansia bangkit dari berbaring ke posisi duduk' WHERE level_id = 6 AND word = '起き上がり介助';
UPDATE public.vocab SET full_meaning = 'membalikkan badan lansia yang berbaring supaya tidak kena luka tekan' WHERE level_id = 6 AND word = '寝返り';
UPDATE public.vocab SET full_meaning = 'posisi duduk di tepi ranjang dengan kaki menggantung' WHERE level_id = 6 AND word = '端座位';
UPDATE public.vocab SET full_meaning = 'kemampuan berdiri dan menjaga posisi tetap stabil' WHERE level_id = 6 AND word = '立位保持';
UPDATE public.vocab SET full_meaning = 'mengganti popok yang kotor dengan yang baru' WHERE level_id = 6 AND word = 'おむつ交換';
UPDATE public.vocab SET full_meaning = 'membersihkan area kemaluan lansia supaya higienis dan tidak infeksi' WHERE level_id = 6 AND word = '陰部洗浄';
UPDATE public.vocab SET full_meaning = 'menjaga tubuh dan lingkungan lansia tetap bersih dan sehat' WHERE level_id = 6 AND word = '清潔保持';
UPDATE public.vocab SET full_meaning = 'mengawasi lansia dari dekat demi keamanan, tanpa membantu berlebihan' WHERE level_id = 6 AND word = '見守り';
UPDATE public.vocab SET full_meaning = 'menyapa dan memberi tahu lansia dulu sebelum mulai membantu' WHERE level_id = 6 AND word = '声かけ';
UPDATE public.vocab SET full_meaning = 'bantuan penuh — semua aktivitas lansia dibantu sepenuhnya' WHERE level_id = 6 AND word = '全介助';
UPDATE public.vocab SET full_meaning = 'bantuan sebagian — hanya untuk hal yang tidak bisa dilakukan lansia sendiri' WHERE level_id = 6 AND word = '一部介助';
UPDATE public.vocab SET full_meaning = 'mendukung lansia supaya bisa melakukan sebanyak mungkin hal secara mandiri' WHERE level_id = 6 AND word = '自立支援';
UPDATE public.vocab SET full_meaning = 'kemampuan tubuh yang masih ada dan dimanfaatkan dalam perawatan' WHERE level_id = 6 AND word = '残存機能';
UPDATE public.vocab SET full_meaning = 'seberapa banyak bantuan yang dibutuhkan lansia dalam suatu aktivitas' WHERE level_id = 6 AND word = '介助量';
UPDATE public.vocab SET full_meaning = 'membersihkan dan menghangatkan kaki lansia dengan air hangat' WHERE level_id = 6 AND word = '足浴';
UPDATE public.vocab SET full_meaning = 'membersihkan dan menghangatkan tangan lansia dengan air hangat' WHERE level_id = 6 AND word = '手浴';
UPDATE public.vocab SET full_meaning = 'mencuci rambut dan kulit kepala lansia' WHERE level_id = 6 AND word = '洗髪';
UPDATE public.vocab SET full_meaning = 'memotong dan merapikan kuku tangan dan kaki lansia' WHERE level_id = 6 AND word = '爪切り';
UPDATE public.vocab SET full_meaning = 'menyisir dan merapikan rambut lansia' WHERE level_id = 6 AND word = '整髪';
UPDATE public.vocab SET full_meaning = 'mencukur jenggot dan kumis lansia supaya rapi' WHERE level_id = 6 AND word = '髭剃り';
UPDATE public.vocab SET full_meaning = 'bentuk penyajian makanan, disesuaikan dengan kemampuan mengunyah dan menelan' WHERE level_id = 6 AND word = '食事形態';
UPDATE public.vocab SET full_meaning = 'makanan yang dipotong halus supaya gampang dikunyah' WHERE level_id = 6 AND word = '刻み食';
UPDATE public.vocab SET full_meaning = 'potongan makanan sebesar satu suapan supaya gampang dimakan' WHERE level_id = 6 AND word = '一口大';
UPDATE public.vocab SET full_meaning = 'pengental untuk minuman supaya lansia tidak gampang tersedak' WHERE level_id = 6 AND word = 'とろみ';
UPDATE public.vocab SET full_meaning = 'memberi cukup minum supaya lansia tidak dehidrasi' WHERE level_id = 6 AND word = '水分補給';
UPDATE public.vocab SET full_meaning = 'menyiapkan dan mengantar makanan ke tempat lansia' WHERE level_id = 6 AND word = '配膳';
UPDATE public.vocab SET full_meaning = 'membereskan peralatan makan setelah lansia selesai makan' WHERE level_id = 6 AND word = '下膳';
UPDATE public.vocab SET full_meaning = 'mengangkat tubuh lansia dengan memeluknya saat memindahkan' WHERE level_id = 6 AND word = '抱え上げ';
UPDATE public.vocab SET full_meaning = 'pegangan atau palang untuk membantu lansia berpindah posisi' WHERE level_id = 6 AND word = '介助バー';
UPDATE public.vocab SET full_meaning = 'keadaan tubuh dan hati yang tenang dan nyaman' WHERE level_id = 6 AND word = '安楽';
UPDATE public.vocab SET full_meaning = 'membantu lansia bangun dan turun dari ranjang untuk beraktivitas' WHERE level_id = 6 AND word = '離床';
UPDATE public.vocab SET full_meaning = 'keadaan berbaring di tempat tidur untuk istirahat' WHERE level_id = 6 AND word = '臥床';
UPDATE public.vocab SET full_meaning = 'menaikkan bagian kepala ranjang sampai lansia setengah duduk' WHERE level_id = 6 AND word = 'ギャッジアップ';
UPDATE public.vocab SET full_meaning = 'mengajak dan mengarahkan lansia ke toilet pada waktu yang pas' WHERE level_id = 6 AND word = '排泄誘導';
UPDATE public.vocab SET full_meaning = 'kebiasaan waktu dan frekuensi buang air lansia — diamati untuk menentukan perawatan' WHERE level_id = 6 AND word = '排泄パターン';
UPDATE public.vocab SET full_meaning = 'mencegah munculnya luka tekan (dekubitus) pada lansia yang lama berbaring' WHERE level_id = 6 AND word = '褥瘡予防';
UPDATE public.vocab SET full_meaning = 'membantu lansia pindah dari tempat tidur ke kursi roda' WHERE level_id = 6 AND word = '車椅子移乗';
UPDATE public.vocab SET full_meaning = 'berendam hanya sampai pinggang supaya jantung tidak terbebani' WHERE level_id = 6 AND word = '半身浴';
UPDATE public.vocab SET usage_id = 'Menyedot dahak dari saluran napas lansia yang tidak bisa mengeluarkannya sendiri.', full_meaning = 'menyedot dahak dari tenggorokan atau saluran napas dengan alat khusus' WHERE level_id = 6 AND word = '喀痰吸引';
UPDATE public.vocab SET usage_id = 'Memberi nutrisi lewat selang untuk lansia yang tidak bisa makan lewat mulut.', full_meaning = 'pemberian nutrisi cair lewat selang langsung ke lambung atau usus' WHERE level_id = 6 AND word = '経管栄養';
UPDATE public.vocab SET usage_id = 'Mengukur tekanan darah lansia dengan tensimeter.', full_meaning = 'mengukur tekanan darah dengan tensimeter' WHERE level_id = 6 AND word = '血圧測定';
UPDATE public.vocab SET usage_id = 'Suhu tubuh lansia — salah satu penanda kondisi kesehatan.', full_meaning = 'suhu tubuh yang diukur untuk memantau kondisi kesehatan' WHERE level_id = 6 AND word = '体温';
UPDATE public.vocab SET usage_id = 'Mengukur suhu tubuh lansia dengan termometer.', full_meaning = 'mengukur suhu tubuh dengan termometer' WHERE level_id = 6 AND word = '検温';
UPDATE public.vocab SET usage_id = 'Jumlah napas lansia per menit.', full_meaning = 'jumlah napas dalam satu menit — salah satu tanda vital' WHERE level_id = 6 AND word = '呼吸数';
UPDATE public.vocab SET usage_id = 'Membantu lansia minum obat sesuai aturan.', full_meaning = 'membantu lansia minum obat dengan benar dan tepat waktu' WHERE level_id = 6 AND word = '服薬介助';
UPDATE public.vocab SET usage_id = 'Memberikan obat kepada lansia sesuai resep.', full_meaning = 'memberikan obat sesuai instruksi medis' WHERE level_id = 6 AND word = '与薬';
UPDATE public.vocab SET usage_id = 'Mengoleskan salep pada kulit lansia.', full_meaning = 'mengoleskan obat salep pada kulit' WHERE level_id = 6 AND word = '軟膏塗布';
UPDATE public.vocab SET usage_id = 'Meneteskan obat ke mata lansia.', full_meaning = 'memberikan obat tetes mata' WHERE level_id = 6 AND word = '点眼';
UPDATE public.vocab SET full_meaning = 'memasukkan cairan lewat dubur untuk merangsang buang air besar' WHERE level_id = 6 AND word = '浣腸';
UPDATE public.vocab SET full_meaning = 'mengeluarkan tinja yang mengeras dari dubur secara manual' WHERE level_id = 6 AND word = '摘便';
UPDATE public.vocab SET full_meaning = 'menghirup obat berbentuk uap lewat saluran napas' WHERE level_id = 6 AND word = '吸入';
UPDATE public.vocab SET usage_id = 'Merawat dan membersihkan luka lansia.', full_meaning = 'membersihkan dan merawat luka supaya tidak infeksi' WHERE level_id = 6 AND word = '創傷処置';
UPDATE public.vocab SET full_meaning = 'mengganti kasa penutup luka dengan yang baru' WHERE level_id = 6 AND word = 'ガーゼ交換';
UPDATE public.vocab SET usage_id = 'Mengukur kadar gula darah lansia.', full_meaning = 'mengukur kadar gula darah dengan alat khusus' WHERE level_id = 6 AND word = '血糖測定';
UPDATE public.vocab SET usage_id = 'Menyuntikkan insulin untuk mengontrol gula darah lansia diabetes.', full_meaning = 'menyuntikkan insulin untuk menurunkan kadar gula darah' WHERE level_id = 6 AND word = 'インスリン注射';
UPDATE public.vocab SET usage_id = 'Mengambil sampel darah lansia untuk pemeriksaan.', full_meaning = 'mengambil sampel darah untuk pemeriksaan' WHERE level_id = 6 AND word = '採血';
UPDATE public.vocab SET full_meaning = 'mengeluarkan urine dari kandung kemih lewat selang kateter' WHERE level_id = 6 AND word = '導尿';
UPDATE public.vocab SET usage_id = 'Pemberian oksigen di rumah untuk lansia dengan gangguan napas.', full_meaning = 'terapi oksigen yang dilakukan di rumah' WHERE level_id = 6 AND word = '在宅酸素療法';
UPDATE public.vocab SET usage_id = 'Alat bantu napas untuk lansia yang tidak bisa bernapas sendiri.', full_meaning = 'alat medis yang membantu atau menggantikan pernapasan' WHERE level_id = 6 AND word = '人工呼吸器';
UPDATE public.vocab SET usage_id = 'Mencegah kesalahan pemberian obat kepada lansia.', full_meaning = 'mencegah salah jenis, dosis, atau waktu saat memberi obat' WHERE level_id = 6 AND word = '誤薬防止';
UPDATE public.vocab SET usage_id = 'Kerja sama staf perawatan dengan perawat untuk lansia.', full_meaning = 'kerja sama dan komunikasi antara pengasuh dan perawat' WHERE level_id = 6 AND word = '看護師連携';
UPDATE public.vocab SET full_meaning = 'perbuatan medis yang menurut hukum hanya boleh dilakukan tenaga medis berwenang' WHERE level_id = 6 AND word = '医療行為';
UPDATE public.vocab SET usage_id = 'Cara bertindak saat kondisi lansia berubah mendadak.', full_meaning = 'langkah yang diambil saat kondisi lansia memburuk mendadak' WHERE level_id = 6 AND word = '急変時対応';
UPDATE public.vocab SET usage_id = 'Menyelamatkan lansia yang henti jantung atau henti napas.', full_meaning = 'pertolongan darurat untuk memulihkan denyut jantung dan napas (CPR)' WHERE level_id = 6 AND word = '心肺蘇生';
UPDATE public.vocab SET full_meaning = 'penanganan awal saat ada cedera atau sakit mendadak' WHERE level_id = 6 AND word = '応急処置';
UPDATE public.vocab SET usage_id = 'Mengamati kondisi tubuh lansia untuk mendeteksi perubahan.', full_meaning = 'mengamati kondisi kesehatan lansia secara berkala' WHERE level_id = 6 AND word = '体調観察';
UPDATE public.vocab SET usage_id = 'Menjaga kesehatan lansia supaya tetap baik.', full_meaning = 'pengelolaan kesehatan lansia sehari-hari' WHERE level_id = 6 AND word = '健康管理';
UPDATE public.vocab SET usage_id = 'Aturan dasar pencegahan infeksi yang berlaku untuk semua orang.', full_meaning = 'langkah dasar pencegahan infeksi yang diterapkan ke semua orang' WHERE level_id = 6 AND word = '標準予防策';
UPDATE public.vocab SET full_meaning = 'membersihkan tangan dengan cairan antiseptik atau alkohol' WHERE level_id = 6 AND word = '手指消毒';
UPDATE public.vocab SET usage_id = 'Dokter menentukan jenis dan dosis obat untuk lansia.', full_meaning = 'jenis dan takaran obat yang ditetapkan dokter' WHERE level_id = 6 AND word = '処方';
UPDATE public.vocab SET usage_id = 'Alat bantu beroda untuk lansia yang sulit berjalan.', full_meaning = 'kursi beroda untuk membantu mobilitas orang yang sulit berjalan' WHERE level_id = 6 AND word = '車椅子';
UPDATE public.vocab SET usage_id = 'Kursi roda bermotor listrik yang bisa dikemudikan sendiri.', full_meaning = 'kursi roda bertenaga listrik yang bisa dijalankan sendiri' WHERE level_id = 6 AND word = '電動車椅子';
UPDATE public.vocab SET usage_id = 'Papan licin untuk memindahkan lansia dengan cara menggeser.', full_meaning = 'papan licin untuk membantu berpindah dengan cara digeser' WHERE level_id = 6 AND word = 'スライディングボード';
UPDATE public.vocab SET full_meaning = 'kain licin untuk menggeser posisi tubuh di atas tempat tidur' WHERE level_id = 6 AND word = 'スライディングシート';
UPDATE public.vocab SET usage_id = 'Alat angkat untuk lansia yang tidak bisa berpindah sendiri.', full_meaning = 'mesin pengangkat untuk membantu berpindah tempat' WHERE level_id = 6 AND word = '移乗用リフト';
UPDATE public.vocab SET usage_id = 'Batang pegangan untuk menopang gerakan lansia.', full_meaning = 'batang pegangan untuk menopang tubuh saat bergerak' WHERE level_id = 6 AND word = '手すり';
UPDATE public.vocab SET usage_id = 'Popok penyerap untuk lansia yang sulit ke toilet.', full_meaning = 'popok penyerap untuk yang sulit ke toilet sendiri' WHERE level_id = 6 AND word = 'おむつ';
UPDATE public.vocab SET full_meaning = 'popok model celana yang bisa dipakai-lepas sendiri' WHERE level_id = 6 AND word = 'リハビリパンツ';
UPDATE public.vocab SET usage_id = 'Pispot yang diselipkan di bawah pinggul lansia yang berbaring.', full_meaning = 'pispot yang diselipkan di bawah pinggul untuk buang air sambil berbaring' WHERE level_id = 6 AND word = '差し込み便器';
UPDATE public.vocab SET usage_id = 'Alat angkat untuk menurunkan lansia ke dalam bak mandi.', full_meaning = 'mesin angkat untuk membantu masuk dan keluar bak mandi' WHERE level_id = 6 AND word = '入浴用リフト';
UPDATE public.vocab SET usage_id = 'Alat yang membantu lansia beraktivitas sehari-hari secara mandiri.', full_meaning = 'alat bantu supaya kegiatan harian bisa dikerjakan sendiri' WHERE level_id = 6 AND word = '自助具';
UPDATE public.vocab SET usage_id = 'Alat yang memperkuat suara untuk yang sulit mendengar.', full_meaning = 'alat penguat suara untuk gangguan pendengaran' WHERE level_id = 6 AND word = '補聴器';
UPDATE public.vocab SET usage_id = 'Alat bantu penglihatan.', full_meaning = 'alat bantu penglihatan sehari-hari' WHERE level_id = 6 AND word = '眼鏡';
UPDATE public.vocab SET usage_id = 'Lift beroda yang didorong di lantai untuk memindahkan lansia.', full_meaning = 'lift beroda yang didorong di lantai untuk memindahkan lansia' WHERE level_id = 6 AND word = '床走行式リフト';
UPDATE public.vocab SET usage_id = 'Pagar di sisi tempat tidur supaya lansia tidak jatuh.', full_meaning = 'pagar sisi ranjang pencegah jatuh' WHERE level_id = 6 AND word = 'ベッド柵';
UPDATE public.vocab SET full_meaning = 'sarung tangan licin untuk menggeser dan mengatur posisi tubuh lansia' WHERE level_id = 6 AND word = '介助グローブ';
UPDATE public.vocab SET usage_id = 'Alat angkat untuk memindahkan lansia antar ruangan atau perabot.', full_meaning = 'alat pengangkat untuk memindahkan lansia antar tempat' WHERE level_id = 6 AND word = '移動用リフト';
UPDATE public.vocab SET usage_id = 'Layanan sewa alat bantu lewat asuransi perawatan (kaigo hoken).', full_meaning = 'layanan penyewaan alat bantu lewat asuransi perawatan' WHERE level_id = 6 AND word = '福祉用具貸与';
UPDATE public.vocab SET usage_id = 'Istilah umum untuk alat bantu berjalan.', full_meaning = 'sebutan umum alat yang membantu berjalan' WHERE level_id = 6 AND word = '歩行補助具';
UPDATE public.vocab SET usage_id = 'Sendok atau alat makan khusus supaya lansia bisa makan sendiri.', full_meaning = 'alat makan khusus supaya bisa makan secara mandiri' WHERE level_id = 6 AND word = '食事用自助具';
UPDATE public.vocab SET full_meaning = 'alat bantu memakai kaus kaki tanpa perlu membungkuk' WHERE level_id = 6 AND word = 'ストッキングエイド';
UPDATE public.vocab SET usage_id = 'Meja kecil di sisi ranjang untuk meletakkan barang.' WHERE level_id = 6 AND word = 'ベッドサイドテーブル';
UPDATE public.vocab SET full_meaning = 'alat penyedot dahak atau lendir dari saluran napas' WHERE level_id = 6 AND word = '吸引器';
UPDATE public.vocab SET usage_id = 'Bantal penopang supaya posisi tubuh lansia nyaman.' WHERE level_id = 6 AND word = '安楽枕';
UPDATE public.vocab SET usage_id = 'Sabuk pengaman pembatas gerak — hanya untuk situasi tertentu.', full_meaning = 'sabuk pembatas gerak tubuh yang hanya boleh dipakai di situasi tertentu' WHERE level_id = 6 AND word = '抑制帯';
UPDATE public.vocab SET usage_id = 'Tingkatan resmi seberapa besar perawatan yang dibutuhkan lansia.', full_meaning = 'tingkatan resmi kebutuhan perawatan lansia' WHERE level_id = 6 AND word = '要介護度';
UPDATE public.vocab SET usage_id = 'Rencana layanan yang disusun sesuai kebutuhan tiap lansia.', full_meaning = 'dokumen rencana layanan perawatan untuk tiap lansia' WHERE level_id = 6 AND word = 'ケアプラン';
UPDATE public.vocab SET usage_id = 'Petugas yang membantu perawatan di rumah lansia.', full_meaning = 'petugas yang datang membantu perawatan di rumah' WHERE level_id = 6 AND word = 'ホームヘルパー';
UPDATE public.vocab SET usage_id = 'Layanan perawatan dengan mengunjungi rumah lansia.', full_meaning = 'layanan perawatan dengan berkunjung ke rumah' WHERE level_id = 6 AND word = '訪問介護';
UPDATE public.vocab SET usage_id = 'Layanan medis oleh perawat di rumah lansia.', full_meaning = 'layanan keperawatan medis oleh perawat di rumah' WHERE level_id = 6 AND word = '訪問看護';
UPDATE public.vocab SET usage_id = 'Menyampaikan info kondisi lansia dari satu shift ke shift berikutnya.', full_meaning = 'serah-terima informasi saat pergantian shift' WHERE level_id = 6 AND word = '申し送り';
UPDATE public.vocab SET usage_id = 'Catatan tertulis kondisi dan layanan yang diberikan ke lansia.', full_meaning = 'dokumentasi tertulis kondisi lansia dan layanan yang diberikan' WHERE level_id = 6 AND word = '介護記録';
UPDATE public.vocab SET usage_id = 'Penilaian menyeluruh kondisi dan kebutuhan lansia sebelum menyusun rencana.', full_meaning = 'penilaian menyeluruh kondisi dan kebutuhan lansia' WHERE level_id = 6 AND word = 'アセスメント';
UPDATE public.vocab SET usage_id = 'Latihan untuk memulihkan atau menjaga fungsi tubuh.', full_meaning = 'latihan pemulihan dan pemeliharaan fungsi tubuh' WHERE level_id = 6 AND word = 'リハビリテーション';
UPDATE public.vocab SET usage_id = 'Penyusunan rencana dan koordinasi perawatan untuk lansia di rumah.', full_meaning = 'layanan penyusunan rencana dan koordinasi perawatan di rumah' WHERE level_id = 6 AND word = '居宅介護支援';
UPDATE public.vocab SET usage_id = 'Lansia mulai tinggal dan dirawat di fasilitas.', full_meaning = 'mulai tinggal dan dirawat di fasilitas perawatan' WHERE level_id = 6 AND word = '入所';
UPDATE public.vocab SET usage_id = 'Lansia berhenti tinggal di fasilitas perawatan.', full_meaning = 'berhenti tinggal di fasilitas perawatan' WHERE level_id = 6 AND word = '退所';
UPDATE public.vocab SET usage_id = 'Membatasi gerak lansia — pada dasarnya dilarang.', full_meaning = 'pembatasan gerak fisik yang pada dasarnya dilarang' WHERE level_id = 6 AND word = '身体拘束';
UPDATE public.vocab SET usage_id = 'Perawatan yang disesuaikan kebutuhan dan kebiasaan tiap lansia.', full_meaning = 'perawatan yang menyesuaikan kebutuhan dan kebiasaan tiap orang' WHERE level_id = 6 AND word = '個別ケア';
UPDATE public.vocab SET usage_id = 'Bagian biaya layanan yang dibayar sendiri oleh pengguna.', full_meaning = 'bagian biaya yang ditanggung sendiri oleh pengguna layanan' WHERE level_id = 6 AND word = '利用者負担';
UPDATE public.vocab SET usage_id = 'Persen biaya yang ditanggung pengguna, sesuai penghasilan.', full_meaning = 'persentase biaya yang ditanggung pengguna sesuai penghasilan' WHERE level_id = 6 AND word = '負担割合';
UPDATE public.vocab SET usage_id = 'Rapat antarpetugas untuk menyusun rencana perawatan lansia.', full_meaning = 'rapat antarpetugas untuk membahas rencana perawatan' WHERE level_id = 6 AND word = 'サービス担当者会議';
UPDATE public.vocab SET usage_id = 'Petugas yang menangani konsultasi dan urusan penghuni fasilitas.', full_meaning = 'petugas konsultasi dan koordinasi di fasilitas' WHERE level_id = 6 AND word = '生活相談員';
UPDATE public.vocab SET usage_id = 'Pemandu latihan untuk menjaga dan memulihkan fungsi tubuh lansia.', full_meaning = 'tenaga pemandu latihan fungsi tubuh' WHERE level_id = 6 AND word = '機能訓練指導員';
UPDATE public.vocab SET usage_id = 'Persetujuan lansia/keluarga setelah dapat penjelasan yang cukup.', full_meaning = 'persetujuan setelah menerima penjelasan yang cukup tentang layanan' WHERE level_id = 6 AND word = 'インフォームドコンセント';
UPDATE public.vocab SET usage_id = 'Rencana perawatan terperinci yang disusun staf untuk tiap lansia.', full_meaning = 'rencana perawatan terperinci untuk tiap penghuni fasilitas' WHERE level_id = 6 AND word = '介護計画';
UPDATE public.vocab SET usage_id = 'Latihan menjaga dan memulihkan fungsi gerak tubuh lansia.', full_meaning = 'latihan terprogram untuk fungsi gerak tubuh' WHERE level_id = 6 AND word = '機能訓練';
UPDATE public.vocab SET usage_id = 'Bantuan urusan rumah tangga seperti memasak dan bersih-bersih.', full_meaning = 'bantuan urusan rumah tangga dalam layanan kunjungan' WHERE level_id = 6 AND word = '生活援助';
UPDATE public.vocab SET usage_id = 'Mendampingi lansia pergi-pulang berobat.', full_meaning = 'pendampingan pergi dan pulang berobat' WHERE level_id = 6 AND word = '通院介助';
UPDATE public.vocab SET usage_id = 'Mengatur jenis, dosis, dan waktu minum obat lansia.', full_meaning = 'pengaturan jenis, dosis, dan jadwal minum obat' WHERE level_id = 6 AND word = '服薬管理';
UPDATE public.vocab SET usage_id = 'Memastikan keadaan lansia aman, terutama yang tinggal sendiri.', full_meaning = 'pengecekan rutin keadaan lansia, terutama yang tinggal sendiri' WHERE level_id = 6 AND word = '安否確認';
UPDATE public.vocab SET usage_id = 'Latihan memperbaiki kemampuan menelan lansia.', full_meaning = 'latihan menjaga dan memperbaiki kemampuan menelan' WHERE level_id = 6 AND word = '嚥下訓練';
UPDATE public.vocab SET usage_id = 'Sarung tangan licin untuk membantu menggeser tubuh lansia.', example_meaning = 'Dengan sarung tangan bantu, tubuh lansia lebih ringan digerakkan.' WHERE level_id = 6 AND word = '介助グローブ';
