-- 042: Pass bahasa luwes #2 — pola A: full_meaning yang berupa daftar sinonim
-- dipisah koma (gaya kamus, kaku) diubah jadi frasa natural. Semua baris N3.
-- Catatan: baris 感想/記入/鍵 sudah ditangani di 041.

UPDATE public.vocab SET full_meaning = 'cahaya atau penerangan — misalnya sinar lampu' WHERE level_id = 3 AND word = '明かり';
UPDATE public.vocab SET full_meaning = 'menjadi terang atau fajar menyingsing; juga dipakai saat tahun berganti' WHERE level_id = 3 AND word = '明ける';
UPDATE public.vocab SET full_meaning = 'jelas dan nyata — gamblang, tidak samar' WHERE level_id = 3 AND word = '明らか';
UPDATE public.vocab SET full_meaning = 'iblis atau setan — roh jahat' WHERE level_id = 3 AND word = '悪魔';
UPDATE public.vocab SET full_meaning = 'baru atau segar — sesuatu yang dimulai lagi dari awal' WHERE level_id = 3 AND word = '新た';
UPDATE public.vocab SET full_meaning = 'segala macam — semua tanpa kecuali' WHERE level_id = 3 AND word = 'あらゆる';
UPDATE public.vocab SET full_meaning = 'perkumpulan atau pertemuan — acara kumpul-kumpul' WHERE level_id = 3 AND word = '集まり';
UPDATE public.vocab SET full_meaning = 'bagian atau porsi dari sesuatu yang lebih besar' WHERE level_id = 3 AND word = '部分';
UPDATE public.vocab SET full_meaning = 'analisis — mengurai sesuatu untuk dikaji lebih dalam' WHERE level_id = 3 AND word = '分析';
UPDATE public.vocab SET full_meaning = 'bidang atau ranah keahlian' WHERE level_id = 3 AND word = '分野';
UPDATE public.vocab SET full_meaning = 'kedudukan atau status sosial — termasuk jabatan' WHERE level_id = 3 AND word = '地位';
UPDATE public.vocab SET full_meaning = 'perwakilan — orang atau pihak yang mewakili' WHERE level_id = 3 AND word = '代表';
UPDATE public.vocab SET full_meaning = 'kira-kira atau secara garis besar' WHERE level_id = 3 AND word = '大体';
UPDATE public.vocab SET full_meaning = 'diam atau membisu — tidak bersuara' WHERE level_id = 3 AND word = '黙る';
UPDATE public.vocab SET full_meaning = 'memeluk atau mendekap — juga menggendong' WHERE level_id = 3 AND word = '抱く';
UPDATE public.vocab SET full_meaning = 'perjumpaan — momen bertemu atau berkenalan dengan seseorang' WHERE level_id = 3 AND word = '出会い';
UPDATE public.vocab SET full_meaning = 'anak laki-laki atau pemuda' WHERE level_id = 3 AND word = '男子';
UPDATE public.vocab SET full_meaning = 'usaha atau kerja keras' WHERE level_id = 3 AND word = '努力';
UPDATE public.vocab SET full_meaning = 'kekurangan — jumlahnya tidak cukup' WHERE level_id = 3 AND word = '不足';
UPDATE public.vocab SET full_meaning = 'sekali lagi — terjadi atau dilakukan kembali' WHERE level_id = 3 AND word = '再び';
UPDATE public.vocab SET full_meaning = 'ilmu pengetahuan — bidang studi dan keilmuan' WHERE level_id = 3 AND word = '学問';
UPDATE public.vocab SET full_meaning = 'ilmuwan atau sarjana — orang yang mendalami ilmu' WHERE level_id = 3 AND word = '学者';
UPDATE public.vocab SET full_meaning = 'hebat atau dahsyat — intens dan keras' WHERE level_id = 3 AND word = '激しい';
UPDATE public.vocab SET full_meaning = 'penemuan — menciptakan sesuatu yang baru' WHERE level_id = 3 AND word = '発明';
UPDATE public.vocab SET full_meaning = 'melepas atau mencopot sesuatu dari tempatnya' WHERE level_id = 3 AND word = '外す';
UPDATE public.vocab SET full_meaning = 'kesesuaian atau kecocokan — sama persis satu sama lain' WHERE level_id = 3 AND word = '一致';
UPDATE public.vocab SET full_meaning = 'di luar dugaan — tidak disangka-sangka' WHERE level_id = 3 AND word = '意外';
UPDATE public.vocab SET full_meaning = 'pelatihan atau latihan yang terarah' WHERE level_id = 3 AND word = '訓練';
UPDATE public.vocab SET full_meaning = 'terjatuh atau tersungkur' WHERE level_id = 3 AND word = '転ぶ';
UPDATE public.vocab SET full_meaning = 'kecepatan tinggi — juga singkatan jalan tol (高速道路)' WHERE level_id = 3 AND word = '高速';
UPDATE public.vocab SET full_meaning = 'kerja sama — saling bantu untuk satu tujuan' WHERE level_id = 3 AND word = '協力';
UPDATE public.vocab SET full_meaning = 'kuat dan bertenaga — ampuh' WHERE level_id = 3 AND word = '強力';
UPDATE public.vocab SET full_meaning = 'rakyat atau warga negara' WHERE level_id = 3 AND word = '国民';
UPDATE public.vocab SET full_meaning = 'mulai sekarang dan ke depannya' WHERE level_id = 3 AND word = '今後';
UPDATE public.vocab SET full_meaning = 'pembayaran atau tagihan — juga berarti akuntansi' WHERE level_id = 3 AND word = '会計';
UPDATE public.vocab SET full_meaning = 'dasar atau pokok — fondasi dari sesuatu' WHERE level_id = 3 AND word = '基本';
UPDATE public.vocab SET full_meaning = 'artikel atau tulisan berita' WHERE level_id = 3 AND word = '記事';
UPDATE public.vocab SET full_meaning = 'peringatan atau kenang-kenangan' WHERE level_id = 3 AND word = '記念';
UPDATE public.vocab SET full_meaning = 'permulaan — saat sesuatu dimulai' WHERE level_id = 3 AND word = '開始';
UPDATE public.vocab SET full_meaning = 'harapan atau ekspektasi terhadap sesuatu' WHERE level_id = 3 AND word = '期待';
UPDATE public.vocab SET full_meaning = 'tiba-tiba atau mendadak' WHERE level_id = 3 AND word = '急に';
UPDATE public.vocab SET full_meaning = 'cepat dan pesat perkembangannya' WHERE level_id = 3 AND word = '急速';
UPDATE public.vocab SET full_meaning = 'serius dan rajin — bersungguh-sungguh' WHERE level_id = 3 AND word = '真面目';
UPDATE public.vocab SET full_meaning = 'puas — merasa cukup dan senang' WHERE level_id = 3 AND word = '満足';
UPDATE public.vocab SET full_meaning = 'belajar atau mempelajari sesuatu' WHERE level_id = 3 AND word = '学ぶ';
UPDATE public.vocab SET full_meaning = 'antusias dan bersemangat' WHERE level_id = 3 AND word = '熱心';
UPDATE public.vocab SET full_meaning = 'kemampuan atau kecakapan' WHERE level_id = 3 AND word = '能力';
UPDATE public.vocab SET full_meaning = 'keuntungan atau laba — juga berarti manfaat' WHERE level_id = 3 AND word = '利益';
UPDATE public.vocab SET full_meaning = 'bukti atau pembuktian — juga dipakai untuk sertifikat' WHERE level_id = 3 AND word = '証明';
UPDATE public.vocab SET full_meaning = 'konsentrasi — memusatkan perhatian ke satu hal' WHERE level_id = 3 AND word = '集中';
UPDATE public.vocab SET full_meaning = 'usaha dagang atau bisnis' WHERE level_id = 3 AND word = '商売';
UPDATE public.vocab SET full_meaning = 'dokumen atau berkas' WHERE level_id = 3 AND word = '書類';
UPDATE public.vocab SET full_meaning = 'tanah atau lahan' WHERE level_id = 3 AND word = '土地';
UPDATE public.vocab SET full_meaning = 'berturut-turut — terjadi beruntun tanpa jeda' WHERE level_id = 3 AND word = '連続';
UPDATE public.vocab SET full_meaning = 'pada akhirnya — ujung-ujungnya' WHERE level_id = 3 AND word = '結局';
UPDATE public.vocab SET full_meaning = 'dengan kata lain — singkatnya' WHERE level_id = 3 AND word = 'つまり';
UPDATE public.vocab SET full_meaning = 'menerima atau mengambil sesuatu yang diberikan' WHERE level_id = 3 AND word = '受け取る';
UPDATE public.vocab SET full_meaning = 'membagi atau memisahkan — memilah jadi beberapa bagian' WHERE level_id = 3 AND word = '分ける';
UPDATE public.vocab SET full_meaning = 'mendadak dan drastis' WHERE level_id = 3 AND word = '急激';
UPDATE public.vocab SET full_meaning = 'jelas dan tegas — tidak ambigu' WHERE level_id = 3 AND word = '明確';
UPDATE public.vocab SET full_meaning = 'sekutu atau pendukung — pihak yang ada di sisimu' WHERE level_id = 3 AND word = '味方';
UPDATE public.vocab SET full_meaning = 'memperoleh atau meraih — juga berarti menyimpan' WHERE level_id = 3 AND word = '収める';
UPDATE public.vocab SET full_meaning = 'pandai dan cerdik' WHERE level_id = 3 AND word = '利口';
UPDATE public.vocab SET full_meaning = 'rangsangan atau dorongan — sesuatu yang memancing reaksi' WHERE level_id = 3 AND word = '刺激';
UPDATE public.vocab SET full_meaning = 'kelompok atau kumpulan orang' WHERE level_id = 3 AND word = '集団';
UPDATE public.vocab SET full_meaning = 'turnamen atau kejuaraan — acara besar' WHERE level_id = 3 AND word = '大会';
UPDATE public.vocab SET full_meaning = 'sulap — trik ilusi' WHERE level_id = 3 AND word = '手品';
UPDATE public.vocab SET full_meaning = 'fajar — saat langit mulai terang' WHERE level_id = 3 AND word = '夜明け';
UPDATE public.vocab SET full_meaning = 'berlebih — ekstra di luar yang dibutuhkan' WHERE level_id = 3 AND word = '余分';
UPDATE public.vocab SET full_meaning = 'umum — berlaku untuk kebanyakan orang' WHERE level_id = 3 AND word = '一般';
UPDATE public.vocab SET full_meaning = 'mahir atau pandai; untuk makanan berarti lezat' WHERE level_id = 3 AND word = '上手い';
UPDATE public.vocab SET full_meaning = 'sejenis atau semacam — satu jenis dari sesuatu' WHERE level_id = 3 AND word = '一種';
UPDATE public.vocab SET full_meaning = 'lumayan atau cukup; dengan kalimat negatif berarti sulit' WHERE level_id = 3 AND word = 'なかなか';
UPDATE public.vocab SET full_meaning = 'malah atau justru — lebih baik begitu' WHERE level_id = 3 AND word = 'むしろ';
UPDATE public.vocab SET full_meaning = 'pertemuan atau rapat' WHERE level_id = 3 AND word = '会合';
UPDATE public.vocab SET full_meaning = 'gangguan atau penghalang' WHERE level_id = 3 AND word = '邪魔';
UPDATE public.vocab SET full_meaning = 'nasi atau makanan — kata kasual untuk makan' WHERE level_id = 3 AND word = '飯';
UPDATE public.vocab SET full_meaning = 'mengemudi — juga mengoperasikan mesin' WHERE level_id = 3 AND word = '運転';
UPDATE public.vocab SET full_meaning = 'omongan buruk — hinaan atau gunjingan di belakang' WHERE level_id = 3 AND word = '悪口';
UPDATE public.vocab SET full_meaning = 'lepas atau terlepas — juga berarti bisa diambil' WHERE level_id = 3 AND word = '取れる';
UPDATE public.vocab SET full_meaning = 'mengangkat atau membahas suatu topik; juga berarti menyita' WHERE level_id = 3 AND word = '取り上げる';
UPDATE public.vocab SET full_meaning = 'budaya atau kebudayaan' WHERE level_id = 3 AND word = '文化';
UPDATE public.vocab SET full_meaning = 'kebebasan — bebas dan leluasa' WHERE level_id = 3 AND word = '自由';
UPDATE public.vocab SET full_meaning = 'tidak boleh — juga berarti percuma atau gagal' WHERE level_id = 3 AND word = '駄目';
UPDATE public.vocab SET full_meaning = 'pengaruh atau dampak' WHERE level_id = 3 AND word = '影響';
UPDATE public.vocab SET full_meaning = 'sangat atau jauh lebih — kadarnya lumayan besar' WHERE level_id = 3 AND word = '随分';
UPDATE public.vocab SET full_meaning = 'hubungan atau kaitan' WHERE level_id = 3 AND word = '関係';
UPDATE public.vocab SET full_meaning = 'keluhan atau protes — omelan' WHERE level_id = 3 AND word = '文句';
UPDATE public.vocab SET full_meaning = 'hebat atau luar biasa; dengan kalimat negatif berarti tidak seberapa' WHERE level_id = 3 AND word = '大した';
UPDATE public.vocab SET full_meaning = 'sekadar atau cuma — tidak lebih dari itu' WHERE level_id = 3 AND word = '単なる';
UPDATE public.vocab SET full_meaning = 'baik atau boleh — versi sopan dari いい' WHERE level_id = 3 AND word = '宜しい';
UPDATE public.vocab SET full_meaning = 'watak atau kepribadian seseorang' WHERE level_id = 3 AND word = '性格';
UPDATE public.vocab SET full_meaning = 'menahan diri atau bersabar' WHERE level_id = 3 AND word = '我慢';
UPDATE public.vocab SET full_meaning = 'lengah — lalai karena merasa aman' WHERE level_id = 3 AND word = '油断';
UPDATE public.vocab SET full_meaning = 'asyik sampai lupa waktu — larut dalam sesuatu' WHERE level_id = 3 AND word = '夢中';
UPDATE public.vocab SET full_meaning = 'bimbang atau ragu; juga berarti tersesat' WHERE level_id = 3 AND word = '迷う';
UPDATE public.vocab SET full_meaning = 'koridor atau lorong' WHERE level_id = 3 AND word = '廊下';
UPDATE public.vocab SET full_meaning = 'ganti kereta atau bus — transit' WHERE level_id = 3 AND word = '乗り換え';
UPDATE public.vocab SET full_meaning = 'telepon genggam — HP' WHERE level_id = 3 AND word = '携帯電話';
UPDATE public.vocab SET full_meaning = 'pos — layanan surat dan pengiriman' WHERE level_id = 3 AND word = '郵便';
UPDATE public.vocab SET full_meaning = 'reservasi atau booking' WHERE level_id = 3 AND word = '予約';
UPDATE public.vocab SET full_meaning = 'pekerjaan atau profesi' WHERE level_id = 3 AND word = '職業';
UPDATE public.vocab SET full_meaning = 'acara atau kegiatan resmi — termasuk perayaan' WHERE level_id = 3 AND word = '行事';
UPDATE public.vocab SET full_meaning = 'acara atau pertunjukan — event' WHERE level_id = 3 AND word = '催し';
UPDATE public.vocab SET full_meaning = 'salam atau sapaan — termasuk ucapan selamat' WHERE level_id = 3 AND word = '挨拶';
UPDATE public.vocab SET full_meaning = 'konfirmasi — mengecek untuk memastikan' WHERE level_id = 3 AND word = '確認';
UPDATE public.vocab SET full_meaning = 'emosi atau perasaan' WHERE level_id = 3 AND word = '感情';
UPDATE public.vocab SET full_meaning = 'perasaan atau suasana hati — mood' WHERE level_id = 3 AND word = '気持ち';
UPDATE public.vocab SET full_meaning = 'terharu — tersentuh sampai berkesan' WHERE level_id = 3 AND word = '感動';
UPDATE public.vocab SET full_meaning = 'kegembiraan yang menggebu — terlalu bersemangat' WHERE level_id = 3 AND word = '興奮';
UPDATE public.vocab SET full_meaning = 'lega dan tenang — tidak khawatir' WHERE level_id = 3 AND word = '安心';
UPDATE public.vocab SET full_meaning = 'kegembiraan atau suka cita' WHERE level_id = 3 AND word = '喜び';
UPDATE public.vocab SET full_meaning = 'ketakutan — rasa ngeri' WHERE level_id = 3 AND word = '恐怖';
UPDATE public.vocab SET full_meaning = 'kesepian — merasa sendirian' WHERE level_id = 3 AND word = '孤独';
UPDATE public.vocab SET full_meaning = 'simpati atau belas kasihan' WHERE level_id = 3 AND word = '同情';
UPDATE public.vocab SET full_meaning = 'kasih sayang atau cinta' WHERE level_id = 3 AND word = '愛情';
UPDATE public.vocab SET full_meaning = 'kekaguman — sesuatu yang diidam-idamkan' WHERE level_id = 3 AND word = '憧れ';
UPDATE public.vocab SET full_meaning = 'rasa syukur dan terima kasih' WHERE level_id = 3 AND word = '感謝';
UPDATE public.vocab SET full_meaning = 'harapan atau keinginan' WHERE level_id = 3 AND word = '希望';
UPDATE public.vocab SET full_meaning = 'keberanian — nyali' WHERE level_id = 3 AND word = '勇気';
UPDATE public.vocab SET full_meaning = 'kebingungan — tidak tahu harus bagaimana' WHERE level_id = 3 AND word = '戸惑い';
UPDATE public.vocab SET full_meaning = 'kebanggaan — harga diri' WHERE level_id = 3 AND word = '誇り';
UPDATE public.vocab SET full_meaning = 'kepedulian — perhatian tulus ke orang lain' WHERE level_id = 3 AND word = '思いやり';
UPDATE public.vocab SET full_meaning = 'cemburu atau iri hati' WHERE level_id = 3 AND word = '嫉妬';
UPDATE public.vocab SET full_meaning = 'terharu mendalam — sangat tersentuh' WHERE level_id = 3 AND word = '感激';
UPDATE public.vocab SET full_meaning = 'bikin nostalgia — rindu masa lalu' WHERE level_id = 3 AND word = '懐かしい';
UPDATE public.vocab SET full_meaning = 'kagum atau terkesan' WHERE level_id = 3 AND word = '感心';
UPDATE public.vocab SET full_meaning = 'kekhawatiran — rasa cemas' WHERE level_id = 3 AND word = '心配';
UPDATE public.vocab SET full_meaning = 'rasa puas dan bermakna — batin terasa penuh' WHERE level_id = 3 AND word = '充実感';
UPDATE public.vocab SET full_meaning = 'kesal karena kalah atau gagal — gemas menyesal' WHERE level_id = 3 AND word = '悔しい';
UPDATE public.vocab SET full_meaning = 'sepi atau kesepian — merindukan' WHERE level_id = 3 AND word = '寂しい';
UPDATE public.vocab SET full_meaning = 'perih di hati — pilu menyayat' WHERE level_id = 3 AND word = '切ない';
UPDATE public.vocab SET full_meaning = 'rasa takut atau khawatir' WHERE level_id = 3 AND word = '恐れ';
UPDATE public.vocab SET full_meaning = 'keterkejutan — rasa kaget' WHERE level_id = 3 AND word = '驚き';
UPDATE public.vocab SET full_meaning = 'kebimbangan atau keraguan — galau' WHERE level_id = 3 AND word = '迷い';
UPDATE public.vocab SET full_meaning = 'gelisah dan panik — merasa dikejar waktu' WHERE level_id = 3 AND word = '焦り';
UPDATE public.vocab SET full_meaning = 'obsesi — keterikatan berlebihan pada sesuatu' WHERE level_id = 3 AND word = '執着';
UPDATE public.vocab SET full_meaning = 'kecewa berat — patah semangat' WHERE level_id = 3 AND word = '落胆';
UPDATE public.vocab SET full_meaning = 'perasaan lega — beban hilang' WHERE level_id = 3 AND word = '安堵';
UPDATE public.vocab SET full_meaning = 'penderitaan batin — pergulatan dalam hati' WHERE level_id = 3 AND word = '苦悩';
UPDATE public.vocab SET full_meaning = 'tenang dan damai — kalem' WHERE level_id = 3 AND word = '穏やか';
UPDATE public.vocab SET full_meaning = 'ceria dan periang' WHERE level_id = 3 AND word = '朗らか';
UPDATE public.vocab SET full_meaning = 'penghiburan — sesuatu yang menenangkan hati' WHERE level_id = 3 AND word = '慰め';
UPDATE public.vocab SET full_meaning = 'malu-malu — canggung salah tingkah' WHERE level_id = 3 AND word = '照れ';
UPDATE public.vocab SET full_meaning = 'nyaman — enak dirasakan' WHERE level_id = 3 AND word = '心地よい';
UPDATE public.vocab SET full_meaning = 'gemas frustrasi — pengin bertindak tapi tidak bisa' WHERE level_id = 3 AND word = 'もどかしい';
UPDATE public.vocab SET full_meaning = 'iri — pengin seperti orang lain' WHERE level_id = 3 AND word = '羨ましい';
UPDATE public.vocab SET full_meaning = 'bisa diandalkan — bikin tenang' WHERE level_id = 3 AND word = '頼もしい';
UPDATE public.vocab SET full_meaning = 'kuat hati karena merasa ada yang mendukung' WHERE level_id = 3 AND word = '心強い';
UPDATE public.vocab SET full_meaning = 'motivasi — semangat untuk mengerjakan' WHERE level_id = 3 AND word = 'やる気';
UPDATE public.vocab SET full_meaning = 'keinginan kuat — semangat tinggi untuk mencapai sesuatu' WHERE level_id = 3 AND word = '意欲';
UPDATE public.vocab SET full_meaning = 'perhatian halus — peka terhadap perasaan orang lain' WHERE level_id = 3 AND word = '気遣い';
UPDATE public.vocab SET full_meaning = 'kesehatan — kondisi badan yang prima' WHERE level_id = 3 AND word = '健康';
UPDATE public.vocab SET full_meaning = 'penyakit — kondisi badan yang sakit' WHERE level_id = 3 AND word = '病気';
UPDATE public.vocab SET full_meaning = 'gejala — tanda-tanda penyakit' WHERE level_id = 3 AND word = '症状';
UPDATE public.vocab SET full_meaning = 'pengobatan atau terapi medis' WHERE level_id = 3 AND word = '治療';
UPDATE public.vocab SET full_meaning = 'obat — untuk menyembuhkan penyakit' WHERE level_id = 3 AND word = '薬';
UPDATE public.vocab SET full_meaning = 'rasa sakit atau nyeri' WHERE level_id = 3 AND word = '痛み';
UPDATE public.vocab SET full_meaning = 'kelelahan — badan terasa letih' WHERE level_id = 3 AND word = '疲労';
UPDATE public.vocab SET full_meaning = 'imunitas — kekebalan tubuh' WHERE level_id = 3 AND word = '免疫';
UPDATE public.vocab SET full_meaning = 'flu atau pilek — masuk angin' WHERE level_id = 3 AND word = '風邪';
UPDATE public.vocab SET full_meaning = 'ingus — hidung meler' WHERE level_id = 3 AND word = '鼻水';
UPDATE public.vocab SET full_meaning = 'pusing berputar — vertigo' WHERE level_id = 3 AND word = 'めまい';
UPDATE public.vocab SET full_meaning = 'bengkak — badan sembab (edema)' WHERE level_id = 3 AND word = 'むくみ';
UPDATE public.vocab SET full_meaning = 'luka atau cedera' WHERE level_id = 3 AND word = '傷';
UPDATE public.vocab SET full_meaning = 'infeksi — tertular penyakit' WHERE level_id = 3 AND word = '感染';
UPDATE public.vocab SET full_meaning = 'nutrisi atau gizi' WHERE level_id = 3 AND word = '栄養';
UPDATE public.vocab SET full_meaning = 'olahraga — menggerakkan badan' WHERE level_id = 3 AND word = '運動';
UPDATE public.vocab SET full_meaning = 'istirahat untuk memulihkan tenaga' WHERE level_id = 3 AND word = '休養';
UPDATE public.vocab SET full_meaning = 'kebiasaan hidup — pola gaya hidup sehari-hari' WHERE level_id = 3 AND word = '生活習慣';
UPDATE public.vocab SET full_meaning = 'istirahat total — bed rest' WHERE level_id = 3 AND word = '安静';
UPDATE public.vocab SET full_meaning = 'penanganan medis — termasuk pertolongan pertama' WHERE level_id = 3 AND word = '処置';
UPDATE public.vocab SET full_meaning = 'stamina — daya tahan dan kekuatan fisik' WHERE level_id = 3 AND word = '体力';
UPDATE public.vocab SET full_meaning = 'koyo — kompres tempel' WHERE level_id = 3 AND word = '湿布';
UPDATE public.vocab SET full_meaning = 'memburuk — kondisinya makin parah' WHERE level_id = 3 AND word = '悪化';
UPDATE public.vocab SET full_meaning = 'membaik — berubah jadi lebih baik' WHERE level_id = 3 AND word = '改善';
UPDATE public.vocab SET full_meaning = 'darurat — harus ditangani segera' WHERE level_id = 3 AND word = '緊急';
UPDATE public.vocab SET full_meaning = 'berita atau kabar' WHERE level_id = 3 AND word = 'ニュース';
UPDATE public.vocab SET full_meaning = 'wartawan atau reporter' WHERE level_id = 3 AND word = '記者';
UPDATE public.vocab SET full_meaning = 'siaran — penyiaran TV atau radio' WHERE level_id = 3 AND word = '放送';
UPDATE public.vocab SET full_meaning = 'liputan — mencari bahan berita di lapangan' WHERE level_id = 3 AND word = '取材';
UPDATE public.vocab SET full_meaning = 'penyuntingan — merapikan tulisan atau video (editing)' WHERE level_id = 3 AND word = '編集';
UPDATE public.vocab SET full_meaning = 'pengumuman — memaparkan ke publik' WHERE level_id = 3 AND word = '発表';
UPDATE public.vocab SET full_meaning = 'berita kilat — breaking news' WHERE level_id = 3 AND word = '速報';
UPDATE public.vocab SET full_meaning = 'liputan khusus — edisi spesial satu tema' WHERE level_id = 3 AND word = '特集';
UPDATE public.vocab SET full_meaning = 'informasi atau keterangan' WHERE level_id = 3 AND word = '情報';
UPDATE public.vocab SET full_meaning = 'gosip — kabar burung yang belum tentu benar' WHERE level_id = 3 AND word = '噂';
UPDATE public.vocab SET full_meaning = 'penyiaran daring — streaming atau distribusi konten' WHERE level_id = 3 AND word = '配信';
UPDATE public.vocab SET full_meaning = 'pembawa acara — MC atau moderator' WHERE level_id = 3 AND word = '司会';
UPDATE public.vocab SET full_meaning = 'bias — condong berpihak, tidak netral' WHERE level_id = 3 AND word = '偏向';
UPDATE public.vocab SET full_meaning = 'kredibilitas — seberapa bisa dipercaya' WHERE level_id = 3 AND word = '信頼性';
UPDATE public.vocab SET full_meaning = 'ralat — membetulkan kesalahan' WHERE level_id = 3 AND word = '訂正';
UPDATE public.vocab SET full_meaning = 'unggahan — kiriman ke media atau medsos' WHERE level_id = 3 AND word = '投稿';
UPDATE public.vocab SET full_meaning = 'lalu — begitu itu terjadi' WHERE level_id = 3 AND word = 'すると';
UPDATE public.vocab SET full_meaning = 'karena itu — makanya' WHERE level_id = 3 AND word = 'それで';
UPDATE public.vocab SET full_meaning = 'atau — bisa juga' WHERE level_id = 3 AND word = 'あるいは';
UPDATE public.vocab SET full_meaning = 'lebih lanjut — ditambah lagi' WHERE level_id = 3 AND word = 'さらに';
UPDATE public.vocab SET full_meaning = 'tapi dengan catatan — ada syaratnya' WHERE level_id = 3 AND word = 'ただし';
UPDATE public.vocab SET full_meaning = 'soalnya — alasannya karena' WHERE level_id = 3 AND word = 'というのは';
