-- 058: perpanjang 5 dialog lepas N4 (kategori daily/work) yang di bawah ambang
-- panjang minimal (8 baris) — antrean E1 program kaiwa-30d (lihat
-- scheduler/kaiwa-30d/STATE.md). Dialog ini ADA di database tetapi TIDAK punya
-- file migrasi sumber di repo, jadi ditulis INSERT ... ON CONFLICT
-- (level_id, title) DO UPDATE. Judul, tema, dan 4 baris asli tiap dialog
-- dipertahankan persis; 4 baris baru ditambahkan di akhir (4 -> 8).
-- vocab_highlight ditulis ulang penuh ke format glosarium Fase D
-- (kata berkanji "yomi · romaji"; kata kana-saja = romaji telanjang).
-- Idempoten. Jalankan: npm run seed:kaiwa -- --file 058_extend_kaiwa_lepas_n4_short.sql

INSERT INTO public.kaiwa_stories (level_id, title, category, lines, vocab_highlight, is_premium) VALUES
(2, 'Bertanya tentang Hobi', 'daily',
 '[{"speaker":"田中","text":"アリさんの趣味は何ですか。","reading":"アリさんのしゅみはなんですか。","romaji":"Ari-san no shumi wa nan desu ka.","trans":"Hobi Ari apa?"},{"speaker":"アリ","text":"サッカーをすることです。よく公園でします。","reading":"サッカーをすることです。よくこうえんでします。","romaji":"Sakkaa o suru koto desu. Yoku kouen de shimasu.","trans":"Bermain sepak bola. Sering main di taman."},{"speaker":"田中","text":"いいですね。私も時々見ます。","reading":"いいですね。わたしもときどきみます。","romaji":"Ii desu ne. Watashi mo tokidoki mimasu.","trans":"Bagus ya. Saya juga kadang menonton."},{"speaker":"アリ","text":"今度一緒にしましょう。","reading":"こんどいっしょにしましょう。","romaji":"Kondo issho ni shimashou.","trans":"Lain kali main bareng yuk."},{"speaker":"田中","text":"どのくらい前からサッカーをしていますか。","reading":"どのくらいまえからサッカーをしていますか。","romaji":"Dono kurai mae kara sakkaa o shite imasu ka.","trans":"Sudah sejak berapa lama main sepak bola?"},{"speaker":"アリ","text":"国にいた時から、十年ぐらい続けています。","reading":"くににいたときから、じゅうねんぐらいつづけています。","romaji":"Kuni ni ita toki kara, juunen gurai tsuzukete imasu.","trans":"Sejak masih di negara saya, sudah sekitar sepuluh tahun terus bermain."},{"speaker":"田中","text":"すごいですね。私はスポーツが苦手なので、見るだけです。","reading":"すごいですね。わたしはスポーツがにがてなので、みるだけです。","romaji":"Sugoi desu ne. Watashi wa supootsu ga nigate na node, miru dake desu.","trans":"Hebat ya. Saya kurang pandai olahraga, jadi hanya menonton."},{"speaker":"アリ","text":"大丈夫ですよ。楽しければ、上手じゃなくてもいいです。","reading":"だいじょうぶですよ。たのしければ、じょうずじゃなくてもいいです。","romaji":"Daijoubu desu yo. Tanoshikereba, jouzu janakute mo ii desu.","trans":"Tidak apa-apa. Kalau menyenangkan, tidak jago pun tidak masalah."}]'::jsonb,
 '[{"word":"趣味","reading":"しゅみ · shumi","meaning":"hobi"},{"word":"公園","reading":"こうえん · kouen","meaning":"taman"},{"word":"続ける","reading":"つづける · tsuzukeru","meaning":"terus melakukan, melanjutkan"},{"word":"苦手","reading":"にがて · nigate","meaning":"kurang pandai, kurang suka"},{"word":"上手","reading":"じょうず · jouzu","meaning":"pandai, mahir"}]'::jsonb, false),

(2, 'Membuat Janji', 'daily',
 '[{"speaker":"田中","text":"今度の週末、一緒に映画を見に行きませんか。","reading":"こんどのしゅうまつ、いっしょにえいがをみにいきませんか。","romaji":"Kondo no shuumatsu, issho ni eiga o mi ni ikimasen ka.","trans":"Akhir pekan nanti, mau nonton film bareng tidak?"},{"speaker":"アリ","text":"いいですね。土曜日はどうですか。","reading":"いいですね。どようびはどうですか。","romaji":"Ii desu ne. Doyoubi wa dou desu ka.","trans":"Boleh juga. Bagaimana kalau Sabtu?"},{"speaker":"田中","text":"土曜日は予定があるので、日曜日はどうですか。","reading":"どようびはよていがあるので、にちようびはどうですか。","romaji":"Doyoubi wa yotei ga aru node, nichiyoubi wa dou desu ka.","trans":"Sabtu ada acara, bagaimana kalau Minggu?"},{"speaker":"アリ","text":"日曜日で大丈夫です。楽しみにしています。","reading":"にちようびでだいじょうぶです。たのしみにしています。","romaji":"Nichiyoubi de daijoubu desu. Tanoshimi ni shite imasu.","trans":"Minggu tidak masalah. Saya menantikannya."},{"speaker":"田中","text":"では、日曜日の二時に駅の前で会いましょう。","reading":"では、にちようびのにじにえきのまえであいましょう。","romaji":"Dewa, nichiyoubi no niji ni eki no mae de aimashou.","trans":"Kalau begitu, Minggu jam dua kita bertemu di depan stasiun."},{"speaker":"アリ","text":"二時ですね。映画は何時からですか。","reading":"にじですね。えいがはなんじからですか。","romaji":"Niji desu ne. Eiga wa nanji kara desu ka.","trans":"Jam dua ya. Filmnya mulai jam berapa?"},{"speaker":"田中","text":"二時半からです。先にチケットを買っておきます。","reading":"にじはんからです。さきにチケットをかっておきます。","romaji":"Niji han kara desu. Saki ni chiketto o katte okimasu.","trans":"Mulai jam setengah tiga. Saya belikan tiketnya lebih dulu."},{"speaker":"アリ","text":"ありがとうございます。その日にお金を払いますね。","reading":"ありがとうございます。そのひにおかねをはらいますね。","romaji":"Arigatou gozaimasu. Sono hi ni okane o haraimasu ne.","trans":"Terima kasih. Uangnya saya bayar pada hari itu ya."}]'::jsonb,
 '[{"word":"週末","reading":"しゅうまつ · shuumatsu","meaning":"akhir pekan"},{"word":"予定","reading":"よてい · yotei","meaning":"rencana, acara"},{"word":"会う","reading":"あう · au","meaning":"bertemu"},{"word":"買っておく","reading":"かっておく · katte oku","meaning":"membeli lebih dulu (sebagai persiapan)"},{"word":"払う","reading":"はらう · harau","meaning":"membayar"}]'::jsonb, false),

(2, 'Meminjam Barang', 'daily',
 '[{"speaker":"アリ","text":"すみません、ペンを貸してくれませんか。","reading":"すみません、ペンをかしてくれませんか。","romaji":"Sumimasen, pen o kashite kuremasen ka.","trans":"Maaf, bisa pinjamkan pulpen?"},{"speaker":"田中","text":"いいですよ。どうぞ。","reading":"いいですよ。どうぞ。","romaji":"Ii desu yo. Douzo.","trans":"Boleh. Silakan."},{"speaker":"アリ","text":"ありがとうございます。すぐ返します。","reading":"ありがとうございます。すぐかえします。","romaji":"Arigatou gozaimasu. Sugu kaeshimasu.","trans":"Terima kasih. Akan segera saya kembalikan."},{"speaker":"田中","text":"ゆっくりでいいですよ。","reading":"ゆっくりでいいですよ。","romaji":"Yukkuri de ii desu yo.","trans":"Santai saja, tidak buru-buru."},{"speaker":"アリ","text":"実は、消しゴムも忘れてしまいました。","reading":"じつは、けしゴムもわすれてしまいました。","romaji":"Jitsu wa, keshigomu mo wasurete shimaimashita.","trans":"Sebenarnya, penghapus juga saya lupa bawa."},{"speaker":"田中","text":"消しゴムはこれを使ってください。","reading":"けしゴムはこれをつかってください。","romaji":"Keshigomu wa kore o tsukatte kudasai.","trans":"Untuk penghapus, silakan pakai yang ini."},{"speaker":"アリ","text":"本当にありがとうございます。明日、新しいのを買って返します。","reading":"ほんとうにありがとうございます。あした、あたらしいのをかってかえします。","romaji":"Hontou ni arigatou gozaimasu. Ashita, atarashii no o katte kaeshimasu.","trans":"Terima kasih banyak. Besok saya belikan yang baru untuk menggantinya."},{"speaker":"田中","text":"気にしないでください。困った時はお互いさまですよ。","reading":"きにしないでください。こまったときはおたがいさまですよ。","romaji":"Ki ni shinaide kudasai. Komatta toki wa otagaisama desu yo.","trans":"Jangan dipikirkan. Kalau sedang kesulitan, kita saling membantu."}]'::jsonb,
 '[{"word":"貸す","reading":"かす · kasu","meaning":"meminjamkan"},{"word":"返す","reading":"かえす · kaesu","meaning":"mengembalikan"},{"word":"忘れる","reading":"わすれる · wasureru","meaning":"lupa, tertinggal"},{"word":"使う","reading":"つかう · tsukau","meaning":"memakai"},{"word":"お互いさま","reading":"おたがいさま · otagaisama","meaning":"sama-sama (saling membantu)"}]'::jsonb, false),

(2, 'Menelepon Restoran', 'daily',
 '[{"speaker":"店員","text":"はい、レストランさくらです。","reading":"はい、レストランさくらです。","romaji":"Hai, resutoran Sakura desu.","trans":"Ya, Restoran Sakura."},{"speaker":"アリ","text":"今晩、二人で予約したいんですが。","reading":"こんばん、ふたりでよやくしたいんですが。","romaji":"Konban, futari de yoyaku shitai n desu ga.","trans":"Malam ini, saya ingin memesan untuk dua orang."},{"speaker":"店員","text":"何時がよろしいですか。","reading":"なんじがよろしいですか。","romaji":"Nanji ga yoroshii desu ka.","trans":"Jam berapa yang Anda inginkan?"},{"speaker":"アリ","text":"七時にお願いします。","reading":"しちじにおねがいします。","romaji":"Shichiji ni onegaishimasu.","trans":"Tolong jam tujuh."},{"speaker":"店員","text":"かしこまりました。七時に二名様ですね。","reading":"かしこまりました。しちじににめいさまですね。","romaji":"Kashikomarimashita. Shichiji ni meisama desu ne.","trans":"Baik. Jam tujuh untuk dua orang ya."},{"speaker":"アリ","text":"はい。窓の近くの席はありますか。","reading":"はい。まどのちかくのせきはありますか。","romaji":"Hai. Mado no chikaku no seki wa arimasu ka.","trans":"Ya. Apakah ada meja dekat jendela?"},{"speaker":"店員","text":"はい、ご用意できます。お名前をお願いします。","reading":"はい、ごよういできます。おなまえをおねがいします。","romaji":"Hai, go-youi dekimasu. Onamae o onegaishimasu.","trans":"Ya, bisa kami siapkan. Boleh tahu nama Anda?"},{"speaker":"アリ","text":"アリです。では、七時に行きます。よろしくお願いします。","reading":"アリです。では、しちじにいきます。よろしくおねがいします。","romaji":"Ari desu. Dewa, shichiji ni ikimasu. Yoroshiku onegaishimasu.","trans":"Ari. Kalau begitu, jam tujuh saya datang. Mohon bantuannya."}]'::jsonb,
 '[{"word":"予約","reading":"よやく · yoyaku","meaning":"reservasi"},{"word":"席","reading":"せき · seki","meaning":"tempat duduk, meja"},{"word":"窓","reading":"まど · mado","meaning":"jendela"},{"word":"用意","reading":"ようい · youi","meaning":"persiapan, menyiapkan"},{"word":"かしこまりました","reading":"kashikomarimashita","meaning":"baik, dimengerti (sangat sopan)"}]'::jsonb, false),

(2, 'Izin Tidak Masuk Kerja', 'work',
 '[{"speaker":"アリ","text":"課長、すみません。今日は熱があるので、休んでもいいですか。","reading":"かちょう、すみません。きょうはねつがあるので、やすんでもいいですか。","romaji":"Kachou, sumimasen. Kyou wa netsu ga aru node, yasunde mo ii desu ka.","trans":"Pak Kepala, maaf. Hari ini saya demam, boleh izin tidak masuk?"},{"speaker":"課長","text":"大丈夫ですか。無理しないでください。","reading":"だいじょうぶですか。むりしないでください。","romaji":"Daijoubu desu ka. Muri shinaide kudasai.","trans":"Apakah baik-baik saja? Jangan dipaksakan ya."},{"speaker":"アリ","text":"ありがとうございます。明日は出勤します。","reading":"ありがとうございます。あしたはしゅっきんします。","romaji":"Arigatou gozaimasu. Ashita wa shukkin shimasu.","trans":"Terima kasih. Besok saya akan masuk."},{"speaker":"課長","text":"わかりました。お大事に。","reading":"わかりました。おだいじに。","romaji":"Wakarimashita. Odaiji ni.","trans":"Baik. Semoga lekas sembuh."},{"speaker":"アリ","text":"これから病院に行ってきます。","reading":"これからびょういんにいってきます。","romaji":"Korekara byouin ni itte kimasu.","trans":"Sekarang saya mau ke rumah sakit."},{"speaker":"課長","text":"そうですか。診察が終わったら、連絡をください。","reading":"そうですか。しんさつがおわったら、れんらくをください。","romaji":"Sou desu ka. Shinsatsu ga owattara, renraku o kudasai.","trans":"Begitu ya. Kalau pemeriksaan sudah selesai, tolong kabari."},{"speaker":"アリ","text":"はい、必ずご連絡します。ご迷惑をおかけして申し訳ありません。","reading":"はい、かならずごれんらくします。ごめいわくをおかけしてもうしわけありません。","romaji":"Hai, kanarazu go-renraku shimasu. Gomeiwaku o okake shite moushiwake arimasen.","trans":"Ya, pasti saya kabari. Mohon maaf sudah merepotkan."},{"speaker":"課長","text":"気にしないで。仕事のことは心配いりませんよ。","reading":"きにしないで。しごとのことはしんぱいいりませんよ。","romaji":"Ki ni shinaide. Shigoto no koto wa shinpai irimasen yo.","trans":"Jangan dipikirkan. Pekerjaan tidak perlu dikhawatirkan."}]'::jsonb,
 '[{"word":"熱","reading":"ねつ · netsu","meaning":"demam"},{"word":"無理","reading":"むり · muri","meaning":"memaksakan diri"},{"word":"診察","reading":"しんさつ · shinsatsu","meaning":"pemeriksaan dokter"},{"word":"連絡","reading":"れんらく · renraku","meaning":"mengabari, menghubungi"},{"word":"迷惑","reading":"めいわく · meiwaku","meaning":"merepotkan, gangguan"}]'::jsonb, false)

ON CONFLICT (level_id, title) DO UPDATE SET
  lines = EXCLUDED.lines,
  vocab_highlight = EXCLUDED.vocab_highlight;
