-- 060: perpanjang 2 dialog lepas N4 sisa (E1 program kaiwa-30d): "Di Klinik"
-- (kaigo, 5 -> 9 baris) dan "Lapor ke Atasan" (work, 4 -> 8 baris). Melengkapi
-- 058. Judul, tema, dan baris asli dipertahankan persis; baris baru ditambahkan
-- di akhir. vocab_highlight ditulis ulang ke format glosarium Fase D.
-- Idempoten. Jalankan: npm run seed:kaiwa -- --file 060_extend_kaiwa_lepas_n4_short_2.sql

INSERT INTO public.kaiwa_stories (level_id, title, category, lines, vocab_highlight, is_premium) VALUES
(2, 'Di Klinik', 'kaigo',
 '[{"speaker":"医者","text":"どうしましたか。","reading":"どうしましたか。","romaji":"Dou shimashita ka.","trans":"Ada keluhan apa?"},{"speaker":"アリ","text":"昨日からお腹が痛いです。","reading":"きのうからおなかがいたいです。","romaji":"Kinou kara onaka ga itai desu.","trans":"Sejak kemarin perut saya sakit."},{"speaker":"医者","text":"熱はありますか。","reading":"ねつはありますか。","romaji":"Netsu wa arimasu ka.","trans":"Apakah ada demam?"},{"speaker":"アリ","text":"少しあります。薬をもらえますか。","reading":"すこしあります。くすりをもらえますか。","romaji":"Sukoshi arimasu. Kusuri o moraemasu ka.","trans":"Ada sedikit. Boleh minta obat?"},{"speaker":"医者","text":"はい、薬を出します。お大事に。","reading":"はい、くすりをだします。おだいじに。","romaji":"Hai, kusuri o dashimasu. Odaiji ni.","trans":"Ya, saya berikan obat. Semoga lekas sembuh."},{"speaker":"アリ","text":"一日に何回飲めばいいですか。","reading":"いちにちになんかいのめばいいですか。","romaji":"Ichinichi ni nankai nomeba ii desu ka.","trans":"Sehari sebaiknya diminum berapa kali?"},{"speaker":"医者","text":"朝と夜、食事の後に飲んでください。","reading":"あさとよる、しょくじのあとにのんでください。","romaji":"Asa to yoru, shokuji no ato ni nonde kudasai.","trans":"Minumlah pagi dan malam, setelah makan."},{"speaker":"アリ","text":"仕事は休んだほうがいいですか。","reading":"しごとはやすんだほうがいいですか。","romaji":"Shigoto wa yasunda hou ga ii desu ka.","trans":"Sebaiknya saya libur kerja?"},{"speaker":"医者","text":"今日と明日は休んで、ゆっくりしてください。","reading":"きょうとあしたはやすんで、ゆっくりしてください。","romaji":"Kyou to ashita wa yasunde, yukkuri shite kudasai.","trans":"Hari ini dan besok istirahatlah, tenangkan diri."}]'::jsonb,
 '[{"word":"お腹","reading":"おなか · onaka","meaning":"perut"},{"word":"痛い","reading":"いたい · itai","meaning":"sakit"},{"word":"薬","reading":"くすり · kusuri","meaning":"obat"},{"word":"食事","reading":"しょくじ · shokuji","meaning":"makan, waktu makan"},{"word":"休む","reading":"やすむ · yasumu","meaning":"istirahat, libur"}]'::jsonb, false),

(2, 'Lapor ke Atasan', 'work',
 '[{"speaker":"アリ","text":"課長、報告があります。今、よろしいですか。","reading":"かちょう、ほうこくがあります。いま、よろしいですか。","romaji":"Kachou, houkoku ga arimasu. Ima, yoroshii desu ka.","trans":"Pak Kepala, ada laporan. Apakah sekarang boleh?"},{"speaker":"課長","text":"はい、どうぞ。","reading":"はい、どうぞ。","romaji":"Hai, douzo.","trans":"Ya, silakan."},{"speaker":"アリ","text":"先ほどの作業が終わりました。","reading":"さきほどのさぎょうがおわりました。","romaji":"Sakihodo no sagyou ga owarimashita.","trans":"Pekerjaan tadi sudah selesai."},{"speaker":"課長","text":"早いですね。ありがとう、助かります。","reading":"はやいですね。ありがとう、たすかります。","romaji":"Hayai desu ne. Arigatou, tasukarimasu.","trans":"Cepat ya. Terima kasih, sangat membantu."},{"speaker":"課長","text":"問題はありませんでしたか。","reading":"もんだいはありませんでしたか。","romaji":"Mondai wa arimasen deshita ka.","trans":"Tidak ada masalah?"},{"speaker":"アリ","text":"一つだけ、機械の音が少し変でした。","reading":"ひとつだけ、きかいのおとがすこしへんでした。","romaji":"Hitotsu dake, kikai no oto ga sukoshi hen deshita.","trans":"Hanya satu, suara mesin agak aneh."},{"speaker":"課長","text":"わかりました。後で私が確認します。","reading":"わかりました。あとでわたしがかくにんします。","romaji":"Wakarimashita. Ato de watashi ga kakunin shimasu.","trans":"Baik. Nanti saya yang memeriksanya."},{"speaker":"アリ","text":"お願いします。次は何をしましょうか。","reading":"おねがいします。つぎはなにをしましょうか。","romaji":"Onegai shimasu. Tsugi wa nani o shimashou ka.","trans":"Mohon bantuannya. Selanjutnya apa yang harus saya kerjakan?"}]'::jsonb,
 '[{"word":"報告","reading":"ほうこく · houkoku","meaning":"laporan"},{"word":"作業","reading":"さぎょう · sagyou","meaning":"pekerjaan/operasi"},{"word":"終わる","reading":"おわる · owaru","meaning":"selesai"},{"word":"確認","reading":"かくにん · kakunin","meaning":"memeriksa, memastikan"},{"word":"機械","reading":"きかい · kikai","meaning":"mesin"}]'::jsonb, false)

ON CONFLICT (level_id, title) DO UPDATE SET
  lines = EXCLUDED.lines,
  vocab_highlight = EXCLUDED.vocab_highlight;
