-- 061: perpanjang 5 dialog lepas N3 (E1 program kaiwa-30d, Day 11): "Di Panti Jompo" (kaigo),
-- "Komplain dengan Sopan" dan "Membatalkan Janji" (daily), "Rapat di Kantor" (work),
-- "Wawancara Kerja Sederhana" (biz); masing-masing 4 -> 10 baris. Judul, kategori, dan
-- 4 baris asli dipertahankan persis; baris baru ditambahkan di akhir. vocab_highlight
-- ditulis ulang ke format glosarium Fase D. Idempoten.
-- Jalankan: npm run seed:kaiwa -- --file 061_extend_kaiwa_lepas_n3_short.sql

INSERT INTO public.kaiwa_stories (level_id, title, category, lines, vocab_highlight, is_premium) VALUES
(3, 'Di Panti Jompo', 'kaigo',
 '[{"speaker":"アリ","text":"田中さん、おはようございます。よく眠れましたか。","reading":"たなかさん、おはようございます。よくねむれましたか。","romaji":"Tanaka-san, ohayou gozaimasu. Yoku nemuremashita ka.","trans":"Pak Tanaka, selamat pagi. Tidurnya nyenyak?"},{"speaker":"利用者","text":"ええ、おかげさまで。","reading":"ええ、おかげさまで。","romaji":"Ee, okagesama de.","trans":"Iya, berkat bantuanmu."},{"speaker":"アリ","text":"では、これから朝ごはんの時間です。手伝いましょうか。","reading":"では、これからあさごはんのじかんです。てつだいましょうか。","romaji":"Dewa, kore kara asagohan no jikan desu. Tetsudaimashou ka.","trans":"Kalau begitu, sekarang waktunya sarapan. Saya bantu ya?"},{"speaker":"利用者","text":"ありがとう。お願いします。","reading":"ありがとう。おねがいします。","romaji":"Arigatou. Onegaishimasu.","trans":"Terima kasih. Tolong ya."},{"speaker":"アリ","text":"今日は天気がいいので、後で庭を散歩しませんか。","reading":"きょうはてんきがいいので、あとでにわをさんぽしませんか。","romaji":"Kyou wa tenki ga ii node, ato de niwa o sanpo shimasen ka.","trans":"Cuaca hari ini bagus, bagaimana kalau nanti kita jalan-jalan di taman?"},{"speaker":"利用者","text":"いいですね。最近、足が弱くなってきたので、ゆっくりお願いします。","reading":"いいですね。さいきん、あしがよわくなってきたので、ゆっくりおねがいします。","romaji":"Ii desu ne. Saikin, ashi ga yowaku natte kita node, yukkuri onegaishimasu.","trans":"Bagus. Akhir-akhir ini kaki saya melemah, jadi pelan-pelan ya."},{"speaker":"アリ","text":"はい、無理をしないでください。疲れたらすぐに言ってくださいね。","reading":"はい、むりをしないでください。つかれたらすぐにいってくださいね。","romaji":"Hai, muri o shinaide kudasai. Tsukaretara sugu ni itte kudasai ne.","trans":"Baik, jangan memaksakan diri. Kalau lelah, segera katakan ya."},{"speaker":"利用者","text":"ありがとう。あなたは本当に優しいですね。","reading":"ありがとう。あなたはほんとうにやさしいですね。","romaji":"Arigatou. Anata wa hontou ni yasashii desu ne.","trans":"Terima kasih. Kamu benar-benar baik hati."},{"speaker":"アリ","text":"いいえ、とんでもないです。では、先に朝ごはんを食べましょう。","reading":"いいえ、とんでもないです。では、さきにあさごはんをたべましょう。","romaji":"Iie, tondemo nai desu. Dewa, saki ni asagohan o tabemashou.","trans":"Tidak, itu berlebihan. Nah, sarapan dulu ya."},{"speaker":"利用者","text":"そうですね。今朝はお味噌汁が飲みたいです。","reading":"そうですね。けさはおみそしるがのみたいです。","romaji":"Sou desu ne. Kesa wa omisoshiru ga nomitai desu.","trans":"Benar. Pagi ini saya ingin minum sup miso."}]'::jsonb,
 '[{"word":"眠れる","reading":"ねむれる · nemureru","meaning":"bisa tidur"},{"word":"手伝う","reading":"てつだう · tetsudau","meaning":"membantu"},{"word":"散歩","reading":"さんぽ · sanpo","meaning":"jalan-jalan santai"},{"word":"無理をする","reading":"むりをする · muri o suru","meaning":"memaksakan diri"},{"word":"疲れる","reading":"つかれる · tsukareru","meaning":"lelah"},{"word":"おかげさまで","reading":"okagesama de","meaning":"berkat Anda"}]'::jsonb, false),

(3, 'Komplain dengan Sopan', 'daily',
 '[{"speaker":"アリ","text":"すみません、先週買ったこの靴なんですが、すぐ壊れてしまいました。","reading":"すみません、せんしゅうかったこのくつなんですが、すぐこわれてしまいました。","romaji":"Sumimasen, senshuu katta kono kutsu nan desu ga, sugu kowarete shimaimashita.","trans":"Permisi, sepatu yang saya beli minggu lalu ini langsung rusak."},{"speaker":"店員","text":"申し訳ございません。レシートはお持ちですか。","reading":"もうしわけございません。レシートはおもちですか。","romaji":"Moushiwake gozaimasen. Reshiito wa omochi desu ka.","trans":"Mohon maaf. Apakah Anda membawa struk?"},{"speaker":"アリ","text":"はい、ここにあります。交換してもらえますか。","reading":"はい、ここにあります。こうかんしてもらえますか。","romaji":"Hai, koko ni arimasu. Koukan shite moraemasu ka.","trans":"Ya, ada di sini. Bisa ditukar?"},{"speaker":"店員","text":"はい、新しいものとお取り替えいたします。","reading":"はい、あたらしいものとおとりかえいたします。","romaji":"Hai, atarashii mono to otorikae itashimasu.","trans":"Ya, akan kami tukar dengan yang baru."},{"speaker":"店員","text":"少々お待ちください。同じ商品の在庫を確認いたします。","reading":"しょうしょうおまちください。おなじしょうひんのざいこをかくにんいたします。","romaji":"Shoushou omachi kudasai. Onaji shouhin no zaiko o kakunin itashimasu.","trans":"Mohon tunggu sebentar. Kami cek stok barang yang sama."},{"speaker":"アリ","text":"はい、お願いします。サイズは二十五センチです。","reading":"はい、おねがいします。サイズはにじゅうごセンチです。","romaji":"Hai, onegaishimasu. Saizu wa nijuugo senchi desu.","trans":"Baik, tolong. Ukurannya 25 cm."},{"speaker":"店員","text":"申し訳ございません、そのサイズは今ちょうど売り切れております。","reading":"もうしわけございません、そのサイズはいまちょうどうりきれております。","romaji":"Moushiwake gozaimasen, sono saizu wa ima choudo urikirete orimasu.","trans":"Mohon maaf, ukuran itu kebetulan sedang habis."},{"speaker":"アリ","text":"そうですか。では、お金を返してもらうことはできますか。","reading":"そうですか。では、おかねをかえしてもらうことはできますか。","romaji":"Sou desu ka. Dewa, okane o kaeshite morau koto wa dekimasu ka.","trans":"Begitu ya. Kalau begitu, bisakah uangnya dikembalikan?"},{"speaker":"店員","text":"はい、返金できます。こちらの書類にお名前をお願いします。","reading":"はい、へんきんできます。こちらのしょるいにおなまえをおねがいします。","romaji":"Hai, henkin dekimasu. Kochira no shorui ni onamae o onegaishimasu.","trans":"Ya, bisa dikembalikan. Mohon tulis nama Anda di formulir ini."},{"speaker":"アリ","text":"分かりました。いろいろありがとうございました。","reading":"わかりました。いろいろありがとうございました。","romaji":"Wakarimashita. Iroiro arigatou gozaimashita.","trans":"Baik. Terima kasih atas bantuannya."}]'::jsonb,
 '[{"word":"壊れる","reading":"こわれる · kowareru","meaning":"rusak"},{"word":"交換","reading":"こうかん · koukan","meaning":"penukaran"},{"word":"在庫","reading":"ざいこ · zaiko","meaning":"stok barang"},{"word":"売り切れる","reading":"うりきれる · urikireru","meaning":"habis terjual"},{"word":"返金","reading":"へんきん · henkin","meaning":"pengembalian uang"},{"word":"申し訳ない","reading":"もうしわけない · moushiwakenai","meaning":"mohon maaf (formal)"}]'::jsonb, false),

(3, 'Membatalkan Janji', 'daily',
 '[{"speaker":"アリ","text":"申し訳ないんですが、明日の約束をキャンセルしてもいいですか。","reading":"もうしわけないんですが、あしたのやくそくをキャンセルしてもいいですか。","romaji":"Moushiwakenai n desu ga, ashita no yakusoku o kyanseru shite mo ii desu ka.","trans":"Maaf sekali, boleh saya batalkan janji besok?"},{"speaker":"田中","text":"どうしたんですか。","reading":"どうしたんですか。","romaji":"Dou shita n desu ka.","trans":"Ada apa?"},{"speaker":"アリ","text":"急に仕事が入ってしまって。","reading":"きゅうにしごとがはいってしまって。","romaji":"Kyuu ni shigoto ga haitte shimatte.","trans":"Tiba-tiba ada pekerjaan masuk."},{"speaker":"田中","text":"分かりました。また今度にしましょう。","reading":"わかりました。またこんどにしましょう。","romaji":"Wakarimashita. Mata kondo ni shimashou.","trans":"Baik. Lain kali saja ya."},{"speaker":"田中","text":"大丈夫ですか。何か大変なことがあったんですか。","reading":"だいじょうぶですか。なにかたいへんなことがあったんですか。","romaji":"Daijoubu desu ka. Nanika taihen na koto ga atta n desu ka.","trans":"Anda baik-baik saja? Apakah ada sesuatu yang berat?"},{"speaker":"アリ","text":"いえ、急にシフトを変わってほしいと言われたんです。","reading":"いえ、きゅうにシフトをかわってほしいといわれたんです。","romaji":"Ie, kyuu ni shifuto o kawatte hoshii to iwareta n desu.","trans":"Tidak, tiba-tiba saya diminta menggantikan shift."},{"speaker":"田中","text":"そうですか。仕事なら仕方がないですね。","reading":"そうですか。しごとならしかたがないですね。","romaji":"Sou desu ka. Shigoto nara shikata ga nai desu ne.","trans":"Begitu ya. Kalau soal pekerjaan, apa boleh buat."},{"speaker":"アリ","text":"本当にすみません。来週の土曜日はどうですか。","reading":"ほんとうにすみません。らいしゅうのどようびはどうですか。","romaji":"Hontou ni sumimasen. Raishuu no doyoubi wa dou desu ka.","trans":"Sungguh maaf. Bagaimana dengan Sabtu minggu depan?"},{"speaker":"田中","text":"土曜日なら大丈夫です。時間は同じでいいですか。","reading":"どようびならだいじょうぶです。じかんはおなじでいいですか。","romaji":"Doyoubi nara daijoubu desu. Jikan wa onaji de ii desu ka.","trans":"Kalau Sabtu bisa. Waktunya sama saja?"},{"speaker":"アリ","text":"はい、同じ時間にお願いします。また連絡します。","reading":"はい、おなじじかんにおねがいします。またれんらくします。","romaji":"Hai, onaji jikan ni onegaishimasu. Mata renraku shimasu.","trans":"Ya, di jam yang sama. Nanti saya hubungi lagi."}]'::jsonb,
 '[{"word":"約束","reading":"やくそく · yakusoku","meaning":"janji"},{"word":"キャンセル","reading":"kyanseru","meaning":"membatalkan"},{"word":"急に","reading":"きゅうに · kyuu ni","meaning":"tiba-tiba"},{"word":"仕方がない","reading":"しかたがない · shikata ga nai","meaning":"apa boleh buat"},{"word":"連絡","reading":"れんらく · renraku","meaning":"menghubungi"}]'::jsonb, false),

(3, 'Rapat di Kantor', 'work',
 '[{"speaker":"課長","text":"今日の会議で来月の計画について話し合いましょう。","reading":"きょうのかいぎでらいげつのけいかくについてはなしあいましょう。","romaji":"Kyou no kaigi de raigetsu no keikaku ni tsuite hanashiaimashou.","trans":"Di rapat hari ini, mari kita diskusikan rencana bulan depan."},{"speaker":"アリ","text":"はい。資料はもう準備してあります。","reading":"はい。しりょうはもうじゅんびしてあります。","romaji":"Hai. Shiryou wa mou junbi shite arimasu.","trans":"Baik. Materinya sudah saya siapkan."},{"speaker":"課長","text":"助かります。では、説明をお願いできますか。","reading":"たすかります。では、せつめいをおねがいできますか。","romaji":"Tasukarimasu. Dewa, setsumei o onegai dekimasu ka.","trans":"Sangat membantu. Kalau begitu, bisa tolong jelaskan?"},{"speaker":"アリ","text":"かしこまりました。画面をご覧ください。","reading":"かしこまりました。がめんをごらんください。","romaji":"Kashikomarimashita. Gamen o goran kudasai.","trans":"Baik. Silakan lihat layarnya."},{"speaker":"課長","text":"まず、来月の売り上げの目標から見ていきましょう。","reading":"まず、らいげつのうりあげのもくひょうからみていきましょう。","romaji":"Mazu, raigetsu no uriage no mokuhyou kara miteikimashou.","trans":"Pertama, mari kita lihat dari target penjualan bulan depan."},{"speaker":"アリ","text":"はい。今月より五パーセント増やす予定です。","reading":"はい。こんげつよりごパーセントふやすよていです。","romaji":"Hai. Kongetsu yori go paasento fuyasu yotei desu.","trans":"Baik. Rencananya ditingkatkan lima persen dari bulan ini."},{"speaker":"課長","text":"そのためには、何が必要だと思いますか。","reading":"そのためには、なにがひつようだとおもいますか。","romaji":"Sono tame ni wa, nani ga hitsuyou da to omoimasu ka.","trans":"Menurutmu apa yang diperlukan untuk itu?"},{"speaker":"アリ","text":"作業の手順を見直して、ミスを減らすことだと思います。","reading":"さぎょうのてじゅんをみなおして、ミスをへらすことだとおもいます。","romaji":"Sagyou no tejun o minaoshite, misu o herasu koto da to omoimasu.","trans":"Menurut saya, meninjau ulang prosedur kerja dan mengurangi kesalahan."},{"speaker":"課長","text":"なるほど。では、その案をまとめて、金曜日までに提出してください。","reading":"なるほど。では、そのあんをまとめて、きんようびまでにていしゅつしてください。","romaji":"Naruhodo. Dewa, sono an o matomete, kinyoubi made ni teishutsu shite kudasai.","trans":"Begitu. Kalau begitu, rangkum usul itu dan serahkan sampai hari Jumat."},{"speaker":"アリ","text":"かしこまりました。金曜日までに必ずお送りします。","reading":"かしこまりました。きんようびまでにかならずおおくりします。","romaji":"Kashikomarimashita. Kinyoubi made ni kanarazu ookuri shimasu.","trans":"Baik. Pasti saya kirimkan sebelum hari Jumat."}]'::jsonb,
 '[{"word":"計画","reading":"けいかく · keikaku","meaning":"rencana"},{"word":"資料","reading":"しりょう · shiryou","meaning":"materi/dokumen"},{"word":"売り上げ","reading":"うりあげ · uriage","meaning":"penjualan"},{"word":"見直す","reading":"みなおす · minaosu","meaning":"meninjau ulang"},{"word":"手順","reading":"てじゅん · tejun","meaning":"prosedur, urutan langkah"},{"word":"提出","reading":"ていしゅつ · teishutsu","meaning":"menyerahkan"}]'::jsonb, false),

(3, 'Wawancara Kerja Sederhana', 'biz',
 '[{"speaker":"面接官","text":"自己紹介をお願いします。","reading":"じこしょうかいをおねがいします。","romaji":"Jikoshoukai o onegaishimasu.","trans":"Tolong perkenalkan diri Anda."},{"speaker":"アリ","text":"アリと申します。インドネシア出身で、三年間日本語を勉強しています。","reading":"アリともうします。インドネシアしゅっしんで、さんねんかんにほんごをべんきょうしています。","romaji":"Ari to moushimasu. Indonesia shusshin de, sannenkan nihongo o benkyou shite imasu.","trans":"Nama saya Ari. Saya dari Indonesia dan sudah belajar bahasa Jepang selama tiga tahun."},{"speaker":"面接官","text":"なぜ当社で働きたいのですか。","reading":"なぜとうしゃではたらきたいのですか。","romaji":"Naze tousha de hatarakitai no desu ka.","trans":"Mengapa Anda ingin bekerja di perusahaan kami?"},{"speaker":"アリ","text":"技術を学びながら、社会に貢献したいからです。","reading":"ぎじゅつをまなびながら、しゃかいにこうけんしたいからです。","romaji":"Gijutsu o manabinagara, shakai ni kouken shitai kara desu.","trans":"Karena saya ingin berkontribusi pada masyarakat sambil mempelajari keterampilan."},{"speaker":"面接官","text":"日本語で困ったことはありますか。","reading":"にほんごでこまったことはありますか。","romaji":"Nihongo de komatta koto wa arimasu ka.","trans":"Apakah ada hal yang menyulitkan dalam bahasa Jepang?"},{"speaker":"アリ","text":"電話で話すとき、早い会話が聞き取れないことがあります。","reading":"でんわではなすとき、はやいかいわがききとれないことがあります。","romaji":"Denwa de hanasu toki, hayai kaiwa ga kikitorenai koto ga arimasu.","trans":"Saat bicara lewat telepon, kadang saya tidak bisa menangkap percakapan yang cepat."},{"speaker":"面接官","text":"そうですか。それをどうやって練習していますか。","reading":"そうですか。それをどうやってれんしゅうしていますか。","romaji":"Sou desu ka. Sore o dou yatte renshuu shite imasu ka.","trans":"Begitu. Bagaimana Anda melatihnya?"},{"speaker":"アリ","text":"毎日ニュースを聞いて、わからない言葉をノートに書いています。","reading":"まいにちニュースをきいて、わからないことばをノートにかいています。","romaji":"Mainichi nyuusu o kiite, wakaranai kotoba o nooto ni kaite imasu.","trans":"Setiap hari saya mendengarkan berita dan mencatat kata yang tidak saya mengerti."},{"speaker":"面接官","text":"素晴らしいですね。いつから働けますか。","reading":"すばらしいですね。いつからはたらけますか。","romaji":"Subarashii desu ne. Itsu kara hatarakemasu ka.","trans":"Luar biasa. Mulai kapan Anda bisa bekerja?"},{"speaker":"アリ","text":"来月の一日から働けます。よろしくお願いいたします。","reading":"らいげつのついたちからはたらけます。よろしくおねがいいたします。","romaji":"Raigetsu no tsuitachi kara hatarakemasu. Yoroshiku onegai itashimasu.","trans":"Saya bisa mulai bekerja dari tanggal 1 bulan depan. Mohon bantuannya."}]'::jsonb,
 '[{"word":"自己紹介","reading":"じこしょうかい · jikoshoukai","meaning":"perkenalan diri"},{"word":"貢献","reading":"こうけん · kouken","meaning":"kontribusi"},{"word":"困る","reading":"こまる · komaru","meaning":"kesulitan"},{"word":"聞き取る","reading":"ききとる · kikitoru","meaning":"menangkap (yang didengar)"},{"word":"練習","reading":"れんしゅう · renshuu","meaning":"latihan"},{"word":"素晴らしい","reading":"すばらしい · subarashii","meaning":"luar biasa"}]'::jsonb, false)

ON CONFLICT (level_id, title) DO UPDATE SET
  lines = EXCLUDED.lines,
  vocab_highlight = EXCLUDED.vocab_highlight;

