-- 064: perpanjang 2 dialog lepas N3 terakhir (E1 program kaiwa-30d, Day 15): "Menanyakan Jalan yang Rumit"
-- (daily) dan "Menjelaskan Gejala ke Apoteker" (kaigo); masing-masing 4 -> 10 baris. Judul, kategori,
-- dan 4 baris asli dipertahankan persis; 6 baris baru ditambahkan di akhir. vocab_highlight ditulis
-- ke format glosarium Fase D. Idempoten.
-- Jalankan: npm run seed:kaiwa -- --file 064_extend_kaiwa_lepas_n3_short_2.sql

INSERT INTO public.kaiwa_stories (level_id, title, category, lines, vocab_highlight, is_premium) VALUES
(3, 'Menanyakan Jalan yang Rumit', 'daily',
 '[{"speaker":"アリ","text":"すみません、市役所へ行きたいんですが、道に迷ってしまいました。","reading":"すみません、しやくしょへいきたいんですが、みちにまよってしまいました。","romaji":"Sumimasen, shiyakusho e ikitai n desu ga, michi ni mayotte shimaimashita.","trans":"Permisi, saya ingin ke kantor walikota tapi tersesat."},{"speaker":"田中","text":"あの信号を右に曲がって、まっすぐ行くと左側にあります。","reading":"あのしんごうをみぎにまがって、まっすぐいくとひだりがわにあります。","romaji":"Ano shingou o migi ni magatte, massugu iku to hidarigawa ni arimasu.","trans":"Belok kanan di lampu merah itu, lalu lurus, ada di sebelah kiri."},{"speaker":"アリ","text":"歩いてどのくらいかかりますか。","reading":"あるいてどのくらいかかりますか。","romaji":"Aruite dono kurai kakarimasu ka.","trans":"Kalau jalan kaki perlu berapa lama?"},{"speaker":"田中","text":"十分ぐらいですよ。","reading":"じゅっぷんぐらいですよ。","romaji":"Juppun gurai desu yo.","trans":"Sekitar sepuluh menit."},{"speaker":"アリ","text":"途中に大きな交差点があると聞いたんですが、わかりにくいですか。","reading":"とちゅうにおおきなこうさてんがあるときいたんですが、わかりにくいですか。","romaji":"Tochuu ni ookina kousaten ga aru to kiita n desu ga, wakarinikui desu ka.","trans":"Saya dengar ada persimpangan besar di tengah jalan, apakah susah dikenali?"},{"speaker":"田中","text":"少しわかりにくいですね。交差点の手前に郵便局があるので、それを目印にしてください。","reading":"すこしわかりにくいですね。こうさてんのてまえにゆうびんきょくがあるので、それをめじるしにしてください。","romaji":"Sukoshi wakarinikui desu ne. Kousaten no temae ni yuubinkyoku ga aru node, sore o mejirushi ni shite kudasai.","trans":"Memang agak susah dikenali. Ada kantor pos sebelum persimpangan, jadikan itu patokan."},{"speaker":"アリ","text":"郵便局ですね。そのあとはどうすればいいですか。","reading":"ゆうびんきょくですね。そのあとはどうすればいいですか。","romaji":"Yuubinkyoku desu ne. Sono ato wa dou sureba ii desu ka.","trans":"Kantor pos ya. Setelah itu bagaimana?"},{"speaker":"田中","text":"郵便局の角を左に曲がると、大きな白い建物が見えます。それが市役所です。","reading":"ゆうびんきょくのかどをひだりにまがると、おおきなしろいたてものがみえます。それがしやくしょです。","romaji":"Yuubinkyoku no kado o hidari ni magaru to, ookina shiroi tatemono ga miemasu. Sore ga shiyakusho desu.","trans":"Kalau belok kiri di sudut kantor pos, akan terlihat gedung putih besar. Itulah kantor walikota."},{"speaker":"アリ","text":"よくわかりました。親切に教えてくださって、ありがとうございます。","reading":"よくわかりました。しんせつにおしえてくださって、ありがとうございます。","romaji":"Yoku wakarimashita. Shinsetsu ni oshiete kudasatte, arigatou gozaimasu.","trans":"Saya mengerti. Terima kasih sudah menjelaskan dengan ramah."},{"speaker":"田中","text":"いいえ。また道に迷ったら、聞いてくださいね。","reading":"いいえ。またみちにまよったら、きいてくださいね。","romaji":"Iie. Mata michi ni mayottara, kiite kudasai ne.","trans":"Sama-sama. Kalau tersesat lagi, tanya saja ya."}]',
 '[{"word":"市役所","reading":"しやくしょ · shiyakusho","meaning":"kantor walikota"},{"word":"道に迷う","reading":"みちにまよう · michi ni mayou","meaning":"tersesat"},{"word":"曲がる","reading":"まがる · magaru","meaning":"berbelok"},{"word":"交差点","reading":"こうさてん · kousaten","meaning":"persimpangan"},{"word":"目印","reading":"めじるし · mejirushi","meaning":"patokan, penanda"},{"word":"建物","reading":"たてもの · tatemono","meaning":"bangunan"}]', false),

(3, 'Menjelaskan Gejala ke Apoteker', 'kaigo',
 '[{"speaker":"アリ","text":"頭痛がひどくて、夜よく眠れないんです。","reading":"ずつうがひどくて、よるよくねむれないんです。","romaji":"Zutsuu ga hidokute, yoru yoku nemurenai n desu.","trans":"Sakit kepalanya parah, malam jadi susah tidur."},{"speaker":"薬剤師","text":"いつから続いていますか。","reading":"いつからつづいていますか。","romaji":"Itsu kara tsuzuite imasu ka.","trans":"Sejak kapan berlanjut?"},{"speaker":"アリ","text":"三日前からです。","reading":"みっかまえからです。","romaji":"Mikka mae kara desu.","trans":"Sejak tiga hari lalu."},{"speaker":"薬剤師","text":"では、この薬を食後に飲んでください。","reading":"では、このくすりをしょくごにのんでください。","romaji":"Dewa, kono kusuri o shokugo ni nonde kudasai.","trans":"Kalau begitu, minum obat ini setelah makan ya."},{"speaker":"薬剤師","text":"熱や吐き気はありませんか。","reading":"ねつやはきけはありませんか。","romaji":"Netsu ya hakike wa arimasen ka.","trans":"Apakah ada demam atau mual?"},{"speaker":"アリ","text":"熱はありませんが、肩も凝っていて、目も疲れています。","reading":"ねつはありませんが、かたもこっていて、めもつかれています。","romaji":"Netsu wa arimasen ga, kata mo kotte ite, me mo tsukarete imasu.","trans":"Tidak demam, tetapi bahu juga pegal dan mata lelah."},{"speaker":"薬剤師","text":"今、ほかに飲んでいる薬はありますか。","reading":"いま、ほかにのんでいるくすりはありますか。","romaji":"Ima, hoka ni nonde iru kusuri wa arimasu ka.","trans":"Sekarang, apakah ada obat lain yang sedang Anda minum?"},{"speaker":"アリ","text":"胃の薬を毎朝飲んでいます。一緒に飲んでも大丈夫ですか。","reading":"いのくすりをまいあさのんでいます。いっしょにのんでもだいじょうぶですか。","romaji":"I no kusuri o maiasa nonde imasu. Issho ni nonde mo daijoubu desu ka.","trans":"Saya minum obat lambung tiap pagi. Apakah aman diminum bersamaan?"},{"speaker":"薬剤師","text":"問題ありませんが、一日三回までにしてください。","reading":"もんだいありませんが、いちにちさんかいまでにしてください。","romaji":"Mondai arimasen ga, ichinichi sankai made ni shite kudasai.","trans":"Tidak masalah, tetapi batasi sampai tiga kali sehari."},{"speaker":"アリ","text":"わかりました。もし治らなかったら、病院に行きます。","reading":"わかりました。もしなおらなかったら、びょういんにいきます。","romaji":"Wakarimashita. Moshi naoranakattara, byouin ni ikimasu.","trans":"Baik. Kalau tidak sembuh, saya akan pergi ke rumah sakit."}]',
 '[{"word":"頭痛","reading":"ずつう · zutsuu","meaning":"sakit kepala"},{"word":"続く","reading":"つづく · tsuzuku","meaning":"berlanjut"},{"word":"食後","reading":"しょくご · shokugo","meaning":"setelah makan"},{"word":"吐き気","reading":"はきけ · hakike","meaning":"mual"},{"word":"凝る","reading":"こる · koru","meaning":"pegal, kaku (otot)"},{"word":"治る","reading":"なおる · naoru","meaning":"sembuh"}]', false)
ON CONFLICT (level_id, title) DO UPDATE SET
  lines = EXCLUDED.lines,
  vocab_highlight = EXCLUDED.vocab_highlight;
